Warning: truncated output (original token count: 12592)
Total output lines: 163

import {RouteScheduler} from '../navigation/scheduler';
import {UnitSpatialIndex} from './spatial';
import {isWalkable,bridgeBanks} from '../../map/bridges';
import {recruitmentSources} from '../economy/recruitment';
import {TRAINING,type ArmyRoute} from '../../shared/configs/training';
import {UNITS,UNIT_KIND,UNIT_LIMIT,UNIT_STRIDE,UNIT_STATE,FORMATIONS,UNIT_MODES,type UnitMode,type UnitType,type Formation} from '../../shared/configs/units';
import {RESOURCE_KEYS} from '../../shared/configs/buildings';
import {COMBAT,CAPTURE_CONFIG,isMilitaryStructure,ATTACK_MODE_CONFIG} from '../../shared/configs/combat';
import {NavigationGrid,type Point,type CellPassable} from '../navigation/grid';
import {discoveryFrontier,ScoutTraffic} from './discovery';
import {cellAtWorld} from '../../map/hex/coordinates';
import {formationSlots} from './formations';
import type {Command} from '../../shared/types/protocol';
import type {TerritoryMatch} from '../territory/match';
interface Path{points:Point[];index:number;speed:number;retreat:boolean;}
export interface ArmyGroup{id:number;ids:number[];formation:Formation;cohesion:boolean;x:number;y:number;angle:number;heading:number;target:Point;route:Point[];index:number;speed:number;slots:Point[];settling:boolean;waypoints:Point[];}
export class Army {
 readonly embarked=new Uint32Array(UNIT_LIMIT);readonly waitingForTransport=new Uint8Array(UNIT_LIMIT);
 onRemove:(id:number)=>void=()=>{};specialTarget:(i:number)=>Point|undefined=()=>undefined;
 get visibleCount(){return this.count-this.embarked.reduce((n,id,i)=>n+Number(!!id&&!!this.ids[i]),0);}
 get visibleIndices(){const out:number[]=[];for(let i=0;i<this.size;i++)if(this.ids[i]&&!this.embarked[i])out.push(i);return out;}
 canCapture(i:number){return this.kind[i]<2&&!this.embarked[i];}
 readonly routes=new RouteScheduler();readonly routeErrors:string[]=[];private orderEpoch=new Uint32Array(UNIT_LIMIT);private orderValidationRevision=0;
 enqueueOrder(command:Extract<Command,{type:'MOVE_UNITS'|'ATTACK_UNIT'|'ATTACK_BUILDING'|'RETREAT_UNITS'}>,priority:'human'|'background'='human'){const indices=this.indices(command.playerId,command.unitIds);if(command.type==='MOVE_UNITS'&&(!this.navigation.land(command.target)||!FORMATIONS.includes(command.formation??'block')||typeof(command.cohesion??false)!=='boolean'||typeof(command.append??false)!=='boolean'))throw new Error('Destino ou formação inválida.');if(command.type==='ATTACK_UNIT'){const i=this.index(command.targetId);if(i<0||!this.match.diplomacy!.hostile(command.playerId,this.owner[i]))throw new Error('Escolha uma tropa inimiga durante guerra.');}if(command.type==='ATTACK_BUILDING'){const b=this.match.state.buildings.find(b=>b.id===command.buildingId);if(!b||!this.match.diplomacy!.hostile(command.playerId,b.ownerId))throw new Error('Escolha uma construção inimiga durante guerra.');}if(command.type==='RETREAT_UNITS'&&!this.match.state.buildings.some(b=>b.ownerId===command.playerId&&b.type==='barracks'&&!b.construction))throw new Error('Construa um quartel para receber as tropas.');this.orderValidationRevision++;const epochs=indices.map(i=>command.type==='MOVE_UNITS'&&command.append?this.orderEpoch[i]:++this.orderEpoch[i]),ids=indices.map(i=>this.ids[i]),factory=()=>command.type==='MOVE_UNITS'?this.moveSteps(command.playerId,command.unitIds,command.target,command.formation,command.cohesion,command.append):command.type==='ATTACK_UNIT'?this.attackSteps(command.playerId,command.unitIds,command.targetId):command.type==='ATTACK_BUILDING'?this.attackBuildingSteps(command.playerId,command.unitIds,command.buildingId):this.retreatSteps(command.playerId,command.unitIds);let checked=-1,valid=true;this.routes.enqueue(this.restartOnTopology(factory),priority,()=>{if(this.match.state.phase!=='playing')return false;if(checked!==this.orderValidationRevision){checked=this.orderValidationRevision;valid=indices.every((i,n)=>this.ids[i]===ids[n]&&this.orderEpoch[i]===epochs[n]);}return valid;},e=>this.routeErrors.push(e instanceof Error?e.message:String(e)));}
 private *restartOnTopology(factory:()=>Generator<void,unknown,unknown>):Generator<void,unknown,unknown>{while(true){const revision=this.match.map.navigationRevision??0,relations=this.match.state.diplomacy.revision,task=factory();try{while((this.match.map.navigationRevision??0)===revision&&this.match.state.diplomacy.revision===relations){const result=task.next();if(result.done)return result.value;yield;}}finally{task.return(undefined);}}}
 private drain<T>(task:Generator<void,T,unknown>):T{let r=task.next();while(!r.done)r=task.next();return r.value;}
 private cancelPending(indices:number[]){this.orderValidationRevision++;for(const i of indices)this.orderEpoch[i]++;}

 readonly spatial=new UnitSpatialIndex(this);
 private cellX=new Float32Array(UNIT_LIMIT).fill(NaN);private cellY=new Float32Array(UNIT_LIMIT).fill(NaN);private cellIds=new Int32Array(UNIT_LIMIT).fill(-1);
 cell(i:number){if(this.cellX[i]!==this.x[i]||this.cellY[i]!==this.y[i]){this.cellX[i]=this.x[i];this.cellY[i]=this.y[i];this.cellIds[i]=cellAtWorld(this.match.map,this.x[i],this.y[i])?.id??-1;}return this.match.map.cells[this.cellIds[i]];}
 private frontierCache=new Map<number,{signature:string;ids:Set<number>}>();
 private trafficIndex:ScoutTraffic|null=null;
 private scoutSnapshots=new Map<number,{id:number;x:number;y:number;owner:number;target:number;returning:boolean}>();
 private pendingModes=new Map<number,object>();
 private reachableCache=new Map<number,{signature:string;seen:Set<number>}>();
 private lastBridgeSignature='';private lastBridgeRevision=-1;private lastLandX=new Float32Array(UNIT_LIMIT);private lastLandY=new Float32Array(UNIT_LIMIT);
 private patrolSeed=123456789;private patrolRandom(){this.patrolSeed^=this.patrolSeed<<13;this.patrolSeed^=this.patrolSeed>>>17;this.patrolSeed^=this.patrolSeed<<5;return (this.patrolSeed>>>0)/4294967296;}private defenseFields=new Map<number,{signature:string;distances:Uint16Array}>();readonly buildingOrders=new Map<number,number>();botVisibility:(owner:number,targetId:number)=>boolean=()=>true;readonly modes=new Uint8Array(UNIT_LIMIT);private modeOrders=new Map<number,{ids:number[];mode:UnitMode;elapsed:number;target:number;signature:string;returning:boolean;cityId:number|null;buildingId:number|null;secureAnchor:number|null;lastX:number;lastY:number;stalled:number}>();private nextMode=1;
 readonly navigation:NavigationGrid;count=0;revision=0;routeRevision=0;size=0;private nextId=1;private nextGroup=1;private nextBatch=1;
 readonly x=new Float32Array(UNIT_LIMIT);readonly y=new Float32Array(UNIT_LIMIT);readonly angle=new Float32Array(UNIT_LIMIT);readonly kind=new Uint8Array(UNIT_LIMIT);readonly owner=new Uint8Array(UNIT_LIMIT);readonly ids=new Uint32Array(UNIT_LIMIT);readonly hp=new Float32Array(UNIT_LIMIT);readonly supply=new Float32Array(UNIT_LIMIT);readonly state=new Uint8Array(UNIT_LIMIT);readonly target=new Int32Array(UNIT_LIMIT).fill(-1);readonly cooldown=new Float32Array(UNIT_LIMIT);readonly shots=new Uint32Array(UNIT_LIMIT);readonly groupId=new Uint32Array(UNIT_LIMIT);
 readonly slotIndex=new Int32Array(UNIT_LIMIT).fill(-1);readonly groups=new Map<number,ArmyGroup>();private byId=new Map<number,number>();private paths=new Map<number,Path>();readonly recovery=new Map<number,number>(); // unit index -> barracks id
 private free:number[]=[];private pendingPursuits=new Map<number,object>();private pursuits=new Map<number,{targetId:number;elapsed:number;x:number;y:number}>();
 constructor(readonly match:TerritoryMatch,readonly deferAutomaticRoutes=false){for(const c of match.map.config.seed)this.patrolSeed=(Math.imul(this.patrolSeed,31)+c.charCodeAt(0))>>>0;this.navigation=new NavigationGrid(match.map);match.onDefeat=id=>this.eliminate(id);}
 definition(i:number){return UNITS[UNIT_KIND[this.kind[i]]];}
 spawn(playerId:number,type:UnitType,p:Point){if(this.count>=UNIT_LIMIT||!(type==='aircraft'?!!cellAtWorld(this.match.map,p.x,p.y):type==='transport'||type==='cargo'?cellAtWorld(this.match.map,p.x,p.y)?.terrain==='water':this.navigation.land(p))||!this.match.state.players.some(c=>c.id===playerId&&!c.defeated))throw new Error('Não foi possível posicionar a unidade.');const i=this.free.pop()??this.size++;this.ids[i]=this.nextId++;this.byId.set(this.ids[i],i);this.x[i]=p.x;this.y[i]=p.y;this.lastLandX[i]=p.x;this.lastLandY[i]=p.y;this.kind[i]=UNIT_KIND.indexOf(type);this.embarked[i]=0;this.waitingForTransport[i]=0;this.owner[i]=playerId;this.hp[i]=this.definition(i).health;this.supply[i]=100;this.angle[i]=0;this.state[i]=UNIT_STATE.idle;this.target[i]=-1;this.cooldown[i]=0;this.shots[i]=0;this.groupId[i]=0;this.slotIndex[i]=-1;this.modes[i]=0;this.count++;this.revision++;return this.ids[i];}
 index(id:number){return this.byId.get(id)??-1;}
 get queuedCount(){return this.match.state.training.reduce((n,q)=>n+q.batches.reduce((m,b)=>m+b.remaining,0),0);}
 private indicesForMilitary(playerId:number){let population=0;for(let i=0;i<this.size;i++)if(this.ids[i]&&this.owner[i]===playerId)population+=this.definition(i).population;return population;}
 queuedFor(playerId:number){return this.match.state.training.filter(q=>q.playerId===playerId).reduce((n,q)=>n+q.batches.reduce((m,b)=>m+b.remaining,0),0);}
 recruit(playerId:number,buildingId:number,type:UnitType,count:number){
  if(this.match.state.phase!=='playing'||!this.match.state.players.some(p=>p.id===playerId&&!p.defeated))throw new Error('Recrutamento indisponível.');
  const def=UNITS[type];if(!def||!Number.isInteger(count)||count<1||count>TRAINING.maxBatch[type])throw new Error('Um espaço aceita até 10 infantarias ou 1 tanque.');
  if(this.count+this.queuedCount+count>UNIT_LIMIT)throw new Error('Limite de 5.000 tropas, incluindo treinamento, atingido.');
  const economy=this.match.economy!,b=economy.buildings.find(b=>b.id===buildingId&&b.ownerId===playerId&&b.type==='barracks'&&!b.construction);if(!b)throw new Error('Construa e escolha um quartel do seu país.');
  let queue=this.match.state.training.find(q=>q.buildingId===buildingId);if(queue&&queue.batches.length>=TRAINING.slots)throw new Error('Fila cheia: cada quartel tem 4 espaços de treinamento.');
  const country=economy.countries.find(c=>c.playerId===playerId)!,populationSources=recruitmentSources(this.match.map,economy.buildings,country,b.anchorId,def.population*count);for(const key of RESOURCE_KEYS)if(country.stock[key]<(def.cost[key]??0)*count)throw new Error('Recursos insuficientes para esse recrutamento.');
  for(const key of RESOURCE_KEYS)country.stock[key]-=(def.cost[key]??0)*count;for(const source of populationSources)economy.buildings.find(b=>b.id===source.cityId)!.city!.population-=source.population;economy.recalculate();
  if(!queue){queue={buildingId,playerId,batches:[]};this.match.state.training.push(queue);}queue.batches.push({id:this.nextBatch++,unitType:type,total:count,remaining:count,elapsed:0,duration:TRAINING.seconds[type],populationSources});this.match.social?.militarization(playerId,def.population*count,country.population,this.indicesForMilitary(playerId)+this.queuedFor(playerId));this.match.state.revision++;
 }
 stepTraining(dt:number){if(this.match.state.phase!=='playing')return;for(const queue of [...this.match.state.training]){
  const b=this.match.state.buildings.find(b=>b.id===queue.buildingId&&b.type==='barracks'&&!b.construction&&b.ownerId===queue.playerId),player=this.match.state.players.find(p=>p.id===queue.playerId);
  if(!b||player?.defeated){if(!player?.defeated){const c=this.match.economy!.countries.find(c=>c.playerId===queue.playerId)!;for(const batch of queue.batches){const def=UNITS[batch.unitType];for(const key of RESOURCE_KEYS)c.stock[key]+=(def.cost[key]??0)*batch.remaining;let refund=def.population*batch.remaining;for(const source of batch.populationSources??[]){const city=this.match.economy!.buildings.find(b=>b.id===source.cityId&&b.ownerId===queue.playerId&&b.city),people=Math.min(refund,source.population);if(city){city.city!.population+=people;refund-=people;}}if(refund)this.match.economy!.changePopulation(queue.playerId,refund);}this.match.economy!.recalculate();}this.match.state.training.splice(this.match.state.training.indexOf(queue),1);this.match.state.revision++;continue;}
  let budget=dt;while(budget>1e-8&&queue.batches.length){const batch=queue.batches[0];if(this.count>=UNIT_LIMIT)break;const used=Math.min(budget,batch.duration-batch.elapsed);batch.elapsed+=used;budget-=used;
   if(batch.elapsed+1e-7>=batch.duration){const center=this.match.map.cells[b.anchorId],a=this.nextId*2.39996,r=8+Math.sqrt(this.nextId%40)*4,p={x:center.x+Math.cos(a)*r,y:center.y+Math.sin(a)*r};this.spawn(queue.playerId,batch.unitType,this.navigation.clear(center,p)?p:center);let assigned=UNITS[batch.unitType].population;for(const source of batch.populationSources??[]){const used=Math.min(assigned,source.population);source.population-=used;assigned-=used;if(!assigned)break;}batch.remaining--;batch.elapsed=0;if(!batch.remaining)queue.batches.shift();}else break;
  }if(!queue.batches.length)this.match.state.training.splice(this.match.state.training.indexOf(queue),1);this.match.state.revision++;
 }}
 eliminate(playerId:number){this.match.state.training=this.match.state.training.filter(q=>q.playerId!==playerId);for(let i=0;i<this.size;i++)if(this.ids[i]&&this.owner[i]===playerId)this.remove(i);}
 routeViews():ArmyRoute[]{return [...this.groups.values()].filter(g=>g.waypoints.length&&this.owner[this.index(g.ids[0])]===1).map(g=>({groupId:g.id,unitIds:[...g.ids],points:[{...g.target},...g.waypoints.map(p=>({...p}))]}));}
 indices(playerId:number,ids:number[]){if(this.match.state.phase!=='playing'||!this.match.state.players.some(p=>p.id===playerId&&!p.defeated)||!Array.isArray(ids)||!ids.length||ids.length>UNIT_LIMIT)throw new Error('Seleção militar inválida.');const indices=[...new Set(ids)].map(id=>this.index(id));if(indices.some(i=>i<0||this.owner[i]!==playerId))throw new Error('Selecione apenas tropas vivas do seu país.');return indices;}
 private detach(i:number){this.buildingOrders.delete(i);this.pursuits.delete(i);this.pendingPursuits.delete(i);const group=this.groups.get(this.groupId[i]);if(group){this.routeRevision++;const n=this.slotIndex[i];if(n>=0){group.ids.splice(n,1);group.slots.splice(n,1);for(let j=n;j<group.ids.length;j++){const index=this.index(group.ids[j]);if(index>=0)this.slotIndex[index]=j;}}if(!group.ids.length)this.groups.delete(group.id);}this.groupId[i]=0;this.slotIndex[i]=-1;this.paths.delete(i);this.recovery.delete(i);this.target[i]=-1;this.state[i]=UNIT_STATE.idle;}
 private detachMany(indices:number[]){const selected=new Set(indices),groups=new Set(indices.map(i=>this.groupId[i]));if(groups.size>1||!groups.has(0))this.routeRevision++;for(const id of groups){const g=this.groups.get(id);if(!g)continue;let next=0;for(let n=0;n<g.ids.length;n++){const i=this.index(g.ids[n]);if(i<0||selected.has(i))continue;g.ids[next]=g.ids[n];g.slots[next]=g.slots[n];this.slotIndex[i]=next++;}g.ids.length=next;g.slots.length=next;if(!next)this.groups.delete(id);}for(const i of indices){this.buildingOrders.delete(i);this.pursuits.delete(i);this.pendingPursuits.delete(i);this.paths.delete(i);this.recovery.delete(i);this.groupId[i]=0;this.slotIndex[i]=-1;this.target[i]=-1;this.state[i]=UNIT_STATE.idle;}}
 remove(i:number){if(!this.ids[i])return;this.onRemove(this.ids[i]);this.orderValidationRevision++;this.match.social?.loss(this.owner[i],this.definition(i).population);this.embarked[i]=0;this.waitingForTransport[i]=0;this.clearModes([i]);this.detach(i);this.byId.delete(this.ids[i]);this.ids[i]=0;this.hp[i]=0;this.owner[i]=0;this.free.push(i);this.count--;this.revision++;}
 private slotsAt(indices:number[],formation:Formation,angle:number,target:Point,allowed?:CellPassable){return this.drain(this.slotsAtSteps(indices,formation,angle,target,allowed));}
 private *slotsAtSteps(indices:number[],formation:Formation,angle:number,target:Point,allowed?:CellPassable){const offsets=formationSlots(indices.length,formation,angle),result:Point[]=[];const occupied=new Set<string>();let checks=0,offsetCount=0;for(const offset of offsets){if(offsetCount++%16===0)yield;const desired={x:target.x+offset.x,y:target.y+offset.y};if(this.navigation.clear(target,desired,allowed)&&!occupied.has(`${Math.round(desired.x)},${Math.round(desired.y)}`)){occupied.add(`${Math.round(desired.x)},${Math.round(desired.y)}`);result.push(offset);continue;}let found=false;search:for(let ring=1;ring<30;ring++)for(let j=0;j<ring*8;j++){if(++checks%32===0)yield;const a=j/(ring*8)*Math.PI*2,p={x:target.x+Math.cos(a)*ring*COMBAT.formationGap,y:target.y+Math.sin(a)*ring*COMBAT.formationGap},key=`${Math.round(p.x)},${Math.round(p.y)}`;if(!occupied.has(key)&&this.navigation.clear(target,p,allowed)){occupied.add(key);result.push({x:p.x-target.x,y:p.y-target.y});found=true;break search;}}if(!found)throw new Error('Não há espaço terrestre para posicionar essa formação.');}return result;}
 move(playerId:number,ids:number[],target:Point,formation:Formation='block',cohesion=false,append=false,automatic=false){if(!automatic)this.cancelPending(this.indices(playerId,ids));return this.drain(this.moveSteps(playerId,ids,target,formation,cohesion,append,automatic));}
 private *moveSteps(playerId:number,ids:number[],target:Point,formation:Formation='block',cohesion=false,append=false,automatic=false){if(!target||!Number.isFinite(target.x)||!Number.isFinite(target.y))throw new Error('Destino inválido.');target={x:target.x,y:target.y};const indices=this.indices(playerId,ids);if(!FORMATIONS.includes(formation)||typeof cohesion!=='boolean')throw new Error('Configuração de formação inválida.');if(typeof append!=='boolean')throw new Error('Ordem de rota inválida.');const allowed=automatic&&indices.every(i=>this.modes[i]===UNIT_MODES.discovery)?this.discoveryAllowed(playerId):undefined;if(append){const existing=this.groups.get(this.groupId[indices[0]]);if(existing&&existing.ids.length===ind…3592 tokens truncated…er]of [...this.modeOrders]){if(order.elapsed<1||!budget||this.pendingModes.has(key))continue;budget--;this.modeOrders.delete(key);this.modeOrders.set(key,order);const interval=order.elapsed;order.elapsed=0;const factory=()=>this.modeSteps(key,order,interval);if(this.deferAutomaticRoutes||order.ids.length>32){this.pendingModes.set(key,order);const army=this,assignedIds=order.ids;const task=function*():Generator<void,unknown,unknown>{try{return yield* army.restartOnTopology(factory);}finally{army.pendingModes.delete(key);army.updateScout(key);}};this.routes.enqueue(task(),'background',()=>this.modeOrders.get(key)===order&&order.ids===assignedIds,e=>this.routeErrors.push(e instanceof Error?e.message:String(e)),()=>{if(this.pendingModes.get(key)===order)this.pendingModes.delete(key);this.updateScout(key);});}else this.drain(factory());}}
 private *modeSteps(key:number,order:NonNullable<ReturnType<typeof this.modeOrders.get>>,interval:number):Generator<void,unknown,unknown>{try{
if(order.ids.some(id=>this.index(id)<0))order.ids=order.ids.filter(id=>this.index(id)>=0);if(!order.ids.length){this.modeOrders.delete(key);return;}const indices=order.ids.map(id=>this.index(id)),owner=this.owner[indices[0]],d=this.match.diplomacy!,cells=this.match.map.cells;
 const enemies=this.match.state.players.filter(p=>!p.defeated&&d.hostile(owner,p.id)).map(p=>p.id),threats=this.match.state.players.filter(p=>!p.defeated&&(d.hostile(owner,p.id)||this.match.state.diplomacy.relations.some(r=>r.state==='TENSION'&&r.preparedBy===p.id&&((r.a===owner&&r.b===p.id)||(r.b===owner&&r.a===p.id))))).map(p=>p.id);let signature=order.mode==='discovery'?this.match.state.players.filter(p=>d.allied(owner,p.id)).map(p=>p.id).join(',')+(order.returning?':'+this.match.state.borderRevision+':'+this.match.state.buildingRevision:''):(order.mode==='defense'?threats:enemies).join(',')+(order.mode==='defense'&&threats.length?':'+this.match.state.borderRevision:order.mode==='attack'?':'+this.match.state.buildingRevision:'');
 const moving=indices.some(i=>this.paths.has(i)||this.groups.has(this.groupId[i])),fighting=indices.some(i=>this.state[i]===UNIT_STATE.attack);const cx=indices.reduce((n,i)=>n+this.x[i],0)/indices.length,cy=indices.reduce((n,i)=>n+this.y[i],0)/indices.length;order.stalled=moving&&!fighting&&Math.hypot(cx-order.lastX,cy-order.lastY)<.5?order.stalled+interval:0;order.lastX=cx;order.lastY=cy;const stuck=order.stalled>=4;if(stuck){for(const i of indices)this.detach(i);order.target=-1;order.returning=false;order.stalled=0;}
 if(order.returning&&order.signature===signature)return;
 if(order.returning){order.returning=false;signature=this.match.state.players.filter(p=>d.allied(owner,p.id)).map(p=>p.id).join(',');for(const i of indices)this.detach(i);order.target=-1;}
 if(order.mode==='attack'&&!enemies.length){if(order.target>=0||order.signature!==signature)for(const i of indices)this.detach(i);order.target=-1;order.buildingId=null;order.secureAnchor=null;order.signature=signature;return;}
 // Keep occupying economic structures until capture completes, even after their anchor changes owner.
 const objective=order.mode==='attack'?this.match.state.buildings.find(b=>b.id===order.buildingId&&enemies.includes(b.ownerId)):undefined;
 if(order.mode==='attack'&&order.buildingId!==null&&!objective){for(const i of indices)this.detach(i);order.buildingId=null;order.target=-1;}
 const destroyObjective=!!objective&&(isMilitaryStructure(objective.type)||!!objective.construction||objective.type==='city'&&indices.length<CAPTURE_CONFIG.cityMinimumTroops);
 if(objective&&destroyObjective)for(const i of indices)this.buildingOrders.set(i,objective.id);
 const target=cells[order.target],busy=indices.some(i=>this.paths.has(i)||this.groups.has(this.groupId[i])||this.state[i]===UNIT_STATE.attack),hasBuilding=target&&this.match.state.buildings.some(b=>enemies.includes(b.ownerId)&&b.anchorId===target.id),valid=target&&(order.mode==='discovery'?target.ownerId===null&&this.discoveryTraffic(owner,key,true).clear(target):order.mode==='attack'?(!!objective||target.ownerId!==null&&enemies.includes(target.ownerId)||order.secureAnchor!==null&&target.ownerId===null||hasBuilding):target.ownerId!==null&&(target.ownerId===owner||d.allied(owner,target.ownerId)));
 const holdingObjective=objective&&indices.filter(i=>Math.hypot(this.x[i]-cells[objective.anchorId].x,this.y[i]-cells[objective.anchorId].y)<=CAPTURE_CONFIG.radius).length>=(objective.type==='city'?CAPTURE_CONFIG.cityMinimumTroops:1);
 if(signature===order.signature&&valid&&(busy||holdingObjective||order.mode==='defense'&&threats.length))return;
 if(signature!==order.signature||!valid){for(const i of indices)this.detach(i);order.target=-1;}order.signature=signature;
 const start={x:this.x[indices[0]],y:this.y[indices[0]]},distance=(p:Point)=>(p.x-start.x)**2+(p.y-start.y)**2,friendly=(id:number|null)=>id!==null&&(id===owner||d.allied(owner,id));
 const reachable=order.mode==='discovery'?this.discoveryReachable(owner,start):null;
 const candidateIds=new Set<number>();
 if(order.mode==='discovery'){for(const id of this.frontier(owner))candidateIds.add(id);const current=cellAtWorld(this.match.map,start.x,start.y);if(current)for(const n of current.neighbors)if(cells[n].ownerId===null)candidateIds.add(n);}
 else for(const p of this.match.state.players)if(order.mode==='attack'?enemies.includes(p.id):friendly(p.id))for(const id of this.match.owned.get(p.id)??[])candidateIds.add(id);
 let candidates=[...candidateIds].map(id=>cells[id]).filter(c=>c.terrain==='land'&&(order.mode!=='discovery'||reachable!.has(c.id)));
 const attackBuildings=order.mode==='attack'?new Map(this.match.state.buildings.filter(b=>enemies.includes(b.ownerId)).map(b=>[b.anchorId,b])):null;
 if(order.mode==='attack'){
 // Resolve the structure first; then secure its four surrounding hex rings before advancing.
 const local=new Set<number>();if(order.secureAnchor!==null&&!objective){local.add(order.secureAnchor);let ring=[order.secureAnchor];for(let n=0;n<ATTACK_MODE_CONFIG.secureRadius;n++){const next:number[]=[];for(const id of ring)for(const neighbor of cells[id].neighbors)if(!local.has(neighbor)){local.add(neighbor);next.push(neighbor);}ring=next;}}
 const localLand=[...local].map(id=>cells[id]).filter(c=>c.terrain==='land'&&(c.ownerId===null||enemies.includes(c.ownerId))&&!this.match.economy!.occupied[c.id]);
 const buildings=[...attackBuildings!.values()].map(b=>cells[b.anchorId]).sort((a,b)=>distance(a)-distance(b)),fronts=candidates.filter(c=>!this.match.economy!.occupied[c.id]&&c.neighbors.some(n=>!enemies.includes(cells[n].ownerId??0))).sort((a,b)=>distance(a)-distance(b));
 candidates=objective?[cells[objective.anchorId]]:[...new Map([...buildings.filter(c=>local.has(c.id)),...localLand.sort((a,b)=>distance(a)-distance(b)),...buildings,...fronts].map(c=>[c.id,c])).values()];
 }
 else if(order.mode==='defense'&&threats.length){const hostileCells=cells.filter(c=>c.ownerId!==null&&threats.includes(c.ownerId)),border=candidates.filter(c=>c.neighbors.some(n=>cells[n].terrain==='land'&&!friendly(cells[n].ownerId)));const key=threats.join(',')+':'+this.match.state.borderRevision;let field=this.defenseFields.get(owner);if(!field||field.signature!==key){const distances=new Uint16Array(cells.length).fill(65535),queue:number[]=[];for(const c of hostileCells){distances[c.id]=0;queue.push(c.id);}for(let h=0;h<queue.length;h++)for(const n of cells[queue[h]].neighbors)if(cells[n].terrain==='land'&&distances[n]===65535){distances[n]=distances[queue[h]]+1;queue.push(n);}field={signature:key,distances};this.defenseFields.set(owner,field);}const scores=new Map(border.map(c=>[c.id,field!.distances[c.id]**2*this.match.map.layout.radius**2+distance(c)*.01]));candidates=border.sort((a,b)=>scores.get(a.id)!-scores.get(b.id)!);}
 else if(order.mode==='defense'){for(let n=candidates.length-1;n>0;n--){const j=Math.floor(this.patrolRandom()*(n+1));[candidates[n],candidates[j]]=[candidates[j],candidates[n]];}}
 else if(order.mode==='discovery'){
 const cities=this.match.state.buildings.filter(b=>b.ownerId===owner&&b.type==='city');let city=cities.find(b=>b.id===order.cityId);if(!city){city=cities.sort((a,b)=>distance(cells[a.anchorId])-distance(cells[b.anchorId]))[0];order.cityId=city?.id??null;}
 const frontier=discoveryFrontier(this.match.map,candidates,city?cells[city.anchorId]:start,start,friendly),traffic=this.discoveryTraffic(owner,key);candidates=frontier.filter(c=>traffic.clear(c));
 // Crowded frontiers release their destination and retry; they are not exhausted territory.
 if(frontier.length&&!candidates.length){for(const i of indices)this.detach(i);order.target=-1;return;}
 }
 else candidates.sort((a,b)=>distance(a)-distance(b));
 // At most four orders per tick; cached connectivity skips islands without any route search.
 let attempts=0,assigned=false;for(const c of candidates){if(distance(c)<1&&!(order.mode==='attack'?attackBuildings!.has(c.id):hasBuilding))continue;if(!this.navigation.connected(start,c))continue;if(attempts>=12)break;attempts++;try{if(order.mode==='defense'){const route=(yield* this.navigation.routeSteps(start,c));if(!this.friendlyRoute(owner,start,route))continue;const slots=(yield* this.slotsAtSteps(indices,'block',Math.atan2(c.y-start.y,c.x-start.x),c));let invalid=false;for(let n=0;n<indices.length;n++){if(n%16===0)yield;const i=indices[n];if(!this.friendlyRoute(owner,{x:this.x[i],y:this.y[i]},[start])||!this.friendlyRoute(owner,c,[{x:c.x+slots[n].x,y:c.y+slots[n].y}])){invalid=true;break;}}if(invalid)continue;}yield* this.moveSteps(owner,order.ids,c,'block',true,false,true);order.target=c.id;if(order.mode==='attack'){const building=attackBuildings!.get(c.id);order.buildingId=building?.id??null;if(building){order.secureAnchor=c.id;if(isMilitaryStructure(building.type)||building.construction||building.type==='city'&&indices.length<CAPTURE_CONFIG.cityMinimumTroops)for(const i of indices)this.buildingOrders.set(i,building.id);}}this.updateScout(key);assigned=true;break;}catch{/* Try the next reachable target without cancelling the mode. */}}
 if(order.mode==='discovery'&&!assigned){yield* this.returnDiscoverySteps(owner,indices);order.target=-1;order.returning=true;order.signature=this.match.state.players.filter(p=>d.allied(owner,p.id)).map(p=>p.id).join(',')+':'+this.match.state.borderRevision+':'+this.match.state.buildingRevision;}

 }finally{this.updateScout(key);}}
 private slotPoint(group:ArmyGroup,n:number){const s=group.slots[n],a=(group.settling?group.angle:group.heading)-group.angle,point={x:group.x+s.x*Math.cos(a)-s.y*Math.sin(a),y:group.y+s.x*Math.sin(a)+s.y*Math.cos(a)};const i=this.index(group.ids[0]),allowed=i>=0&&this.modes[i]===UNIT_MODES.discovery?this.discoveryAllowed(this.owner[i]):undefined;return this.navigation.clear(group,point,allowed)?point:{x:group.x,y:group.y};}
 private advance(i:number,p:Point,budget:number){const dx=p.x-this.x[i],dy=p.y-this.y[i],distance=Math.hypot(dx,dy);if(distance<.05)return {travel:0,arrived:true};const travel=Math.min(distance,budget),next={x:Math.fround(this.x[i]+dx/distance*travel),y:Math.fround(this.y[i]+dy/distance*travel)};if(this.modes[i]===UNIT_MODES.discovery&&!this.navigation.clear({x:this.x[i],y:this.y[i]},next,this.discoveryAllowed(this.owner[i]))){this.detach(i);for(const order of this.modeOrders.values())if(order.ids.includes(this.ids[i])){order.target=-1;order.returning=false;order.elapsed=1;}return {travel:0,arrived:false};}if(this.modes[i]!==UNIT_MODES.discovery&&!this.navigation.clear({x:this.x[i],y:this.y[i]},next))return {travel:0,arrived:false};if(this.modes[i]===UNIT_MODES.defense){const c=cellAtWorld(this.match.map,next.x,next.y);const id=c?.bridgeOwnerId??c?.ownerId;if(id===null||id===undefined||id!==this.owner[i]&&!this.match.diplomacy!.allied(this.owner[i],id)){this.detach(i);for(const order of this.modeOrders.values())if(order.ids.includes(this.ids[i])){order.target=-1;order.elapsed=1;}return {travel:0,arrived:false};}}this.angle[i]=Math.atan2(dy,dx);this.x[i]=next.x;this.y[i]=next.y;if(this.cell(i)?.terrain==='land'){this.lastLandX[i]=next.x;this.lastLandY[i]=next.y;}this.match.captureAtPosition(this.owner[i],next.x,next.y,true);return {travel,arrived:travel>=distance-.05};}
 private follow(i:number,path:Path,dt:number){let budget=path.speed*dt;while(budget>.0001&&path.index<path.points.length){const result=this.advance(i,path.points[path.index],budget);if(result.arrived)path.index++;else if(!result.travel)break;budget-=result.travel;}if(path.index>=path.points.length){this.paths.delete(i);this.state[i]=path.retreat?UNIT_STATE.recover:UNIT_STATE.idle;}}
 private refreshBridges(){
  if(this.lastBridgeRevision===this.match.state.buildingRevision)return;this.lastBridgeRevision=this.match.state.buildingRevision;
  const signature=this.match.state.buildings.filter(b=>b.type==='bridge'&&!b.construction).map(b=>b.id+':'+b.ownerId).join(',');if(signature===this.lastBridgeSignature)return;this.lastBridgeSignature=signature;
  const groups=[...this.groups.values()].map(g=>({...g,ids:[...g.ids],waypoints:[...g.waypoints]}));
  for(let i=0;i<this.size;i++)if(this.ids[i]&&this.kind[i]<2&&!this.embarked[i]&&!this.navigation.land({x:this.x[i],y:this.y[i]})){const cell=cellAtWorld(this.match.map,this.x[i],this.y[i]),banks=cell?bridgeBanks(this.match.map,cell.id):null;const safe={x:this.lastLandX[i],y:this.lastLandY[i]};const p=this.navigation.land(safe)?safe:banks?this.match.map.cells[banks[0]]:null;if(p){this.x[i]=p.x;this.y[i]=p.y;}this.detach(i);}
  for(const g of groups){const ids=g.ids.filter(id=>this.index(id)>=0);if(!ids.length)continue;const owner=this.owner[this.index(ids[0])];try{const id=this.move(owner,ids,g.target,g.formation,g.cohesion,false,true);this.groups.get(id)!.waypoints=g.waypoints;}catch{for(const id of ids)this.detach(this.index(id));}}
  for(const [i,path]of this.paths)if(path.retreat){try{path.points=this.navigation.route({x:this.x[i],y:this.y[i]},path.points.at(-1)!,this.modes[i]===UNIT_MODES.discovery?this.discoveryAllowed(this.owner[i]):undefined);path.index=0;}catch{this.detach(i);}}
  this.revision++;
 }
 step(dt:number){this.routes.step();this.refreshBridges();this.stepBuildingOrders();this.stepModes(dt);this.stepPursuits(dt);for(const group of this.groups.values()){if(!group.cohesion)continue;const alive=group.ids.map(id=>this.index(id)).filter(i=>i>=0),lag=alive.reduce((max,i)=>{const p=this.slotPoint(group,this.slotIndex[i]);return Math.max(max,Math.hypot(this.x[i]-p.x,this.y[i]-p.y));},0);group.speed=Math.min(...alive.map(i=>this.definition(i).speed));let budget=lag>COMBAT.maxGroupLag?0:group.speed*dt;while(budget>0&&group.index<group.route.length){const p=group.route[group.index],dx=p.x-group.x,dy=p.y-group.y,d=Math.hypot(dx,dy);if(d<.01){group.index++;continue;}const travel=Math.min(d,budget);group.heading=Math.atan2(dy,dx);group.x+=dx/d*travel;group.y+=dy/d*travel;budget-=travel;if(travel>=d)group.index++;}group.settling=group.index>=group.route.length;}
 for(let i=0;i<this.size;i++){if(!this.ids[i]||this.kind[i]>=2||this.embarked[i])continue;const recoveryId=this.recovery.get(i);if(recoveryId!==undefined&&!this.match.state.buildings.some(b=>b.id===recoveryId&&b.ownerId===this.owner[i]&&b.type==='barracks'&&!b.construction)){this.detach(i);continue;}if(this.state[i]===UNIT_STATE.attack)continue;const path=this.paths.get(i);if(path){this.follow(i,path,dt);continue;}const group=this.groups.get(this.groupId[i]);if(!group||!group.cohesion)continue;const n=this.slotIndex[i],slot=group.slots[n];if(!slot)continue;const point=this.slotPoint(group,n);if(Math.hypot(point.x-this.x[i],point.y-this.y[i])<.2){this.state[i]=group.settling?UNIT_STATE.idle:UNIT_STATE.moving;continue;}this.state[i]=UNIT_STATE.moving;const speed=group.speed;let budget=speed*dt;while(budget>.0001){const result=this.advance(i,point,budget);if(!result.travel){if(!result.arrived){try{this.paths.set(i,{points:this.navigation.route({x:this.x[i],y:this.y[i]},point,this.modes[i]===UNIT_MODES.discovery?this.discoveryAllowed(this.owner[i]):undefined),index:0,speed,retreat:false});}catch{/* coast can temporarily prevent keeping a slot */}}break;}budget-=result.travel;if(result.arrived)break;}}
 for(const [id,group]of this.groups){if(group.ids.every(unitId=>{const i=this.index(unitId);return i<0||(!this.paths.has(i)&&this.state[i]===UNIT_STATE.idle);})){if(group.waypoints.length&&group.ids.length){const ids=[...group.ids],waypoints=group.waypoints.map(p=>({...p}));try{const nextId=this.move(this.owner[this.index(ids[0])],ids,waypoints.shift()!,group.formation,group.cohesion);this.groups.get(nextId)!.waypoints=waypoints;continue;}catch{group.waypoints=[];}}for(const unitId of group.ids){const i=this.index(unitId);if(i>=0){this.groupId[i]=0;this.slotIndex[i]=-1;}}this.groups.delete(id);this.routeRevision++;}}}
 resume(i:number){this.state[i]=this.recovery.has(i)?(this.paths.has(i)?UNIT_STATE.retreat:UNIT_STATE.recover):this.paths.has(i)||this.groups.has(this.groupId[i])?UNIT_STATE.moving:UNIT_STATE.idle;}
 snapshot(data:Float32Array=new Float32Array(this.visibleCount*UNIT_STRIDE)){let n=0;for(let i=0;i<this.size;i++){if(!this.ids[i]||this.embarked[i])continue;const k=n++*UNIT_STRIDE,path=this.paths.get(i),group=this.groups.get(this.groupId[i]),pursued=this.pursuitTarget(i),target=this.specialTarget(i)??(pursued>=0?{x:this.x[pursued],y:this.y[pursued]}:path?.points.at(-1)??group?.target);data[k+0]=this.ids[i];data[k+1]=this.x[i];data[k+2]=this.y[i];data[k+3]=this.angle[i];data[k+4]=this.kind[i];data[k+5]=this.owner[i];data[k+6]=this.state[i]===UNIT_STATE.moving||this.state[i]===UNIT_STATE.retreat?1:0;data[k+7]=target?.x??this.x[i];data[k+8]=target?.y??this.y[i];data[k+9]=this.hp[i];data[k+10]=this.definition(i).health;data[k+11]=this.state[i];data[k+12]=this.target[i]>=0?this.target[i]+1:this.target[i]<-1?this.target[i]+1:0;data[k+13]=this.groupId[i];data[k+14]=this.shots[i];data[k+15]=this.supply[i];data[k+16]=this.modes[i];}return data;}
}
