import type {ArmyRoute} from '../configs/training';
import type {BotDifficulty} from '../configs/bots';
import type {DiplomaticAction} from '../configs/diplomacy';
import type {UnitType,Formation,UnitMode} from '../configs/units';
import type {BuildingType} from '../configs/buildings';
import type {MatchState,OwnershipChange} from '../../simulation/territory/types';
import type {MapConfig,ProceduralMap} from '../../map/types';
export type Command = {type:'RESUME_COMMERCE';playerId:number;unitId:number} | {type:'SET_AIR_RETURN';playerId:number;unitIds:number[];enabled:boolean} | {type:'PRODUCE_MISSILE';playerId:number;buildingId:number;missileType:'tactical'|'strategic'} | {type:'LAUNCH_MISSILE';playerId:number;buildingId:number;anchorId:number} | {type:'BEGIN_PREPARATION';name:string;countryId:string;botCountryIds:string[]} | {type:'SELECT_TERRAIN';anchorId:number} |  {type:'SURRENDER';playerId:number;opponentId:number} |  {type:'ATTACK_BUILDING';playerId:number;unitIds:number[];buildingId:number} |  {type:'SET_UNIT_MODE';playerId:number;unitIds:number[];mode:UnitMode} | {type:'ATTACK_UNIT';playerId:number;unitIds:number[];targetId:number} | {type:'DIPLOMACY_RESPONSE';playerId:number;offerId:number;accept:boolean} | {type:'DIPLOMACY_ACTION';playerId:number;action:DiplomaticAction;targetId?:number;warId?:number} | {type:'RETREAT_UNITS';playerId:number;unitIds:number[]} | {type:'START_SKIRMISH';playerId:number} | {type:'RECRUIT_UNITS';playerId:number;buildingId:number;unitType:UnitType;count:number} | {type:'MOVE_UNITS';playerId:number;unitIds:number[];target:{x:number;y:number};formation?:Formation;cohesion?:boolean;append?:boolean} | {type:'STOP_UNITS';playerId:number;unitIds:number[]} | {type:'ADD_ENTITIES';count:number} | {type:'SET_MOVING';enabled:boolean} | {type:'SET_COMBAT';enabled:boolean} | {type:'SET_PAUSED';enabled:boolean} | {type:'RESET'} | {type:'GENERATE_MAP';config:MapConfig;requestId:number} | {type:'PREPARE_MATCH';playerCount:number;botDifficulty?:BotDifficulty;victoryHoldSeconds?:number} | {type:'START_MATCH';spawnId:number;name:string;countryId?:string;botCountryIds?:string[]} | {type:'MOVE_EXPEDITION';playerId:number;target:{x:number;y:number}} | {type:'BUILD_STRUCTURE';playerId:number;buildingType:BuildingType;anchorId:number;rotation:number} | {type:'DEMOLISH_STRUCTURE';playerId:number;buildingId:number};
export type WorkerInput = {type:'SET_AI_DEBUG';enabled:boolean} |  {type:'COMMAND';command:Command} | {type:'RECYCLE';buffer:ArrayBuffer} | {type:'RECYCLE_UNITS';buffer:ArrayBuffer};
export interface GameplayProfile {aiMs:number;economyMs:number;combatMs:number;movementMs:number;territoryMs:number;occupancyMs:number;victoryMs:number;totalMs:number;samples:number;units:number;groups:number;routeSearches:number;encirclementScans:number;targetSearches:number;militarySnapshotMs:number;snapshotReuses:number;inFlight:number;unitBytes:number;pendingRoutes:number;routeQueueMs:number;routeCacheHits:number;unitMetadataBytes:number;}
export interface Snapshot {profile:GameplayProfile;type:'SNAPSHOT';tick:number;time:number;count:number;moving:number;combat:number;searching:number;simMs:number;snapshotMs:number;lagMs:number;paused:boolean;moveEnabled:boolean;combatEnabled:boolean;positions:ArrayBuffer;}
export type WorkerOutput = {type:'AI_DEBUG';bots:unknown;telemetry:unknown} |  {type:'UNITS';format:'compact-v1';tick:number;time:number;positions:ArrayBuffer;metadata:ArrayBuffer;pendingRoutes:number;routes?:ArmyRoute[]} | Snapshot | {type:'READY'} | {type:'ERROR';message:string;requestId?:number} | {type:'MAP';map:ProceduralMap;generationMs:number;requestId:number} | {type:'MATCH';state:MatchState;changes:OwnershipChange[]};
