/** Rates are per simulation second. All economy balancing lives here. */
export const ECONOMY_CONFIG = {
 tickRate: 2,
 initialStock: {money: 100, food: 120, mineral: 0, fuel: 10},
 initialPopulation: 80,
 cityCapacity: 300,
 cityGrowth: .4,
 newCitySettlers: 20,
 relocationPerSecond:1.5,
 minimumCivilianPopulation: 60,
 minimumCityCivilianPopulation: 20,
 emergencyMineralPerSecond: .15,
 maxBuildersFraction: .33,
 recoveryBase: .16,
 recoveryPopulationBonus: .023,
 recoveryMinimumMultiplier: .5,
 foodPerPerson: .008,
 refineryFoodConsumption: .2,
 mineFoodConsumption: .12,
 production:{cityMoney:6,farmFood:2,mineMineral:2,refineryFuel:1},
 factory: {consumption: {food:.25, mineral:1.25, fuel:.6}, moneyProduction:10},
 overcrowding: {
  firstLimit: 1.25, extremeLimit: 1.5,
  firstGrowthMultiplier: .5, secondGrowthMultiplier: .25,
  firstFoodMultiplier: 1.25, secondFoodMultiplier: 1.4, extremeFoodMultiplier: 1.6,
 },
 buildings: {
  city: {cost: {money:950, mineral:350, food:320}, builders:55},
  factory: {cost: {money:850, mineral:180, fuel:50}, builders:45},
  farm: {cost: {money:300, mineral:45}, builders:15},
  mine: {cost: {money:480, mineral:60}, builders:20},
  barracks: {cost: {money:750, mineral:80}, builders:35},
  refinery: {cost: {money:650, mineral:120}, builders:35},
  defense: {cost: {money:300, mineral:45}, builders:12},
 },
 bot: {foodForecastSeconds:90, foodReserveSeconds:30, moneyReserve:100, militaryFoodReserveSeconds:60, populationReserve:60, foodMargin:.25, targetMineralRate:3, factoryReserveSeconds:120},
};
