import {VisualControls} from './ui/visual-controls';
import {UnitWireDecoder} from '../../packages/shared/types/unit-wire';
const unitDecoder=new UnitWireDecoder();
import {HudControls} from './ui/hud-controls';
import {GameControls} from './ui/game-controls';
import {DiplomacyControls} from './ui/diplomacy-controls';
import {UnitControls} from './ui/unit-controls';
import './ui/style.css';
import './ui/hud.css';
import { FieldRenderer } from './renderer/field';
import { Minimap } from './ui/minimap';
import {MapControls} from './ui/map-controls';
import {MatchControls} from './ui/match-controls';
import {BuildControls} from './ui/build-controls';
import { ENGINE } from '../../packages/shared/configs/engine';
import type { Command,Snapshot,WorkerInput,WorkerOutput } from '../../packages/shared/types/protocol';
const get=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const formatter=new Intl.NumberFormat('pt-BR');let toastTimer:ReturnType<typeof setTimeout>;
function notify(message:string){get('notification').textContent=message;get('notification').classList.add('shown');clearTimeout(toastTimer);toastTimer=setTimeout(()=>get('notification').classList.remove('shown'),4000);}
async function start(){const field=new FieldRenderer();await field.init(get('canvas-host'));get('loading').remove();const minimap=new Minimap(get('minimap') as HTMLCanvasElement,field.camera);
 const worker=new Worker(new URL('../../packages/simulation/worker.ts',import.meta.url),{type:'module'});let current:Snapshot|null=null,previous:Snapshot|null=null,currentData:Float32Array|null=null,previousData:Float32Array|null=null,receivedAt=0;let militaryCurrent:ArrayBuffer|null=null,militaryPrevious:ArrayBuffer|null=null;let lastMetrics=0;let desiredMoving=false,desiredCombat=false,desiredPaused=false;
 let debugPanel:HTMLElement|null=null,debugData:unknown=null;if(new URLSearchParams(location.search).get('aiDebug')==='1'){const panel=document.createElement('details');panel.style.cssText='position:fixed;right:12px;top:80px;z-index:1000;background:#202020;color:#ddd;width:min(420px,calc(100vw - 24px));max-height:70vh;overflow:auto;padding:12px;font-size:11px';const title=document.createElement('summary');title.textContent='Debug IA · economia, diplomacia e telemetria';const output=document.createElement('pre');output.style.whiteSpace='pre-wrap';debugPanel=output;const button=document.createElement('button');button.textContent='Exportar telemetria';button.onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(debugData,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='webrts-telemetria.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};panel.append(title,button,output);document.body.append(panel);worker.postMessage({type:'SET_AI_DEBUG',enabled:true} satisfies WorkerInput);}
 const send=(command:Command)=>worker.postMessage({type:'COMMAND',command} satisfies WorkerInput);
 const mapControls=new MapControls(field,minimap,(config,requestId)=>send({type:'GENERATE_MAP',config,requestId}),notify);
 const matchControls=new MatchControls(field,minimap,mapControls,send,notify);
 const buildControls=new BuildControls(field,mapControls,matchControls,send,notify);
 const unitControls=new UnitControls(field,mapControls,matchControls,buildControls,send,notify);
 new DiplomacyControls(field,matchControls,mapControls,send,notify);
 new HudControls(field,mapControls,matchControls,buildControls,unitControls);new GameControls(matchControls,mapControls,send);const visualControls=new VisualControls(field,mapControls,minimap);
 worker.onerror=()=>{mapControls.failed('A geração foi interrompida. Recarregue a página.');get('run-state').textContent='Falha na simulação';notify('Não foi possível iniciar a simulação. Recarregue a página.');};
 worker.onmessage=(event:MessageEvent<WorkerOutput>)=>{const data=event.data;if(data.type==='AI_DEBUG'){debugData=data.telemetry;if(debugPanel)debugPanel.textContent=JSON.stringify(data.bots,null,2);return;}if(data.type==='ERROR'){notify(data.message);if(data.requestId!==undefined)mapControls.failed(data.message,data.requestId);else {matchControls.failed(data.message);buildControls.failed(data.message);}return;}if(data.type==='UNITS'){if(militaryPrevious)worker.postMessage({type:'RECYCLE_UNITS',buffer:militaryPrevious} satisfies WorkerInput,[militaryPrevious]);militaryPrevious=militaryCurrent;militaryCurrent=data.positions;unitControls.received(unitDecoder.decode(new Float32Array(data.positions),new Float32Array(data.metadata)),data.routes,data.pendingRoutes);return;}if(data.type==='MATCH'){matchControls.received(data.state,data.changes);return;}if(data.type==='MAP'){mapControls.received(data.map,data.generationMs,data.requestId);return;}if(data.type!=='SNAPSHOT')return;
 if(previous)worker.postMessage({type:'RECYCLE',buffer:previous.positions} satisfies WorkerInput,[previous.positions]);previous=current;previousData=currentData;current=data;currentData=new Float32Array(data.positions);receivedAt=performance.now();
 desiredPaused=data.paused;desiredMoving=data.moveEnabled;desiredCombat=data.combatEnabled;if(performance.now()-lastMetrics>250){lastMetrics=performance.now();const p=data.profile;get('real-routes').textContent=p.routeSearches+' / '+p.groups;get('profile-ai-combat').textContent=p.aiMs.toFixed(2)+' / '+p.combatMs.toFixed(2)+' ms';get('profile-move-territory').textContent=p.movementMs.toFixed(2)+' / '+(p.territoryMs+p.occupancyMs).toFixed(2)+' ms';get('profile-economy-victory').textContent=p.economyMs.toFixed(2)+' / '+p.victoryMs.toFixed(2)+' ms';get('real-targets').textContent=String(p.targetSearches);get('real-sieges').textContent=String(p.encirclementScans);get('real-snapshot').textContent=p.militarySnapshotMs.toFixed(2)+' ms · '+(p.unitBytes/1024).toFixed(1)+' KB';get('real-pool').textContent=p.snapshotReuses+' / '+p.inFlight;get('count').textContent=formatter.format(data.count);get('moving').textContent=formatter.format(data.moving);get('combat-count').textContent=formatter.format(data.combat);get('sim-ms').textContent=data.simMs.toFixed(2)+' ms';get('snapshot-ms').textContent=data.snapshotMs.toFixed(2)+' ms';get('tick').textContent=formatter.format(data.tick);get('snapshot-size').textContent=(data.positions.byteLength/1024).toFixed(0)+' KB';get('searching').textContent=formatter.format(data.searching);get('lag').textContent=data.lagMs.toFixed(0)+' ms';}get('run-state').textContent=matchControls.state?.phase==='finished'?'Partida encerrada':data.paused?'Pausado':'Simulação ativa';get('run-state').classList.toggle('paused',data.paused);
 get<HTMLButtonElement>('pause').textContent=data.paused?'Continuar':'Pausar';get('pause').setAttribute('aria-pressed',String(data.paused));get('pause-match').textContent=data.paused?'Continuar partida':'Pausar partida';get('pause-match').setAttribute('aria-pressed',String(data.paused));get('move').textContent=data.moveEnabled?'Parar movimento':'Movimentar todas';get('move').setAttribute('aria-pressed',String(data.moveEnabled));get('combat').textContent=data.combatEnabled?'Parar combate simulado':'Iniciar combate simulado';get('combat').setAttribute('aria-pressed',String(data.combatEnabled));document.querySelectorAll<HTMLButtonElement>('[data-add]').forEach(b=>b.disabled=data.count>=ENGINE.maxEntities);
 };
 document.querySelectorAll<HTMLButtonElement>('[data-add]').forEach(button=>button.onclick=()=>{const count=Number(button.dataset.add);mapControls.entities(true);send({type:'ADD_ENTITIES',count});notify('Adicionando '+formatter.format(count)+' entidades ao campo.');});
 get('move').onclick=()=>{mapControls.entities(true);desiredMoving=!desiredMoving;send({type:'SET_MOVING',enabled:desiredMoving});};get('combat').onclick=()=>{mapControls.entities(true);desiredCombat=!desiredCombat;send({type:'SET_COMBAT',enabled:desiredCombat});};const pause=()=>{desiredPaused=!desiredPaused;send({type:'SET_PAUSED',enabled:desiredPaused});};get('pause').onclick=pause;get('pause-match').onclick=pause;
 get('reset').onclick=()=>{desiredMoving=desiredCombat=desiredPaused=false;send({type:'RESET'});notify('Teste reiniciado com 2.000 entidades.');};get('zoom-in').onclick=()=>field.camera.zoomAt(1.25);get('zoom-out').onclick=()=>field.camera.zoomAt(.8);get('fit').onclick=()=>field.camera.fit();get('collapse').onclick=()=>{const body=get('lab-body'),hidden=!body.hidden;body.hidden=hidden;get('collapse').textContent=hidden?'+':'−';get('collapse').setAttribute('aria-expanded',String(!hidden));};const help=get<HTMLDialogElement>('help');get('help-button').onclick=()=>help.showModal();get('close-help').onclick=()=>help.close();help.addEventListener('click',e=>{if(e.target===help)help.close();});window.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&!(e.target instanceof HTMLElement&&['BUTTON','INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))&&!document.querySelector('dialog[open]')){e.preventDefault();pause();}});
 let elapsed=0,frames=0,lastUi=0,frameSmooth=16.7;const history:number[]=[];const chart=get('frame-chart') as HTMLCanvasElement;const chartCtx=chart.getContext('2d')!;
 field.app.ticker.add(ticker=>{const dt=Math.min(ticker.deltaMS/1000,.1);field.camera.update(dt);mapControls.updateHover();if(current&&currentData){const interval=previous?Math.max(1,current.time-previous.time):50;const alpha=current.paused||!current.moveEnabled?1:Math.min(1,(performance.now()-receivedAt)/interval);field.draw(currentData,previousData,current.count,alpha);}elapsed+=ticker.deltaMS;frames++;frameSmooth=frameSmooth*.92+ticker.deltaMS*.08;
 if(performance.now()-lastUi>250){get('visible').textContent=formatter.format(field.visible);get('real-units').textContent=(current?.profile.units??0)+' / '+field.military.visible;get('real-lod').textContent=field.military.lod;get('fps-top').textContent=Math.round(frames*1000/Math.max(1,elapsed))+' FPS';get('render-ms').textContent=field.renderMs.toFixed(2)+' ms';get('frame-ms').textContent=frameSmooth.toFixed(2)+' ms';get('zoom-level').textContent=Math.round(field.camera.zoom*100)+'%';visualControls.update();frames=0;elapsed=0;lastUi=performance.now();if(currentData&&current)minimap.draw(currentData,current.count,field.military.data);history.push(frameSmooth);if(history.length>65)history.shift();chartCtx.clearRect(0,0,260,40);chartCtx.strokeStyle='#505050';chartCtx.beginPath();chartCtx.moveTo(0,29);chartCtx.lineTo(260,29);chartCtx.stroke();chartCtx.strokeStyle='#82c9a0';chartCtx.beginPath();history.forEach((ms,i)=>{const x=i*4,y=40-Math.min(60,ms)/60*40;if(i===0)chartCtx.moveTo(x,y);else chartCtx.lineTo(x,y);});chartCtx.stroke();const memory=(performance as Performance&{memory?:{usedJSHeapSize:number}}).memory;get('memory').textContent=memory?(memory.usedJSHeapSize/1048576).toFixed(1)+' MB':'Indisponível';}
 });
 const lifecycle=new AbortController();type Tool={name:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean};execute:(input:unknown)=>unknown};const context=(document as Document&{modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
 if(context?.registerTool){const tools:Tool[]=[{name:'read_engine_metrics',description:'Read current WebRTS laboratory metrics.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({count:current?.count??0,tick:current?.tick??0,simMs:current?.simMs??0,visible:field.visible,paused:current?.paused??false})},{name:'add_test_entities',description:'Add synthetic entities to the visible WebRTS stress test.',inputSchema:{type:'object',properties:{count:{type:'integer',minimum:1,maximum:100000}},required:['count'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input)=>{const n=(input as {count?:unknown})?.count;if(typeof n!=='number'||!Number.isInteger(n)||n<1||n>100000)throw new Error('count must be an integer between 1 and 100000');const before=current?.count??0;send({type:'ADD_ENTITIES',count:n});const target=Math.min(ENGINE.maxEntities,before+n);await new Promise<void>((resolve,reject)=>{const start=performance.now();const check=()=>{if(current?.count===target){resolve();return;}if(performance.now()-start>3000){reject(new Error('Simulation did not acknowledge command'));return;}setTimeout(check,25);};check();});return {count:current?.count};}}];for(const tool of tools){try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{/* optional browser capability */}}}
 window.addEventListener('pagehide',()=>{lifecycle.abort();worker.terminate();field.app.destroy(true,{children:true,texture:true});},{once:true});
}
start().catch(error=>{console.error(error);get('loading').innerHTML='<strong>Não foi possível abrir o campo</strong><span>O navegador precisa de WebGL habilitado. Recarregue após verificar a aceleração gráfica.</span>';});
