import {BUILDINGS,RESOURCE_KEYS} from '../shared/configs/buildings';
import {GAME_PACING_CONFIG as C} from '../shared/configs/pacing';
import {TERRITORY_RULES} from '../shared/configs/territory';
import type {TerritoryMatch} from './territory/match';
import type {Army} from './units/army';
export class MatchTelemetry {
 private nextSample=0;private nextObserve=0;private owners=new Map<number,number>();private buildings=new Set<number>();
 readonly data={seed:'',mapSize:'',playerCount:0,duration:0,finished:false,first:{farm:null,mine:null,barracks:null,refinery:null,factory:null,troop:null,war:null,territory:null,cityCapture:null,relevantArmy:null}as Record<string,number|null>,milestones:{}as Record<number,Record<string,number>>,structuresBuilt:{}as Record<number,number>,cityCaptures:0,wars:[]as {id:number;start:number;duration:number|null}[],averageWarDuration:0,samples:[]as {time:number;remaining:number;countries:unknown[]}[],winnerId:null as number|null,victoryCause:null as string|null};
 constructor(private match:TerritoryMatch,private army:Army){this.data.seed=match.map.config.seed;this.data.mapSize=match.map.config.size;this.data.playerCount=match.state.playerCount;for(const b of match.state.buildings){this.owners.set(b.id,b.ownerId);this.buildings.add(b.id);}for(const p of match.state.players)this.data.milestones[p.id]={};}
 step(time:number){const d=this.data,s=this.match.state;d.duration=s.victory.finishedAt??time;d.finished=s.phase==='finished';d.winnerId=s.victory.winnerId;d.victoryCause=s.victory.reason;if(time<this.nextObserve&&!d.finished)return;this.nextObserve=time+1;
 const mark=(id:number,type:string)=>{d.first[type]??=time;d.milestones[id][type]??=time;};for(const b of s.buildings){if(!this.buildings.has(b.id)){this.buildings.add(b.id);d.structuresBuilt[b.ownerId]=(d.structuresBuilt[b.ownerId]??0)+1;mark(b.ownerId,b.type);}const old=this.owners.get(b.id);if(old!==undefined&&old!==b.ownerId&&b.type==='city'){mark(b.ownerId,'cityCapture');d.cityCaptures++;}this.owners.set(b.id,b.ownerId);}
 for(const p of s.players){let troops=0;for(let i=0;i<this.army.size;i++)if(this.army.ids[i]&&this.army.owner[i]===p.id)troops++;if(troops)mark(p.id,'troop');if(troops>=12)mark(p.id,'relevantArmy');if(p.territory>TERRITORY_RULES.initialCells)mark(p.id,'territory');}
 d.wars=s.diplomacy.wars.filter(w=>!w.exercise).map(w=>({id:w.id,start:w.startedAt,duration:w.endedAt===null?null:w.endedAt-w.startedAt}));if(d.wars.length){d.first.war??=d.wars[0].start;for(const w of s.diplomacy.wars)if(!w.exercise)d.milestones[w.attackerId].war??=w.startedAt;}const ended=d.wars.filter(w=>w.duration!==null);d.averageWarDuration=ended.length?ended.reduce((n,w)=>n+w.duration!,0)/ended.length:0;
 if(time>=this.nextSample||d.finished){this.nextSample=time+C.telemetryInterval;const countries=s.economies.map(e=>{let troops=0;for(let i=0;i<this.army.size;i++)if(this.army.ids[i]&&this.army.owner[i]===e.playerId)troops++;const consumption={money:0,food:e.foodConsumption,mineral:0,fuel:0};for(const b of s.buildings)if(b.ownerId===e.playerId)for(const k of RESOURCE_KEYS)if(k!=='food')consumption[k]+=(BUILDINGS[b.type].consumption?.[k]??0)*(b.operatingRate??1);const production=Object.fromEntries(RESOURCE_KEYS.map(k=>[k,e.rates[k]+consumption[k]]));return {id:e.playerId,population:e.population,troops,income:e.rates.money*60,production,consumption,balance:{...e.rates},stock:{...e.stock},builders:e.builders,territory:s.players.find(p=>p.id===e.playerId)!.territory,structures:s.buildings.filter(b=>b.ownerId===e.playerId).length};});d.samples.push({time,remaining:s.players.filter(p=>!p.defeated).length,countries});if(d.samples.length>C.maxTelemetrySamples)d.samples.shift();}
 }
}
