import {UnitWireEncoder,UNIT_WIRE_STRIDE} from '../shared/types/unit-wire';
import {UNIT_STRIDE} from '../shared/configs/units';
import { ENGINE } from '../shared/configs/engine';
import type { Snapshot, WorkerInput } from '../shared/types/protocol';
import { Simulation } from './engine';
import { FixedClock } from './fixed-clock';
import {DEFAULT_MAP_CONFIG,newMapSeed} from '../map/types';
const ctx=self as unknown as {postMessage:(message:unknown,transfer?:Transferable[])=>void;onmessage:((event:MessageEvent<WorkerInput>)=>void)|null};
let preparationClock=performance.now();let debugEnabled=false,lastDebug=0;const sim=new Simulation(true,true),clock=new FixedClock(1000/ENGINE.tickRate,ENGINE.maxCatchUp,performance.now());
let encoder=new UnitWireEncoder(),encodingArmy=sim.army,fullUnits=new Float32Array(0),lastRoutesRevision=-1,lastRoutesCount=-1;const unitPool:ArrayBuffer[]=[];let unitInFlight=0;let unitMetadataBytes=0;let unitSnapshotMs=0;let unitReused=0;const pool:ArrayBuffer[]=[];let inFlight=0;let simMs=0;let dirty=true;let lastSent=0;let lastMatchSent=0;let sentRevision=-1;
function send(){if(inFlight>=3)return;const size=sim.world.count*5*4;let buffer=pool.pop();if(!buffer||buffer.byteLength!==size)buffer=new ArrayBuffer(size);const start=performance.now();sim.snapshot(new Float32Array(buffer));const snapshotMs=performance.now()-start;const data:Snapshot={type:'SNAPSHOT',profile:{...sim.profile,units:sim.army?.count??0,groups:sim.army?.groups.size??0,routeSearches:sim.army?.navigation.searches??0,encirclementScans:sim.territorial?.scans??0,targetSearches:sim.combat?.searching??0,militarySnapshotMs:unitSnapshotMs,snapshotReuses:unitReused,inFlight:unitInFlight,unitBytes:(sim.army?.count??0)*UNIT_WIRE_STRIDE*4,pendingRoutes:sim.army?.routes.pending??0,routeQueueMs:sim.army?.routes.lastMs??0,routeCacheHits:sim.army?.navigation.cacheHits??0,unitMetadataBytes},tick:sim.tick,time:performance.timeOrigin+performance.now(),count:sim.world.count,moving:sim.moveEnabled?sim.world.count:0,combat:sim.engaged,searching:sim.combatEnabled?sim.world.count:0,simMs,snapshotMs,lagMs:clock.droppedMs,paused:sim.paused,moveEnabled:sim.moveEnabled,combatEnabled:sim.combatEnabled,positions:buffer};ctx.postMessage(data,[buffer]);inFlight++;dirty=false;lastSent=performance.now();}
ctx.onmessage=(event)=>{try{const input=event.data;if(input.type==='SET_AI_DEBUG'){debugEnabled=input.enabled;return;}if(input.type==='RECYCLE_UNITS'){unitInFlight=Math.max(0,unitInFlight-1);if(unitPool.length<3)unitPool.push(input.buffer);return;}if(input.type==='RECYCLE'){inFlight=Math.max(0,inFlight-1);if(pool.length<3)pool.push(input.buffer);return;}if(input.command.type==='GENERATE_MAP'){const started=performance.now();sim.command(input.command);const map=sim.map!;sentRevision=-1;sendUnits();ctx.postMessage({type:'MAP',map,generationMs:performance.now()-started,requestId:input.command.requestId});clock.reset(performance.now());return;}sim.command(input.command,'human',true);if(input.command.type==='BEGIN_PREPARATION')preparationClock=performance.now();if(['BEGIN_PREPARATION','SELECT_TERRAIN','PREPARE_MATCH','START_MATCH','MOVE_EXPEDITION','BUILD_STRUCTURE','DEMOLISH_STRUCTURE','RECRUIT_UNITS','START_SKIRMISH','DIPLOMACY_ACTION','DIPLOMACY_RESPONSE'].includes(input.command.type))sendMatch();if(['START_MATCH','PREPARE_MATCH','RECRUIT_UNITS','MOVE_UNITS','STOP_UNITS','RETREAT_UNITS','START_SKIRMISH'].includes(input.command.type))sendUnits();if(input.command.type==='RESET')clock.reset(performance.now());dirty=true;}catch(error){ctx.postMessage({type:'ERROR',message:error instanceof Error?error.message:String(error),requestId:event.data.type==='COMMAND'&&event.data.command.type==='GENERATE_MAP'?event.data.command.requestId:undefined});}};
setInterval(()=>{const now=performance.now();let steps=0;if(sim.match?.state.preparation?.active){sim.step(Math.max(0,(now-preparationClock)/1000));preparationClock=now;clock.reset(now);steps=1;}else steps=clock.advance(now,sim.paused,()=>{const start=performance.now();sim.step();simMs=performance.now()-start;});for(const message of sim.army?.routeErrors.splice(0)??[])ctx.postMessage({type:'ERROR',message});if(steps||dirty||performance.now()-lastSent>500){send();sendUnits();}if(debugEnabled&&sim.bots&&performance.now()-lastDebug>=1000){lastDebug=performance.now();ctx.postMessage({type:'AI_DEBUG',bots:sim.bots.debug(),telemetry:sim.telemetry?.data});}if(sim.match&&sim.match.state.revision!==sentRevision&&performance.now()-lastMatchSent>=100)sendMatch();},10);
ctx.postMessage({type:'READY'});

const started=performance.now();sim.command({type:'GENERATE_MAP',config:{...DEFAULT_MAP_CONFIG,seed:newMapSeed()},requestId:0});ctx.postMessage({type:'MAP',map:sim.map!,generationMs:performance.now()-started,requestId:0});clock.reset(performance.now());

function sendMatch(){if(!sim.match)return;ctx.postMessage({type:'MATCH',state:sim.match.state,changes:sim.match.drainChanges()});lastMatchSent=performance.now();sentRevision=sim.match.state.revision;}

function sendUnits(){if(unitInFlight>=3)return;const count=sim.army?.visibleCount??0,size=count*UNIT_WIRE_STRIDE*4;if(encodingArmy!==sim.army){encoder=new UnitWireEncoder();encodingArmy=sim.army;lastRoutesRevision=-1;lastRoutesCount=-1;}let buffer=unitPool.pop();if(!buffer||buffer.byteLength!==size)buffer=new ArrayBuffer(size);else unitReused++;if(fullUnits.length!==count*UNIT_STRIDE)fullUnits=new Float32Array(count*UNIT_STRIDE);const start=performance.now();sim.army?.snapshot(fullUnits);const metadata=new Float32Array(encoder.encode(fullUnits,new Float32Array(buffer)));let routes;if(lastRoutesRevision!==(sim.army?.routeRevision??0)||lastRoutesCount!==(sim.army?.groups.size??0)){routes=sim.army?.routeViews()??[];lastRoutesRevision=sim.army?.routeRevision??0;lastRoutesCount=sim.army?.groups.size??0;}unitSnapshotMs=performance.now()-start;unitMetadataBytes=metadata.byteLength;ctx.postMessage({type:'UNITS',format:'compact-v1',tick:sim.tick,time:performance.timeOrigin+performance.now(),positions:buffer,metadata:metadata.buffer,pendingRoutes:sim.army?.routes.pending??0,routes},[buffer,metadata.buffer]);unitInFlight++;}
