import {countryLabel} from '../../../packages/shared/configs/countries';
import {type DiplomaticAction} from '../../../packages/shared/configs/diplomacy';
import type {MatchState} from '../../../packages/simulation/territory/types';
import type {RelationState} from '../../../packages/simulation/diplomacy/types';
import type {Command} from '../../../packages/shared/types/protocol';
import type {FieldRenderer} from '../renderer/field';
import type {MatchControls} from './match-controls';
import type {MapControls} from './map-controls';
const get=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const labels:Record<RelationState,string>={NEUTRAL:'Neutro',ALLIED:'Aliado',TENSION:'Tensão',WAR:'Em guerra',TRUCE:'Trégua'};
export class DiplomacyControls {
 private state:MatchState|null=null;private lastEvent=0;
 constructor(private field:FieldRenderer,match:MatchControls,private map:MapControls,send:(command:Command)=>void,private notify:(text:string)=>void){const previous=match.onState;match.onState=s=>{previous?.(s);this.state=s;if(!s||s.phase!=='playing'){this.lastEvent=0;field.military.enemies.clear();field.military.allies.clear();}this.refresh();};const selection=match.onSelection;match.onSelection=cell=>{selection?.(cell);get('cell-war-status').textContent='';if(!cell||!this.state||cell.terrain==='water')return;const pocket=this.state.encirclements.find(p=>p.cellIds.includes(cell.id));if(pocket){get('cell-war-status').textContent='Bolsão cercado · '+(pocket.blocked==='troops'?'tropas impedem anexação':pocket.blocked==='structures'?'estruturas impedem anexação':Math.ceil(pocket.remaining)+' s para anexação');return;}if(cell.ownerId===null){get('cell-war-status').textContent='Terra neutra: conquistada pela passagem de tropas.';return;}if(cell.ownerId===1)return;const relation=this.state.diplomacy.relations.find(r=>r.a===1&&r.b===cell.ownerId);get('cell-war-status').textContent=relation?.state==='WAR'?'Território hostil. Destrua estruturas e elimine resistência antes de ocupar.':relation?.state==='ALLIED'?'Território aliado: passagem livre e suprimento preservado.':relation?.state==='TRUCE'?'Trégua: combate e conquista suspensos.':'País neutro: não pode ser conquistado sem declaração de guerra.';};get<HTMLSelectElement>('diplomacy-target').onchange=()=>this.refresh();get<HTMLSelectElement>('diplomacy-war').onchange=()=>this.refresh();document.querySelectorAll<HTMLButtonElement>('[data-diplomacy]').forEach(b=>b.onclick=()=>send({type:'DIPLOMACY_ACTION',playerId:1,action:b.dataset.diplomacy as DiplomaticAction,targetId:Number(get<HTMLSelectElement>('diplomacy-target').value),warId:Number(get<HTMLSelectElement>('diplomacy-war').value)}));get('focus-country').onclick=()=>{const id=Number(get<HTMLSelectElement>('diplomacy-target').value),player=this.state?.players.find(p=>p.id===id),city=this.state?.cities.find(c=>c.ownerId===id),spawn=this.state?.spawns.find(s=>s.id===player?.spawnId),cell=this.map.map?.cells[city?.anchorId??spawn?.anchorId??-1];if(cell){field.camera.x=cell.x;field.camera.y=cell.y;field.camera.zoom=Math.max(.65,field.camera.zoom);}};}
 private choices(id:string,items:{id:number;name:string}[]){const select=get<HTMLSelectElement>(id),chosen=Number(select.value);if([...select.options].map(o=>o.value).join(',')!==items.map(i=>i.id).join(',')){select.replaceChildren();for(const item of items){const o=document.createElement('option');o.value=String(item.id);o.textContent=item.name;select.append(o);}if(items.some(i=>i.id===chosen))select.value=String(chosen);}return Number(select.value);}
 private refresh(){const s=this.state,playing=s?.phase==='playing';get('diplomacy-section').hidden=!playing||!!s?.players[0]?.defeated;if(!playing||s.players[0]?.defeated||!s.players.some(p=>p.id!==1&&!p.defeated)){get('diplomacy-section').hidden=true;get('diplomacy-events').replaceChildren();get('encirclement-list').replaceChildren();return;}const d=s.diplomacy,name=(id:number)=>s.players.find(p=>p.id===id)?.name??'País '+id,target=this.choices('diplomacy-target',s.players.filter(p=>p.id!==1&&!p.defeated).map(p=>({id:p.id,name:countryLabel(p)}))),r=d.relations.find(r=>r.a===1&&r.b===target)!,wars=d.wars.filter(w=>w.endedAt===null),warId=this.choices('diplomacy-war',wars.map(w=>({id:w.id,name:name(w.attackerId)+' × '+name(w.defenderId)}))),war=wars.find(w=>w.id===warId),pending=d.offers.filter(o=>o.status==='pending'&&o.from===1&&o.to===target);get('diplomacy-relation').textContent=labels[r.state];get('diplomacy-relation').dataset.relation=r.state;get('diplomacy-timer').textContent=r.state==='TENSION'?'Declaração disponível em '+Math.ceil(Math.max(0,r.readyAt-d.time))+' s':r.state==='TRUCE'?'Trégua termina em '+Math.ceil(Math.max(0,r.truceUntil-d.time))+' s':pending.length?'Proposta aguardando resposta.':'';get('diplomacy-war-row').hidden=!wars.length;
 const relation=(a:number,b:number)=>d.relations.find(r=>r.a===Math.min(a,b)&&r.b===Math.max(a,b)),incompatible=(a:number,b:number)=>a===b||['ALLIED','TRUCE','WAR'].includes(relation(a,b)?.state??'NEUTRAL'),opponents=(w:typeof wars[number],actor:number)=>[w.attackerId,...w.attackerAllies].includes(actor)?[w.defenderId,...w.defenderAllies]:[w.attackerId,...w.attackerAllies];const disable=(action:string,value:boolean)=>{const b=document.querySelector<HTMLButtonElement>(`[data-diplomacy="${action}"]`)!;b.disabled=value;};disable('request_alliance',r.state!=='NEUTRAL'||pending.some(o=>o.kind==='alliance'));disable('break_alliance',r.state!=='ALLIED'||wars.some(w=>[[w.attackerId,...w.attackerAllies],[w.defenderId,...w.defenderAllies]].some(side=>side.includes(1)&&side.includes(target))));disable('prepare_war',r.state!=='NEUTRAL');disable('cancel_preparation',r.state!=='TENSION'||r.preparedBy!==1);disable('declare_war',r.state!=='TENSION'||r.preparedBy!==1||d.time+1e-7<r.readyAt);disable('request_truce',!wars.some(w=>[w.attackerId,w.defenderId].includes(1)&&[w.attackerId,w.defenderId].includes(target))||pending.some(o=>o.kind==='truce'));disable('call_ally',!war||![war.attackerId,war.defenderId].includes(1)||r.state!=='ALLIED'||[war.attackerId,war.defenderId,...war.attackerAllies,...war.defenderAllies].includes(target)||pending.some(o=>o.kind==='support')||!!war&&opponents(war,1).some(id=>incompatible(target,id)));const relationTo=(id:number)=>d.relations.find(r=>r.a===Math.min(id,1)&&r.b===Math.max(id,1));disable('join_war',!war||[war.attackerId,war.defenderId,...war.attackerAllies,...war.defenderAllies].includes(1)||![war.attackerId,war.defenderId].some(id=>relationTo(id)?.state==='ALLIED')||!!war&&opponents(war,relationTo(war.attackerId)?.state==='ALLIED'?war.attackerId:war.defenderId).some(id=>incompatible(1,id)));
 this.field.military.enemies=new Set(s.combatOpponents);this.field.military.allies=new Set(d.relations.filter(r=>r.a===1&&r.state==='ALLIED').map(r=>r.b));get('diplomacy-events').replaceChildren();for(const e of d.events.slice(-12).reverse()){const li=document.createElement('li'),time=document.createElement('time'),text=document.createElement('span');time.textContent=Math.floor(e.time/60)+':'+String(Math.floor(e.time%60)).padStart(2,'0');text.textContent=e.message;li.append(time,text);get('diplomacy-events').append(li);}const latest=d.events.at(-1);if(latest&&latest.id>this.lastEvent){this.lastEvent=latest.id;this.notify(latest.message);}get('encirclement-summary').textContent=s.encirclements.length+' bolsões cercados';get('encirclement-list').replaceChildren();for(const p of s.encirclements){const button=document.createElement('button');button.className='pocket-item';const title=document.createElement('strong'),meta=document.createElement('span');title.textContent=name(p.ownerId)+' · '+p.cellIds.length+' hexágonos';meta.textContent='Para '+name(p.claimantId)+' · '+(p.blocked==='troops'?'tropas defendendo':p.blocked==='structures'?'estruturas presentes':Math.ceil(p.remaining)+' s');button.append(title,meta);button.onclick=()=>{const c=this.map.map!.cells[p.cellIds[0]];this.field.camera.x=c.x;this.field.camera.y=c.y;this.field.camera.zoom=Math.max(this.field.camera.zoom,.8);};get('encirclement-list').append(button);}get('war-summary').textContent=wars.length+' guerras ativas';}
}
