import {VICTORY} from '../../../packages/shared/configs/victory';
import {BOT_PERSONALITY_NAMES} from '../../../packages/shared/configs/bots';
import type {MatchState} from '../../../packages/simulation/territory/types';
import type {Command} from '../../../packages/shared/types/protocol';
import type {MatchControls} from './match-controls';
import type {MapControls} from './map-controls';
const get=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id)as T;
const time=(n:number)=>Math.floor(n/60)+':'+String(Math.floor(n%60)).padStart(2,'0');
export class GameControls {
 private state:MatchState|null=null;private finished=false;
 constructor(match:MatchControls,map:MapControls,send:(c:Command)=>void){window.addEventListener('country-selected',()=>this.refresh(send));for(const id of ['bot-difficulty','victory-hold'])get(id).addEventListener('change',()=>match.prepare());get<HTMLInputElement>('victory-hold').value=String(VICTORY.holdSeconds);document.querySelectorAll<HTMLElement>('[data-victory-rules]').forEach(el=>el.textContent='Vitória: controle de '+Math.round(VICTORY.territoryFraction*100)+'% de toda a terra, mantido pelo tempo escolhido.');const previous=match.onState;match.onState=s=>{previous?.(s);this.state=s;this.refresh(send);};const repeat=document.createElement('button');repeat.id='result-repeat-map';repeat.textContent='Repetir este mapa';repeat.onclick=()=>{get<HTMLDialogElement>('match-result').close();if(map.map)map.request(map.map.config);};get('result-replay').after(repeat);get('result-replay').textContent='Nova partida';get('result-map').onclick=()=>get<HTMLDialogElement>('match-result').close();get('reopen-result').onclick=()=>get<HTMLDialogElement>('match-result').showModal();get('result-replay').onclick=()=>{get<HTMLDialogElement>('match-result').close();map.newGame();};}
 private refresh(send:(c:Command)=>void){const s=this.state;for(const id of ['bot-difficulty','victory-hold'])get<HTMLInputElement>(id).disabled=!!s&&(s.phase!=='preparation'||!!s.preparation?.active);const active=!!s&&s.phase!=='preparation';get('victory-status').hidden=!active;if(!active){this.finished=false;get<HTMLDialogElement>('match-result').close();get('incoming-offers').replaceChildren();get('bot-activity').replaceChildren();return;}const v=s.victory,name=(id:number)=>s.players.find(p=>p.id===id)?.name??'País '+id;get('victory-progress').textContent=s.phase==='finished'?'Partida encerrada':v.leaderId!==null?name(v.leaderId)+' · '+v.percent.toFixed(1)+'%':'Objetivo: '+Math.round(VICTORY.territoryFraction*100)+'% da terra';get('victory-countdown').textContent=v.leaderId!==null?(v.winnerId!==null?'Vitória de '+name(v.winnerId):Math.ceil(Math.max(0,v.requiredSeconds-v.heldSeconds))+' s para vencer'):'Mantenha o domínio por '+v.requiredSeconds+' s';get('reopen-result').hidden=s.phase!=='finished'&&!s.players[0]?.defeated;
 get('incoming-offers').replaceChildren();for(const o of s.diplomacy.offers.filter(o=>o.to===1&&o.status==='pending'&&o.from===Number(get('country-dialog').dataset.country))){const card=document.createElement('div');card.className='incoming-offer';const label=document.createElement('p');label.textContent=name(o.from)+' propõe '+(o.kind==='alliance'?'aliança':o.kind==='truce'?'trégua':'apoio militar')+'.';const buttons=document.createElement('div');for(const accept of [true,false]){const b=document.createElement('button');b.textContent=accept?'Aceitar':'Recusar';b.disabled=s.phase!=='playing';b.onclick=()=>send({type:'DIPLOMACY_RESPONSE',playerId:1,offerId:o.id,accept});buttons.append(b);}card.append(label,buttons);get('incoming-offers').append(card);}
 get('bot-activity').replaceChildren();if(!s.bots.length)get('bot-activity').textContent='Bots desativados nesta partida.';for(const bot of s.bots){const row=document.createElement('div');row.className='bot-activity-row';const title=document.createElement('strong'),meta=document.createElement('span'),goal=document.createElement('span');title.textContent=name(bot.playerId)+' · '+BOT_PERSONALITY_NAMES[bot.personality];meta.textContent=bot.action+' · '+bot.army+' tropas';goal.textContent=bot.goal;row.append(title,meta,goal);get('bot-activity').append(row);}
 if((s.phase==='finished'||s.players[0]?.defeated)&&!this.finished){this.finished=true;get('result-title').textContent=s.phase==='finished'&&v.winnerId===null?'Empate':v.winnerId===1?'Vitória':'Derrota';get('result-winner').textContent=s.phase==='finished'&&v.reason==='cities'?(v.winnerId===null?'Todos os países perderam suas cidades.':name(v.winnerId)+' é o último país com cidades e venceu a partida.'):s.players[0]?.defeated?'Seu país perdeu todas as cidades e foi derrotado.':name(v.winnerId!)+' manteve pelo menos '+Math.round(VICTORY.territoryFraction*100)+'% da terra e venceu a partida.';get('result-own').textContent=(s.players[0].territory/s.landTotal*100).toFixed(1)+'%';get('result-control').textContent=v.percent.toFixed(1)+'%';get('result-duration').textContent=time(v.finishedAt??v.time);get('result-hold').textContent=v.reason==='cities'||s.players[0]?.defeated?'Perda de todas as cidades':v.requiredSeconds+' s';get<HTMLDialogElement>('match-result').showModal();}}
}
