import {countryLabel} from '../../../packages/shared/configs/countries';
import {DIPLOMACY} from '../../../packages/shared/configs/diplomacy';
import type {FieldRenderer} from '../renderer/field';
import type {MapControls} from './map-controls';
import type {MatchControls} from './match-controls';
import type {BuildControls} from './build-controls';
import type {UnitControls} from './unit-controls';
import {icon} from './icons';
const get=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const fmt=new Intl.NumberFormat('pt-BR',{maximumFractionDigits:0});
export class HudControls {
 private country=1;private barracks=0;private playing=false;private phase:string|null=null;private defeated=false;
 constructor(private field:FieldRenderer,private map:MapControls,private match:MatchControls,build:BuildControls,units:UnitControls){
  const surface=document.createElement('div');surface.id='hud-surface';surface.innerHTML=`
   <button id="game-menu-button" aria-label="Abrir menu da partida">☰ <span>Menu</span></button>
   <aside id="countries-panel" aria-label="Países da partida" hidden><button id="toggle-countries" aria-expanded="true" aria-controls="countries-list">Países <span>−</span></button><div id="countries-list"></div></aside>
   <section id="missile-alerts" aria-live="assertive" hidden></section><section id="war-alerts" aria-label="Alertas de preparação de guerra" hidden></section>
   <footer id="construction-bar" aria-label="Construções e atalhos de teclado" hidden></footer>
   <section id="construction-options" aria-label="Construção selecionada"></section>
   <dialog id="menu-dialog"><div class="dialog-title"><h2>Menu da partida</h2><button data-close aria-label="Fechar menu">×</button></div><div id="menu-content"></div></dialog>
   <dialog id="country-dialog"><div class="dialog-title"><h2 id="country-modal-title">País</h2><button data-close aria-label="Fechar detalhes do país">×</button></div><p id="country-details"></p><div id="country-resources"></div><button id="country-focus">Ver território</button><div id="country-diplomacy"></div></dialog>
   <dialog id="recruit-dialog"><div class="dialog-title"><h2 id="recruit-modal-title">Quartel</h2><button data-close aria-label="Fechar recrutamento">×</button></div><p>Recrutar unidades</p><div id="recruit-content"></div><section id="training-queue" aria-label="Quatro espaços de treinamento"></section></dialog>`;
  get('game').append(surface);get('cell-inspector').setAttribute('aria-hidden','true');get('cell-inspector').querySelector('.panel-heading')?.remove();const minimap=document.querySelector<HTMLElement>('.minimap-wrap')!;minimap.querySelector('.minimap-label')?.remove();get('current-seed').remove();minimap.append(document.querySelector('.camera-controls')!);get<HTMLCanvasElement>('minimap').width=640;get<HTMLCanvasElement>('minimap').height=426;
  surface.querySelectorAll<HTMLDialogElement>('dialog').forEach(d=>{d.querySelector<HTMLButtonElement>('[data-close]')!.onclick=()=>d.close();d.addEventListener('click',e=>{if(e.target===d)d.close();});});
  get('construction-bar').append(get('open-construction-menu'),get('building-catalog'),get('cancel-work-tool'));
  get('construction-options').append(get('building-options'));
  get('country-diplomacy').append(get('diplomacy-section'));
  const recruit=get('recruit-content');recruit.append(get('recruit-barracks'));document.querySelectorAll('.recruit-row').forEach(row=>recruit.append(row));recruit.append(get('recruit-note'));
  get('countries-panel').append(get('victory-status'));
  const menu=get('menu-content');menu.append(get('view-tabs'));menu.append(document.querySelector('.army-section')!);menu.append(document.querySelector('.capital-actions')!);menu.append(get('bot-activity').parentElement!);menu.append(get('demolish-building'));get('demolish-building').textContent='Cancelar obra selecionada';menu.append(get('send-expedition'));
  const newGame=document.createElement('button');newGame.textContent='Nova partida · novo mapa';newGame.onclick=()=>{get<HTMLDialogElement>('menu-dialog').close();map.newGame();};menu.append(newGame);const helpButton=get('help-button');menu.append(helpButton);helpButton.textContent='Controles';helpButton.addEventListener('click',()=>get<HTMLDialogElement>('menu-dialog').close());
  document.querySelector<HTMLElement>('.topbar')!.hidden=true;
  get('game-menu-button').onclick=()=>get<HTMLDialogElement>('menu-dialog').showModal();
  for(const tab of ['match','map','stress'])get('tab-'+tab).addEventListener('click',()=>get<HTMLDialogElement>('menu-dialog').close());
  for(const key of ['money','population','workers','food','mineral','fuel']){const label=document.querySelector<HTMLElement>(`.resource-card.${key}>span`)!;const name=label.textContent!;label.innerHTML=icon(key);label.title=name;label.setAttribute('aria-label',name);label.parentElement!.setAttribute('aria-label',name);}
  get('toggle-countries').onclick=()=>{const list=get('countries-list');list.hidden=!list.hidden;get('toggle-countries').setAttribute('aria-expanded',String(!list.hidden));get('toggle-countries').querySelector('span')!.textContent=list.hidden?'+':'−';};
  get('country-focus').onclick=()=>{const s=match.state,city=s?.cities.find(c=>c.ownerId===this.country),player=s?.players.find(p=>p.id===this.country),spawn=s?.spawns.find(p=>p.id===player?.spawnId),cell=map.map?.cells[city?.anchorId??spawn?.anchorId??-1];if(cell){field.camera.x=cell.x;field.camera.y=cell.y;field.camera.zoom=Math.max(.65,field.camera.zoom);}get<HTMLDialogElement>('country-dialog').close();};
  map.onUserSelect=cell=>{if(match.state?.phase!=='playing'||match.state.players[0]?.defeated||!cell)return;if(build.isPlacing){build.placeAt(cell);return;}const port=match.state.buildings.find(b=>b.type==='port'&&b.ownerId===1&&!b.construction&&b.cellIds.includes(cell.id));if(port){build.openPort(port.id);return;}const silo=match.state.buildings.find(b=>b.type==='silo'&&b.ownerId===1&&!b.construction&&b.cellIds.includes(cell.id));if(silo){build.openSilo(silo.id);return;}const b=match.state.buildings.find(b=>b.type==='barracks'&&b.ownerId===1&&b.cellIds.includes(cell.id));if(b){this.barracks=b.id;units.recruitAt(b.id);}};
  const previous=match.onState;match.onState=s=>{previous?.(s);const playing=s?.phase==='playing'&&!s.players[0]?.defeated,active=!!s&&s.phase!=='preparation';get('game').classList.toggle('in-match',active);get('countries-panel').hidden=!active;get('construction-bar').hidden=!playing;get('construction-options').hidden=!playing;if(!active&&get('tab-match').getAttribute('aria-selected')==='true')get<HTMLButtonElement>('tab-map').click();
   if(playing&&!this.playing)get<HTMLButtonElement>('tab-match').click();this.playing=!!playing;
   const phase=s?.phase??null,defeated=!!s?.players[0]?.defeated;if(!playing&&(phase!==this.phase||defeated!==this.defeated))surface.querySelectorAll<HTMLDialogElement>('dialog[open]').forEach(d=>d.close());this.phase=phase;this.defeated=defeated;if(!active){get('countries-list').replaceChildren();get('war-alerts').replaceChildren();get('war-alerts').hidden=true;return;}
   if(get<HTMLDialogElement>('recruit-dialog').open&&!s.buildings.some(b=>b.id===this.barracks&&b.ownerId===1&&b.type==='barracks'))get<HTMLDialogElement>('recruit-dialog').close();
   const list=get('countries-list');for(const p of s.players){let button=list.querySelector<HTMLButtonElement>(`[data-country="${p.id}"]`);if(!button){button=document.createElement('button');button.dataset.country=String(p.id);const color=document.createElement('i'),name=document.createElement('span'),count=document.createElement('b');button.append(color,name,count);button.onclick=()=>this.openCountry(p.id);list.append(button);}button.querySelector('i')!.style.backgroundColor='#'+p.color.toString(16).padStart(6,'0');button.querySelector('span')!.textContent=countryLabel(p);button.querySelector('b')!.textContent=p.defeated?'Derrotado':fmt.format(p.territory);button.dataset.defeated=String(p.defeated);button.title=p.name+' · '+fmt.format(p.territory)+' hexágonos';}
   const incoming=s.operations?.missiles??[];get('missile-alerts').hidden=!incoming.length;get('missile-alerts').textContent=incoming.map(m=>'Míssil em voo · impacto em '+Math.ceil(m.remaining)+' s · raio '+m.radius+' hex').join(' | ');this.warAlerts();if(get<HTMLDialogElement>('country-dialog').open)this.countryDetails();
  };
 }
 private warAlerts(){const s=this.match.state,panel=get('war-alerts');if(!s)return;const relations=s.diplomacy.relations.filter(r=>(r.a===1||r.b===1)&&r.state==='TENSION'&&r.preparedBy!==null);const ids=new Set(relations.map(r=>String(r.a===1?r.b:r.a)));for(const node of [...panel.children])if(!ids.has((node as HTMLElement).dataset.country!))node.remove();panel.hidden=!relations.length;for(const r of relations){const id=r.a===1?r.b:r.a,name=s.players.find(p=>p.id===id)?.name??'País '+id;let card=panel.querySelector<HTMLButtonElement>('[data-country="'+id+'"]');if(!card){card=document.createElement('button');card.dataset.country=String(id);card.innerHTML='<strong></strong><span></span><progress max="'+DIPLOMACY.preparationSeconds+'"></progress>';card.onclick=()=>this.openCountry(id);panel.append(card);}const remaining=Math.max(0,r.readyAt-s.diplomacy.time);card.querySelector('strong')!.textContent=r.preparedBy===1?'Preparando guerra contra '+name:name+' prepara guerra contra você';card.querySelector('span')!.textContent=remaining>0?Math.ceil(remaining)+' s até poder declarar guerra':r.preparedBy===1?'Você já pode declarar guerra':name+' já pode declarar guerra';const bar=card.querySelector('progress')!;bar.value=Math.min(DIPLOMACY.preparationSeconds,DIPLOMACY.preparationSeconds-remaining);bar.setAttribute('aria-label','Progresso da preparação de guerra');}}
 private openCountry(id:number){this.country=id;const select=get<HTMLSelectElement>('diplomacy-target');if(id!==1&&!this.match.state?.players.find(p=>p.id===id)?.defeated){select.value=String(id);select.dispatchEvent(new Event('change'));}this.countryDetails();get('country-dialog').dataset.country=String(id);window.dispatchEvent(new Event('country-selected'));get<HTMLDialogElement>('country-dialog').showModal();}
 private countryDetails(){const s=this.match.state,p=s?.players.find(p=>p.id===this.country),economy=s?.economies.find(e=>e.playerId===this.country);if(!s||!p||!economy)return;get('country-modal-title').textContent=countryLabel(p);get('country-dialog').dataset.own=String(p.id===1||p.defeated);get('country-details').textContent=`${p.defeated?'País derrotado':p.human?'Seu país':'País controlado por bot'} · ${fmt.format(p.territory)} hexágonos · ${(p.territory/s.landTotal*100).toFixed(1)}% da terra · ${s.buildings.filter(b=>b.ownerId===p.id).length} construções`;
  const resources=get('country-resources');resources.replaceChildren();for(const [label,value]of [['População',`${fmt.format(economy.population)} / ${economy.capacity}`],['Construtores',fmt.format(Math.floor(economy.builders))+' / '+fmt.format(Math.floor(economy.maxBuilders))],['Recuperação de Construtores',fmt.format(economy.builderRecovery*60)+' / min'],['Consumo de comida',fmt.format(economy.foodConsumption*60)+' / min'],['Dinheiro',fmt.format(economy.stock.money)],['Comida',fmt.format(economy.stock.food)],['Minério',fmt.format(economy.stock.mineral)],['Combustível',fmt.format(economy.stock.fuel)]]){const row=document.createElement('div'),name=document.createElement('span'),amount=document.createElement('strong');name.textContent=label;amount.textContent=value;row.append(name,amount);resources.append(row);}
  for(const b of s.buildings.filter(b=>b.ownerId===p.id&&b.city)){const city=b.city!,row=document.createElement('div'),name=document.createElement('span'),amount=document.createElement('strong');name.textContent='Cidade '+b.id;amount.textContent=fmt.format(city.population)+' / '+city.capacity+' · excedente '+fmt.format(city.excess)+' · +'+fmt.format(city.growthRate*60)+'/min · comida '+fmt.format(city.foodConsumption*60)+'/min';row.append(name,amount);resources.append(row);}
 }
}
