import {BUILDINGS} from '../../../packages/shared/configs/buildings';
import {terrainSuitability} from './terrain-status';
import {cellAtWorld} from '../../../packages/map/hex/coordinates';
import {newMapSeed,validateMapConfig,type ProceduralMap,type MapConfig,type TerritoryCell} from '../../../packages/map/types';
import type {FieldRenderer} from '../renderer/field';
import type {Minimap} from './minimap';
const get=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const fmt=new Intl.NumberFormat('pt-BR');
export class MapControls {
 onGenerating:(()=>void)|null=null;
 onUserSelect:((cell:TerritoryCell|null)=>void)|null=null;
 allowSelect:(event:PointerEvent)=>boolean=()=>true;
 onHover:((cell:TerritoryCell|null)=>void)|null=null;onSelect:((cell:TerritoryCell|null)=>void)|null=null;onMap:((map:ProceduralMap)=>void)|null=null;map:ProceduralMap|null=null;requestId=0;private selected:TerritoryCell|null=null;private pending=false;private pointer:{x:number;y:number}|null=null;private hoveredId=-1;
 constructor(private field:FieldRenderer,private minimap:Minimap,private generate:(config:MapConfig,requestId:number)=>void,private notify:(message:string)=>void){get<HTMLInputElement>('map-seed').value=newMapSeed();get<HTMLFormElement>('map-form').onsubmit=e=>{e.preventDefault();this.request();};get('random-seed').onclick=()=>{this.newGame();};
 get('open-map-settings').onclick=()=>get<HTMLDialogElement>('map-settings-dialog').showModal();get('close-map-settings').onclick=()=>get<HTMLDialogElement>('map-settings-dialog').close();
 for(const name of ['match','map','stress']as const)get('tab-'+name).onclick=()=>{get('map-panel').hidden=name!=='map';get('lab-panel').hidden=name!=='stress';get('match-panel').hidden=name!=='match';get('cell-inspector').hidden=name==='stress'||!this.selected;for(const tab of ['match','map','stress']){get('tab-'+tab).setAttribute('aria-selected',String(name===tab));get('tab-'+tab).tabIndex=name===tab?0:-1;}if(name==='stress')this.entities(true);};get('view-tabs').addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();const tabs=['match','map','stress'].filter(t=>!get<HTMLButtonElement>('tab-'+t).disabled&&getComputedStyle(get('tab-'+t)).display!=='none'),index=tabs.findIndex(t=>get('tab-'+t).getAttribute('aria-selected')==='true'),next=tabs[(index+(e.key==='ArrowRight'?1:tabs.length-1))%tabs.length];get<HTMLButtonElement>('tab-'+next).click();get('tab-'+next).focus();}});
 get('close-inspector').onclick=()=>{this.selected=null;this.onSelect?.(null);this.field.terrain.select(null);get('cell-inspector').hidden=true;};
 let press:{id:number;x:number;y:number;distance:number;cancelled:boolean}|null=null;const canvas=field.app.canvas;canvas.addEventListener('pointerdown',e=>{if(press){press.cancelled=true;return;}press={id:e.pointerId,x:e.clientX,y:e.clientY,distance:0,cancelled:e.button!==0};});canvas.addEventListener('pointermove',e=>{if(press&&press.id===e.pointerId)press.distance=Math.max(press.distance,Math.hypot(e.clientX-press.x,e.clientY-press.y));if(!this.map||e.pointerType==='touch')return;this.pointer={x:e.clientX,y:e.clientY};this.updateHover();});canvas.addEventListener('pointerleave',()=>{this.pointer=null;this.updateHover();});canvas.addEventListener('pointercancel',()=>press=null);canvas.addEventListener('pointerup',e=>{if(!press||press.id!==e.pointerId)return;const valid=!press.cancelled&&press.distance<5&&!e.altKey;press=null;if(!valid||!this.allowSelect(e)||!this.map||(get('map-panel').hidden&&get('match-panel').hidden))return;const r=canvas.getBoundingClientRect(),p=field.camera.screenToWorld(e.clientX-r.left,e.clientY-r.top);const cell=cellAtWorld(this.map,p.x,p.y);this.select(cell);this.onUserSelect?.(cell);});}
 updateHover(){const rect=this.field.app.canvas.getBoundingClientRect(),point=this.pointer&&this.field.camera.screenToWorld(this.pointer.x-rect.left,this.pointer.y-rect.top),cell=this.map&&point?cellAtWorld(this.map,point.x,point.y):null;
 this.field.ownership.highlight(cell?.id??-1);const status=get('hex-status');if(status.hidden!==!cell)status.hidden=!cell;if(cell){const info=terrainSuitability(cell),building=this.field.ownership.buildingAt(cell.id);const title=get('hex-status-title'),detail=get('hex-status-detail'),text=(building?BUILDINGS[building.type].name+' · ':'')+info.detail;if(title.textContent!==info.title)title.textContent=info.title;if(detail.textContent!==text)detail.textContent=text;}if(this.hoveredId!==(cell?.id??-1)){this.hoveredId=cell?.id??-1;this.onHover?.(cell);}}
 entities(visible:boolean){this.field.showEntities=visible;this.minimap.showEntities=visible;}
 private busy(value:boolean){this.pending=value;get<HTMLButtonElement>('generate-map').disabled=value;get<HTMLButtonElement>('random-seed').disabled=value;get('generate-map').textContent=value?'Gerando…':'Gerar mapa';get('map-form').setAttribute('aria-busy',String(value));}
 newGame(){if(this.pending)return;this.request({seed:newMapSeed(),size:get<HTMLSelectElement>('map-size').value as MapConfig['size'],landform:get<HTMLSelectElement>('map-landform').value as MapConfig['landform']});}
 request(config?:MapConfig){if(this.pending)return;try{const c=validateMapConfig(config??{seed:get<HTMLInputElement>('map-seed').value,size:get<HTMLSelectElement>('map-size').value,landform:get<HTMLSelectElement>('map-landform').value});get<HTMLInputElement>('map-seed').value=c.seed;get('map-error').textContent='';this.busy(true);this.onGenerating?.();this.generate(c,++this.requestId);}catch(error){get('map-error').textContent=(error as Error).message;}}
 failed(message:string,requestId?:number){if(requestId!==undefined&&requestId!==this.requestId)return;this.busy(false);get('map-error').textContent=message;}
 received(map:ProceduralMap,generationMs:number,requestId:number){if(requestId!==this.requestId)return;this.map=map;this.selected=null;this.pointer=null;this.hoveredId=-1;get('hex-status').hidden=true;get('cell-inspector').hidden=true;this.field.setMap(map);this.minimap.setMap(map,this.field.terrain.showResources);this.busy(false);get<HTMLInputElement>('map-seed').value=map.config.seed;get<HTMLSelectElement>('map-size').value=map.config.size;get<HTMLSelectElement>('map-landform').value=map.config.landform;get('map-summary').textContent={small:'Pequeno',medium:'Médio',large:'Grande'}[map.config.size]+' · '+fmt.format(map.cells.length)+' hexágonos · '+(map.config.landform==='pangea'?'Pangeia':'Continentes')+' · '+(map.rivers?.length??0)+' rios · '+(map.lakeCount??0)+' lagos';get<HTMLDialogElement>('map-settings-dialog').close();this.onMap?.(map);if(requestId>0)this.notify('Mapa gerado · '+map.config.seed);}
 refreshSelection(){if(this.selected)this.select(this.selected);}
 private select(cell:TerritoryCell|null){this.selected=cell;this.onSelect?.(cell);this.field.terrain.select(cell);get('cell-inspector').hidden=!cell||get('tab-stress').getAttribute('aria-selected')==='true';if(!cell)return;get('cell-title').textContent=cell.terrain==='land'?'Território terrestre':cell.waterKind==='river'?'Rio':cell.waterKind==='lake'?'Lago':'Mar';get('cell-coordinates').textContent=`q ${cell.q} · r ${cell.r}`;get('cell-region').textContent=cell.regionId>=0?'Região '+(cell.regionId+1):'—';get('cell-landmass').textContent=cell.landmassId>=0?'Massa '+(cell.landmassId+1):'—';get('cell-resource').textContent=cell.resource?{food:'Solo fértil',mineral:'Depósito mineral',fuel:'Reserva de combustível'}[cell.resource]:cell.terrain==='land'?'Solo comum':'Sem recurso';get('cell-richness').textContent=cell.richness===2?'+100% para a estrutura adequada':'—';get('cell-owner').textContent=cell.terrain==='water'?'Não conquistável':cell.ownerId===null?'Não conquistado':cell.ownerId===1?'Seu país':'País '+cell.ownerId;get('cell-neighbors').textContent=String(cell.neighbors.length);}
}
