import {icon} from './icons';
import {spawnAt} from '../../../packages/simulation/territory/spawns';
import {hexDistance} from '../../../packages/map/hex/coordinates';
import {COUNTRIES,countryById,countryLabel} from '../../../packages/shared/configs/countries';
import type {MatchState,OwnershipChange} from '../../../packages/simulation/territory/types';
import type {ProceduralMap,TerritoryCell} from '../../../packages/map/types';
import type {Command} from '../../../packages/shared/types/protocol';
import type {FieldRenderer} from '../renderer/field';
import type {Minimap} from './minimap';
import type {MapControls} from './map-controls';
const get=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
export class MatchControls {
 onState:((state:MatchState|null)=>void)|null=null;onSelection:((cell:TerritoryCell|null)=>void)|null=null;state:MatchState|null=null;private chosen=0;private selected:TerritoryCell|null=null;private starting=false;private countryId='br';private previewSpawn:import('../../../packages/simulation/territory/types').SpawnCandidate|null=null;private lastBuildings=-1;private bridgeCells:number[]=[];private botCountries:string[]=Array(7).fill('random');
 constructor(private field:FieldRenderer,private minimap:Minimap,private mapControls:MapControls,private send:(command:Command)=>void,private notify:(text:string)=>void){mapControls.onGenerating=()=>{this.state=null;this.onState?.(null);get<HTMLButtonElement>('start-match').disabled=true;get('spawn-list').replaceChildren();get('match-error').textContent='Gerando mapa e preparando territórios…';};mapControls.onMap=()=>{this.prepare();get<HTMLButtonElement>('tab-match').disabled=true;};mapControls.onSelect=cell=>this.select(cell);get<HTMLSelectElement>('player-count').onchange=()=>{this.renderCountries();this.prepare();};this.renderCountries();get('map-form').addEventListener('input',()=>{const changed=!this.mapControls.map||get<HTMLInputElement>('map-seed').value!==this.mapControls.map.config.seed||get<HTMLSelectElement>('map-size').value!==this.mapControls.map.config.size||get<HTMLSelectElement>('map-landform').value!==this.mapControls.map.config.landform;get<HTMLButtonElement>('start-match').disabled=changed||this.state?.phase!=='preparation';get('generate-map').classList.toggle('action',changed);get('match-error').textContent='';});get('start-match').onclick=()=>{if(this.state?.phase!=='preparation'||this.state.preparation?.active||!this.mapOptionsMatch())return;this.starting=true;get<HTMLButtonElement>('start-match').disabled=true;this.send({type:'BEGIN_PREPARATION',name:countryById(this.countryId)!.name,countryId:this.countryId,botCountryIds:this.botCountries.slice(0,Number(get<HTMLSelectElement>('player-count').value)-1)});};get('choose-terrain').onclick=()=>{if(this.previewSpawn&&!this.state?.preparation?.reservations.some(r=>r.playerId===1))this.send({type:'SELECT_TERRAIN',anchorId:this.previewSpawn.anchorId});};get('send-expedition').onclick=()=>{if(!this.selected||!this.state?.expedition)return;this.send({type:'MOVE_EXPEDITION',playerId:1,target:{x:this.selected.x,y:this.selected.y}});};get('focus-capital').onclick=()=>{const city=this.state?.cities.find(c=>c.ownerId===1);if(city)this.focus(city.anchorId);};get('focus-expedition').onclick=()=>{const e=this.state?.expedition;if(e){field.camera.x=e.x;field.camera.y=e.y;field.camera.zoom=Math.max(field.camera.zoom,.65);}};}
 private mapOptionsMatch(){const map=this.mapControls.map;return !!map&&get<HTMLInputElement>('map-seed').value===map.config.seed&&get<HTMLSelectElement>('map-size').value===map.config.size&&get<HTMLSelectElement>('map-landform').value===map.config.landform;}
 private renderCountries(){const count=Number(get<HTMLSelectElement>('player-count').value)-1,used=new Set([this.countryId]);for(let n=0;n<count;n++){const id=this.botCountries[n];if(id!=='random'){if(used.has(id))this.botCountries[n]='random';else used.add(id);}}const grid=get('country-choices'),chosen=countryById(this.countryId)!;get('chosen-country').textContent=chosen.flag+' '+chosen.name;grid.replaceChildren();for(const c of COUNTRIES){const b=document.createElement('button');b.type='button';b.className='country-choice';b.setAttribute('aria-pressed',String(c.id===this.countryId));b.title=c.name;b.style.setProperty('--country-color','#'+c.color.toString(16).padStart(6,'0'));const flag=document.createElement('span'),name=document.createElement('span');flag.className='country-flag';flag.textContent=c.flag;flag.setAttribute('aria-hidden','true');name.textContent=c.name;b.append(flag,name);b.onclick=()=>{this.countryId=c.id;this.botCountries=this.botCountries.map(id=>id===c.id?'random':id);this.renderCountries();};grid.append(b);}const bots=get('bot-country-choices');bots.replaceChildren();for(let n=0;n<count;n++){const row=document.createElement('label'),text=document.createElement('span'),select=document.createElement('select');text.textContent='Bot '+(n+1);select.setAttribute('aria-label','País do bot '+(n+1));const random=document.createElement('option');random.value='random';random.textContent='🎲 Escolha automática';select.append(random);for(const c of COUNTRIES){const option=document.createElement('option');option.value=c.id;option.textContent=c.flag+' '+c.name;option.disabled=c.id===this.countryId||this.botCountries.some((id,i)=>i<count&&i!==n&&id===c.id);select.append(option);}select.value=this.botCountries[n];select.onchange=()=>{this.botCountries[n]=select.value;this.renderCountries();};row.append(text,select);bots.append(row);}}
 prepare(){this.state=null;this.onState?.(null);this.selected=null;this.chosen=0;this.starting=false;this.minimap.match=null;get('match-preparation').hidden=false;get('terrain-preparation').hidden=true;this.previewSpawn=null;this.lastBuildings=-1;this.bridgeCells=[];get('match-playing').hidden=true;get('match-status').textContent='Preparando territórios';get('match-error').textContent='';get('spawn-list').replaceChildren();get<HTMLButtonElement>('start-match').disabled=true;get<HTMLSelectElement>('player-count').disabled=false;this.send({type:'PREPARE_MATCH',playerCount:Number(get<HTMLSelectElement>('player-count').value),botDifficulty:get<HTMLSelectElement>('bot-difficulty').value as import('../../../packages/shared/configs/bots').BotDifficulty,victoryHoldSeconds:Number(get<HTMLInputElement>('victory-hold').value)});}
 failed(message:string){this.starting=false;get('match-error').textContent=message;get<HTMLButtonElement>('start-match').disabled=!this.state||this.state.phase!=='preparation';}
 received(state:MatchState,changes:OwnershipChange[]){if(!this.mapControls.map)return;const changedPhase=this.state?.phase!==state.phase;this.state=state;this.starting=false;get<HTMLButtonElement>('tab-match').disabled=state.phase==='preparation';this.field.military.colors=new Map(state.players.map(p=>[p.id,p.color]));for(const change of changes)this.mapControls.map.cells[change.cellId].ownerId=change.ownerId;if(this.lastBuildings!==state.buildingRevision){for(const id of this.bridgeCells)this.mapControls.map.cells[id].bridgeOwnerId=null;this.bridgeCells=state.buildings.filter(b=>b.type==='bridge'&&!b.construction).map(b=>{this.mapControls.map!.cells[b.anchorId].bridgeOwnerId=b.ownerId;return b.anchorId;});this.lastBuildings=state.buildingRevision;}this.field.ownership.updateState(state,changes);this.minimap.match=state;get('match-preparation').hidden=state.phase!=='preparation';get('match-playing').hidden=state.phase==='preparation';get<HTMLSelectElement>('player-count').disabled=state.phase==='playing';get('match-error').textContent='';
 if(state.phase==='preparation'){
  const prep=state.preparation,active=!!prep?.active;get('match-preparation').hidden=active;get('terrain-preparation').hidden=!active;
  get('match-status').textContent=active?'Escolha seu terreno':'Configure sua partida';get<HTMLButtonElement>('start-match').disabled=active||!this.mapOptionsMatch();
  get<HTMLSelectElement>('player-count').disabled=active;
  if(active){get('preparation-countdown').textContent=Math.ceil(prep!.remaining)+' s';const confirmed=prep!.reservations.some(r=>r.playerId===1);get<HTMLButtonElement>('choose-terrain').disabled=confirmed||!this.validPreview();get('choose-terrain').textContent=confirmed?'Terreno confirmado':'Escolher terreno';
   get('terrain-reservations').replaceChildren();for(const r of prep!.reservations){const row=document.createElement('p');row.textContent=(r.playerId===1?'Você':'Bot '+(r.playerId-1))+' · terreno reservado';get('terrain-reservations').append(row);}
   this.field.ownership.preparation([...prep!.reservations.map(r=>({...r.spawn,id:r.playerId===1?-2:-r.playerId-2})),...(!confirmed&&this.previewSpawn?[this.previewSpawn]:[])],confirmed?-2:this.previewSpawn?.id??-1);
  }else this.field.ownership.preparation([],-1);
 }
 else {get('terrain-preparation').hidden=true;get('match-status').textContent=state.phase==='finished'?'Partida encerrada':'Partida iniciada';get('country-title').textContent=countryLabel(state.players[0]);get('human-territory').textContent=new Intl.NumberFormat('pt-BR').format(state.players[0].territory);get('territory-percent').textContent=(state.players[0].territory/state.landTotal*100).toFixed(1)+'%';get('neutral-territory').textContent=new Intl.NumberFormat('pt-BR').format(state.landTotal-state.captured);get('expedition-status').textContent=state.expedition?.status==='moving'?'Em deslocamento':state.expedition?.status==='blocked'?'Passagem bloqueada por água':'Aguardando destino';get('player-list').replaceChildren();for(const player of state.players){const row=document.createElement('div'),color=document.createElement('i'),name=document.createElement('span'),count=document.createElement('b');color.style.backgroundColor='#'+player.color.toString(16).padStart(6,'0');name.textContent=countryLabel(player);count.textContent=String(player.territory);name.className='score-country-name';const relation=state.diplomacy.relations.find(r=>(r.a===1&&r.b===player.id)||(r.b===1&&r.a===player.id));if(player.id!==1){const war=state.combatOpponents.includes(player.id)||relation?.state==='WAR',preparing=relation?.state==='TENSION'&&relation.preparedBy!==null,allied=relation?.state==='ALLIED';if(war||preparing||allied){const badge=document.createElement('span');badge.className='score-relation';badge.dataset.relation=war?'WAR':preparing?'TENSION':'ALLIED';badge.title=war?'Em guerra com seu país':preparing?(relation!.preparedBy===1?'Seu país está preparando guerra contra este país':'Este país está preparando guerra contra seu país'):'Aliado do seu país';badge.setAttribute('role','img');badge.setAttribute('aria-label',badge.title);badge.tabIndex=0;badge.innerHTML=icon(war?'attack':preparing?'preparation':'alliance');name.append(badge);}}row.append(color,name,count);get('player-list').append(row);}if(changedPhase){this.focus(state.cities[0].anchorId);this.notify('Cidade inicial criada. Construa um quartel e recrute suas tropas.');}}
 this.onState?.(state);this.mapControls.refreshSelection();}
 private validPreview(){const map=this.mapControls.map,spawn=this.previewSpawn;return !!map&&!!spawn&&!this.state?.preparation?.reservations.some(r=>r.playerId!==1&&hexDistance(map.cells[r.spawn.anchorId],map.cells[spawn.anchorId])<10);}
 private choose(id:number,focus=false){this.chosen=id;if(!this.state)return;this.field.ownership.preparation(this.state.spawns,id);[...get('spawn-list').children].forEach((b,i)=>b.setAttribute('aria-pressed',String(this.state!.spawns[i].id===id)));if(focus){const spawn=this.state.spawns.find(s=>s.id===id);if(spawn)this.focus(spawn.anchorId);}}
 private focus(id:number){const cell=this.mapControls.map?.cells[id];if(!cell)return;this.field.camera.x=cell.x;this.field.camera.y=cell.y;this.field.camera.zoom=Math.max(this.field.camera.zoom,Math.min(8,32/(this.mapControls.map?.layout.radius??32)));}
 private select(cell:TerritoryCell|null){this.selected=cell;this.onSelection?.(cell);const playing=this.state?.phase==='playing';get('send-expedition').hidden=!playing;get<HTMLButtonElement>('send-expedition').disabled=!cell||cell.terrain==='water';if(this.state?.preparation?.active&&!this.state.preparation.reservations.some(r=>r.playerId===1)&&cell){this.previewSpawn=spawnAt(this.mapControls.map!,cell.id);const valid=this.validPreview();get('terrain-choice-detail').textContent=!this.previewSpawn?'A cidade e o território de raio 4 precisam caber em terra.':!valid?'Muito perto de outro país.':'Terreno válido · 61 hexágonos · fértil '+this.previewSpawn.food+' · minério '+this.previewSpawn.mineral+' · combustível '+this.previewSpawn.fuel;get<HTMLButtonElement>('choose-terrain').disabled=!valid;this.field.ownership.preparation([...this.state.preparation.reservations.map(r=>({...r.spawn,id:-r.playerId-2})),...(this.previewSpawn?[this.previewSpawn]:[])],this.previewSpawn?.id??-1);}}
}
