import {UNIT_STRIDE} from '../../../packages/shared/configs/units';
import { ENGINE,TEAM_COLORS } from '../../../packages/shared/configs/engine';
import type {ProceduralMap} from '../../../packages/map/types';
import {terrainColor} from '../../../packages/map/palette';
import {cellAtWorld,hexCorners} from '../../../packages/map/hex/coordinates';
import type {MatchState} from '../../../packages/simulation/territory/types';
import type { Camera } from '../input/camera';
export class Minimap {
 private context:CanvasRenderingContext2D;private terrain=document.createElement('canvas');private map:ProceduralMap|null=null;private ownership=document.createElement('canvas');private ownershipRevision=-1;showEntities=false;match:MatchState|null=null;
 constructor(private canvas:HTMLCanvasElement,private camera:Camera){this.context=canvas.getContext('2d')!;const navigate=(e:PointerEvent)=>{const r=canvas.getBoundingClientRect();camera.x=Math.max(0,Math.min(ENGINE.worldWidth,(e.clientX-r.left)/r.width*ENGINE.worldWidth));camera.y=Math.max(0,Math.min(ENGINE.worldHeight,(e.clientY-r.top)/r.height*ENGINE.worldHeight));};canvas.addEventListener('pointerdown',e=>{navigate(e);canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(e.buttons)navigate(e);});canvas.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();e.stopPropagation();camera.x+=(e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:0)*250;camera.y+=(e.key==='ArrowDown'?1:e.key==='ArrowUp'?-1:0)*250;camera.clamp();}});}
 setMap(map:ProceduralMap,showResources=true){this.map=map;this.terrain.width=this.canvas.width;this.terrain.height=this.canvas.height;const c=this.terrain.getContext('2d')!,sx=this.terrain.width/ENGINE.worldWidth,sy=this.terrain.height/ENGINE.worldHeight;c.fillStyle='#182b31';c.fillRect(0,0,this.terrain.width,this.terrain.height);const image=c.createImageData(this.terrain.width,this.terrain.height);for(let y=0;y<this.terrain.height;y++)for(let x=0;x<this.terrain.width;x++){const cell=cellAtWorld(map,(x+.5)/sx,(y+.5)/sy),color=cell?terrainColor(cell,showResources):0x182b31,i=(y*this.terrain.width+x)*4;image.data[i]=color>>16;image.data[i+1]=(color>>8)&255;image.data[i+2]=color&255;image.data[i+3]=255;}c.putImageData(image,0,0);this.ownership.width=this.canvas.width;this.ownership.height=this.canvas.height;this.ownershipRevision=-1;}

 draw(data:Float32Array,count:number,units?:Float32Array){const c=this.context,w=this.canvas.width,h=this.canvas.height;c.fillStyle='#182b31';c.fillRect(0,0,w,h);if(this.map)c.drawImage(this.terrain,0,0);const skip=Math.max(1,Math.ceil(count/4000));for(let i=0;this.showEntities&&i<count;i+=skip){c.fillStyle='#'+TEAM_COLORS[data[i*5+3]].toString(16).padStart(6,'0');c.fillRect(data[i*5]/ENGINE.worldWidth*w,data[i*5+1]/ENGINE.worldHeight*h,1.5,1.5);}if(this.match?.phase==='playing'&&this.map){if(this.ownershipRevision!==this.match.borderRevision){this.ownershipRevision=this.match.borderRevision;const oc=this.ownership.getContext('2d')!;oc.clearRect(0,0,w,h);const colors=new Map(this.match.players.map(p=>[p.id,'#'+p.color.toString(16).padStart(6,'0')]));for(const cell of this.map.cells)if(cell.ownerId!==null){oc.fillStyle=colors.get(cell.ownerId)??'#fff';oc.fillRect(cell.x/ENGINE.worldWidth*w,cell.y/ENGINE.worldHeight*h,Math.max(1,this.map.layout.radius/ENGINE.worldWidth*w*1.7),Math.max(1,this.map.layout.radius/ENGINE.worldHeight*h*1.7));}}c.globalAlpha=.65;c.drawImage(this.ownership,0,0);c.globalAlpha=1;for(const city of this.match.cities){const cell=this.map.cells[city.anchorId];c.strokeStyle='#fff';c.strokeRect(cell.x/ENGINE.worldWidth*w-2,cell.y/ENGINE.worldHeight*h-2,4,4);}const e=this.match.expedition;if(e){c.fillStyle='#f4edc9';c.fillRect(e.x/ENGINE.worldWidth*w-1,e.y/ENGINE.worldHeight*h-1,3,3);}}if(units){c.fillStyle='#e9f9b0';const stride=UNIT_STRIDE*Math.max(1,Math.ceil(units.length/UNIT_STRIDE/2000));for(let k=0;k<units.length;k+=stride){c.fillStyle='#'+(this.match?.players.find(p=>p.id===units[k+5])?.color??0xbababa).toString(16).padStart(6,'0');c.fillRect(units[k+1]/ENGINE.worldWidth*w,units[k+2]/ENGINE.worldHeight*h,2,2);}}const b=this.camera.bounds();c.strokeStyle='#eeeeee';c.lineWidth=1;c.strokeRect(b.left/ENGINE.worldWidth*w,b.top/ENGINE.worldHeight*h,(b.right-b.left)/ENGINE.worldWidth*w,(b.bottom-b.top)/ENGINE.worldHeight*h);}
}
