import {bridgeSupport} from '../../map/bridges';
import type {ProceduralMap} from '../../map/types';
import {axialIndex} from '../../map/hex/coordinates';
import {BUILDINGS,CONSTRUCTION,RESOURCE_KEYS,RESOURCE_NAMES,type BuildingType} from '../../shared/configs/buildings';
import {constructionCost} from './rules';
import type {CountryEconomy,PlacementResult} from './types';
export function rotateHex(q:number,r:number,rotation:number){for(let i=0;i<rotation;i++)[q,r]=[-r,q+r];return {q,r};}
export function footprintCells(map:ProceduralMap,type:BuildingType,anchorId:number,rotation:number){const anchor=map.cells[anchorId];if(!anchor)return [];return BUILDINGS[type].footprint.map(([q,r])=>{const h=rotateHex(q,r,rotation);return axialIndex(anchor.q+h.q,anchor.r+h.r,map.layout);});}
export function terrainBonus(map:ProceduralMap,type:BuildingType,cellIds:number[]){const resource=BUILDINGS[type].bonusResource;return resource&&cellIds.length?1+cellIds.filter(id=>map.cells[id]?.resource===resource).length/cellIds.length:1;}
export function bridgePlacementAllowed(map:ProceduralMap,anchorId:number,playerId:number,allied:(a:number,b:number)=>boolean=(a,b)=>a===b){return bridgeSupport(map,anchorId,playerId,allied).valid;}
export function evaluatePlacement(map:ProceduralMap,occupied:Int32Array,economy:CountryEconomy|undefined,playerId:number,type:BuildingType,anchorId:number,rotation:number,allied:(a:number,b:number)=>boolean=(a,b)=>a===b):PlacementResult {
 const fail=(reason:string,cellIds:number[]=[],bonus=1):PlacementResult=>({valid:false,reason,cellIds,bonus});if(!Object.hasOwn(BUILDINGS,type))return fail('Estrutura inválida.');if(!Number.isInteger(rotation)||rotation<0||rotation>5)return fail('Rotação inválida.');if(!Number.isInteger(anchorId)||!map.cells[anchorId])return fail('Selecione um hexágono do mapa.');const def=BUILDINGS[type],cellIds=footprintCells(map,type,anchorId,rotation),bonus=terrainBonus(map,type,cellIds);
 if(cellIds.some(id=>id<0))return fail('A estrutura não cabe no mapa.',cellIds,bonus);const support=type==='bridge'?bridgeSupport(map,anchorId,playerId,allied):null;if(support&&!support.valid)return fail(support.reason,cellIds);if(type==='port'&&!map.cells[anchorId].neighbors.some(id=>map.cells[id].terrain==='water'))return fail('O porto precisa ficar em terra adjacente a água navegável.',cellIds);if(type!=='bridge'&&cellIds.some(id=>map.cells[id].terrain==='water'))return fail('A construção precisa ficar inteiramente em terra.',cellIds,bonus);if(type!=='bridge'&&cellIds.some(id=>map.cells[id].ownerId!==playerId))return fail('Todos os hexágonos precisam pertencer ao seu país.',cellIds,bonus);if(cellIds.some(id=>occupied[id]!==0))return fail('A área já está ocupada por outra estrutura.',cellIds,bonus);if(!economy)return fail('Economia do jogador indisponível.',cellIds,bonus);const effectiveCost=constructionCost(economy,type,support?.costMultiplier),quote={cost:effectiveCost,costMultiplier:support?.costMultiplier??1,duration:CONSTRUCTION[type].seconds*(support?.timeMultiplier??1)};if(economy.builders+1e-8<def.builders)return {...fail('Faltam '+Math.ceil(def.builders-economy.builders)+' Construtores.',cellIds,bonus),...quote};for(const key of RESOURCE_KEYS){const cost=effectiveCost[key]??0;if(economy.stock[key]+1e-8<cost)return {...fail('Faltam '+Math.ceil(cost-economy.stock[key])+' de '+RESOURCE_NAMES[key]+'.',cellIds,bonus),...quote};}return {cost:effectiveCost,costMultiplier:support?.costMultiplier??1,duration:CONSTRUCTION[type].seconds*(support?.timeMultiplier??1),valid:true,reason:support?'Ponte · materiais '+Math.round(support.costMultiplier*100)+'% · '+Math.round(CONSTRUCTION[type].seconds*support.timeMultiplier)+' s':bonus>1?'Posição válida · bônus de solo: +'+new Intl.NumberFormat('pt-BR',{maximumFractionDigits:2}).format((bonus-1)*100)+'%.':'Posição válida.',cellIds,bonus};
}
