import {BUILDINGS,RESOURCE_KEYS,type ResourceStock,type StockResource,type BuildingType} from '../shared/configs/buildings';
import {ECONOMY_CONFIG as E} from '../shared/configs/economy';
import {AI_CONFIG as C,type StrategicState} from '../shared/configs/ai';
import {constructionCost,cityDemand} from '../simulation/economy/rules';
import type {TerritoryMatch} from '../simulation/territory/match';
export interface ResourceForecast {stock:number;productionPerMinute:number;consumptionPerMinute:number;balancePerMinute:number;plannedConsumptionPerMinute:number;reserve:number;forecast:number;shortageInSeconds:number|null;}
export interface EconomicModel {resources:Record<StockResource,ResourceForecast>;cities:{id:number;population:number;capacity:number;excess:number;growth:number;consumption:number;forecastRatio:number}[];builders:{current:number;maximum:number;recovery:number;reserve:number};planned:BuildingType;factorySafe:boolean;foodUrgent:boolean;housingNeeded:boolean;income:number;}
const zero=():ResourceStock=>({money:0,food:0,mineral:0,fuel:0});
export function economicModel(match:TerritoryMatch,id:number,state:StrategicState,horizon:number):EconomicModel {
 const e=match.state.economies.find(c=>c.playerId===id)!,buildings=match.state.buildings.filter(b=>b.ownerId===id),production=zero(),consumption=zero(),plannedConsumption=zero(),cities:EconomicModel['cities']=[];
 for(const b of buildings){if(b.construction)continue;const d=BUILDINGS[b.type];for(const k of RESOURCE_KEYS){production[k]+=(d.production[k]??0)*b.bonus*(b.operatingRate??(d.foodConsumption>0?e.foodSatisfaction:1));consumption[k]+=(d.consumption?.[k]??0);}
 consumption.food+=d.foodConsumption;if(b.city){consumption.food+=b.city.foodConsumption;const future={...b.city,population:b.city.population+b.city.growthRate*horizon};cityDemand(future,E.cityGrowth);plannedConsumption.food+=Math.max(0,future.foodConsumption-b.city.foodConsumption);cities.push({id:b.id,population:b.city.population,capacity:b.city.capacity,excess:b.city.excess,growth:b.city.growthRate,consumption:b.city.foodConsumption*60,forecastRatio:future.population/b.city.capacity});}}
 if(!buildings.some(b=>(BUILDINGS[b.type].production.mineral??0)>0))production.mineral=E.emergencyMineralPerSecond;
 const count=(t:BuildingType)=>buildings.filter(b=>b.type===t).length,housingNeeded=cities.reduce((n,c)=>n+c.population+c.growth*horizon,0)>cities.reduce((n,c)=>n+c.capacity,0)*C.capacityWarning,foodUrgent=!count('farm')||production.food<consumption.food+plannedConsumption.food+C.foodMargin||e.stock.food+e.rates.food*horizon<consumption.food*C.reserveSeconds[state];
 const planned:BuildingType=foodUrgent?'farm':!count('mine')?'mine':housingNeeded?'city':!count('barracks')?'barracks':!count('refinery')?'refinery':e.rates.mineral<E.factory.consumption.mineral+C.foodMargin?'mine':'factory';
 const cost=constructionCost(e,planned),resources={}as EconomicModel['resources'];for(const k of RESOURCE_KEYS){const balance=production[k]-consumption[k],futureBalance=balance-plannedConsumption[k];resources[k]={stock:e.stock[k],productionPerMinute:production[k]*60,consumptionPerMinute:consumption[k]*60,balancePerMinute:balance*60,plannedConsumptionPerMinute:plannedConsumption[k]*60+(cost[k]??0)/horizon*60,reserve:Math.max(consumption[k]*C.reserveSeconds[state],k==='money'?ECONOMY_MONEY_RESERVE(state):0),forecast:e.stock[k]+futureBalance*horizon-(cost[k]??0),shortageInSeconds:futureBalance<0?e.stock[k]/-futureBalance:null};}
 const factoryCost=constructionCost(e,'factory');const factorySafe=RESOURCE_KEYS.filter(k=>k!=='money').every(k=>{const r=resources[k],input=E.factory.consumption[k as keyof typeof E.factory.consumption]??0;return r.balancePerMinute/60-(k==='food'?plannedConsumption.food:0)>=input+(k==='food'?C.foodMargin:0)&&r.stock-(factoryCost[k]??0)>=r.reserve+input*C.factoryReserveSeconds;});
 return {resources,cities,builders:{current:e.builders,maximum:e.maxBuilders,recovery:e.builderRecovery,reserve:state==='GUERRA'||state==='CRISE'?0:BUILDINGS.farm.builders*.5},planned,factorySafe,foodUrgent,housingNeeded,income:production.money};
}
function ECONOMY_MONEY_RESERVE(state:StrategicState){return state==='GUERRA'||state==='CRISE'?C.economyMoneyReserve.war:state==='PREPARAÇÃO'?C.economyMoneyReserve.preparation:C.economyMoneyReserve.peace;}
