Warning: truncated output (original token count: 9070)
Total output lines: 163

import {MISSILES,type MissileType} from '../shared/configs/operations';
import {recruitmentAvailable} from '../simulation/economy/recruitment';
import {planCrossing,crossingBudget,type CrossingPlan} from './crossings';
import {AI_CONFIG as C,type StrategicState} from '../shared/configs/ai';
import {BOT_WEIGHTS,type BotPersonality} from '../shared/configs/bots';
import {BUILDINGS,RESOURCE_KEYS,type BuildingType} from '../shared/configs/buildings';
import {ECONOMY_CONFIG as E} from '../shared/configs/economy';
import {UNITS,UNIT_STATE,UNIT_MODES} from '../shared/configs/units';
import {TRAINING} from '../shared/configs/training';
import {constructionCost} from '../simulation/economy/rules';
import {evaluatePlacement} from '../simulation/economy/placement';
import {isMilitaryStructure} from '../shared/configs/combat';
import type {TerritoryMatch} from '../simulation/territory/match';
import type {Army} from '../simulation/units/army';
import type {Command} from '../shared/types/protocol';
import type {BotView} from './types';
import {economicModel,type EconomicModel} from './economy-model';
import {Perception} from './perception';
interface Goal {building?:BuildingType;score:number;label:string;reason:string;run:()=>boolean;}
interface WarPlan {target:number;score:number;reason:string;ready:boolean;objection:string;}
interface Bot extends BotView {crossing:CrossingPlan|null;nextCrossing:number;crossingCursor:number;bridgeDestination:number|null;navalScan:number;nextNaval:number;navalUnits:number[];navalDestination:number|null;reservedBarracks:number[];state:StrategicState;nextEconomy:number;nextStrategy:number;nextMilitary:number;nextDiplomacy:number;placementCursor:number;lastOrder:number;target:number|null;intel:Perception;model:EconomicModel|null;goals:Goal[];warPlan:WarPlan|null;spending:{time:number;amount:number}[];warProgress:Map<number,{baseline:number;territory:number;lastProgress:number;assessment:string}>;}
/** Multi-rate Utility AI. All actions use authoritative player commands and costs. */
export class BotSystem {
 readonly bots:Bot[]=[];time=0;decisions=0;orders=0;private budget=0;private failures=new Map<number,string>();private randomState=1234567;private policy:typeof C.difficulty.normal;
 constructor(private match:TerritoryMatch,private army:Army,private send:(command:Command)=>void,includeHuman=false){const difficulty=match.state.botDifficulty;this.policy=C.difficulty[difficulty==='off'?'normal':difficulty];if(difficulty==='off')return;
 for(const c of match.map.config.seed)this.randomState=(Math.imul(this.randomState,31)+c.charCodeAt(0))>>>0;
 const personalities:BotPersonality[]=['aggressive','economic','diplomatic'];for(const p of match.state.players.filter(p=>includeHuman||!p.human))this.bots.push({playerId:p.id,personality:personalities[(p.id+1)%3],action:'Preparando economia',goal:'',army:0,utility:0,decisions:0,lastDecision:0,crossing:null,nextCrossing:0,crossingCursor:0,bridgeDestination:null,navalScan:0,nextNaval:0,navalUnits:[],navalDestination:null,reservedBarracks:[],state:'DESENVOLVIMENTO',nextEconomy:p.id*.13,nextStrategy:p.id*.17,nextMilitary:p.id*.11,nextDiplomacy:12+p.id*.23,placementCursor:0,lastOrder:-100,target:null,intel:new Perception(p.id,match,army),model:null,goals:[],warPlan:null,spending:[],warProgress:new Map()});
 for(const b of this.bots){const e=match.economy!,real=e.countries.find(c=>c.playerId===b.playerId)!,geometric={...real,builders:1e9,stock:{money:1e9,food:1e9,mineral:1e9,fuel:1e9}};for(const id of match.owned.get(b.playerId)??[]){const p=evaluatePlacement(match.map,e.occupied,geometric,b.playerId,'barracks',id,0);if(p.valid){b.reservedBarracks=p.cellIds;break;}}}
 army.botVisibility=(owner,targetId)=>{const observer=this.bots.find(b=>b.playerId===owner);return !observer||((targetId<0?observer.intel.buildings.get(-targetId):observer.intel.units.get(targetId))?.confidence??0)>.98;};
 match.state.bots=this.views();match.diplomacy!.manualHuman=!includeHuman;match.diplomacy!.respond=o=>{const b=this.bots.find(b=>b.playerId===o.to);if(!b)return false;if(o.kind==='alliance')return this.allianceScore(b,o.from)>=C.allianceThreshold;if(o.kind==='support'){const w=match.state.diplomacy.wars.find(w=>w.id===o.warId)!;return !!b.model&&!b.model.foodUrgent&&this.strength(b.playerId)>C.minScouts&&(w.defenderId===o.from||this.match.social!.get(b.playerId).relations[o.from]>70);}const w=match.state.diplomacy.wars.find(w=>w.id===o.warId);const strength=this.strength(o.to),enemy=b.intel.strength(o.from,this.policy.precision);return strength<enemy*1.2||!!w&&this.time-w.startedAt>C.maxUnproductiveWarSeconds&&(b.warProgress.get(w.id)?.assessment==='equilibrada'||b.state==='CRISE');};}
 private views():BotView[]{return this.bots.map(({playerId,personality,action,goal,army,utility,decisions,lastDecision})=>({playerId,personality,action,goal,army,utility,decisions,lastDecision}));}
 private noise(){this.randomState^=this.randomState<<13;this.randomState^=this.randomState>>>17;this.randomState^=this.randomState<<5;return ((this.randomState>>>0)/4294967296-.5)*this.policy.noise;}
 private issue(c:Command){try{this.send(c);return true;}catch(error){if('playerId'in c)this.failures.set(c.playerId,error instanceof Error?error.message:String(error));return false;}}
 private indices(id:number){const out:number[]=[];for(let i=0;i<this.army.size;i++)if(this.army.ids[i]&&!this.army.embarked[i]&&this.army.kind[i]<3&&this.army.owner[i]===id)out.push(i);return out;}
 private strength(id:number){return this.indices(id).reduce((n,i)=>n+(this.army.kind[i]===1?5:this.army.kind[i]===2?6:1)*this.army.hp[i]/this.army.definition(i).health,0);}
 private home(id:number){return this.match.map.cells[this.match.state.buildings.find(b=>b.ownerId===id&&b.type==='city')!.anchorId];}
 private wars(id:number){return this.match.state.diplomacy.wars.filter(w=>w.endedAt===null&&this.match.diplomacy!.sides(w).flat().includes(id));}
 private frontier(b:Bot){const set=new Set<number>();for(const id of this.match.owned.get(b.playerId)??[])for(const n of this.match.map.cells[id].neighbors){const c=this.match.map.cells[n];if(c.terrain==='land'&&c.ownerId===null)set.add(n);}return [...set];}
 private placement(b:Bot,type:BuildingType){const owned=[...this.match.owned.get(b.playerId)??[]],e=this.match.economy!,country=e.countries.find(c=>c.playerId===b.playerId)!,home=this.home(b.playerId);let best:{id:number;score:number}|null=null;
 for(let n=0;n<Math.min(C.placementAnchors,owned.length);n++){const id=owned[(b.placementCursor+n)%owned.length],cell=this.match.map.cells[id],valid=evaluatePlacement(this.match.map,e.occupied,country,b.playerId,type,id,0,(a,c)=>this.match.diplomacy!.allied(a,c));if(!valid.valid)continue;const needsBarracks=!this.match.state.buildings.some(v=>v.ownerId===b.playerId&&v.type==='barracks'&&!v.construction);if(needsBarracks&&type!=='barracks'&&valid.cellIds.some(id=>b.reservedBarracks.includes(id)))continue;const danger=cell.neighbors.some(n=>{const owner=b.intel.knownOwners.get(n);return owner&&this.match.diplomacy!.hostile(b.playerId,owner);});const score=(type==='barracks'&&id===b.reservedBarracks[0]?1000:0)+valid.bonus*100-Math.hypot(cell.x-home.x,cell.y-home.y)/100+(type==='port'&&cell.neighbors.some(n=>this.match.map.cells[n].waterKind==='sea')?120:0)+(type==='defense'&&danger?80:danger?-40:0);if(!best||score>best.score)best={id,score};}
 b.placementCursor=owned.length?(b.placementCursor+C.placementAnchors)%owned.length:0;return best;}
 private allianceScore(b:Bot,other:number){const s=this.match.social!.get(b.playerId),o=this.match.social!.get(other),d=this.match.diplomacy!,shared=this.match.state.players.filter(p=>p.id!==other&&p.id!==b.playerId&&((s.threats[p.id]??0)>C.tensionThreshold&&b.intel.border(p.id)>0||d.hostile(b.playerId,p.id)&&d.hostile(other,p.id))).length;
 const need=Math.max(0,...Object.values(s.threats))/10,conflict=b.warPlan?.target===other?35:0,relation=s.relations[other]??45,border=b.intel.border(other),economic=b.model?.resources.fuel.balancePerMinute??0;
 return o.reputation*.25+relation*.6+shared*20+need+(border?4:0)+(economic>0?2:0)+BOT_WEIGHTS[b.personality].diplomacy*8-conflict-(o.reputation<30?15:0)-(b.intel.strength(other)>this.strength(b.playerId)*2?8:0);}
 private strategic(b:Bot){const id=b.playerId,war=this.wars(id),s=this.match.social!.get(id),country=this.match.state.economies.find(e=>e.playerId===id)!,previous=b.state;let maxThreat=0;
 for(const p of this.match.state.players){if(p.id===id||p.defeated)continue;const border=b.intel.border(p.id),enemy=b.intel.strength(p.id,this.policy.precision),industry=[...b.intel.buildings.values()].filter(v=>v.owner===p.id&&(v.type==='factory'||v.type==='refinery')).length,near=b.intel.currentEnemies(p.id).filter(v=>Math.hypot(v.x-this.home(id).x,v.y-this.home(id).y)<C.visionRadius*2).length;
 const hostile=this.match.diplomacy!.hostile(id,p.id),tension=this.match.diplomacy!.relation(id,p.id)?.state==='TENSION';s.threats[p.id]=Math.min(100,enemy/Math.max(C.minScouts,this.strength(id))*12+(border?C.threat.border:0)+near*C.threat.nearbyTroops+industry*C.threat.industry+(hostile?40:tension?25:0)+Math.max(0,this.match.social!.hostilityMemory(id,p.id))*C.threat.history+Math.min(10,(b.intel.observedGrowth.get(p.id)??0)*C.threat.militaryGrowth)*(border?1:.2));maxThreat=Math.max(maxThreat,s.threats[p.id]);}
 const preparation=this.match.state.diplomacy.relations.some(r=>r.preparedBy===id);
 const shortage=country.rates.food<0&&country.stock.food/-country.rates.food<C.crisisFoodSeconds;
 b.state=shortage||war.length&&this.strength(id)<C.minScouts?'CRISE':war.length?'GUERRA':preparation?'PREPARAÇÃO':s.recoveryUntil>this.time?'RECUPERAÇÃO':maxThreat>C.tensionThreshold?'TENSÃO':this.frontier(b).length&&this.indices(id).length>=C.minScouts?'EXPANSÃO':'DESENVOLVIMENTO';
 if(previous!==b.state)b.target=null;b.model=economicModel(this.match,id,b.state,this.policy.horizon);
 if(!war.length&&b.state!=='RECUPERAÇÃO'){b.warPlan=this.planWar(b);if(b.warPlan&&!b.model.foodUrgent&&!preparation&&this.strength(id)>=C.minimumWarStrength*.6){b.state='TENSÃO';b.model=economicModel(this.match,id,b.state,this.policy.horizon);}}else if(war.length)b.warPlan=null;
 }
 private planWar(b:Bot):WarPlan|null{const id=b.playerId,m=b.model!,e=this.match.economy!,country=e.countries.find(c=>c.playerId===id)!,frontier=this.frontier(b),owned=[...this.match.owned.get(id)??[]],free=owned.filter(id=>!e.occupied[id]).length,social=this.match.social!.get(id),force=this.strength(id),plans:WarPlan[]=[];
 const neutralSpace=frontier.length,landPressure=free<C.minFreeCells||owned.length<country.population*C.expansionTargetPerPopulation;
 for(const p of this.match.state.players){if(p.id===id||p.defeated||(!b.intel.border(p.id)&&!this.match.state.buildings.some(v=>v.ownerId===id&&v.type==='port'&&!v.construction)))continue;const relation=this.match.diplomacy!.relation(id,p.id)!;if(!['NEUTRAL','TENSION'].includes(relation.state)||relation.truceUntil>this.time)continue;const known=[...b.intel.buildings.values()].filter(s=>s.owner===p.id),economicValue=known.reduce((n,s)=>n+(s.type?C.strategicValue[s.type]*s.confidence:0),0),resourceValue=[...b.intel.knownOwners].filter(([cell,owner])=>owner===p.id&&this.match.map.cells[cell].resource!==null).length*C.strategicValue.resource;
 const scarcity=RESOURCE_KEYS.filter(k=>k!=='money').find(k=>m.resources[k].forecast<0&&!owned.some(id=>this.match.map.cells[id].resource===k)&&[...b.intel.knownOwners].some(([id,owner])=>owner===p.id&&this.match.map.cells[id].resource===k));
 const threat=(social.threats[p.id]??0)>65&&social.relations[p.id]<35,opportunity=economicValue+resourceValue>=C.strategicRegionThreshold&&(b.intel.border(p.id)>2||this.match.state.buildings.some(v=>v.ownerId===id&&v.type==='port'&&!v.construction));
 if(!(scarcity&&neutralSpace<8||landPressure&&neutralSpace<8||threat||opportunity))continue;
 const reason=scarcity?scarcity==='food'?'comida':scarcity==='mineral'?'minério':'combustível':threat?'conter ameaça hostil':opportunity?'infraestrutura e depósitos estratégicos':'território';
 const enemy=b.intel.strength(p.id,this.policy.precision),allies=this.match.state.players.filter(q=>q.id!==p.id&&this.match.diplomacy!.allied(p.id,q.id)).reduce((n,q)=>n+b.intel.strength(q.id)*.65,0),ownAllies=this.match.state.players.filter(q=>q.id!==id&&this.match.diplomacy!.allied(id,q.id)).reduce((n,q)=>n+b.intel.strength(q.id)*.35,0),estimated=Math.max(4,enemy)+allies,ratio=(force+ownAllies)/estimated;
 const reserve=country.stock.food>=country.foodConsumption*C.warFoodSeconds&&country.stock.money>=UNITS.infantry.cost.money!*2&&country.stock.mineral>=UNITS.infantry.cost.mineral!*2,capacity=m.income>=UNITS.infantry.cost.money!/C.warReserveSeconds&&country.foodSatisfaction>.95,ready=force>=C.minimumWarStrength&&ratio>=C.warForceRatio&&reserve&&capacity;
 const score=(scarcity?76:threat?70:60)+Math.min(20,economicValue/10)+(ratio-1)*10+BOT_WEIGHTS[b.personality].military*4-Math.max(0,65-this.match.social!.get(p.id).reputation)*-.04;
 plans.push({target:p.id,score,reason,ready,objection:force<C.minimumWarStrength?'Força insuficiente':ratio<C.warForceRatio?'Força semelhante ou aliados inimigos':!reserve?'Reservas insuficientes':!capacity?'Economia insuficiente':'Preparação sustentável'});}
 return plans.sort((a,b)=>b.score-a.score)[0]??null;}
 private economic(b:Bot){if(!b.model)this.strategic(b);b.model=economicModel(this.match,b.playerId,b.state,this.policy.horizon);const id=b.playerId,c=this.match.state.economies.find(c=>c.playerId===id)!,m=b.model!,buildings=this.match.state.buildings.filter(v=>v.ownerId===id),count=(t:BuildingType)=>buildings.filter(v=>v.type===t).length,atWar=!!this.wars(id).length,weights=BOT_WEIGHTS[b.personality],goals:Goal[]=[];
 const build=(type:BuildingType,score:number,reason:string)=>{if(score<=0||buildings.some(v=>v.type===type&&v.construction))return;const cost=constructionCost(c,type),urgent=score>=100;goals.push({building:type,score:score*weights.economy+this.noise(),label:'Construindo '+BUILDINGS[type].name.toLowerCase(),reason,run:()=>{if(c.builders<BUILDINGS[type].builders||RESOURCE_KEYS.some(k=>c.stock[k]<(cost[k]??0)+(urgent||k==='mineral'||k==='fuel'?0:m.resources[k].reserve)))return false;const p=this.placement(b,type);return !!p&&this.issue({type:'BUILD_STRUCTURE',playerId:id,buildingType:type,anchorId:p.id,rotation:0});}});};
 build('farm',m.foodUrgent?C.utility.farmCritical:0,'Consumo futuro e reserva de comida');build('mine',!count('mine')?C.utility.firstMine:0,'Primeira fonte de minério');const basics=count('farm')&&count('mine'),safe=basics&&!m.foodUrgent;
 if(basics){build('city',m.housingNeeded&&(!atWar||!this.homeThreatened(b))?(c.population/c.capacity>1.4?C.utility.cityCritical:C.utility.cityPlanned):0,'Capacidade individual das cidades e superpopulação prevista');build('barracks',safe&&!count('barracks')?C.utility.firstBarracks:0,'Exploração e defesa com economia estável');
 const nextCost=constructionCost(c,m.planned),mineralNeed=(nextCost.mineral??0)/C.constructionPlanningSeconds+E.factory.consumption.mineral*(count('factory')+1),mineralNet=m.resources.mineral.balancePerMinute/60;
 build('mine',safe&&count('barracks')&&mineralNet<mineralNeed&&c.stock.mineral<(nextCost.mineral??0)+mineralNeed*this.policy.horizon?C.utility.materials:0,'Preparar materiais para o próximo investimento');
 build('refinery',safe&&count('barracks')&&(!count('refinery')||m.resources.fuel.balancePerMinute/60<E.factory.consumption.fuel&&c.stock.fuel<constructionCost(c,'factory').fuel!+E.factory.consumption.fuel*this.policy.horizon)?C.utility.refinery:0,'Combustível previsto para indústria e tanques');
 build('factory',safe&&count('refinery')&&m.factorySafe?(count('factory')===0?C.utility.firstFactory:C.utility.factory):0,'Conversão sustentável após custos, crescimento e reserva de insumos');
 const needed=this.desiredArmy(b);build('barracks',safe&&count('barracks')&&needed>count('barracks')*16&&atWar?C.utility.trainingCapacity:0,'Reposição e capacidade de treinamento');
 build('port',safe&&count('barracks')&&count('port')<Math.min(3,Math.max(1,count('city')))&&[...this.match.owned.get(id)??[]].some(n=>this.match.map.cells[n].neighbors.some(n=>this.match.map.cells[n].terrain==='water'))?85:0,'Comércio e acesso a outros continentes');
 build('silo',safe&&!count('silo')&&count('factory')>=2&&c.stock.money>=15000&&c.stock.mineral>=4000&&c.stock.fuel>=2400?125:0,'Arma estratégica de fim de partida');

 if(safe&&count('barracks')){
  const allied=(a:number,c:number)=>this.match.diplomacy!.allied(a,c),e=this.match.economy!;
  if(b.crossing){
   const next=b.crossing.cells.find(n=>this.match.map.cells[n].bridgeOwnerId==null&&!e.occupied[n]);
   if(next===undefined&&!buildings.some(v=>v.type==='bridge'&&v.construction)){b.bridgeDestination=b.crossing.destination;b.crossing=null;}
   else if(next!==undefined){const updated=crossingBudget(this.match.map,b.crossing.cells,b.crossing.destination,id,allied);if(!updated)b.crossing=null;else b.crossing=updated;}
  }
  if(!b.crossing&&!buildings.some(v=>v.type==='bridge'&&v.construction)&&b.bridgeDestination===null&&this.time>=b.nextCrossing&&c.stock.money>=BUILDINGS.bridge.cost.money!*2&&c.stock.mineral>=BUILDINGS.bridge.cost.mineral!*2){b.nextCrossing=this.time+24;b.crossing=planCrossing(this.match.map,this.match.owned.get(id)??new Set(),e.occupied,id,allied,b.intel.knownOwners,b.crossingCursor);b.crossingCursor+=8;}
  if(b.crossing&&!buildings.some(v=>v.type==='bridge'&&v.construction)){
   const plan=b.crossing,next=plan.cells.find(n=>this.match.map.cells[n].bridgeOwnerId==null);
   if(next!==undefined)goals.push({building:'bridge',score:120,label:'Construindo travessia por segmentos',reason:'Reservar o custo integral antes de iniciar a ponte',run:()=>{
    if(c.builders<plan.builders||RESOURCE_KEYS.some(k=>c.stock[k]<(plan.cost[k]??0)+m.resources[k].reserve))return false;
    return…70 tokens truncated….sort((a,b)=>b.score-a.score);b.goals=goals;const top=goals[0],topCost=top?.building?constructionCost(c,top.building):{},canSave=!!top?.building&&c.builders+c.builderRecovery*this.policy.horizon>=BUILDINGS[top.building].builders&&RESOURCE_KEYS.every(k=>c.stock[k]+Math.max(0,c.rates[k])*this.policy.horizon>=(topCost[k]??0));const chosen=goals.find((g,index)=>(index===0||!canSave||g.score>=120)&&(!b.crossing||g.building==='bridge'||g.building==='farm'&&m.foodUrgent)&&g.run());b.action=chosen?.label??(m.foodUrgent?'Reservando para comida':m.housingNeeded?'Reservando para cidade':c.builders<BUILDINGS[m.planned].builders?'Aguardando Construtores':'Acumulando reservas para '+BUILDINGS[m.planned].name);b.utility=chosen?.score??goals[0]?.score??0;b.lastDecision=this.time;b.decisions++;this.decisions++;b.model=economicModel(this.match,id,b.state,this.policy.horizon);
 }
 private desiredArmy(b:Bot){const c=this.match.state.economies.find(e=>e.playerId===b.playerId)!;return Math.max(C.minScouts,Math.floor(Math.min(c.population*C.militaryPopulation[b.state]*BOT_WEIGHTS[b.personality].military,(b.model?.income??0)*C.armyFundingSeconds*C.militaryBudget[b.state]*BOT_WEIGHTS[b.personality].military/UNITS.infantry.cost.money!)));}
 private military(b:Bot){const id=b.playerId,units=this.indices(id),m=b.model;if(!m)return;b.army=units.length;const ready=units.filter(i=>!this.army.waitingForTransport[i]&&![UNIT_STATE.retreat,UNIT_STATE.recover].includes(this.army.state[i]as 3|4));
 const hurt=ready.filter(i=>this.army.hp[i]<this.army.definition(i).health*C.retreatHealth||this.army.supply[i]<C.retreatSupply);if(hurt.length&&this.budget&&this.issue({type:'RETREAT_UNITS',playerId:id,unitIds:hurt.map(i=>this.army.ids[i])})){this.budget--;b.goal='Recuperando tropas no quartel';}
 this.advancedMilitary(b);this.recruit(b);const navalTarget=b.navalDestination===null?null:this.match.map.cells[b.navalDestination];if(navalTarget?.ownerId===id||this.wars(id).length||this.time>b.nextNaval+180){b.navalUnits=[];b.navalDestination=null;}const healthy=ready.filter(i=>!hurt.includes(i)&&!b.navalUnits.includes(this.army.ids[i]));if(!healthy.length||!this.budget)return;const d=this.match.diplomacy!,enemies=this.match.state.players.filter(p=>d.hostile(id,p.id));
 if(!enemies.length&&b.bridgeDestination!==null){
 const point=this.match.map.cells[b.bridgeDestination],scouts=healthy.filter(i=>this.army.kind[i]<2).slice(0,3);
 if(point.ownerId===id){b.bridgeDestination=null;}else if(scouts.length){
  if(scouts.some(i=>this.army.groups.get(this.army.groupId[i])?.target===point||Math.hypot((this.army.groups.get(this.army.groupId[i])?.target.x??-1)-point.x,(this.army.groups.get(this.army.groupId[i])?.target.y??-1)-point.y)<1))return;
  if(this.move(b,scouts,point,'Explorando a margem alcançada pela ponte'))return;
 }
 }
 if(!enemies.length){const scoutCount=Math.min(C.maxScouts,Math.max(C.minScouts,Math.floor(healthy.length/4))),explorers=healthy.filter(i=>this.army.kind[i]<2).slice(0,scoutCount);for(const i of explorers){if(this.army.modes[i]!==UNIT_MODES.discovery&&this.budget&&this.issue({type:'SET_UNIT_MODE',playerId:id,unitIds:[this.army.ids[i]],mode:'discovery'})){this.budget--;b.goal='Descobrindo terra por caminhos permitidos';}}const defenders=healthy.filter(i=>!explorers.includes(i)).filter(i=>this.army.modes[i]!==UNIT_MODES.defense);if(defenders.length&&this.budget){this.issue({type:'SET_UNIT_MODE',playerId:id,unitIds:defenders.map(i=>this.army.ids[i]),mode:'defense'});this.budget--;}return;}
 if(this.time-b.lastOrder<C.attackReorderSeconds)return;const center={x:healthy.reduce((n,i)=>n+this.army.x[i],0)/healthy.length,y:healthy.reduce((n,i)=>n+this.army.y[i],0)/healthy.length},ownBuildings=this.match.state.buildings.filter(v=>v.ownerId===id),invaders=enemies.flatMap(p=>b.intel.currentEnemies(p.id)).filter(s=>ownBuildings.some(v=>Math.hypot(s.x-this.match.map.cells[v.anchorId].x,s.y-this.match.map.cells[v.anchorId].y)<C.visionRadius));
 if(invaders.length&&this.strength(id)<invaders.reduce((n,s)=>n+s.strength,0)*1.3){const v=invaders[0];this.move(b,healthy,{x:v.x,y:v.y},'Defendendo infraestrutura');return;}
 const targets=[...b.intel.buildings.values()].filter(s=>enemies.some(p=>p.id===s.owner)).map(s=>({cell:s.cellId!,score:(s.type?C.strategicValue[s.type]:10)*s.confidence-Math.hypot(s.x-center.x,s.y-center.y)/30}));
 if(!targets.length)for(const [cell,owner]of b.intel.knownOwners)if(owner&&enemies.some(p=>p.id===owner))targets.push({cell,score:10-Math.hypot(this.match.map.cells[cell].x-center.x,this.match.map.cells[cell].y-center.y)/30});
 const held=b.target===null?null:b.intel.buildings.get(b.target),target=held&&enemies.some(p=>p.id===held.owner)?held.cellId!:targets.sort((a,b)=>b.score-a.score)[0]?.cell;
 if(target!==undefined){const point=this.match.map.cells[target],blocker=enemies.flatMap(p=>b.intel.currentEnemies(p.id)).filter(v=>Math.hypot(v.x-point.x,v.y-point.y)<C.visionRadius).sort((a,c)=>Math.hypot(a.x-center.x,a.y-center.y)-Math.hypot(c.x-center.x,c.y-center.y))[0];if(blocker){const force=healthy.filter(i=>this.army.pursuitTarget(i)<0).sort((a,c)=>Math.hypot(this.army.x[a]-blocker.x,this.army.y[a]-blocker.y)-Math.hypot(this.army.x[c]-blocker.x,this.army.y[c]-blocker.y)).slice(0,C.taskForceSize);if(force.length&&this.budget&&this.issue({type:'ATTACK_UNIT',playerId:id,unitIds:force.map(i=>this.army.ids[i]),targetId:blocker.id})){this.budget--;b.lastOrder=this.time;b.goal='Eliminando defensores da infraestrutura';this.orders++;return;}}const known=[...b.intel.buildings.values()].find(v=>v.cellId===target),available=healthy.filter(i=>{const g=this.army.groups.get(this.army.groupId[i]);return this.army.state[i]!==UNIT_STATE.attack&&(this.army.modes[i]!==0||!g||Math.hypot(g.target.x-point.x,g.target.y-point.y)>C.attackVisionStep);}),force=available.sort((a,c)=>Math.hypot(this.army.x[a]-point.x,this.army.y[a]-point.y)-Math.hypot(this.army.x[c]-point.x,this.army.y[c]-point.y)).slice(0,C.taskForceSize);if(!force.length)return;b.target=known?.id??null;this.move(b,force,point,'Capturando infraestrutura estratégica');}
 }
 private advancedMilitary(b:Bot){
 const id=b.playerId,stock=this.match.state.economies.find(c=>c.playerId===id)!.stock,silo=this.match.state.buildings.find(v=>v.ownerId===id&&v.type==='silo'&&!v.construction),enemies=[...b.intel.buildings.values()].filter(v=>this.match.diplomacy!.hostile(id,v.owner)&&v.confidence>.5&&v.cellId!==undefined);
 if(silo&&enemies.length){if(!silo.missile){const cells=this.match.map.cells,own=this.match.state.buildings.filter(v=>v.ownerId===id||this.match.diplomacy!.allied(id,v.ownerId)),safe=(radius:number)=>enemies.some(v=>own.every(a=>a.cellIds.every(n=>Math.max(Math.abs(cells[n].q-cells[v.cellId!].q),Math.abs(cells[n].r-cells[v.cellId!].r),Math.abs(cells[n].q+cells[n].r-cells[v.cellId!].q-cells[v.cellId!].r))>radius)));if(!safe(3))return;const type:MissileType=safe(8)&&RESOURCE_KEYS.every(k=>stock[k]>=(MISSILES.strategic.cost[k]??0)*1.2)?'strategic':'tactical';if(RESOURCE_KEYS.every(k=>stock[k]>=(MISSILES[type].cost[k]??0)+(b.model?.resources[k].reserve??0)))this.issue({type:'PRODUCE_MISSILE',playerId:id,buildingId:silo.id,missileType:type});}
 else if(silo.missile.elapsed>=silo.missile.duration){const radius=MISSILES[silo.missile.type].radius,cells=this.match.map.cells,distance=(a:number,c:number)=>Math.max(Math.abs(cells[a].q-cells[c].q),Math.abs(cells[a].r-cells[c].r),Math.abs(cells[a].q+cells[a].r-cells[c].q-cells[c].r)),allies=this.match.state.buildings.filter(v=>v.ownerId===id||this.match.diplomacy!.allied(id,v.ownerId));const candidates=enemies.filter(v=>this.match.diplomacy!.hostile(id,cells[v.cellId!].ownerId??0)&&!allies.some(a=>a.cellIds.some(n=>distance(n,v.cellId!)<=radius))).map(v=>({id:v.cellId!,score:enemies.reduce((n,e)=>n+(distance(e.cellId!,v.cellId!)<=radius?(e.type?C.strategicValue[e.type]:10):0),0)})).sort((a,c)=>c.score-a.score);if(candidates.length)this.issue({type:'LAUNCH_MISSILE',playerId:id,buildingId:silo.id,anchorId:candidates[0].id});}}
 if(!this.wars(id).length&&this.budget&&!b.navalUnits.length&&this.time>=b.nextNaval&&this.match.state.buildings.some(v=>v.ownerId===id&&v.type==='port'&&!v.construction)){
 const ground=this.indices(id).filter(i=>this.army.kind[i]<2&&!this.army.waitingForTransport[i]&&![UNIT_STATE.attack,UNIT_STATE.retreat,UNIT_STATE.recover].includes(this.army.state[i]as 2|3|4));
 if(ground.length){
  const start={x:this.army.x[ground[0]],y:this.army.y[ground[0]]},cells=this.match.map.cells,candidates:typeof cells=[];
  for(let n=0;n<Math.min(256,cells.length);n++){const c=cells[(b.navalScan+n*97)%cells.length],owner=b.intel.knownOwners.get(c.id);if(c.terrain==='land'&&c.neighbors.some(id=>cells[id].terrain==='water')&&(owner==null||owner===id||this.match.diplomacy!.allied(id,owner))&&!this.army.navigation.connected(start,c))candidates.push(c);}
  b.navalScan=(b.navalScan+256*97)%cells.length;
  for(const dest of candidates.sort((a,c)=>Math.hypot(a.x-start.x,a.y-start.y)-Math.hypot(c.x-start.x,c.y-start.y)).slice(0,3))if(this.move(b,ground.slice(0,Math.max(1,Math.min(10,ground.length-2))),dest,'Expedição naval para explorar outra margem')){b.nextNaval=this.time+45;b.navalUnits=ground.slice(0,Math.max(1,Math.min(10,ground.length-2))).map(i=>this.army.ids[i]);b.navalDestination=dest.id;break;}
 }
 }

 }
 private homeThreatened(b:Bot){const home=this.home(b.playerId);return this.match.state.players.some(p=>this.match.diplomacy!.hostile(b.playerId,p.id)&&b.intel.currentEnemies(p.id).some(v=>Math.hypot(v.x-home.x,v.y-home.y)<C.visionRadius));}
 private recruit(b:Bot){const id=b.playerId,c=this.match.state.economies.find(c=>c.playerId===id)!,m=b.model!,troops=this.indices(id),atWar=!!this.wars(id).length,desired=this.desiredArmy(b);if(troops.length+this.army.queuedFor(id)>=desired||m.foodUrgent&&!atWar)return;
 const barracks=this.match.state.buildings.find(v=>v.ownerId===id&&v.type==='barracks'&&!v.construction&&(this.match.state.training.find(q=>q.buildingId===v.id)?.batches.length??0)<TRAINING.slots);if(!barracks)return;
 b.spending=b.spending.filter(s=>this.time-s.time<C.spendWindow);const spent=b.spending.reduce((n,s)=>n+s.amount,0),allowance=m.income*C.spendWindow*C.militaryBudget[b.state]*BOT_WEIGHTS[b.personality].military;
 const tanks=troops.filter(i=>this.army.kind[i]===1).length,planes=troops.filter(i=>this.army.kind[i]===2).length,type=atWar&&troops.length>=10&&planes<Math.min(3,Math.floor(desired/12))&&c.stock.fuel>250&&c.stock.money>1300&&m.resources.fuel.balancePerMinute>0?'aircraft':atWar&&troops.length>=8&&tanks<Math.floor(desired/8)&&m.resources.fuel.balancePerMinute>0?'tank':'infantry',def=UNITS[type],initial=troops.length+this.army.queuedFor(id)<C.minScouts;
 if(!initial&&spent+def.cost.money!>allowance)return;const investment=b.goals[0]?.building;if(!initial&&investment&&['factory','refinery','city'].includes(investment)&&(!atWar&&b.state!=='TENSÃO'||atWar&&this.strength(id)>=C.minimumWarStrength&&!this.homeThreatened(b))&&c.stock.money<constructionCost(c,investment).money!+def.cost.money!)return;
 if(recruitmentAvailable(this.match.state.buildings,c)<def.population||RESOURCE_KEYS.some(k=>c.stock[k]<(def.cost[k]??0)+m.resources[k].reserve+(b.crossing?.cost[k]??0)))return;
 if(this.issue({type:'RECRUIT_UNITS',playerId:id,buildingId:barracks.id,unitType:type,count:1})){b.spending.push({time:this.time,amount:def.cost.money!});b.action='Recrutando '+def.name.toLowerCase();b.decisions++;this.decisions++;}
 }
 private move(b:Bot,indices:number[],point:{x:number;y:number},goal:string){if(!indices.length||!this.budget)return false;this.budget--;const okay=this.issue({type:'MOVE_UNITS',playerId:b.playerId,unitIds:indices.map(i=>this.army.ids[i]),target:point,formation:'block',cohesion:false});if(okay){b.goal=goal;b.lastOrder=this.time;this.orders++;}return okay;}
 private diplomatic(b:Bot){const id=b.playerId,d=this.match.diplomacy!,s=this.match.social!.get(id),wars=this.wars(id),plan=b.warPlan;
 const command=(action:'prepare_war'|'declare_war'|'cancel_preparation'|'request_truce'|'request_alliance'|'break_alliance'|'call_ally'|'join_war',targetId?:number,warId?:number)=>this.issue({type:'DIPLOMACY_ACTION',playerId:id,action,targetId,warId});
 for(const r of d.state.relations.filter(r=>r.preparedBy===id)){const other=r.a===id?r.b:r.a;if(!plan||plan.target!==other||(!plan.ready&&plan.objection==='Força semelhante ou aliados inimigos'&&d.state.time>=r.readyAt)||b.state==='CRISE'||b.model?.foodUrgent&&this.match.state.economies.find(c=>c.playerId===id)!.stock.food<this.match.state.economies.find(c=>c.playerId===id)!.foodConsumption*C.warFoodSeconds){command('cancel_preparation',other);b.action='Cancelando preparação: necessidade resolvida';return;}if(plan.ready&&d.state.time>=r.readyAt+C.preparationMinimum&&command('declare_war',other)){b.action='Declarando guerra por '+plan.reason;return;}}
 for(const w of wars){const side=d.sides(w).find(side=>side.includes(id))!,opposing=d.sides(w).find(side=>!side.includes(id))!,enemy=opposing[0],previous=b.warProgress.get(w.id),territory=this.match.state.players.find(p=>p.id===id)!.territory,progress=previous&&territory<=previous.territory?previous.lastProgress:this.time,ratio=this.strength(id)/Math.max(1,opposing.reduce((n,p)=>n+b.intel.strength(p),0)),assessment=ratio<.6?'perdida':ratio>1.4?'vantajosa':this.time-progress>C.stalemateSeconds?'equilibrada':'disputada';b.warProgress.set(w.id,{baseline:previous?.baseline??territory,territory,lastProgress:progress,assessment});
 const baseline=previous?.baseline??territory;if(s.morale<C.capitulation.morale&&(territory<baseline*(1-C.capitulation.territoryLoss)||this.strength(id)<C.minimumWarStrength&&this.match.state.economies.find(c=>c.playerId===id)!.population<this.match.state.economies.find(c=>c.playerId===id)!.capacity*.65)&&ratio<1/C.capitulation.forceRatio&&this.strength(id)<this.desiredArmy(b)*C.capitulation.maximumArmyFraction){if(this.issue({type:'SURRENDER',playerId:id,opponentId:enemy})){b.action='Rendição: perdas militares e colapso nacional';return;}}
 if(side[0]===id){if(this.time-w.startedAt>C.truceMinimumWarSeconds&&(assessment==='perdida'||this.time-progress>C.maxUnproductiveWarSeconds)&&command('request_truce',enemy))return;const ally=this.match.state.players.find(p=>p.id!==id&&!p.defeated&&d.allied(id,p.id)&&!d.sides(w).flat().includes(p.id));if(ally&&command('call_ally',ally.id,w.id))return;}}
 if(wars.length||b.state==='RECUPERAÇÃO'||b.state==='CRISE')return;
 if(plan?.ready&&d.relation(id,plan.target)?.state==='NEUTRAL'&&command('prepare_war',plan.target)){b.action='Preparando guerra por '+plan.reason;return;}
 const allies=this.match.state.players.filter(p=>p.id!==id&&!p.defeated&&d.allied(id,p.id));
 for(const ally of allies){const external=this.match.state.players.some(p=>p.id!==id&&p.id!==ally.id&&!p.defeated&&!d.allied(id,p.id)&&(s.threats[p.id]??0)>C.tensionThreshold),border=b.intel.border(ally.id),free=[...this.match.owned.get(id)??[]].filter(cell=>!this.match.economy!.occupied[cell]).length;
 if(!external&&border&&((this.frontier(b).length<8&&free<C.minFreeCells&&this.strength(id)>b.intel.strength(ally.id)*C.allianceDominanceRatio)||this.match.state.players.filter(p=>!p.defeated&&p.id!==id).every(p=>d.allied(id,p.id))&&this.strength(id)>=C.minimumWarStrength)&&command('break_alliance',ally.id)){b.action='Rompendo aliança por disputa territorial';return;}}
 for(const w of d.state.wars.filter(w=>w.endedAt===null&&!d.sides(w).flat().includes(id)))if(d.allied(id,w.defenderId)&&this.strength(id)>=C.minimumWarStrength&&(s.threats[w.attackerId]??0)>C.tensionThreshold&&command('join_war',undefined,w.id))return;
 if(allies.length>=C.maxAllies)return;const candidate=this.match.state.players.filter(p=>p.id!==id&&!p.defeated&&d.relation(id,p.id)?.state==='NEUTRAL'&&(!plan||plan.target!==p.id)).map(p=>({id:p.id,score:this.allianceScore(b,p.id)})).sort((a,b)=>b.score-a.score)[0];if(candidate&&candidate.score>=C.allianceOfferThreshold&&command('request_alliance',candidate.id))b.action='Propondo aliança estratégica';
 }
 debug(){return this.bots.map(b=>({playerId:b.playerId,lastFailure:this.failures.get(b.playerId),personality:b.personality,state:b.state,action:b.action,goals:b.goals.map(({score,label,reason})=>({score,label,reason})),economy:b.model,social:this.match.social!.get(b.playerId),warPlan:b.warPlan,warAssessment:[...b.warProgress],militaryTarget:b.target,crossing:b.crossing,desiredArmy:this.desiredArmy(b),actualArmy:this.indices(b.playerId).length,queued:this.army.queuedFor(b.playerId),strength:this.strength(b.playerId),unitStates:Object.fromEntries([0,1,2,3,4].map(state=>[state,this.indices(b.playerId).filter(i=>this.army.state[i]===state).length])),targetDistance:b.target===null?null:this.indices(b.playerId).map(i=>{const point=b.intel.buildings.get(b.target!);return point?Math.hypot(this.army.x[i]-point.x,this.army.y[i]-point.y):null;}),intelligence:{discovered:b.intel.discovered.size,visible:b.intel.visible.size,units:[...b.intel.units.values()],buildings:[...b.intel.buildings.values()]}}));}
 step(dt:number){if(this.match.state.phase!=='playing'||!this.bots.length)return;this.time+=dt;this.budget=C.ordersPerTick;let changed=false;for(const b of this.bots){if(this.match.state.players.find(p=>p.id===b.playerId)?.defeated){b.action='Derrotado';b.army=0;continue;}b.intel.update(this.time);
 if(this.time>=b.nextStrategy){this.strategic(b);b.nextStrategy=this.time+C.intervals.strategy*this.policy.interval;}
 if(this.time>=b.nextEconomy){this.economic(b);b.nextEconomy=this.time+C.intervals.economy*this.policy.interval;changed=true;}
 if(this.time>=b.nextMilitary&&this.budget>0){this.military(b);b.nextMilitary=this.time+C.intervals.military*this.policy.interval;}
 if(this.time>=b.nextDiplomacy){this.diplomatic(b);b.nextDiplomacy=this.time+C.intervals.diplomacy*this.policy.interval;}}
 if(changed){this.match.state.bots=this.views();this.match.state.revision++;}}
}
