import {AI_CONFIG} from '../../shared/configs/ai';
import type {SocialSystem} from './social';
import {DIPLOMACY,type DiplomaticAction} from '../../shared/configs/diplomacy';
import type {MatchState} from '../territory/types';
import type {DiplomacyState,Relation,War,DiplomaticOffer} from './types';
export function createDiplomacy():DiplomacyState{return {time:0,relations:[],wars:[],offers:[],events:[],revision:0};}
export class DiplomacySystem {
 manualHuman=false;respond:(offer:DiplomaticOffer)=>boolean=()=>true;readonly state:DiplomacyState;private nextWar=1;private nextOffer=1;private nextEvent=1;
 constructor(private match:MatchState,private social?:SocialSystem){this.state=match.diplomacy;for(const a of match.players)for(const b of match.players)if(a.id<b.id)this.state.relations.push({a:a.id,b:b.id,state:'NEUTRAL',preparedBy:null,readyAt:0,truceUntil:0});}
 active(id:number){return !!this.match.players.find(p=>p.id===id&&!p.defeated);}
 private validate(a:number,b:number){if(this.match.phase!=='playing'||a===b||!Number.isInteger(a)||!Number.isInteger(b)||![a,b].every(id=>this.active(id)))throw new Error('Escolha outro país válido.');}
 name(id:number){return this.match.players.find(p=>p.id===id)?.name??'País '+id;}
 relation(a:number,b:number):Relation|undefined{return this.state.relations.find(r=>r.a===Math.min(a,b)&&r.b===Math.max(a,b));}
 allied(a:number,b:number){return this.active(a)&&this.active(b)&&(a===b||this.relation(a,b)?.state==='ALLIED');}
 sides(w:War){return [[w.attackerId,...w.attackerAllies],[w.defenderId,...w.defenderAllies]];}
 warBetween(a:number,b:number){return this.state.wars.find(w=>w.endedAt===null&&this.sides(w).some((side,index)=>side.includes(a)&&this.sides(w)[1-index].includes(b)));}
 hostile(a:number,b:number){return this.active(a)&&this.active(b)&&a!==b&&!!this.warBetween(a,b);}
 captureOwner(actor:number,defender:number){const w=this.warBetween(actor,defender);if(!w)return null;return this.sides(w)[0].includes(actor)?w.attackerId:w.defenderId;}
 private changed(){this.state.revision++;this.match.revision++;this.match.combatOpponents=this.match.players.filter(p=>this.hostile(1,p.id)).map(p=>p.id);}
 event(message:string){this.state.events.push({id:this.nextEvent++,time:this.state.time,message});if(this.state.events.length>DIPLOMACY.eventLimit)this.state.events.shift();this.changed();}
 private offer(kind:DiplomaticOffer['kind'],from:number,to:number,warId:number|null=null){if(this.state.offers.some(o=>o.status==='pending'&&o.kind===kind&&o.from===from&&o.to===to))throw new Error('Já existe uma proposta aguardando resposta.');const o:DiplomaticOffer={id:this.nextOffer++,kind,from,to,warId,replyAt:this.state.time+DIPLOMACY.responseSeconds,status:'pending'};this.state.offers.push(o);if(this.state.offers.length>DIPLOMACY.offerLimit)this.state.offers.shift();this.event(`${this.name(from)} ${kind==='alliance'?'propôs aliança a':kind==='truce'?'propôs trégua a':'solicitou apoio militar de'} ${this.name(to)}.`);}
 private newWar(a:number,b:number,exercise=false){const w:War={id:this.nextWar++,attackerId:a,defenderId:b,attackerAllies:[],defenderAllies:[],startedAt:this.state.time,endedAt:null,exercise};this.state.wars.push(w);if(!exercise)this.social?.war(a,b);const r=this.relation(a,b)!;r.state='WAR';r.preparedBy=null;r.readyAt=0;this.event(`${this.name(a)} declarou guerra a ${this.name(b)}${exercise?' no exercício militar':''}.`);return w;}
 /** Explicit Phase 6 exercise; uses the same authoritative hostility/capture rules. */
 testWar(a:number,b:number){this.validate(a,b);const r=this.relation(a,b)!;if(r.state==='ALLIED'||r.state==='TRUCE')throw new Error('A patrulha não pode abrir guerra durante aliança ou trégua.');return this.warBetween(a,b)??this.newWar(a,b,true);}
 private join(actor:number,w:War){const sides=this.sides(w),side=sides.findIndex(s=>this.allied(actor,s[0]));if(side<0||sides.flat().includes(actor)||sides[1-side].some(id=>this.allied(actor,id)))throw new Error('Esse país não pode participar desse lado da guerra.');const opposing=sides[1-side];if(opposing.some(id=>this.relation(actor,id)!.truceUntil>this.state.time))throw new Error('A trégua impede a entrada nessa guerra.');if(opposing.some(id=>this.hostile(actor,id)))throw new Error('Esse país já participa de outra guerra contra esse adversário.');(side===0?w.attackerAllies:w.defenderAllies).push(actor);for(const opponent of opposing){const r=this.relation(actor,opponent)!;r.state='WAR';r.preparedBy=null;r.readyAt=0;}this.social?.help(actor,side===0?w.attackerId:w.defenderId,side===1);this.event(`${this.name(actor)} entrou na guerra ao lado de ${this.name(side===0?w.attackerId:w.defenderId)}.`);}
 act(actor:number,action:DiplomaticAction,target?:number,warId?:number){if(action==='join_war'){const w=this.state.wars.find(w=>w.id===warId&&w.endedAt===null);if(this.match.phase!=='playing'||!w||!this.active(actor))throw new Error('Guerra inválida.');this.join(actor,w);return;}this.validate(actor,target!);const other=target!,r=this.relation(actor,other)!;
 switch(action){case 'request_alliance':if(r.state!=='NEUTRAL')throw new Error('Alianças só podem ser propostas entre países neutros.');this.offer('alliance',actor,other);break;
 case 'break_alliance':if(r.state!=='ALLIED')throw new Error('Não há aliança para encerrar.');if(this.state.wars.some(w=>w.endedAt===null&&this.sides(w).some(s=>s.includes(actor)&&s.includes(other))))throw new Error('Não é possível romper a aliança durante uma guerra conjunta.');r.state='NEUTRAL';this.social?.betrayal(actor,other);this.event(`${this.name(actor)} encerrou a aliança com ${this.name(other)}.`);break;
 case 'prepare_war':if(r.state!=='NEUTRAL'||r.truceUntil>this.state.time)throw new Error('Encerre a aliança ou aguarde a trégua antes de preparar guerra.');r.state='TENSION';r.preparedBy=actor;r.readyAt=this.state.time+DIPLOMACY.preparationSeconds;this.event(`${this.name(actor)} prepara guerra contra ${this.name(other)}. Tensão por ${DIPLOMACY.preparationSeconds} s.`);break;
 case 'cancel_preparation':if(r.state!=='TENSION'||r.preparedBy!==actor)throw new Error('Não há preparação sua para cancelar.');r.state='NEUTRAL';r.preparedBy=null;r.readyAt=0;this.event(`${this.name(actor)} cancelou a preparação contra ${this.name(other)}.`);break;
 case 'declare_war':if(r.state!=='TENSION'||r.preparedBy!==actor||this.state.time+1e-7<r.readyAt)throw new Error('Prepare a guerra e aguarde o período de tensão.');this.newWar(actor,other);break;
 case 'request_truce':{const w=this.warBetween(actor,other);if(!w||![w.attackerId,w.defenderId].includes(actor)||![w.attackerId,w.defenderId].includes(other))throw new Error('A trégua deve ser negociada entre os líderes da guerra.');this.offer('truce',actor,other,w.id);break;}
 case 'call_ally':{const w=this.state.wars.find(w=>w.id===warId&&w.endedAt===null);if(!w||![w.attackerId,w.defenderId].includes(actor)||!this.allied(actor,other)||this.sides(w).flat().includes(other))throw new Error('Escolha um aliado que ainda não participe da sua guerra.');if(this.sides(w).find(s=>!s.includes(actor))!.some(id=>this.allied(other,id)||this.hostile(other,id)||this.relation(other,id)!.truceUntil>this.state.time))throw new Error('O aliado tem um tratado incompatível com essa guerra.');this.offer('support',actor,other,w.id);break;}
 default:throw new Error('Ação diplomática inválida.');}}

 eliminate(id:number){for(const w of this.state.wars){if(w.endedAt!==null)continue;if(w.attackerId===id||w.defenderId===id){w.endedAt=this.state.time;this.social?.peace(this.sides(w).flat(),AI_CONFIG.recoverySeconds);}w.attackerAllies=w.attackerAllies.filter(p=>p!==id);w.defenderAllies=w.defenderAllies.filter(p=>p!==id);}for(const r of this.state.relations){if(r.a===id||r.b===id||r.state==='WAR'&&!this.hostile(r.a,r.b)){r.state='NEUTRAL';r.preparedBy=null;r.readyAt=0;r.truceUntil=0;}}for(const o of this.state.offers)if(o.status==='pending'&&(o.from===id||o.to===id||o.warId!==null&&this.state.wars.find(w=>w.id===o.warId)?.endedAt!==null))o.status='rejected';this.event(this.name(id)+' perdeu todas as cidades e foi derrotado.');}
 private resolve(o:DiplomaticOffer,accept:boolean){if(!this.active(o.from)||!this.active(o.to)){o.status='rejected';this.changed();return;}if(!accept){o.status='rejected';this.event(`${this.name(o.to)} recusou a proposta de ${this.name(o.from)}.`);return;}try{const r=this.relation(o.from,o.to)!;if(o.kind==='alliance'){if(r.state!=='NEUTRAL')throw new Error();r.state='ALLIED';this.social?.alliance(o.from,o.to);this.event(`${this.name(o.to)} aceitou a aliança com ${this.name(o.from)}.`);}else if(o.kind==='support'){const w=this.state.wars.find(w=>w.id===o.warId&&w.endedAt===null);if(!w||!this.allied(o.from,o.to))throw new Error();this.join(o.to,w);}else {const w=this.state.wars.find(w=>w.id===o.warId&&w.endedAt===null);if(!w)throw new Error();w.endedAt=this.state.time;this.social?.peace(this.sides(w).flat(),AI_CONFIG.recoverySeconds);const [a,b]=this.sides(w);for(const x of a)for(const y of b){const relation=this.relation(x,y)!;if(!this.hostile(x,y)){relation.state='TRUCE';relation.preparedBy=null;relation.readyAt=0;relation.truceUntil=this.state.time+DIPLOMACY.truceSeconds;}}this.event(`Trégua aceita entre ${this.name(w.attackerId)} e ${this.name(w.defenderId)} por ${DIPLOMACY.truceSeconds} s. Conquistas permanecem.`);}o.status='accepted';}catch{o.status='rejected';this.event(`${this.name(o.to)} recusou a proposta: a situação diplomática mudou.`);}this.changed();}
 answer(actor:number,offerId:number,accept:boolean){const o=this.state.offers.find(o=>o.id===offerId&&o.status==='pending'&&o.to===actor);if(this.match.phase!=='playing'||!o||typeof accept!=='boolean')throw new Error('Proposta diplomática indisponível.');this.resolve(o,accept);}
 step(dt:number){this.state.time+=dt;for(const r of this.state.relations)if(r.state==='TRUCE'&&this.state.time+1e-7>=r.truceUntil){r.state='NEUTRAL';r.truceUntil=0;this.event(`A trégua entre ${this.name(r.a)} e ${this.name(r.b)} terminou.`);}for(const o of this.state.offers){if(o.status!=='pending'||this.state.time+1e-7<o.replyAt||this.manualHuman&&o.to===1)continue;this.resolve(o,this.respond(o));}}
}
