import {completeConstruction} from './economy-fixture';
import {describe,it,expect} from 'vitest';
import {Simulation} from '../simulation/engine';
import {DEFAULT_MAP_CONFIG} from '../map/types';
import {economicModel} from '../ai/economy-model';
import {Perception} from '../ai/perception';
import {BUILDINGS} from '../shared/configs/buildings';
import {UNITS} from '../shared/configs/units';
import {TRAINING} from '../shared/configs/training';
import {DIPLOMACY_CONFIG} from '../shared/configs/social';
import {fundCountry} from './economy-fixture';
function setup(){const s=new Simulation();s.command({type:'GENERATE_MAP',config:{...DEFAULT_MAP_CONFIG,size:'small'},requestId:0});for(const c of s.map!.cells)c.terrain='land';s.command({type:'PREPARE_MATCH',playerCount:4,botDifficulty:'off'});s.command({type:'START_MATCH',spawnId:0,name:'Test'});return s;}
describe('Utility AI economic forecasts and hidden social state',()=>{
 it('predicts population demand and separates gross production, consumption, reserves and builder capacity',()=>{const s=setup(),e=s.match!.economy!,c=e.countries[0],m=economicModel(s.match!,1,'DESENVOLVIMENTO',180);expect(m.foodUrgent).toBe(true);expect(m.resources.food.plannedConsumptionPerMinute).toBeGreaterThan(0);expect(m.resources.food.forecast).toBeLessThan(c.stock.food);expect(m.resources.food.shortageInSeconds).toBeGreaterThan(0);expect(m.builders.maximum).toBeCloseTo(c.population*.33);expect(m.factorySafe).toBe(false);});
 it('keeps morale, reputation and bilateral memory independent and out of public snapshots',()=>{const s=setup(),social=s.match!.social!,d=s.match!.diplomacy!,rep=social.get(1).reputation;social.loss(1,10);expect(social.get(1).reputation).toBe(rep);expect(social.get(1).morale).toBeLessThan(70);d.testWar(1,2);expect(social.get(1).reputation).toBe(rep);social.war(1,2);expect(social.get(1).reputation).toBeLessThan(rep);expect(social.get(2).relations[1]).toBeLessThan(social.get(2).relations[3]);expect(JSON.stringify(s.match!.state)).not.toMatch(/reputation|morale|threats|history/);});
 it('reduces war penalty gradually for discredited countries and recovers reputation slowly',()=>{const a=setup(),b=setup();b.match!.social!.get(2).reputation=15;a.match!.social!.war(1,2);b.match!.social!.war(1,2);expect(b.match!.social!.get(1).reputation).toBeGreaterThan(a.match!.social!.get(1).reputation);const before=b.match!.social!.get(2).reputation;b.match!.social!.step(60);expect(b.match!.social!.get(2).reputation-before).toBeLessThan(DIPLOMACY_CONFIG.reputation.peaceRecoveryPerMinute);});
 it('never observes a hidden troop and degrades old information without following live hidden positions',()=>{const s=setup(),intel=new Perception(1,s.match!,s.army!),far=s.map!.cells[s.match!.state.cities[3].anchorId],id=s.army!.spawn(4,'tank',far);intel.update(1);expect(intel.units.has(id)).toBe(false);const home=s.map!.cells[s.match!.state.cities[0].anchorId],i=s.army!.index(id);s.army!.x[i]=home.x;s.army!.y[i]=home.y;intel.update(4);expect(intel.units.get(id)?.confidence).toBe(1);s.army!.x[i]=far.x;s.army!.y[i]=far.y;intel.update(184);expect(intel.units.get(id)?.x).toBeCloseTo(home.x,3);expect(intel.units.get(id)?.confidence).toBeCloseTo(.5);});
});
describe('Preserving infrastructure and explicit destruction',()=>{
 it('captures a city intact after occupation, transfers population and defeats only the previous owner',()=>{const s=setup(),m=s.match!,city=m.state.buildings.find(b=>b.ownerId===2&&b.type==='city')!,point=s.map!.cells[city.anchorId];m.diplomacy!.testWar(1,2);const ids=Array.from({length:3},()=>s.army!.spawn(1,'tank',point));for(let n=0;n<30*20;n++)s.step();expect(city.ownerId).toBe(1);expect(city.hp).toBe(city.maxHp);expect(city.cellIds.every(id=>s.map!.cells[id].ownerId===1)).toBe(true);expect(m.state.players[1].defeated).toBe(true);expect(m.state.players[0].defeated).toBe(false);expect(m.economy!.countries[0].capacity).toBe(BUILDINGS.city.housing*2);expect(ids.every(id=>s.army!.index(id)>=0)).toBe(true);expect(s.telemetry!.data.first.cityCapture).not.toBeNull();});
 it('does not automatically attack a farm; an explicit order attacks it and movement cancels that order',()=>{const s=setup(),m=s.match!,c=fundCountry(m.economy!,2,300),cell=s.map!.cells.find(v=>v.ownerId===2&&!m.economy!.occupied[v.id]&&v.neighbors.filter(n=>s.map!.cells[n].ownerId===2&&!m.economy!.occupied[n]).length>=4)!;
 // Use validated placement to avoid depending on a particular seed layout.
 const owned=[...m.owned.get(2)!];let farm;for(const id of owned){try{farm=m.economy!.build(2,'farm',id,0);break;}catch{}}expect(farm).toBeDefined();const point=s.map!.cells[farm!.anchorId],id=s.army!.spawn(1,'tank',point);m.diplomacy!.testWar(1,2);s.combat!.step(1);expect(farm!.hp).toBe(farm!.maxHp);s.command({type:'ATTACK_BUILDING',playerId:1,unitIds:[id],buildingId:farm!.id});s.combat!.step(2);expect(farm!.hp).toBeLessThan(farm!.maxHp);s.army!.move(1,[id],point);expect(s.army!.buildingOrders.size).toBe(0);void c;void cell;});
 it('pays and waits for actual unit training under the same economy rules',()=>{const s=setup(),m=s.match!,c=fundCountry(m.economy!,1,300);let barracks;for(const cell of m.owned.get(1)!){try{barracks=m.economy!.build(1,'barracks',cell,0);break;}catch{}}completeConstruction(m.economy!,barracks!);const money=c.stock.money;s.army!.recruit(1,barracks!.id,'infantry',1);expect(c.stock.money).toBe(money-UNITS.infantry.cost.money!);s.army!.stepTraining(TRAINING.seconds.infantry-.1);expect(s.army!.count).toBe(0);s.army!.stepTraining(.1);expect(s.army!.count).toBe(1);});
});

describe('Defeat, resistance and recovery safeguards',()=>{
 it('refuses capitulation outside a war and transfers intact infrastructure when surrender is explicit',()=>{const s=setup(),m=s.match!,old=m.state.buildings.find(b=>b.ownerId===2&&b.type==='city')!,stock={...m.state.economies[1].stock},territory=m.state.players[0].territory+m.state.players[1].territory;expect(()=>s.command({type:'SURRENDER',playerId:1,opponentId:2})).toThrow();m.diplomacy!.testWar(1,2);s.command({type:'SURRENDER',playerId:2,opponentId:1},'bot');expect(m.state.players[1].defeated).toBe(true);expect(old.ownerId).toBe(1);expect(old.hp).toBe(old.maxHp);expect(m.state.cities.find(c=>c.id===old.id)?.ownerId).toBe(1);expect(m.owned.has(2)).toBe(false);expect(m.state.players[0].territory).toBe(territory);expect(m.state.economies[1].stock.money).toBe(0);expect(m.state.economies[0].stock.money).toBeGreaterThan(stock.money);});
 it('does not capture an economic structure when attackers have an explicit destruction order',()=>{const s=setup(),m=s.match!,city=m.state.buildings.find(b=>b.ownerId===2&&b.type==='city')!,point=s.map!.cells[city.anchorId],ids=Array.from({length:3},()=>s.army!.spawn(1,'infantry',point));m.diplomacy!.testWar(1,2);s.army!.attackBuilding(1,ids,city.id);for(let n=0;n<22;n++)s.territorial!.step(1);expect(city.ownerId).toBe(2);expect(city.hp).toBe(city.maxHp);});
 it('conserves inhabitants while relocating surplus between cities',()=>{const s=setup(),m=s.match!,e=m.economy!,first=e.buildings.find(b=>b.ownerId===1&&b.city)!,candidate=e.buildings.find(b=>b.ownerId===2&&b.city)!;m.diplomacy!.testWar(1,2);m.captureBuilding(1,candidate.id);first.city!.population=first.city!.capacity+80;candidate.city!.population=20;e.recalculate();const population=e.countries[0].population;e.step(.5);expect(first.city!.population).toBeLessThan(first.city!.capacity+80);expect(candidate.city!.population).toBeGreaterThan(20);expect(e.countries[0].population).toBeGreaterThanOrEqual(population);expect(e.countries[0].population-population).toBeLessThan(1);});
});
