import {VICTORY} from '../shared/configs/victory';
import {fundCountry} from './economy-fixture';
import {BUILDINGS} from '../shared/configs/buildings';
import {describe,it,expect} from 'vitest';
import {Simulation} from '../simulation/engine';
import {DEFAULT_MAP_CONFIG} from '../map/types';
import {type BotDifficulty} from '../shared/configs/bots';
function setup(difficulty:BotDifficulty='normal',hold=30){const sim=new Simulation();sim.command({type:'GENERATE_MAP',config:{...DEFAULT_MAP_CONFIG,size:'small'},requestId:0});for(const c of sim.map!.cells)c.terrain='land';sim.command({type:'PREPARE_MATCH',playerCount:4,botDifficulty:difficulty,victoryHoldSeconds:hold});sim.command({type:'START_MATCH',spawnId:0,name:'Human'});return sim;}
function ticks(s:Simulation,seconds:number){for(let n=0;n<seconds*20;n++)s.step();}
function dominate(s:Simulation,actor=1){const target=Math.ceil(s.match!.state.landTotal*VICTORY.territoryFraction);for(const cell of s.map!.cells){if(s.match!.state.players[actor-1].territory>=target)break;if(cell.ownerId===null)s.match!.captureCellInWar(actor,cell.id);}expect(s.match!.state.players[actor-1].territory).toBe(target);}
describe('Phase 9 bots',()=>{
 it('builds, recruits with paid costs, expands and keeps public state compact',async()=>{const s=setup();for(let n=0;n<30;n++){ticks(s,30);await new Promise(resolve=>setTimeout(resolve,0));}const state=s.match!.state;expect(state.bots.map(b=>b.personality)).toEqual(['aggressive','economic','diplomatic']);for(const p of state.players.slice(1)){if(p.defeated)continue;expect(p.territory).toBeGreaterThan(61);expect(state.buildings.some(b=>b.ownerId===p.id&&b.type==='barracks')).toBe(true);expect(state.buildings.some(b=>b.ownerId===p.id&&b.type==='mine')).toBe(true);// Different resource bonuses and city income make the passive human stock an invalid spending baseline.
expect(state.buildings.filter(b=>b.ownerId===p.id&&!b.initial).reduce((spent,b)=>spent+(b.materialsSpent.money??0),0)).toBeGreaterThan(0);expect(Number.isFinite(state.economies[p.id-1].stock.money)).toBe(true);expect(state.bots[p.id-2].army).toBeGreaterThan(3);expect(state.bots[p.id-2].army).toBeLessThanOrEqual(state.economies[p.id-1].population*.5);expect(state.economies[p.id-1].maxBuilders).toBeCloseTo(state.economies[p.id-1].population*.33);for(const amount of Object.values(state.economies[p.id-1].stock))expect(amount).toBeGreaterThanOrEqual(0);}expect(state.buildings.some(b=>b.ownerId!==1&&b.type==='farm')).toBe(true);for(let n=0;n<10;n++){ticks(s,30);await new Promise(resolve=>setTimeout(resolve,0));}expect(state.buildings.some(b=>b.ownerId!==1&&(b.type==='factory'||b.type==='refinery'||b.type==='city'&&!b.initial))).toBe(true);expect('constructionCount'in state.economies[0]).toBe(false);expect(state.players[0].territory).toBeGreaterThanOrEqual(0);expect('frontier'in state.bots[0]).toBe(false);},120000);
 it('prioritizes peaceful expansion and sends alliance proposals for human acceptance',()=>{const s=setup();ticks(s,330);const d=s.match!.diplomacy!;expect(d.state.wars).toHaveLength(0);expect(d.state.relations.some(r=>r.state==='TENSION')).toBe(false);// An offer now needs a strategic reason; the human still answers it explicitly.
 if(!d.state.offers.some(o=>o.to===1&&o.status==='pending'))s.command({type:'DIPLOMACY_ACTION',playerId:2,action:'request_alliance',targetId:1},'bot');const offer=d.state.offers.find(o=>o.to===1&&o.status==='pending')!;expect(offer).toBeDefined();s.command({type:'DIPLOMACY_RESPONSE',playerId:1,offerId:offer.id,accept:true});expect(offer.status).toBe('accepted');expect(d.allied(offer.from,1)).toBe(true);expect(()=>s.command({type:'DIPLOMACY_RESPONSE',playerId:1,offerId:offer.id,accept:true})).toThrow();});
 it('uses deterministic choices and freezes all bot work while paused',()=>{const a=setup(),b=setup();ticks(a,30);ticks(b,30);expect(a.army!.snapshot()).toEqual(b.army!.snapshot());expect(a.match!.state).toEqual(b.match!.state);a.paused=true;const before=structuredClone(a.match!.state),army=a.army!.snapshot(),decisions=a.bots!.decisions;ticks(a,60);expect(a.match!.state).toEqual(before);expect(a.army!.snapshot()).toEqual(army);expect(a.bots!.decisions).toBe(decisions);});
 it('enforces actor authority and the same recruitment costs and movement ownership for bots',()=>{const s=setup('off');fundCountry(s.match!.economy!,2);const p=s.match!.state.spawns.find(p=>p.id===s.match!.state.players[1].spawnId)!,c=s.map!.cells[p.cellIds.find(id=>!s.match!.economy!.occupied[id])!];expect(()=>s.command({type:'BUILD_STRUCTURE',playerId:2,buildingType:'refinery',anchorId:c.id,rotation:0})).toThrow(/jogador/);s.command({type:'BUILD_STRUCTURE',playerId:2,buildingType:'refinery',anchorId:c.id,rotation:0},'bot');expect(s.match!.state.economies[1].stock.money).toBe(10000-BUILDINGS.refinery.cost.money!);const id=s.army!.spawn(2,'infantry',c);expect(()=>s.command({type:'MOVE_UNITS',playerId:1,unitIds:[id],target:c})).toThrow();expect(()=>s.command({type:'MOVE_UNITS',playerId:2,unitIds:[id],target:c},'bot')).not.toThrow();});
 it('supports a passive sandbox and bounded difficulty without economic cheats',()=>{const off=setup('off'),easy=setup('easy'),hard=setup('hard');expect(easy.match!.state.economies.map(c=>c.stock)).toEqual(hard.match!.state.economies.map(c=>c.stock));ticks(off,120);expect(off.army!.count).toBe(0);expect(off.match!.state.bots).toHaveLength(0);expect(off.match!.state.players.every(p=>p.territory===61)).toBe(true);ticks(easy,30);ticks(hard,30);expect(hard.bots!.decisions).toBeGreaterThan(easy.bots!.decisions);expect(easy.match!.state.diplomacy.wars).toHaveLength(0);});
 it('retreats injured troops to an owned barracks and clears bots on a new map',()=>{const s=setup();ticks(s,300);const i=Array.from(s.army!.ids).findIndex((id,i)=>id&&s.army!.owner[i]===2),id=s.army!.ids[i];s.army!.hp[i]=20;ticks(s,1);expect(s.army!.recovery.has(s.army!.index(id))).toBe(true);const bots=s.bots;s.command({type:'RESET'});expect(s.bots).toBe(bots);s.command({type:'GENERATE_MAP',config:{...DEFAULT_MAP_CONFIG,size:'small'},requestId:1});expect(s.bots).toBeNull();expect(s.victory).toBeNull();});
});
describe('Phase 10 victory',()=>{
 it('counts all land, including unclaimed land, and requires a full uninterrupted 30 seconds',()=>{const s=setup('off');ticks(s,40);expect(s.match!.state.victory.leaderId).toBeNull();dominate(s);ticks(s,29.95);expect(s.match!.state.phase).toBe('playing');expect(s.match!.state.victory.heldSeconds).toBeCloseTo(29.95);s.step();expect(s.match!.state.phase).toBe('finished');expect(s.match!.state.victory.winnerId).toBe(1);expect(s.match!.state.victory.heldSeconds).toBe(30);});
 it('resets held time immediately if even one transfer drops control below the configured fraction',()=>{const s=setup('off',5);dominate(s);ticks(s,4);s.match!.diplomacy!.testWar(2,1);const id=Array.from(s.match!.owned.get(1)!).find(id=>!s.match!.economy!.occupied[id])!;s.match!.captureCellInWar(2,id);s.step();expect(s.match!.state.victory.heldSeconds).toBe(0);expect(s.match!.state.victory.leaderId).toBeNull();s.match!.captureCellInWar(1,id);ticks(s,4.95);expect(s.match!.state.phase).toBe('playing');s.step();expect(s.match!.state.phase).toBe('finished');});
 it('supports an opponent winner and freezes gameplay and commands after the result',()=>{const s=setup('off',1);dominate(s,2);const c=s.map!.cells.find(c=>c.ownerId===1)!;s.army!.spawn(1,'infantry',c);ticks(s,1);expect(s.match!.state.victory.winnerId).toBe(2);const state=structuredClone(s.match!.state),army=s.army!.snapshot();ticks(s,60);expect(s.match!.state).toEqual(state);expect(s.army!.snapshot()).toEqual(army);expect(()=>s.command({type:'DIPLOMACY_ACTION',playerId:1,action:'request_alliance',targetId:3})).toThrow(/terminou/);s.command({type:'RESET'});expect(s.match!.state.phase).toBe('finished');});
 it('holds the victory clock during pause and rejects invalid rules without replacing state',()=>{const s=setup('off',2);dominate(s);ticks(s,1);s.paused=true;ticks(s,20);expect(s.match!.state.victory.heldSeconds).toBeCloseTo(1);s.paused=false;ticks(s,1);expect(s.match!.state.phase).toBe('finished');const bad=new Simulation();bad.command({type:'GENERATE_MAP',config:DEFAULT_MAP_CONFIG,requestId:0});bad.command({type:'PREPARE_MATCH',playerCount:4,botDifficulty:'off'});const before=bad.match;expect(()=>bad.command({type:'PREPARE_MATCH',playerCount:4,victoryHoldSeconds:0})).toThrow();expect(bad.match).toBe(before);});
});
describe('Phase 11 bounded incremental processing',()=>{
 it('maintains ownership indices and limits siege scans to relevant countries and treaty changes',()=>{const s=setup('off');for(const p of s.match!.state.players)expect(s.match!.owned.get(p.id)!.size).toBe(p.territory);s.match!.diplomacy!.testWar(1,2);s.territorial!.step(1);const scans=s.territorial!.scans;s.match!.diplomacy!.event('Informational event');s.territorial!.step(1);expect(s.territorial!.scans).toBe(scans);const c=s.map!.cells.find(c=>c.ownerId===null)!;s.match!.captureCellInWar(1,c.id);expect(s.match!.owned.get(1)!.size).toBe(62);s.territorial!.step(1);expect(s.territorial!.scans).toBe(scans+1);s.territorial!.step(1);expect(s.territorial!.scans).toBe(scans+1);});
 it('writes exact military snapshots into reusable storage and reports finite system timings',()=>{const s=setup('off'),c=s.map!.cells.find(c=>c.ownerId===1)!;s.army!.spawn(1,'tank',c);const storage=new Float32Array(16);expect(s.army!.snapshot(storage)).toBe(storage);expect(storage[15]).toBe(100);ticks(s,1);for(const n of Object.values(s.profile))expect(Number.isFinite(n)).toBe(true);expect(s.profile.samples).toBe(20);expect(s.profile.totalMs).toBeGreaterThan(0);});
});
