import {describe,it,expect} from 'vitest';
import {Simulation} from '../simulation/engine';
import {DEFAULT_MAP_CONFIG} from '../map/types';
import {BUILDINGS,CONSTRUCTION,type BuildingType} from '../shared/configs/buildings';
import {evaluatePlacement,footprintCells} from '../simulation/economy/placement';
import {bridgeBanks} from '../map/bridges';
import {fundCountry} from './economy-fixture';
function setup(){const sim=new Simulation(false);sim.command({type:'GENERATE_MAP',config:{...DEFAULT_MAP_CONFIG,size:'small'},requestId:0});sim.command({type:'PREPARE_MATCH',playerCount:2,botDifficulty:'off'});sim.command({type:'START_MATCH',spawnId:0,name:'Obras'});const match=sim.match!,e=match.economy!,map=sim.map!,country=fundCountry(e);return {sim,match,e,map,country};}
function build(s:ReturnType<typeof setup>,type:BuildingType){const anchor=s.map.cells.find(c=>evaluatePlacement(s.map,s.e.occupied,s.country,1,type,c.id,0,(a,b)=>s.match.diplomacy!.allied(a,b)).valid)!;return s.e.build(1,type,anchor.id,0);}
describe('Timed construction and reserved builders',()=>{
 it.each(['farm','mine','refinery','factory','barracks','defense'] as const)('reserves workers for %s and settles exactly once after its duration',type=>{const s=setup(),before=s.country.builders,b=build(s,type),def=BUILDINGS[type],timing=CONSTRUCTION[type];expect(s.country.builders).toBeCloseTo(before-def.builders);expect(s.country.busyBuilders).toBe(def.builders);expect(b.construction?.duration).toBe(timing.seconds);s.e.stepConstruction(timing.seconds-.1);expect(b.construction).toBeDefined();expect(s.country.builders).toBeCloseTo(before-def.builders);s.e.stepConstruction(.1);expect(b.construction).toBeUndefined();expect(b.buildersSpent).toBeCloseTo(def.builders*timing.loss);expect(s.country.builders).toBeCloseTo(before-def.builders*timing.loss);expect(s.country.busyBuilders).toBe(0);const returned=s.country.builders;s.e.stepConstruction(100);expect(s.country.builders).toBe(returned);});
 it('produces nothing before completion and regenerates continuously without counting reserved workers twice',()=>{const s=setup();s.country.builders=40;const food=s.country.foodProduction,b=build(s,'farm'),before=s.country.builders;s.e.step(2);expect(s.country.builders).toBeGreaterThan(before);expect(s.country.foodProduction).toBe(food);s.e.stepConstruction(8);expect(s.country.foodProduction).toBeCloseTo(BUILDINGS.farm.production.food!*b.bonus);expect(s.country.builders+(s.country.busyBuilders??0)).toBeLessThanOrEqual(s.country.maxBuilders);});
 it('cancellation returns committed workers once and preserves spent materials and starter rights',()=>{const s=setup(),before=s.country.builders,b=build(s,'farm'),stock={...s.country.stock};s.e.stepConstruction(3);s.e.demolish(1,b.id);expect(s.country.builders).toBeCloseTo(before);expect(s.country.stock).toEqual(stock);expect(s.country.freeBuildsUsed.farm).toBe(true);expect(s.e.occupied[b.anchorId]).toBe(0);s.e.destroy(b.id);s.e.stepConstruction(50);expect(s.country.builders).toBeCloseTo(before);});
 it('does not add housing or transfer settlers until the city finishes',()=>{const s=setup(),capacity=s.country.capacity,pop=s.country.population;const anchor=s.map.cells.find(c=>footprintCells(s.map,'city',c.id,0).every(id=>id>=0&&s.map.cells[id].terrain==='land'&&!s.e.occupied[id]&&[null,1].includes(s.map.cells[id].ownerId)))!;for(const id of footprintCells(s.map,'city',anchor.id,0))s.match.captureAtPosition(1,s.map.cells[id].x,s.map.cells[id].y);const b=s.e.build(1,'city',anchor.id,0);expect(s.country.capacity).toBe(capacity);expect(b.city!.population).toBe(0);s.e.stepConstruction(30);expect(s.country.capacity).toBe(capacity+BUILDINGS.city.housing);expect(s.country.population).toBe(pop);expect(b.city!.population).toBe(20);});
 it('does not recruit or fire from unfinished military structures',()=>{const s=setup(),b=build(s,'barracks');expect(()=>s.sim.army!.recruit(1,b.id,'infantry',1)).toThrow(/quartel/);s.e.stepConstruction(20);expect(()=>s.sim.army!.recruit(1,b.id,'infantry',1)).not.toThrow();const defense=build(s,'defense'),c=s.map.cells[defense.anchorId],id=s.sim.army!.spawn(2,'tank',{x:c.x+180,y:c.y});s.match.diplomacy!.testWar(1,2);const hp=s.sim.army!.hp[s.sim.army!.index(id)];s.sim.combat!.step(1);expect(s.sim.army!.hp[s.sim.army!.index(id)]).toBe(hp);s.e.stepConstruction(8);s.sim.combat!.step(1);expect(s.sim.army!.hp[s.sim.army!.index(id)]).toBeLessThan(hp);});
 it('pauses work with the simulation and updates structure state at completion',()=>{const s=setup(),b=build(s,'farm');s.sim.paused=true;for(let n=0;n<300;n++)s.sim.step();expect(b.construction!.elapsed).toBe(0);s.sim.paused=false;for(let n=0;n<200;n++)s.sim.step();expect(b.construction).toBeUndefined();expect(s.match.state.buildingRevision).toBeGreaterThan(1);});
});
describe('Bridge bank diplomacy',()=>{
 function river(){const s=setup(),cell=s.map.cells.find(c=>bridgeBanks(s.map,c.id)&&!s.e.occupied[c.id])!,banks=bridgeBanks(s.map,cell.id)!;s.map.cells[banks[0]].ownerId=1;s.map.cells[banks[1]].ownerId=2;return {...s,cell,banks};}
 it('rejects neutral relations, tension, truce and war while permitting an allied bank',()=>{const s=river(),check=()=>evaluatePlacement(s.map,s.e.occupied,s.country,1,'bridge',s.cell.id,0,(a,b)=>s.match.diplomacy!.allied(a,b));for(const state of ['NEUTRAL','TENSION','TRUCE','WAR'] as const){s.match.state.diplomacy.relations[0].state=state;expect(check().valid).toBe(false);expect(()=>s.e.build(1,'bridge',s.cell.id,0)).toThrow(/aliados/);}s.match.state.diplomacy.relations[0].state='ALLIED';expect(check().valid).toBe(true);const b=s.e.build(1,'bridge',s.cell.id,0);expect(s.cell.bridgeOwnerId??null).toBeNull();s.e.stepConstruction(CONSTRUCTION.bridge.seconds);expect(s.cell.bridgeOwnerId).toBe(1);expect(b.construction).toBeUndefined();});
 it('permits own-to-neutral expansion',()=>{const s=river();s.map.cells[s.banks[1]].ownerId=null;expect(()=>s.e.build(1,'bridge',s.cell.id,0)).not.toThrow();});
 it('revalidates the alliance at completion and returns builders if the banks become rivals during work',()=>{const s=river();s.match.state.diplomacy.relations[0].state='ALLIED';const before=s.country.builders,b=s.e.build(1,'bridge',s.cell.id,0);s.match.state.diplomacy.relations[0].state='WAR';s.e.stepConstruction(CONSTRUCTION.bridge.seconds);expect(s.e.buildings).not.toContain(b);expect(s.cell.bridgeOwnerId??null).toBeNull();expect(s.country.builders).toBeCloseTo(before);});
});

describe('Concurrent work and ownership transitions',()=>{
 it('settles two simultaneous works independently and keeps every other reservation intact',()=>{const s=setup(),before=s.country.builders,farm=build(s,'farm'),mine=build(s,'mine');expect(s.country.busyBuilders).toBe(BUILDINGS.farm.builders+BUILDINGS.mine.builders);s.e.stepConstruction(10);expect(farm.construction).toBeUndefined();expect(mine.construction?.elapsed).toBe(10);expect(s.country.builders).toBeCloseTo(before-BUILDINGS.mine.builders-BUILDINGS.farm.builders*.25);expect(s.country.busyBuilders).toBe(BUILDINGS.mine.builders);s.e.stepConstruction(4);expect(s.country.builders).toBeCloseTo(before-BUILDINGS.mine.builders*.3-BUILDINGS.farm.builders*.25);expect(s.country.busyBuilders).toBe(0);});
 it('transfers an unfinished work and its reserved builders during surrender',()=>{const s=setup(),b=build(s,'mine');s.match.diplomacy!.testWar(1,2);s.match.surrender(1,2);expect(b.ownerId).toBe(2);expect(b.construction!.ownerId).toBe(2);const winner=s.e.countries[1],before=winner.builders;expect(winner.busyBuilders).toBe(BUILDINGS.mine.builders);s.e.stepConstruction(14);expect(b.construction).toBeUndefined();expect(winner.builders).toBeCloseTo(before+BUILDINGS.mine.builders*.7);expect(s.country.busyBuilders).toBe(0);});
 it('adds the new city to the match only after its work completes',()=>{const s=setup(),anchor=s.map.cells.find(c=>footprintCells(s.map,'city',c.id,0).every(id=>id>=0&&s.map.cells[id].terrain==='land'&&!s.e.occupied[id]&&[null,1].includes(s.map.cells[id].ownerId)))!;for(const id of footprintCells(s.map,'city',anchor.id,0))s.match.captureAtPosition(1,s.map.cells[id].x,s.map.cells[id].y);s.match.build(1,'city',anchor.id,0);const b=s.e.buildings.at(-1)!;expect(s.match.state.cities.some(c=>c.id===b.id)).toBe(false);for(let n=0;n<600;n++)s.sim.step();expect(b.construction).toBeUndefined();expect(s.match.state.cities.find(c=>c.id===b.id)?.ownerId).toBe(1);});
});
