import {describe,it,expect} from 'vitest';
import {COUNTRIES,assignCountries,spriteCountryTint} from '../shared/configs/countries';
import {Simulation} from '../simulation/engine';
import {DEFAULT_MAP_CONFIG} from '../map/types';
function prepare(){const sim=new Simulation(false);sim.command({type:'GENERATE_MAP',config:DEFAULT_MAP_CONFIG,requestId:0});sim.command({type:'PREPARE_MATCH',playerCount:4,botDifficulty:'off'});return sim;}
describe('Países e identificação visual',()=>{
 it('oferece 20 países distintos com nomes, bandeiras e cores e escolhe bots determinísticos sem repetir',()=>{expect(COUNTRIES).toHaveLength(20);expect(new Set(COUNTRIES.map(c=>c.id)).size).toBe(20);expect(new Set(COUNTRIES.map(c=>c.color)).size).toBe(20);expect(COUNTRIES.every(c=>c.name&&c.flag)).toBe(true);const countries=assignCountries(8,'br',undefined,'map');expect(new Set(countries.map(c=>c.id)).size).toBe(8);expect(countries).toEqual(assignCountries(8,'br',undefined,'map'));});
 it('reserva escolhas explícitas dos bots antes de sortear os demais',()=>{const chosen=assignCountries(4,'jp',['random','br','us'],'test');expect(chosen[0].id).toBe('jp');expect(chosen[2].id).toBe('br');expect(chosen[3].id).toBe('us');expect(['jp','br','us']).not.toContain(chosen[1].id);});
 it('usa o país escolhido para nome e cor, sem mudar os recursos iniciais',()=>{const sim=prepare();sim.command({type:'START_MATCH',spawnId:2,name:'Brasil',countryId:'br',botCountryIds:['us','jp','random']});const state=sim.match!.state;expect(state.players[0]).toMatchObject({name:'Brasil',countryId:'br',color:COUNTRIES[0].color,spawnId:2});expect(state.players[1].name).toBe('Estados Unidos');expect(state.players[2].name).toBe('Japão');expect(new Set(state.players.map(p=>p.countryId)).size).toBe(4);expect(state.players.every(p=>p.territory===61)).toBe(true);expect(state.economies[0].stock).toEqual(state.economies[1].stock);});
 it('rejeita seleção duplicada, desconhecida e quantidade inválida sem iniciar a partida',()=>{const sim=prepare();for(const ids of [['br','jp','us'],['unknown','jp','us'],['jp'],['jp','jp','us']]){expect(()=>sim.command({type:'START_MATCH',spawnId:0,name:'Brasil',countryId:'br',botCountryIds:ids})).toThrow();expect(sim.match!.state.phase).toBe('preparation');expect(sim.match!.state.players).toHaveLength(0);}expect(()=>sim.command({type:'START_MATCH',spawnId:0,name:'?',countryId:'unknown'})).toThrow();});
 it('mantém luz e detalhe na tonalização de sprites',()=>{expect(spriteCountryTint(0xffffff)).toBe(0xffffff);expect(spriteCountryTint(0x000000)).toBe(0x8c8c8c);expect(spriteCountryTint(0xff0000)).toBe(0xff8c8c);});
});
