import {completeConstruction} from './economy-fixture';
import {describe,it,expect} from 'vitest';
import {Simulation} from '../simulation/engine';
import {DEFAULT_MAP_CONFIG} from '../map/types';
import {BUILDINGS,type BuildingType} from '../shared/configs/buildings';
import {ECONOMY_CONFIG as C} from '../shared/configs/economy';
import {constructionCost} from '../simulation/economy/rules';
import {evaluatePlacement,footprintCells} from '../simulation/economy/placement';
import {recruitmentAvailable} from '../simulation/economy/recruitment';
import {TRAINING} from '../shared/configs/training';
import {fundCountry} from './economy-fixture';
function setup(){const sim=new Simulation(false);sim.command({type:'GENERATE_MAP',config:DEFAULT_MAP_CONFIG,requestId:0});for(const c of sim.map!.cells)c.terrain='land';sim.command({type:'PREPARE_MATCH',playerCount:2,botDifficulty:'off'});sim.command({type:'START_MATCH',spawnId:0,name:'Teste'});const e=sim.match!.economy!,country=fundCountry(e,1,200);for(const c of sim.map!.cells)if(c.ownerId!==2)c.ownerId=1;return {sim,e,country,map:sim.map!,army:sim.army!};}
function build(s:ReturnType<typeof setup>,type:BuildingType,near?:number){s.country.builders=s.country.maxBuilders;const anchors=s.map.cells.filter(c=>evaluatePlacement(s.map,s.e.occupied,s.country,1,type,c.id,0).valid);if(near!==undefined){const p=s.map.cells[near];anchors.sort((a,b)=>(a.x-p.x)**2+(a.y-p.y)**2-((b.x-p.x)**2+(b.y-p.y)**2));}return completeConstruction(s.e,s.e.build(1,type,anchors[0].id,0));}
describe('Fixed economy and territorial recruitment',()=>{
 it('keeps all construction prices fixed after investment and destruction',()=>{const s=setup();s.country.freeBuildsUsed={farm:true,mine:true};const prices=Object.fromEntries(Object.keys(BUILDINGS).map(t=>[t,constructionCost(s.country,t as BuildingType)]));for(let n=0;n<5;n++){const b=build(s,'defense');s.e.destroy(b.id);}for(const t of Object.keys(BUILDINGS))expect(constructionCost(s.country,t as BuildingType)).toEqual(prices[t]);expect(constructionCost(s.country,'factory')).toEqual({money:850,mineral:180,fuel:50});});
 it('provides 300 housing per city without generating free citizens',()=>{const s=setup(),before=s.country.population,newCity=build(s,'city');expect(s.country.capacity).toBe(600);expect(s.country.population).toBe(before);expect(newCity.city!.population).toBe(C.newCitySettlers);s.e.step(1);expect(s.country.population).toBeCloseTo(before+C.cityGrowth*2);});
 it.each(['mine','farm','refinery']as const)('counts all rich footprint cells for %s, including noncentral deposits',type=>{const s=setup(),anchor=s.map.cells.find(c=>evaluatePlacement(s.map,s.e.occupied,s.country,1,type,c.id,0).valid)!,ids=footprintCells(s.map,type,anchor.id,0);for(const id of ids)s.map.cells[id].resource=null;expect(evaluatePlacement(s.map,s.e.occupied,s.country,1,type,anchor.id,0).bonus).toBe(1);for(let n=0;n<ids.length;n++){s.map.cells[ids[ids.length-1-n]].resource=BUILDINGS[type].bonusResource;expect(evaluatePlacement(s.map,s.e.occupied,s.country,1,type,anchor.id,0).bonus).toBeCloseTo(1+(n+1)/ids.length);}for(const id of ids)s.map.cells[id].resource=null;s.map.cells[ids.at(-1)!].resource=BUILDINGS[type].bonusResource;const b=completeConstruction(s.e,s.e.build(1,type,anchor.id,0)),bonus=1+1/ids.length,key=type==='farm'?'food':type==='mine'?'mineral':'fuel';expect(b.bonus).toBeCloseTo(bonus);expect(s.country.rates[key]).toBeCloseTo(BUILDINGS[type].production[key]!*bonus-(key==='food'?s.country.foodConsumption:0));});
 it('recruits five tank crew from the nearest city then the next, keeping local reserves',()=>{const s=setup(),first=s.e.buildings.find(b=>b.ownerId===1&&b.city)!,near=build(s,'city');near.city!.population=22;first.city!.population=100;s.e.recalculate();const barracks=build(s,'barracks',near.anchorId);s.army.recruit(1,barracks.id,'tank',1);expect(near.city!.population).toBe(20);expect(first.city!.population).toBe(97);expect(s.country.population).toBe(117);expect(s.sim.match!.state.training[0].batches[0].populationSources).toEqual([{cityId:near.id,population:2},{cityId:first.id,population:3}]);});
 it('rejects insufficient local civilian reserves without spending resources or queue slots',()=>{const s=setup();for(let n=0;n<3;n++)build(s,'city');const b=build(s,'barracks');for(const city of s.e.buildings.filter(b=>b.ownerId===1&&b.city))city.city!.population=20;s.e.recalculate();const stock={...s.country.stock};expect(recruitmentAvailable(s.e.buildings,s.country)).toBe(0);expect(()=>s.army.recruit(1,b.id,'infantry',1)).toThrow(/População/);expect(s.country.stock).toEqual(stock);expect(s.army.queuedCount).toBe(0);});
 it('refunds only untrained civilians to their origin when the barracks is destroyed',()=>{const s=setup(),city=s.e.buildings.find(b=>b.ownerId===1&&b.city)!,near=build(s,'city');city.city!.population=100;near.city!.population=40;s.e.recalculate();const b=build(s,'barracks',near.anchorId);s.army.recruit(1,b.id,'infantry',3);expect(near.city!.population).toBe(37);s.army.stepTraining(TRAINING.seconds.infantry);expect(s.army.count).toBe(1);s.e.destroy(b.id);s.army.stepTraining(.05);expect(near.city!.population).toBe(39);expect(city.city!.population).toBe(100);expect(s.army.queuedCount).toBe(0);});
});
