import {describe,it,expect} from 'vitest';
import {Simulation} from '../simulation/engine';
import {DEFAULT_MAP_CONFIG} from '../map/types';
import {BUILDINGS,CONSTRUCTION,BUILDING_TYPES,type BuildingType} from '../shared/configs/buildings';
import {ECONOMY_CONFIG as C} from '../shared/configs/economy';
import {evaluatePlacement,footprintCells,rotateHex} from '../simulation/economy/placement';
import {builderRecovery,cityDemand,constructionCost,constructionCostRows} from '../simulation/economy/rules';
import {fundCountry,completeConstruction} from './economy-fixture';
function setup(){const sim=new Simulation(false);sim.command({type:'GENERATE_MAP',config:DEFAULT_MAP_CONFIG,requestId:0});sim.command({type:'PREPARE_MATCH',playerCount:4,botDifficulty:'off'});sim.command({type:'START_MATCH',spawnId:0,name:'Human'});return sim;}
function location(sim:Simulation,type:BuildingType,playerId=1){const e=sim.match!.economy!;return [...sim.match!.owned.get(playerId)!].map(id=>sim.map!.cells[id]).find(c=>evaluatePlacement(sim.map!,e.occupied,e.countries.find(c=>c.playerId===playerId),playerId,type,c.id,0).valid);}
function build(sim:Simulation,type:BuildingType,playerId=1){const anchor=location(sim,type,playerId);expect(anchor).toBeDefined();sim.match!.build(playerId,type,anchor!.id,0);return sim.match!.state.buildings.at(-1)!;}
describe('Population economy and consumed builders',()=>{
 it('initializes equal limited stocks and updates only on existing economy ticks, respecting pause',()=>{const s=setup(),e=s.match!.economy!,c=e.countries[0];expect(c.stock).toEqual(C.initialStock);expect(c.population).toBe(80);expect(c.maxBuilders).toBeCloseTo(26.4);expect(c.builders).toBeCloseTo(26.4);expect(c.rates.food).toBe(-80*C.foodPerPerson);for(let n=0;n<9;n++)s.step();expect(c.stock.money).toBe(100);s.step();expect(c.stock.money).toBe(100+BUILDINGS.city.production.money!*.5);expect(c.population).toBeCloseTo(80.2);s.paused=true;const before=structuredClone(c);for(let n=0;n<100;n++)s.step();expect(c).toEqual(before);});
 it('supports a second city at 200 population with the recovered 33% constructor capacity',()=>{const s=setup(),e=s.match!.economy!,c=fundCountry(e,1,200);expect(c.maxBuilders).toBe(66);c.builders=0;c.stock.food=0;e.recalculate();e.step(400);expect(c.population).toBe(200);expect(c.builders).toBe(66);c.stock.food=10000;e.recalculate();expect(c.builders).toBeGreaterThanOrEqual(55);expect(c.builders).toBeLessThanOrEqual(c.maxBuilders);const anchor=s.map!.cells.find(cell=>footprintCells(s.map!,'city',cell.id,0).every(id=>id>=0&&s.map!.cells[id].terrain==='land'&&!e.occupied[id]&&(s.map!.cells[id].ownerId===null||s.map!.cells[id].ownerId===1)))!;for(const id of footprintCells(s.map!,'city',anchor.id,0))s.match!.captureAtPosition(1,s.map!.cells[id].x,s.map!.cells[id].y);const before=c.builders;s.match!.build(1,'city',anchor.id,0);expect(c.builders).toBeCloseTo(before-55);completeConstruction(e,e.buildings.at(-1)!);expect(c.capacity).toBe(C.cityCapacity*2);});
 it.each(['farm','mine']as const)('waives only materials of first %s, consumes builders and never restores rights on demolition',type=>{const s=setup(),e=s.match!.economy!,c=e.countries[0],before={...c.stock};const b=build(s,type);expect(c.stock).toEqual(before);expect(c.builders).toBeCloseTo(26.4-BUILDINGS[type].builders);expect(b.materialsSpent).toEqual({});expect(c.freeBuildsUsed[type]).toBe(true);const spent=c.builders;e.demolish(1,b.id);expect(c.builders).toBeCloseTo(spent+BUILDINGS[type].builders);expect(constructionCost(c,type)).toEqual(BUILDINGS[type].cost);expect(c.stock).toEqual(before);expect(e.countries[1].freeBuildsUsed[type]).toBe(false);});
 it('persists independent first-build rights after destruction and revalidates repeated placement atomically',()=>{const s=setup(),e=s.match!.economy!,c=e.countries[0],farm=build(s,'farm'),before=structuredClone(c);expect(()=>s.match!.build(1,'farm',farm.anchorId,0)).toThrow(/ocupada/);expect(c).toEqual(before);e.destroy(farm.id);expect(c.freeBuildsUsed.farm).toBe(true);expect(c.freeBuildsUsed.mine).toBe(false);expect(c.builders).toBeCloseTo(26.4);build(s,'farm',2);expect(e.countries[1].freeBuildsUsed.farm).toBe(true);});
 it('charges the normal quartel costs and returns committed builders but not materials on unfinished destruction',()=>{const s=setup(),e=s.match!.economy!,c=fundCountry(e),stock={...c.stock},b=build(s,'barracks');expect(c.stock.money).toBe(stock.money-BUILDINGS.barracks.cost.money!);expect(c.stock.mineral).toBe(stock.mineral-BUILDINGS.barracks.cost.mineral!);expect(c.builders).toBe(66-BUILDINGS.barracks.builders);const before=structuredClone(c);e.destroy(b.id);expect(c.stock).toEqual(before.stock);expect(c.builders).toBeCloseTo(before.builders+BUILDINGS.barracks.builders);});
 it('validates location, builders and then materials without consuming first-build rights on failure',()=>{const s=setup(),e=s.match!.economy!,c=e.countries[0],anchor=location(s,'farm')!;c.builders=0;c.stock.money=0;expect(()=>s.match!.build(1,'farm',anchor.id,0)).toThrow(/Construtores/);expect(c.freeBuildsUsed.farm).toBe(false);expect(()=>s.match!.build(1,'farm',e.buildings[0].anchorId,0)).toThrow(/ocupada/);c.builders=20;build(s,'farm');e.step(100);const candidate=location(s,'farm');expect(candidate).toBeUndefined();const owned=s.map!.cells.find(cell=>footprintCells(s.map!,'farm',cell.id,0).every(id=>id>=0&&s.map!.cells[id].ownerId===1&&!e.occupied[id]))!;c.builders=20;c.stock.money=0;expect(()=>s.match!.build(1,'farm',owned.id,0)).toThrow(/dinheiro/);expect(e.occupied[owned.id]).toBe(0);});
 it('recovers gradually, with diminishing population returns and a positive famine floor',()=>{const s=setup(),e=s.match!.economy!,c=e.countries[0];build(s,'farm');const before=c.builders;e.step(.5);expect(c.builders).toBeGreaterThan(before);expect(c.builders).toBeLessThan(before+1);expect(builderRecovery(800)/builderRecovery(80)).toBeLessThan(3);expect(builderRecovery(80,0)).toBeCloseTo(builderRecovery(80)*.5);e.destroy(e.buildings.find(b=>b.type==='farm')!.id);c.stock.food=0;c.builders=0;const pop=c.population;e.step(.5);expect(c.builders).toBeGreaterThan(0);expect(c.population).toBe(pop);expect(c.maxBuilders).toBeCloseTo(pop*.33);expect(c.stock.food).toBe(0);});
 it('uses population-proportional food demand and small refinery/mine food requirements',()=>{const s=setup(),e=s.match!.economy!,c=fundCountry(e,1,400);const initial=c.foodConsumption;completeConstruction(e,build(s,'refinery'));c.builders=c.maxBuilders;completeConstruction(e,build(s,'mine'));expect(c.foodConsumption).toBeCloseTo(initial+C.refineryFoodConsumption+C.mineFoodConsumption);expect(initial).toBeGreaterThan(C.refineryFoodConsumption+C.mineFoodConsumption);const city=e.buildings.find(b=>b.ownerId===1&&b.city)!.city!;city.population=100;e.recalculate();const a=city.foodConsumption;city.population=200;e.recalculate();expect(city.foodConsumption).toBeCloseTo(a*2);});
 it('penalizes only surplus inhabitants with cumulative tiers and stops extreme growth without deaths',()=>{const make=(population:number)=>({population,capacity:200,excess:0,growthRate:0,foodConsumption:0});const normal=make(200),first=make(250),second=make(280),extreme=make(310);for(const city of [normal,first,second,extreme])cityDemand(city,C.cityGrowth);expect(normal.growthRate).toBe(C.cityGrowth);expect(first.foodConsumption).toBeCloseTo((200+50*1.25)*C.foodPerPerson);expect(first.growthRate).toBeCloseTo(C.cityGrowth*(200+50*.5)/250);expect(second.foodConsumption).toBeCloseTo((200+50*1.25+30*1.4)*C.foodPerPerson);expect(second.growthRate).toBeCloseTo(C.cityGrowth*(200+50*.5+30*.25)/280);expect(extreme.growthRate).toBe(0);expect(extreme.excess).toBe(110);});
 it('keeps two city populations independent, aggregates country totals and permits safe expansion',()=>{const s=setup(),e=s.match!.economy!,c=fundCountry(e,1,300),first=e.buildings.find(b=>b.ownerId===1&&b.city)!;const anchor=s.map!.cells.find(cell=>{const ids=footprintCells(s.map!,'city',cell.id,0);return ids.every(id=>id>=0&&s.map!.cells[id].terrain==='land'&&!e.occupied[id]&&(s.map!.cells[id].ownerId===null||s.map!.cells[id].ownerId===1));})!;for(const id of footprintCells(s.map!,'city',anchor.id,0))s.match!.captureAtPosition(1,s.map!.cells[id].x,s.map!.cells[id].y);s.match!.build(1,'city',anchor.id,0);const second=e.buildings.at(-1)!;expect(c.population).toBe(300);completeConstruction(e,e.buildings.at(-1)!);expect(c.capacity).toBe(C.cityCapacity*2);const overcrowded=C.cityCapacity*1.55;first.city!.population=overcrowded;second.city!.population=100;e.recalculate();expect(c.population).toBe(overcrowded+100);expect(c.maxBuilders).toBeCloseTo((overcrowded+100)*C.maxBuildersFraction);e.step(.5);expect(first.city!.population).toBeCloseTo(overcrowded-C.relocationPerSecond*.5);expect(second.city!.population).toBeCloseTo(100+C.cityGrowth*.5+C.relocationPerSecond*.5);expect(c.population).toBeCloseTo(overcrowded+100+C.cityGrowth*.5);expect(second.city!.growthRate).toBe(C.cityGrowth);expect(first.city!.growthRate).toBe(0);expect(()=>e.demolish(1,second.id)).toThrow(/em construção/);});
 it('allows demolition of a non-city during overcrowding and clamps builders after population loss',()=>{const s=setup(),e=s.match!.economy!,c=fundCountry(e,1,300),b=build(s,'refinery');expect(()=>e.demolish(1,b.id)).not.toThrow();e.changePopulation(1,-220);e.recalculate();expect(c.population).toBe(80);expect(c.maxBuilders).toBeCloseTo(26.4);expect(c.builders).toBeLessThanOrEqual(c.maxBuilders);});
 it('protects cities and footprints, and does not weaken placement rules for starter structures',()=>{const s=setup(),e=s.match!.economy!,anchor=location(s,'mine')!;expect(rotateHex(2,-1,6)).toEqual({q:2,r:-1});for(const type of BUILDING_TYPES){const cells=footprintCells(s.map!,type,anchor.id,0);expect(new Set(cells).size).toBe(BUILDINGS[type].footprint.length);expect(footprintCells(s.map!,type,anchor.id,6)).toEqual(cells);}expect(()=>e.demolish(1,e.buildings[0].id)).toThrow(/em construção/);expect(()=>e.demolish(1,e.buildings[1].id)).toThrow(/seu país/);expect(()=>s.match!.build(1,'mine',s.map!.cells.find(c=>c.ownerId===2)!.id,0)).toThrow();});
 it('omits unnecessary material rows and marks insufficient material and builder rows',()=>{const s=setup(),c=s.match!.economy!.countries[0];expect(constructionCostRows(c,'farm')).toEqual([{label:'Construtores',amount:15,insufficient:false}]);expect(constructionCostRows(c,'mine')).toEqual([{label:'Construtores',amount:20,insufficient:false}]);build(s,'farm');const rows=constructionCostRows(c,'farm');expect(rows.map(r=>r.label)).toEqual(['dinheiro','minério','Construtores']);expect(rows.every(r=>r.amount>0)).toBe(true);expect(rows.every(r=>r.insufficient)).toBe(true);expect(constructionCostRows(c,'barracks').filter(r=>r.label!=='Construtores')).toHaveLength(2);});
 it('recovers after losing the economy, zero stocks and starvation without resetting starter grants',()=>{const s=setup(),e=s.match!.economy!,c=e.countries[0];build(s,'farm');e.step(60);build(s,'mine');for(const b of [...e.buildings])if(b.ownerId===1&&b.type!=='city')e.destroy(b.id);c.stock={money:0,food:0,mineral:0,fuel:0};c.builders=0;e.changePopulation(1,-(c.population-C.minimumCivilianPopulation));e.recalculate();let recovered=false;for(let time=0;time<900;time+=.5){e.step(.5);if(location(s,'farm')){build(s,'farm');recovered=true;break;}}expect(recovered).toBe(true);expect(c.freeBuildsUsed).toEqual({farm:true,mine:true});expect(e.buildings.at(-1)!.materialsSpent).toEqual(BUILDINGS.farm.cost);e.step(120);expect(c.stock.food).toBeGreaterThan(0);});
});
