import {describe,it,expect} from 'vitest';
import {Simulation} from '../simulation/engine';
import {FixedClock} from '../simulation/fixed-clock';
import {ENGINE} from '../shared/configs/engine';
describe('Phase 0 simulation contracts',()=>{
 it('is deterministic for the same seed and command sequence',()=>{const a=new Simulation(false),b=new Simulation(false);for(const s of [a,b]){s.command({type:'ADD_ENTITIES',count:1000});s.command({type:'SET_MOVING',enabled:true});s.command({type:'SET_COMBAT',enabled:true});for(let i=0;i<40;i++)s.step();}expect(a.world.x).toEqual(b.world.x);expect(a.world.y).toEqual(b.world.y);expect(a.engaged).toEqual(b.engaged);});
 it('pauses without moving and resets to the initial reproducible state',()=>{const s=new Simulation(false),initial=s.world.x[0];s.command({type:'SET_MOVING',enabled:true});s.step();expect(s.world.x[0]).not.toBe(initial);s.command({type:'SET_PAUSED',enabled:true});const x=s.world.x[0],tick=s.tick;for(let i=0;i<5;i++)s.step();expect(s.tick).toBe(tick);expect(s.world.x[0]).toBe(x);s.command({type:'RESET'});expect(s.world.count).toBe(ENGINE.initialEntities);expect(s.world.x[0]).toBe(initial);expect(s.moveEnabled).toBe(false);});
 it('caps entity counts and keeps continuous motion within bounds',()=>{const s=new Simulation(false);s.command({type:'ADD_ENTITIES',count:Infinity});expect(s.world.count).toBe(2000);s.command({type:'ADD_ENTITIES',count:1000000});expect(s.world.count).toBe(ENGINE.maxEntities);s.command({type:'SET_MOVING',enabled:true});for(let i=0;i<50;i++)s.step();for(let i=0;i<s.world.count;i++){expect(s.world.x[i]).toBeGreaterThanOrEqual(10);expect(s.world.x[i]).toBeLessThanOrEqual(ENGINE.worldWidth-10);expect(s.world.y[i]).toBeGreaterThanOrEqual(10);expect(s.world.y[i]).toBeLessThanOrEqual(ENGINE.worldHeight-10);}});
 it('serializes a snapshot without renderer or DOM imports',()=>{const s=new Simulation(false),data=new Float32Array(s.world.count*5);s.snapshot(data);expect(data[0]).toBe(s.world.x[0]);expect(data[1]).toBe(s.world.y[0]);expect(data[3]).toBe(s.world.owner[0]);expect(Number.isFinite(data[2])).toBe(true);});
 it('executes fixed 20 Hz updates and bounds catch-up after a stall',()=>{const c=new FixedClock(50,5,0);let n=0;expect(c.advance(49,false,()=>n++)).toBe(0);expect(c.advance(100,false,()=>n++)).toBe(2);expect(n).toBe(2);expect(c.advance(10100,false,()=>n++)).toBe(5);expect(c.droppedMs).toBeGreaterThan(9000);c.advance(11000,true,()=>n++);expect(c.advance(11050,false,()=>n++)).toBe(1);});
});
