import {completeConstruction} from './economy-fixture';
import {describe,it,expect} from 'vitest';
import {Simulation} from '../simulation/engine';
import {DEFAULT_MAP_CONFIG} from '../map/types';
import {BUILDINGS,CONSTRUCTION,BUILDING_TYPES,type BuildingType} from '../shared/configs/buildings';
import {ECONOMY_CONFIG as C} from '../shared/configs/economy';
import {evaluatePlacement} from '../simulation/economy/placement';
import {fundCountry} from './economy-fixture';
function setup(bots:'off'|'normal'='off'){
 const s=new Simulation(false);s.command({type:'GENERATE_MAP',config:{...DEFAULT_MAP_CONFIG,size:'small'},requestId:0});for(const c of s.map!.cells)c.terrain='land';s.command({type:'PREPARE_MATCH',playerCount:4,botDifficulty:bots});s.command({type:'START_MATCH',spawnId:0,name:'Factory'});return s;
}
function build(s:Simulation,type:BuildingType,playerId=1){const e=s.match!.economy!,c=e.countries[playerId-1],anchor=s.map!.cells.find(cell=>evaluatePlacement(s.map!,e.occupied,c,playerId,type,cell.id,0).valid);expect(anchor).toBeDefined();return completeConstruction(e,e.build(playerId,type,anchor!.id,0));}
function factory(){const s=setup(),e=s.match!.economy!,c=fundCountry(e,1,300);c.stock.fuel=1000;const b=build(s,'factory');return {s,e,c,b};}
describe('Factory: resource conversion',()=>{
 it('occupies slot 3, charges advanced construction costs and removes the redundant quarry',()=>{expect(BUILDING_TYPES[2]).toBe('factory');expect(BUILDING_TYPES).toHaveLength(10);expect(Object.hasOwn(BUILDINGS,'quarry')).toBe(false);expect(new Set(BUILDING_TYPES).size).toBe(10);const s=setup(),e=s.match!.economy!,c=fundCountry(e,1,300);c.stock.fuel=1000;const before={...c.stock},b=build(s,'factory');expect(c.builders).toBeCloseTo(99-BUILDINGS.factory.builders*CONSTRUCTION.factory.loss);for(const key of ['money','mineral','fuel']as const)expect(c.stock[key]).toBe(before[key]-BUILDINGS.factory.cost[key]!);expect(b.materialsSpent).toEqual(BUILDINGS.factory.cost);expect(b.cellIds).toHaveLength(4);expect(c.freeBuildsUsed).toEqual({farm:false,mine:false});});
 it('consumes every required resource in exact proportion to the money generated',()=>{const {e,c,b}=factory(),before={...c.stock},populationFood=c.foodConsumption-C.factory.consumption.food;e.step(1);expect(c.stock.money).toBeCloseTo(before.money+BUILDINGS.city.production.money!+C.factory.moneyProduction);expect(c.stock.mineral).toBeCloseTo(before.mineral+C.emergencyMineralPerSecond-C.factory.consumption.mineral);expect(c.stock.fuel).toBeCloseTo(before.fuel-C.factory.consumption.fuel);expect(c.stock.food).toBeCloseTo(before.food-populationFood-C.factory.consumption.food);expect(b.operatingRate).toBe(1);expect(c.rates.money).toBe(BUILDINGS.city.production.money!+C.factory.moneyProduction);expect(c.rates.fuel).toBeCloseTo(-C.factory.consumption.fuel);});
 it('stops with no fuel and consumes none of its other inputs or grants money',()=>{const {e,c,b}=factory();c.stock.fuel=0;e.recalculate();const before={...c.stock},populationFood=c.foodConsumption;e.step(1);expect(c.stock.money).toBeCloseTo(before.money+BUILDINGS.city.production.money!);expect(c.stock.mineral).toBeCloseTo(before.mineral+C.emergencyMineralPerSecond);expect(c.stock.food).toBeCloseTo(before.food-populationFood);expect(c.stock.fuel).toBe(0);expect(b.operatingRate).toBe(0);expect(c.rates.money).toBe(BUILDINGS.city.production.money!);});
 it('scales all inputs and output equally when only part of the fuel is available',()=>{const {e,c}=factory();c.stock.fuel=C.factory.consumption.fuel*.1;e.recalculate();const before={...c.stock},populationFood=e.buildings.find(b=>b.ownerId===1&&b.city)!.city!.foodConsumption;e.step(1);expect(c.stock.money).toBeCloseTo(before.money+BUILDINGS.city.production.money!+C.factory.moneyProduction*.1);expect(c.stock.mineral).toBeCloseTo(before.mineral+C.emergencyMineralPerSecond-C.factory.consumption.mineral*.1);expect(c.stock.food).toBeCloseTo(before.food-populationFood-C.factory.consumption.food*.1);expect(c.stock.fuel).toBeCloseTo(0);});
 it('gives inhabitants food priority and resumes after inputs return',()=>{const {e,c,b}=factory();c.stock.food=0;e.recalculate();const money=c.stock.money,pop=c.population;e.step(1);expect(c.stock.money).toBe(money+BUILDINGS.city.production.money!);expect(c.population).toBe(pop);expect(b.operatingRate).toBe(0);expect(c.builders).toBeGreaterThan(0);c.stock.food=100;e.recalculate();e.step(1);expect(c.stock.money).toBe(money+BUILDINGS.city.production.money!*2+C.factory.moneyProduction);expect(b.operatingRate).toBe(1);});
 it('shares scarce inputs across multiple factories without double-spending',()=>{const s=setup(),e=s.match!.economy!,c=fundCountry(e,1,600);c.stock.fuel=1000;build(s,'factory');build(s,'factory');c.stock.fuel=C.factory.consumption.fuel;const before={...c.stock};e.step(1);expect(c.stock.money).toBeCloseTo(before.money+BUILDINGS.city.production.money!+C.factory.moneyProduction);expect(c.stock.mineral).toBeCloseTo(before.mineral+C.emergencyMineralPerSecond-C.factory.consumption.mineral);expect(c.stock.fuel).toBeCloseTo(0);for(const value of Object.values(c.stock))expect(value).toBeGreaterThanOrEqual(0);});
 it('removes production and input demand on destruction without refunding costs or builders',()=>{const {e,c,b}=factory(),before={...c.stock},builders=c.builders;e.destroy(b.id);expect(c.stock).toEqual(before);expect(c.builders).toBe(builders);expect(c.rates.money).toBe(BUILDINGS.city.production.money!);expect(c.rates.fuel).toBe(0);expect(b.cellIds.every(id=>e.occupied[id]===0)).toBe(true);});
 it('uses live producer output at the same tick and freezes while paused',()=>{const {s,e,c}=factory();for(const type of ['farm','mine','refinery']as const){c.builders=c.maxBuilders;build(s,type);}c.stock.food=10000;c.stock.mineral=0;c.stock.fuel=0;e.recalculate();const money=c.stock.money;e.step(.5);expect(c.stock.money).toBeCloseTo(money+(BUILDINGS.city.production.money!+C.factory.moneyProduction)*.5);expect(c.stock.mineral).toBeGreaterThan(0);expect(c.stock.fuel).toBeGreaterThan(0);s.paused=true;const before=structuredClone(c);for(let n=0;n<40;n++)s.step();expect(c).toEqual(before);});
 it('allows established bots to invest after ensuring input production and reserves',()=>{const s=setup('normal'),e=s.match!.economy!,c=fundCountry(e,3,300),city=e.buildings.find(b=>b.ownerId===3&&b.city)!.city!;city.capacity=400;c.stock.fuel=1000;for(const type of ['farm','farm','mine','refinery','barracks']as const){c.builders=c.maxBuilders;build(s,type,3);}c.builders=c.maxBuilders;c.stock={money:5000,food:10000,mineral:2000,fuel:1000};e.recalculate();for(let n=0;n<60*20;n++)s.step();expect(e.buildings.filter(b=>b.ownerId===3&&b.type==='factory').length).toBeGreaterThanOrEqual(1);expect(c.rates.mineral).toBeGreaterThanOrEqual(0);expect(c.rates.fuel).toBeGreaterThanOrEqual(0);expect(c.stock.food).toBeGreaterThan(0);expect(c.stock.mineral).toBeGreaterThan(0);expect(c.stock.fuel).toBeGreaterThan(0);});
});
