import {completeConstruction} from './economy-fixture';
import {COMBAT} from '../shared/configs/combat';
import {BUILDINGS} from '../shared/configs/buildings';
import {fundCountry} from './economy-fixture';
import {describe,it,expect} from 'vitest';
import {Simulation} from '../simulation/engine';
import {DEFAULT_MAP_CONFIG} from '../map/types';
import {formationSlots} from '../simulation/units/formations';
import {UNIT_STATE,UNIT_STRIDE,UNITS,type Formation} from '../shared/configs/units';
import {evaluatePlacement} from '../simulation/economy/placement';
function setup(){const sim=new Simulation();sim.command({type:'GENERATE_MAP',config:{...DEFAULT_MAP_CONFIG,size:'small'},requestId:0});for(const c of sim.map!.cells)c.terrain='land';sim.command({type:'PREPARE_MATCH',playerCount:4,botDifficulty:'off'});sim.command({type:'START_MATCH',spawnId:0,name:'Test'});fundCountry(sim.match!.economy!);return {sim,army:sim.army!,match:sim.match!,combat:sim.combat!};}
function barracks(s:ReturnType<typeof setup>){const e=s.match.economy!,c=s.sim.map!.cells.find(c=>evaluatePlacement(s.sim.map!,e.occupied,e.countries[0],1,'barracks',c.id,0).valid)!;s.match.build(1,'barracks',c.id,0);completeConstruction(e, s.match.state.buildings.at(-1)!);return s.match.state.buildings.at(-1)!;}
function ticks(sim:Simulation,n:number){for(let i=0;i<n;i++)sim.step();}
describe('Phase 5 formations',()=>{
 it('creates distinct centered line/column/block slots and rotates them in world space',()=>{const line=formationSlots(5,'line',0),column=formationSlots(5,'column',0),block=formationSlots(9,'block',Math.PI/2);expect(new Set(line.map(p=>p.x)).size).toBe(1);expect(new Set(line.map(p=>p.y)).size).toBe(5);expect(new Set(column.map(p=>p.x)).size).toBe(5);expect(new Set(column.map(p=>p.y)).size).toBe(1);expect(new Set(block.map(p=>`${Math.round(p.x)},${Math.round(p.y)}`)).size).toBe(9);expect(formationSlots(5,'line',Math.PI/2)[0].x).toBeCloseTo(-line[0].y);});
 it.each(['line','column','block'] as Formation[])('arrives in %s slots with a single shared macro route and no stacking',formation=>{const {sim,army}=setup(),ids=[];for(let n=0;n<9;n++)ids.push(army.spawn(1,'infantry',{x:2000+n%3*5,y:1800+Math.floor(n/3)*5}));army.move(1,ids,{x:2300,y:1800},formation,true);expect(army.groups.size).toBe(1);expect(army.groups.values().next().value!.route.length).toBe(1);const group=army.groups.values().next().value!,destinations=group.slots.map(s=>({x:2300+s.x,y:1800+s.y}));ticks(sim,600);for(let n=0;n<ids.length;n++){const i=army.index(ids[n]);expect(Math.hypot(army.x[i]-destinations[n].x,army.y[i]-destinations[n].y)).toBeLessThan(.3);expect(army.state[i]).toBe(UNIT_STATE.idle);}expect(new Set(Array.from(army.snapshot()).filter((_,i)=>i%UNIT_STRIDE===1)).size).toBeGreaterThan(formation==='line'?0:1);expect(army.groups.size).toBe(0);});
 it('shares a detour around water, compresses coastal slots and restores the formation at arrival',()=>{const sim=new Simulation();sim.command({type:'GENERATE_MAP',config:{...DEFAULT_MAP_CONFIG,size:'small'},requestId:0});for(const c of sim.map!.cells)c.terrain=c.x>2500&&c.x<2750&&(c.y<1800||c.y>2300)?'water':'land';sim.command({type:'PREPARE_MATCH',playerCount:4,botDifficulty:'off'});sim.command({type:'START_MATCH',spawnId:0,name:'Coast'});const army=sim.army!,ids=[];for(let n=0;n<5;n++)ids.push(army.spawn(1,n===4?'tank':'infantry',{x:2000,y:1000}));army.move(1,ids,{x:3200,y:1000},'line',true);const g=army.groups.values().next().value!,goals=g.slots.map(p=>({x:3200+p.x,y:1000+p.y}));expect(g.route.length).toBeGreaterThan(1);for(let t=0;t<2000;t++){sim.step();for(const id of ids){const i=army.index(id);expect(army.navigation.land({x:army.x[i],y:army.y[i]})).toBe(true);}}for(let n=0;n<ids.length;n++){const i=army.index(ids[n]);expect(Math.hypot(army.x[i]-goals[n].x,army.y[i]-goals[n].y)).toBeLessThan(.3);}expect(army.groups.size).toBe(0);});
 it('caps mixed groups at tank speed with cohesion and lets infantry arrive ahead when disabled',()=>{const run=(cohesion:boolean)=>{const {sim,army}=setup(),a=army.spawn(1,'infantry',{x:2000,y:1800}),b=army.spawn(1,'tank',{x:2000,y:1801});army.move(1,[a,b],{x:2400,y:1800},'line',cohesion);const start={x:army.x[0],y:army.y[0]};sim.step();expect(Math.hypot(army.x[0]-start.x,army.y[0]-start.y)).toBeCloseTo((cohesion?UNITS.tank.speed:UNITS.infantry.speed)/20,3);ticks(sim,200);return {army,dx:army.x[0]-army.x[1]};};expect(Math.abs(run(true).dx)).toBeLessThan(35);expect(run(false).dx).toBeGreaterThan(40);});
 it('keeps stable slots when one member dies and rejects mixed selections before changing orders',()=>{const {army}=setup(),ids=[army.spawn(1,'infantry',{x:2000,y:1800}),army.spawn(1,'infantry',{x:2001,y:1800}),army.spawn(1,'tank',{x:2002,y:1800})];army.move(1,ids,{x:2300,y:1800},'line',true);const group=army.groups.values().next().value!,third={...group.slots[2]};army.remove(army.index(ids[1]));expect(group.slots[1]).toEqual(third);const before=army.snapshot();expect(()=>army.move(1,[ids[0],ids[1]],{x:2200,y:1800},'block',true)).toThrow();expect(army.snapshot()).toEqual(before);const fresh=army.spawn(1,'tank',{x:2001,y:1800});expect(fresh).not.toBe(ids[1]);expect(army.index(ids[1])).toBe(-1);});
});
describe('Phase 6 combat and recovery',()=>{
 it('respects neutral/friendly owners, range, cooldown, pause and automatic attack',()=>{const {sim,army,match}=setup();army.spawn(1,'infantry',{x:2000,y:1800});army.spawn(2,'infantry',{x:2070,y:1800});army.spawn(1,'infantry',{x:2005,y:1800});ticks(sim,20);expect(army.hp[0]).toBe(100);expect(army.hp[1]).toBe(100);match.diplomacy!.testWar(1,2);sim.step();expect(army.hp[1]).toBe(80);expect(army.hp[0]+army.hp[2]).toBe(190);expect(army.state[0]).toBe(UNIT_STATE.attack);const health=army.hp.slice();sim.command({type:'SET_PAUSED',enabled:true});ticks(sim,50);expect(army.hp).toEqual(health);sim.command({type:'SET_PAUSED',enabled:false});ticks(sim,19);expect(army.hp[1]).toBe(80);sim.step();expect(army.hp[1]).toBe(60);army.x[1]=2600;const before=army.hp[1];ticks(sim,40);expect(army.hp[1]).toBe(before);expect(army.state[0]).toBe(UNIT_STATE.idle);});
 it('interrupts movement while attacking, destroys without refund, clears dead IDs and resumes movement',()=>{const {sim,army,match}=setup();const own=army.spawn(1,'tank',{x:2000,y:1800}),enemy=army.spawn(2,'infantry',{x:2080,y:1800});match.diplomacy!.testWar(1,2);army.hp[army.index(enemy)]=40;army.move(1,[own],{x:2300,y:1800});const money=match.state.economies[0].stock.money;sim.step();expect(army.index(enemy)).toBe(-1);expect(army.count).toBe(1);expect(army.x[0]).toBe(2000);sim.step();expect(army.x[0]).toBeGreaterThan(2000);expect(match.state.economies[0].stock.money).toBe(money);expect(army.snapshot().length).toBe(UNIT_STRIDE);expect(()=>army.stop(1,[enemy])).toThrow();});
 it('damages and destroys buildings, releasing footprint/workforce and stopping their production',()=>{const s=setup(),b=barracks(s),c=s.sim.map!.cells[b.anchorId],enemy=s.army.spawn(2,'tank',{x:c.x+80,y:c.y});s.match.diplomacy!.testWar(1,2);b.hp=40;const cells=[...b.cellIds];s.sim.step();expect(s.match.state.buildings.some(v=>v.id===b.id)).toBe(false);expect(s.match.economy!.countries[0].builders).toBe(66-BUILDINGS.barracks.builders*.30);expect(cells.every(id=>s.match.economy!.occupied[id]===0)).toBe(true);expect(s.army.shots[s.army.index(enemy)]).toBe(1);const city=s.match.state.buildings.find(b=>b.ownerId===1&&b.type==='city')!,moneyRate=s.match.state.economies[0].rates.money;s.match.damageBuilding(city.id,city.maxHp);expect(s.match.state.economies[0].rates.money).toBe(moneyRate-BUILDINGS.city.production.money!);expect(s.match.state.cities.some(v=>v.id===city.id)).toBe(false);});
 it('activates base defenses against hostiles in range',()=>{const s=setup(),e=s.match.economy!,anchor=s.sim.map!.cells.find(c=>evaluatePlacement(s.sim.map!,e.occupied,e.countries[0],1,'defense',c.id,0).valid)!;s.match.build(1,'defense',anchor.id,0);completeConstruction(e, s.match.state.buildings.at(-1)!);const enemy=s.army.spawn(2,'tank',{x:anchor.x+180,y:anchor.y});s.match.diplomacy!.testWar(1,2);s.sim.step();expect(s.army.hp[s.army.index(enemy)]).toBe(480);});
 it('retreats without firing and heals only at an owned barracks over time, bounded by money',()=>{const s=setup(),b=barracks(s),c=s.sim.map!.cells[b.anchorId],id=s.army.spawn(1,'tank',{x:c.x+100,y:c.y}),i=s.army.index(id);s.army.hp[i]=450;s.army.spawn(2,'infantry',{x:c.x+110,y:c.y});s.match.diplomacy!.testWar(1,2);s.army.retreat(1,[id]);s.sim.step();expect(s.army.shots[i]).toBe(0);expect(s.army.hp[i]).toBeLessThanOrEqual(450);ticks(s.sim,110);expect(s.army.state[i]).toBe(UNIT_STATE.recover);for(let j=0;j<s.army.size;j++)if(s.army.ids[j]&&s.army.owner[j]===2)s.army.remove(j);const country=s.match.state.economies[0];country.stock.money=.2;const before=s.army.hp[i];s.combat.step(.05);expect(s.army.hp[i]).toBeCloseTo(before+COMBAT.repairHpPerSecond*.05);expect(country.stock.money).toBeCloseTo(.2-COMBAT.repairHpPerSecond*.05*UNITS.tank.repair);s.combat.step(.05);expect(s.army.hp[i]).toBeCloseTo(before+.5);expect(country.stock.money).toBe(0);country.stock.money=100;s.combat.step(20);expect(s.army.hp[i]).toBe(UNITS.tank.health);expect(s.army.state[i]).toBe(UNIT_STATE.idle);expect(country.stock.money).toBeLessThan(100);});
 it('rejects unreachable retreat atomically and cancels recovery when its barracks is removed',()=>{const s=setup(),id=s.army.spawn(1,'infantry',{x:2000,y:1800});expect(()=>s.army.retreat(1,[id])).toThrow(/quartel/);const b=barracks(s);s.army.retreat(1,[id]);expect(s.army.recovery.size).toBe(1);s.match.damageBuilding(b.id,b.maxHp);s.sim.step();expect(s.army.recovery.size).toBe(0);expect(s.army.state[s.army.index(id)]).toBe(UNIT_STATE.idle);expect(()=>s.army.retreat(1,[id,999])).toThrow();});
 it('creates one nearby hostile patrol on neutral land and prevents repeated live patrols',()=>{const s=setup();s.army.spawn(1,'infantry',{x:2000,y:1800});const money=s.match.state.economies[0].stock.money;s.sim.command({type:'START_SKIRMISH',playerId:1});expect(s.army.count).toBe(7);expect(s.match.state.combatOpponents).toEqual([2]);expect(s.match.state.skirmish).not.toBeNull();expect(s.match.state.economies[0].stock.money).toBe(money);expect(()=>s.sim.command({type:'START_SKIRMISH',playerId:1})).toThrow(/patrulha/);});
});
