import {describe,it,expect} from 'vitest';
import {generateMap} from '../map/generation/generate';
import {DEFAULT_MAP_CONFIG,validateMapConfig,type ProceduralMap} from '../map/types';
import {cellAtWorld,hexToWorld,worldToHex,HEX_DIRECTIONS,hexEdge,axialIndex} from '../map/hex/coordinates';
import {ENGINE} from '../shared/configs/engine';
function connected(map:ProceduralMap,ids:number[]){const allowed=new Set(ids),seen=new Set<number>([ids[0]]),queue=[ids[0]];for(let h=0;h<queue.length;h++)for(const n of map.cells[queue[h]].neighbors)if(allowed.has(n)&&!seen.has(n)){seen.add(n);queue.push(n);}return seen.size===ids.length;}
describe('Phase 1 map',()=>{
 it('reproduces the exact map and changes with seed or geography',()=>{const a=generateMap(DEFAULT_MAP_CONFIG),b=generateMap(DEFAULT_MAP_CONFIG);expect(a).toEqual(b);expect(generateMap({...DEFAULT_MAP_CONFIG,seed:'another'}).cells.map(c=>c.terrain)).not.toEqual(a.cells.map(c=>c.terrain));expect(generateMap({...DEFAULT_MAP_CONFIG,landform:'archipelago'}).cells.map(c=>c.terrain)).not.toEqual(a.cells.map(c=>c.terrain));});
 it('preserves hex geometry, reciprocal neighbors and free world-space lookup',()=>{const map=generateMap({...DEFAULT_MAP_CONFIG,size:'small'});for(const c of map.cells){expect(worldToHex(c.x,c.y,map.layout)).toEqual({q:c.q,r:c.r});expect(cellAtWorld(map,c.x,c.y)?.id).toBe(c.id);const p=hexToWorld(c.q,c.r,map.layout);expect(p.x).toBe(c.x);expect(c.neighbors.length).toBeLessThanOrEqual(6);expect(c.neighbors.length).toBeGreaterThanOrEqual(2);expect(c.x).toBeGreaterThan(0);expect(c.x).toBeLessThan(ENGINE.worldWidth);expect(c.y).toBeGreaterThan(0);expect(c.y).toBeLessThan(ENGINE.worldHeight);for(const n of c.neighbors)expect(map.cells[n].neighbors).toContain(c.id);}expect(cellAtWorld(map,-100,-100)).toBeNull();const c=map.cells[Math.floor(map.layout.rows/2)*map.layout.columns+Math.floor(map.layout.columns/2)];expect(cellAtWorld(map,c.x+map.layout.radius*.2,c.y+map.layout.radius*.15)?.id).toBe(c.id);
 for(let d=0;d<6;d++){const [dq,dr]=HEX_DIRECTIONS[d],n=axialIndex(c.q+dq,c.r+dr,map.layout),a=hexEdge(c,map.layout.radius,d),b=hexEdge(map.cells[n],map.layout.radius,(d+3)%6);expect(a[0]).toBeCloseTo(b[2]);expect(a[1]).toBeCloseTo(b[3]);expect(a[2]).toBeCloseTo(b[0]);expect(a[3]).toBeCloseTo(b[1]);}},20000);
 it('creates connected neutral regions and landmasses with resources only on land',()=>{const map=generateMap(DEFAULT_MAP_CONFIG);expect(map.stats.land).toBeGreaterThan(map.cells.length*.1);expect(map.stats.water).toBeGreaterThan(map.cells.length*.1);for(const region of map.regions){expect(connected(map,region.cells)).toBe(true);expect(region.cells.length).toBeGreaterThan(0);for(const id of region.cells){expect(map.cells[id].regionId).toBe(region.id);expect(map.cells[id].landmassId).toBe(region.landmassId);}}for(const mass of map.landmasses)expect(connected(map,mass.cells)).toBe(true);expect(map.regions.flatMap(r=>r.cells).length).toBe(map.stats.land);for(const c of map.cells){expect(c.ownerId).toBeNull();if(c.terrain==='water'){expect(c.resource).toBeNull();expect(c.regionId).toBe(-1);expect(c.landmassId).toBe(-1);expect(c.richness).toBe(0);}else{expect(c.regionId).toBeGreaterThanOrEqual(0);if(c.resource){expect(c.richness).toBe(2);expect(['food','mineral','fuel']).toContain(c.resource);}}}expect(map.stats.food).toBeGreaterThan(map.stats.mineral);expect(map.stats.mineral).toBeGreaterThan(map.stats.fuel);expect(map.stats.fuel).toBeGreaterThan(0);});
 it('supports all map sizes and rejects malformed configurations',()=>{for(const [size,count]of [['small',20000],['medium',30000],['large',50000]]as const)expect(generateMap({...DEFAULT_MAP_CONFIG,size}).cells.length).toBe(count);expect(()=>validateMapConfig({...DEFAULT_MAP_CONFIG,seed:''})).toThrow();expect(()=>validateMapConfig({...DEFAULT_MAP_CONFIG,seed:'a'.repeat(65)})).toThrow();expect(()=>validateMapConfig({...DEFAULT_MAP_CONFIG,size:'huge'})).toThrow();expect(()=>validateMapConfig({...DEFAULT_MAP_CONFIG,landform:'unknown'})).toThrow();expect(validateMapConfig({...DEFAULT_MAP_CONFIG,seed:'  hello  '}).seed).toBe('hello');});
});
