import {describe,it,expect} from 'vitest';
import {spawnAt} from '../simulation/territory/spawns';
import {BotSystem} from '../ai/system';
import {Simulation} from '../simulation/engine';
import {OperationsSystem} from '../simulation/operations/system';
import {DEFAULT_MAP_CONFIG,type TerritoryCell,type ProceduralMap} from '../map/types';
import {HEX_DIRECTIONS,hexToWorld,axialIndex,hexDistance} from '../map/hex/coordinates';
import {evaluatePlacement} from '../simulation/economy/placement';
import {fundCountry,completeConstruction} from './economy-fixture';
import {MISSILES,AIR} from '../shared/configs/operations';
import {UNIT_STRIDE} from '../shared/configs/units';
import {UnitWireDecoder,UnitWireEncoder,UNIT_WIRE_STRIDE} from '../shared/types/unit-wire';
function setup(){const layout={columns:40,rows:30,radius:24,originX:40,originY:40};const cells:TerritoryCell[]=Array.from({length:1200},(_,id)=>{const r=Math.floor(id/40),col=id%40,q=col-Math.floor(r/2);return {id,q,r,...hexToWorld(q,r,layout),terrain:col>=16&&col<20?'water' as const:'land' as const,resource:null,ownerId:null,richness:0,elevation:1,regionId:0,landmassId:col<16?0:1,variation:0,neighbors:HEX_DIRECTIONS.map(([dq,dr])=>axialIndex(q+dq,r+dr,layout)).filter(n=>n>=0)};});const map:ProceduralMap={version:1,layout,cells,config:DEFAULT_MAP_CONFIG,regions:[],landmasses:[{id:0,cells:cells.filter(c=>c.terrain==='land'&&c.id%40<16).map(c=>c.id)},{id:1,cells:cells.filter(c=>c.terrain==='land'&&c.id%40>=20).map(c=>c.id)}],stats:{land:1080,water:120,food:0,mineral:0,fuel:0}};const s=new Simulation(false);s.map=map;s.command({type:'PREPARE_MATCH',playerCount:2,botDifficulty:'off'});s.match!.state.spawns=[{...spawnAt(map,15*40+8)!,id:0},{...spawnAt(map,15*40+28)!,id:1}];s.command({type:'START_MATCH',spawnId:0,name:'Teste'});const m=s.match!,a=s.army!,e=m.economy!;for(const p of m.state.players){fundCountry(e,p.id,500);const c=e.countries.find(c=>c.playerId===p.id)!;c.stock={money:100000,food:100000,mineral:100000,fuel:100000};c.builders=c.maxBuilders;}for(const p of m.state.players){m.owned.get(p.id)!.clear();p.territory=0;}for(const c of cells)if(c.terrain==='land'){c.ownerId=c.id%40<16?1:2;m.owned.get(c.ownerId)!.add(c.id);m.state.players[c.ownerId-1].territory++;}const portCell=cells[15*40+15],dest=cells[15*40+20];const port=completeConstruction(e,e.build(1,'port',portCell.id,0));const enemyPort=completeConstruction(e,e.build(2,'port',dest.id,0));return {s,m,a,e,map,port,enemyPort,portCell,dest,op:s.operations!};}
function step(s:ReturnType<typeof setup>,seconds:number,combat=false){for(let n=0;n<seconds*20;n++){s.a.step(.05);s.op.step(.05);if(combat)s.s.combat!.step(.05);}}
describe('Naval transport and economy',()=>{
 it('requires land adjacent to water and rejects unreachable inland destinations without a port',()=>{const s=setup(),country=s.e.countries[0],inland=s.map.cells.find(c=>c.ownerId===1&&!s.e.occupied[c.id]&&c.neighbors.every(n=>s.map.cells[n].terrain==='land'))!;expect(evaluatePlacement(s.map,s.e.occupied,country,1,'port',inland.id,0).valid).toBe(false);s.e.destroy(s.port.id);const id=s.a.spawn(1,'infantry',s.portCell);expect(()=>s.s.command({type:'MOVE_UNITS',playerId:1,unitIds:[id],target:s.dest})).toThrow(/porto/);expect(s.op.waiting.size).toBe(0);});
 it('loads mixed capacity, hides passengers and sails automatically after the quiet timeout',()=>{const s=setup();const ids=Array.from({length:51},(_,n)=>s.a.spawn(1,n===0?'tank':'infantry',s.portCell));s.m.diplomacy!.testWar(1,2);s.s.command({type:'MOVE_UNITS',playerId:1,unitIds:ids,target:s.dest});s.op.step(.05);const boat=[...s.op.boats.values()].find(b=>b.passengers.length>0)!;expect(boat.passengers.length).toBe(46);expect(s.m.state.operations!.boats[0]?.capacity??boat.passengers.reduce((n,p)=>n+(s.a.kind[s.a.index(p.id)]===1?5:1),0)).toBeLessThanOrEqual(50);expect(s.a.visibleCount).toBe(s.a.count-46);expect(s.a.snapshot().length).toBe(s.a.visibleCount*UNIT_STRIDE);expect(s.op.waiting.size).toBe(5);step(s,14);expect([...s.op.boats.values()].some(b=>b.status==='loading')).toBe(false);expect(ids.filter(id=>s.a.embarked[s.a.index(id)]).length).toBe(0);expect(s.a.x[s.a.index(ids[0])]).toBeGreaterThan(s.portCell.x);});
 it('accepts manual ship routes and sinking kills every passenger exactly once',()=>{const s=setup();s.m.diplomacy!.testWar(1,2);const ids=[s.a.spawn(1,'tank',s.portCell),s.a.spawn(1,'infantry',s.portCell)];s.s.command({type:'MOVE_UNITS',playerId:1,unitIds:ids,target:s.dest});s.op.step(.05);const boat=[...s.op.boats.values()][0],i=s.a.index(boat.id),water=s.map.cells[16*40+17];s.s.command({type:'MOVE_UNITS',playerId:1,unitIds:[boat.id],target:water});expect(boat.status).toBe('manual');const x=s.a.x[i];step(s,1);expect(s.a.x[i]).not.toBe(x);s.a.remove(i);expect(ids.every(id=>s.a.index(id)<0)).toBe(true);expect(s.op.boats.has(boat.id)).toBe(false);expect(s.a.count).toBe(0);});
 it('pays only for completed round trips and suspends commerce during tension or war',()=>{const s=setup(),country=s.e.countries[0],before=country.stock.money;s.op.step(5);expect([...s.op.boats.values()].filter(b=>s.a.kind[s.a.index(b.id)]===4).length).toBe(2);expect(country.stock.money).toBe(before);step(s,20);expect(country.stock.money).toBeGreaterThan(before);s.m.diplomacy!.testWar(1,2);const after=country.stock.money;step(s,25);expect(country.stock.money).toBe(after);expect([...s.op.boats.values()].filter(b=>s.a.kind[s.a.index(b.id)]===4)).toHaveLength(0);});
 it('tower damage is stronger than land troop damage against ships and aircraft',()=>{const s=setup();s.m.diplomacy!.testWar(1,2);const water=s.map.cells[s.portCell.neighbors.find(n=>s.map.cells[n].terrain==='water')!],boat=s.a.spawn(2,'transport',water),j=s.a.index(boat),soldier=s.a.spawn(1,'infantry',s.portCell);s.s.combat!.step(.05);expect(s.a.hp[j]).toBeCloseTo(417.5);s.a.remove(s.a.index(soldier));const defenseCell=s.map.cells.find(c=>c.ownerId===1&&!s.e.occupied[c.id]&&Math.hypot(c.x-water.x,c.y-water.y)<100)!;completeConstruction(s.e,s.e.build(1,'defense',defenseCell.id,0));s.s.combat!.step(1);expect(s.a.hp[j]).toBeCloseTo(337.5);});
});
describe('Aircraft logistics and wire protocol',()=>{
 it('crosses water without capturing territory; consumes supplies away from barracks and reports depletion',()=>{const s=setup(),id=s.a.spawn(1,'aircraft',s.portCell),i=s.a.index(id),before=s.dest.ownerId;s.m.diplomacy!.testWar(1,2);s.s.command({type:'SET_AIR_RETURN',playerId:1,unitIds:[id],enabled:false});s.s.command({type:'MOVE_UNITS',playerId:1,unitIds:[id],target:s.dest});step(s,3);s.s.territorial!.step(1);expect(s.dest.ownerId).toBe(before);expect(s.a.x[i]).toBeCloseTo(s.dest.x,2);expect(s.a.supply[i]).toBeLessThan(100);s.a.supply[i]=.1;const hp=s.a.hp[i];s.op.step(1);expect(s.a.hp[i]).toBeLessThan(hp);expect(s.m.state.diplomacy.events.some(e=>e.message.includes('sem recursos'))).toBe(true);const full=s.a.snapshot(),encoder=new UnitWireEncoder(),compact=new Float32Array(full.length/UNIT_STRIDE*UNIT_WIRE_STRIDE),delta=encoder.encode(full,compact),decoded=new UnitWireDecoder().decode(compact,delta);expect(decoded[4]).toBe(2);expect(decoded[10]).toBe(150);});
 it('returns with a safety reserve, replenishes at a barracks and allows disabling return',()=>{const s=setup(),anchor=s.map.cells.find(c=>evaluatePlacement(s.map,s.e.occupied,s.e.countries[0],1,'barracks',c.id,0).valid)!;completeConstruction(s.e,s.e.build(1,'barracks',anchor.id,0));const id=s.a.spawn(1,'aircraft',s.dest),i=s.a.index(id);s.a.supply[i]=AIR.returnThreshold-1;s.op.step(.05);expect(s.op.flights.get(id)!.returning).toBe(true);step(s,20);expect(s.a.supply[i]).toBeGreaterThan(90);s.s.command({type:'SET_AIR_RETURN',playerId:1,unitIds:[id],enabled:false});s.s.command({type:'MOVE_UNITS',playerId:1,unitIds:[id],target:s.dest});step(s,12);s.a.supply[i]=0;s.op.step(.1);expect(s.op.flights.get(id)!.returning).toBe(false);});
});
describe('Missiles and construction cancellation',()=>{
 it('refunds paid work fully, returns builders and refuses completed structures',()=>{const s=setup(),anchor=s.map.cells.find(c=>evaluatePlacement(s.map,s.e.occupied,s.e.countries[0],1,'refinery',c.id,0).valid)!,country=s.e.countries[0],before={...country.stock},builders=country.builders,b=s.e.build(1,'refinery',anchor.id,0);s.e.stepConstruction(5);s.e.demolish(1,b.id);expect(country.stock).toEqual(before);expect(country.builders).toBeCloseTo(builders);expect(()=>s.e.demolish(1,s.port.id)).toThrow(/em construção/);});
 it('charges production, waits until ready, delays impact and damages each large building only once',()=>{const s=setup();s.m.diplomacy!.testWar(1,2);const anchor=s.map.cells.find(c=>evaluatePlacement(s.map,s.e.occupied,s.e.countries[0],1,'silo',c.id,0).valid)!,silo=completeConstruction(s.e,s.e.build(1,'silo',anchor.id,0));const stock=s.e.countries[0].stock.money;s.s.command({type:'PRODUCE_MISSILE',playerId:1,buildingId:silo.id,missileType:'tactical'});expect(s.e.countries[0].stock.money).toBe(stock-MISSILES.tactical.cost.money!);expect(()=>s.s.command({type:'LAUNCH_MISSILE',playerId:1,buildingId:silo.id,anchorId:s.dest.id})).toThrow(/pronto/);s.op.step(MISSILES.tactical.seconds);const hp=s.enemyPort.hp;s.s.command({type:'LAUNCH_MISSILE',playerId:1,buildingId:silo.id,anchorId:s.dest.id});expect(silo.missile).toBeUndefined();expect(s.enemyPort.hp).toBe(hp);s.op.step(9);expect(s.enemyPort.hp).toBe(hp);s.op.step(1);expect(s.e.buildings.some(b=>b.id===s.enemyPort.id)).toBe(false);expect(s.op.impacts).toHaveLength(0);expect(s.map.cells.filter(c=>hexDistance(c,s.dest)<=3)).toHaveLength(37);expect(s.map.cells.filter(c=>hexDistance(c,s.dest)<=8)).toHaveLength(217);expect(()=>s.e.build(1,'silo',s.portCell.id,0)).toThrow(/somente um/);});
});

describe('Bots use advanced operations with real costs',()=>{
 it('builds a silo, trains aircraft and produces and launches a missile against known enemies',()=>{
 const s=setup(),country=s.e.countries[1];for(const type of ['farm','farm','farm','farm','mine','mine','mine','refinery','refinery','barracks','factory','factory'] as const){country.builders=country.maxBuilders;const anchor=s.map.cells.find(c=>evaluatePlacement(s.map,s.e.occupied,country,2,type,c.id,0).valid)!;completeConstruction(s.e,s.e.build(2,type,anchor.id,0));}country.builders=country.maxBuilders;s.e.recalculate();s.m.state.botDifficulty='normal';s.m.diplomacy!.testWar(1,2);s.s.bots=new BotSystem(s.m,s.a,c=>s.s.command(c,'bot'));for(let n=0;n<16;n++)s.a.spawn(2,'infantry',s.dest);const stock=country.stock.money;
 // Sea trade has made the neighbouring enemy port visible to this country.
 s.s.bots.bots[0].intel.buildings.set(s.port.id,{id:s.port.id,owner:1,x:s.portCell.x,y:s.portCell.y,strength:0,time:0,confidence:1,type:'port',cellId:s.portCell.id});s.s.bots.bots[0].intel.knownOwners.set(s.portCell.id,1);
 for(let n=0;n<100;n++){s.s.bots.step(.1);s.e.stepConstruction(.1);s.a.stepTraining(.1);s.a.step(.1);s.op.step(.1);}
 const silo=s.e.buildings.find(b=>b.ownerId===2&&b.type==='silo');expect(silo).toBeDefined();expect(country.stock.money).toBeLessThan(stock);expect(s.m.state.training.some(q=>q.playerId===2&&q.batches.some(b=>b.unitType==='aircraft'))||Array.from(s.a.kind).some((kind,i)=>kind===2&&s.a.owner[i]===2)).toBe(true);
 completeConstruction(s.e,silo!);s.s.bots.step(2);expect(silo!.missile).toBeDefined();s.op.step(silo!.missile!.duration);for(let n=0;n<30;n++)s.s.bots.step(.1);expect(s.op.impacts.length).toBeGreaterThan(0);expect(silo!.missile).toBeUndefined();
 });
});
