import {describe,it,expect} from 'vitest';
import {Simulation} from '../simulation/engine';
import {DEFAULT_MAP_CONFIG} from '../map/types';
import {ScoutTraffic} from '../simulation/units/discovery';
function setup(){const s=new Simulation(false);s.command({type:'GENERATE_MAP',config:{...DEFAULT_MAP_CONFIG,size:'small'},requestId:0});for(const c of s.map!.cells)c.terrain='land';s.command({type:'PREPARE_MATCH',playerCount:2,botDifficulty:'off'});s.command({type:'START_MATCH',spawnId:0,name:'Performance'});return s;}
describe('Priority 1 simulation regressions',()=>{
 it('queries only nearby live units across bucket boundaries and country partitions',()=>{const s=setup(),a=s.army!;const near=a.spawn(1,'tank',{x:255,y:256}),enemy=a.spawn(2,'tank',{x:257,y:256});for(let n=0;n<1000;n++)a.spawn(1,'tank',{x:3000,y:3000});a.spatial.rebuild();expect([...a.spatial.near(256,256,10)].map(i=>a.ids[i])).toEqual([near,enemy]);const before=a.spatial.candidates;expect([...a.spatial.near(256,256,10,owner=>owner===2)].map(i=>a.ids[i])).toEqual([enemy]);expect(a.spatial.candidates-before).toBe(1);a.remove(a.index(enemy));expect([...a.spatial.near(256,256,10)]).toHaveLength(1);});
 it('retains valid targets without searching and reacquires immediately when one dies',()=>{const s=setup(),a=s.army!,c=s.combat!;const own=a.spawn(1,'tank',{x:2000,y:1800}),first=a.spawn(2,'tank',{x:2050,y:1800}),second=a.spawn(2,'tank',{x:2060,y:1800});s.match!.diplomacy!.testWar(1,2);c.step(.05);expect(c.searching).toBe(3);const target=a.target[a.index(own)]+1;c.step(.05);expect(c.searching).toBe(0);a.remove(a.index(target));c.step(.05);expect(c.searching).toBeGreaterThan(0);expect([first,second]).toContain(a.target[a.index(own)]+1);expect(a.target[a.index(own)]+1).not.toBe(target);});
 it('staggers idle searches, bounds encounter delay and wakes on diplomatic change',()=>{const s=setup(),a=s.army!,c=s.combat!;a.spawn(1,'tank',{x:2000,y:1800});const enemy=a.spawn(2,'tank',{x:3000,y:1800});s.match!.diplomacy!.testWar(1,2);c.step(.05);let searches=0;for(let n=0;n<5;n++){c.step(.05);searches+=c.searching;}expect(searches).toBeLessThan(10);a.x[a.index(enemy)]=2050;for(let n=0;n<8;n++)c.step(.05);expect(a.shots[0]).toBeGreaterThan(0);});
 it('releases mutable scout destinations and honors earlier-order priority and allies',()=>{const s=setup(),t=new ScoutTraffic(s.map!),p={x:2000,y:1800};t.add(2,1,p);expect(t.clear(p,1,1,true,(a,b)=>a===b)).toBe(true);expect(t.clear(p,1,1,false,(a,b)=>a===b)).toBe(false);expect(t.clear(p,1,2,false,(a,b)=>a===b)).toBe(true);t.remove(2);expect(t.clear(p,1,1,false,()=>true)).toBe(true);});
});
