import {describe,it,expect} from 'vitest';
import {Simulation} from '../simulation/engine';
import {DEFAULT_MAP_CONFIG} from '../map/types';
import {RouteScheduler} from '../simulation/navigation/scheduler';
import {NavigationGrid} from '../simulation/navigation/grid';
import {UNIT_STRIDE} from '../shared/configs/units';
import {UnitWireEncoder,UnitWireDecoder,UNIT_WIRE_STRIDE} from '../shared/types/unit-wire';
import {RenderUnitIndex} from '../../apps/client/renderer/unit-index';
import {Perception} from '../ai/perception';
import {AI_CONFIG} from '../shared/configs/ai';
import {worldToHex,axialIndex,cellAtWorld} from '../map/hex/coordinates';
function setup(deferAutomatic=false){const s=new Simulation(false,deferAutomatic);s.command({type:'GENERATE_MAP',config:{...DEFAULT_MAP_CONFIG,size:'small'},requestId:0});for(const c of s.map!.cells)c.terrain='land';s.command({type:'PREPARE_MATCH',playerCount:2,botDifficulty:'off'});s.command({type:'START_MATCH',spawnId:0,name:'Test'});return s;}
describe('Budgeted route scheduling',()=>{
 it('prioritizes human tasks, reserves progress for background tasks and enforces slice limits',()=>{const q=new RouteScheduler(),log:string[]=[];function* job(name:string){for(let n=0;n<20;n++){log.push(name);yield;}}q.enqueue(job('background'),'background',()=>true,e=>{throw e;});q.enqueue(job('human'),'human',()=>true,e=>{throw e;});q.step(1000,8);expect(log).toEqual(['human','human','human','background','human','human','human','background']);expect(q.processed).toBe(8);for(let n=0;n<10;n++)q.step(1000,8);expect(q.pending).toBe(0);expect(log.filter(x=>x==='background')).toHaveLength(20);});
 it('releases reservations when an unstarted queued task is cancelled',()=>{const q=new RouteScheduler();let released=0;function* task(){throw new Error('Cancelled tasks must not execute.');yield;}q.enqueue(task(),'background',()=>false,e=>{throw e;},()=>released++);q.step(1000,4);expect(released).toBe(1);expect(q.pending).toBe(0);});
 it('clears both active and unstarted jobs with exactly one cleanup each',()=>{const q=new RouteScheduler();let released=0;function* task(){yield;yield;}for(let n=0;n<3;n++)q.enqueue(task(),n?'background':'human',()=>true,e=>{throw e;},()=>released++);q.step(1000,1);q.clear();expect(released).toBe(3);expect(q.pending).toBe(0);});
 it('queues a large move without synchronous route searches and cancels it on stop',()=>{const s=setup(),a=s.army!,ids=Array.from({length:200},()=>a.spawn(1,'infantry',{x:2500,y:1800})),before=a.navigation.searches;s.command({type:'MOVE_UNITS',playerId:1,unitIds:ids,target:{x:2800,y:1800}});expect(a.routes.pending).toBe(1);expect(a.navigation.searches).toBe(before);a.routes.step(1000,1);a.stop(1,ids);for(let n=0;n<10;n++)a.routes.step(1000,64);expect(a.groups.size).toBe(0);expect(a.routes.pending).toBe(0);});
 it('preserves sequential appended waypoints queued before the first move is ready',()=>{const s=setup(),a=s.army!,ids=Array.from({length:40},()=>a.spawn(1,'tank',{x:2000,y:1800}));s.command({type:'MOVE_UNITS',playerId:1,unitIds:ids,target:{x:2300,y:1800}});s.command({type:'MOVE_UNITS',playerId:1,unitIds:ids,target:{x:2500,y:1800},append:true});for(let n=0;n<100&&a.routes.pending;n++)a.routes.step(1000,64);expect(a.routeErrors).toEqual([]);const g=[...a.groups.values()][0];expect(g.target).toEqual({x:2300,y:1800});expect(g.waypoints).toEqual([{x:2500,y:1800}]);});
 it('runs independent exploration through the production background queue without blocking a manual order',()=>{const s=setup(true),a=s.army!,center=s.map!.cells[s.match!.state.cities.find(c=>c.ownerId===1)!.anchorId],scouts=[a.spawn(1,'infantry',center),a.spawn(1,'infantry',center)],manual=a.spawn(1,'tank',center);a.setMode(1,scouts,'discovery');a.step(.05);expect(a.routes.pending).toBeGreaterThan(0);s.command({type:'MOVE_UNITS',playerId:1,unitIds:[manual],target:{x:center.x+100,y:center.y}},'human',true);for(let n=0;n<80;n++)s.step();expect(a.routeErrors).toEqual([]);expect(a.x[a.index(manual)]).toBeGreaterThan(center.x+10);expect(scouts.every(id=>a.modes[a.index(id)]===1)).toBe(true);expect(scouts.some(id=>Math.hypot(a.x[a.index(id)]-center.x,a.y[a.index(id)]-center.y)>5)).toBe(true);});
 it('keeps scout reservations valid when a large manual order resets the traffic index',()=>{const s=setup(true),a=s.army!,center=s.map!.cells[s.match!.state.cities.find(c=>c.ownerId===1)!.anchorId],scout=a.spawn(1,'infantry',center),ids=Array.from({length:80},()=>a.spawn(1,'tank',center));a.setMode(1,[scout],'discovery');a.step(.05);a.enqueueOrder({type:'MOVE_UNITS',playerId:1,unitIds:ids,target:{x:center.x+100,y:center.y}});for(let n=0;n<60;n++)s.step();expect(a.routeErrors).toEqual([]);expect(a.modes[a.index(scout)]).toBe(1);expect(a.x[a.index(scout)]!==center.x||a.y[a.index(scout)]!==center.y).toBe(true);});
 it('restarts a suspended move when the terrain topology changes',()=>{const s=setup(),a=s.army!,ids=Array.from({length:40},()=>a.spawn(1,'tank',{x:2200,y:1200}));a.enqueueOrder({type:'MOVE_UNITS',playerId:1,unitIds:ids,target:{x:3100,y:1200},cohesion:true});a.routes.step(1000,1);for(const c of s.map!.cells)if(c.x>2500&&c.x<2800&&c.y<2200)c.terrain='water';s.map!.navigationRevision=(s.map!.navigationRevision??0)+1;for(let n=0;n<500&&a.routes.pending;n++)a.routes.step(1000,64);expect(a.routeErrors).toEqual([]);expect(a.routes.pending).toBe(0);const g=[...a.groups.values()][0];expect(g.route.length).toBeGreaterThan(1);let from:{x:number;y:number}={x:2200,y:1200};for(const p of g.route){expect(a.navigation.clear(from,p)).toBe(true);from=p;}});
 it('shares attack macro routes between nearby troops',()=>{const s=setup(),a=s.army!,ids=Array.from({length:100},(_,n)=>a.spawn(1,'infantry',{x:2000+n%5,y:1800})),target=a.spawn(2,'tank',{x:2700,y:1800});s.match!.diplomacy!.testWar(1,2);const before=a.navigation.searches;a.attack(1,ids,target);expect(a.navigation.searches-before).toBeLessThan(10);expect(ids.every(id=>a.pursuitTarget(a.index(id))===a.index(target))).toBe(true);});
 it('keeps two suspended A* searches independent and reuses generation-stamped storage',()=>{const s=setup(),map=s.map!;for(const c of map.cells)if(c.x>2500&&c.x<2800&&c.y<2200)c.terrain='water';map.navigationRevision=(map.navigationRevision??0)+1;const nav=new NavigationGrid(map),first=nav.routeSteps({x:2200,y:1200},{x:3100,y:1200}),second=nav.routeSteps({x:3100,y:900},{x:2200,y:900});let a=first.next(),b=second.next(),steps=0;while(!a.done||!b.done){if(!a.done)a=first.next();if(!b.done)b=second.next();expect(++steps).toBeLessThan(10000);}for(const [start,result]of [[{x:2200,y:1200},a.value],[{x:3100,y:900},b.value]] as const){let from:{x:number;y:number}=start;for(const point of result){expect(nav.clear(from,point)).toBe(true);from=point;}}expect(nav.expanded).toBeGreaterThan(128);const expanded=nav.expanded;nav.route({x:2200,y:1200},{x:3100,y:1200});expect(nav.cacheHits).toBeGreaterThan(0);expect(nav.expanded).toBe(expanded);});
});
describe('Compact troop transport and viewport index',()=>{
 it('round-trips metadata, orders, health and death through compact snapshots',()=>{const s=setup(),a=s.army!,id=a.spawn(1,'tank',{x:2000,y:1800}),encoder=new UnitWireEncoder(),decoder=new UnitWireDecoder();const encode=()=>{const full=a.snapshot(),compact=new Float32Array(a.count*UNIT_WIRE_STRIDE),delta=encoder.encode(full,compact);return {full,compact,delta};};let packet=encode();expect(decoder.decode(packet.compact,packet.delta)).toEqual(packet.full);expect(packet.compact.byteLength/packet.full.byteLength).toBeCloseTo(11/17);packet=encode();expect(packet.delta).toHaveLength(0);a.setMode(1,[id],'defense');a.hp[a.index(id)]=321;a.shots[a.index(id)]=3;packet=encode();expect(packet.delta).toHaveLength(5);expect(decoder.decode(packet.compact,packet.delta)).toEqual(packet.full);a.remove(a.index(id));packet=encode();expect(decoder.decode(packet.compact,packet.delta)).toHaveLength(0);a.spawn(2,'infantry',{x:2000,y:1800});packet=encode();expect(decoder.decode(packet.compact,packet.delta)).toEqual(packet.full);});
 it('does not republish unchanged route plans when an unrelated recruit appears',()=>{const s=setup(),a=s.army!,id=a.spawn(1,'tank',{x:2000,y:1800});a.move(1,[id],{x:2300,y:1800});a.move(1,[id],{x:2500,y:1800},'block',false,true);const revision=a.routeRevision,plans=a.routeViews();a.spawn(1,'infantry',{x:2100,y:1800});expect(a.routeRevision).toBe(revision);expect(a.routeViews()).toEqual(plans);a.stop(1,[id]);expect(a.routeRevision).toBeGreaterThan(revision);expect(a.routeViews()).toEqual([]);});
 it('queries camera regions, includes interpolation crossings and deduplicates long envelopes',()=>{const data=new Float32Array(5000*UNIT_STRIDE),prev=new Map<number,{x:number;y:number}>();for(let n=0;n<5000;n++){const k=n*UNIT_STRIDE;data[k]=n+1;data[k+1]=3000;data[k+2]=3000;}data[1]=100;data[2]=100;data[UNIT_STRIDE+1]=500;data[UNIT_STRIDE+2]=100;prev.set(2,{x:100,y:100});const index=new RenderUnitIndex();index.rebuild(data,prev);expect([...index.query({left:0,right:150,top:0,bottom:150})]).toEqual([0,UNIT_STRIDE]);expect(index.visited).toBe(2);const all=[...index.query({left:0,right:4000,top:0,bottom:4000})];expect(new Set(all).size).toBe(5000);expect(all).toHaveLength(5000);});
 it('shares bot vision work while preserving the exact union of source visibility',()=>{const s=setup(),a=s.army!,map=s.map!,points=[{x:3000,y:2000},{x:3001,y:2000},{x:3002,y:2001}];for(let n=0;n<300;n++)a.spawn(2,'tank',points[n%points.length]);const perception=new Perception(2,s.match!,a);perception.update(0);const expected=new Set<number>();for(const id of s.match!.owned.get(2)??[]){expected.add(id);for(const n of map.cells[id].neighbors)expected.add(n);}const sources=[...s.match!.state.buildings.filter(b=>b.ownerId===2).map(b=>map.cells[b.anchorId]),...points],radius=AI_CONFIG.visionRadius,bounds=Math.ceil(radius/(map.layout.radius*1.4))+2;for(const source of sources){const {q,r}=worldToHex(source.x,source.y,map.layout);for(let dr=-bounds;dr<=bounds;dr++)for(let dq=-bounds;dq<=bounds;dq++){const c=map.cells[axialIndex(q+dq,r+dr,map.layout)];if(c&&Math.hypot(c.x-source.x,c.y-source.y)<=radius)expected.add(c.id);}}expect(perception.visible).toEqual(expected);expect(perception.visionGroups).toBeLessThan(10);});
});
