import {hexDistance} from '../map/hex/coordinates';
import {describe,it,expect} from 'vitest';
import {generateMap} from '../map/generation/generate';
import {DEFAULT_MAP_CONFIG} from '../map/types';
import {TerritoryMatch} from '../simulation/territory/match';
import {findSpawns} from '../simulation/territory/spawns';
import {Simulation} from '../simulation/engine';
const setup=()=>{const map=generateMap(DEFAULT_MAP_CONFIG);return {map,match:new TerritoryMatch(map,4)};};
describe('Phase 2 territories',()=>{
 it.each(['small','medium','large']as const)('fits full radius-4 territories for eight countries in both geographies: %s',size=>{for(const landform of ['continents','archipelago']as const){const map=generateMap({...DEFAULT_MAP_CONFIG,size,landform}),spawns=findSpawns(map,8),occupied=new Set<number>();expect(spawns).toHaveLength(8);for(const spawn of spawns){expect(spawn.cellIds).toHaveLength(61);for(const id of spawn.cellIds){expect(hexDistance(map.cells[spawn.anchorId],map.cells[id])).toBeLessThanOrEqual(4);expect(map.cells[id].terrain).toBe('land');expect(occupied.has(id)).toBe(false);occupied.add(id);}}}});
 it('produces deterministic, non-overlapping, equal connected starting areas and seven-cell cities',()=>{const {map,match}=setup();expect(match.state.spawns).toEqual(findSpawns(map,4));const all=new Set<number>();for(const spawn of match.state.spawns){expect(spawn.cellIds.length).toBe(61);expect(spawn.cityCells.length).toBe(7);for(let ring=0;ring<=4;ring++)expect(spawn.cellIds.filter(id=>hexDistance(map.cells[spawn.anchorId],map.cells[id])===ring)).toHaveLength(ring?6*ring:1);const seen=new Set([spawn.anchorId]),queue=[spawn.anchorId],allowed=new Set(spawn.cellIds);for(let h=0;h<queue.length;h++)for(const n of map.cells[queue[h]].neighbors)if(allowed.has(n)&&!seen.has(n)){seen.add(n);queue.push(n);}expect(seen.size).toBe(61);for(const id of spawn.cellIds){expect(all.has(id)).toBe(false);expect(map.cells[id].terrain).toBe('land');expect(hexDistance(map.cells[spawn.anchorId],map.cells[id])).toBeLessThanOrEqual(4);all.add(id);}for(const id of spawn.cityCells)expect(allowed.has(id)).toBe(true);}});
 it('assigns the chosen spawn to the human and creates exactly one city per country',()=>{const {map,match}=setup();match.start(2,'Aurora');expect(match.state.players.length).toBe(4);expect(match.state.players[0].spawnId).toBe(2);expect(match.state.players[0].name).toBe('Aurora');expect(match.state.cities.length).toBe(4);expect(match.state.captured).toBe(244);for(const p of match.state.players){expect(p.territory).toBe(61);const city=match.state.cities.find(c=>c.ownerId===p.id)!;for(const id of city.cellIds)expect(map.cells[id].ownerId).toBe(p.id);}expect(()=>match.start(0,'Again')).toThrow();});
 it('only captures neutral land and keeps other countries, water and repeated occupancy unchanged',()=>{const {map,match}=setup();match.start(0,'Human');const neutral=map.cells.find(c=>c.terrain==='land'&&c.ownerId===null)!;expect(match.captureAtPosition(1,neutral.x,neutral.y)).toBe(true);expect(match.captureAtPosition(1,neutral.x,neutral.y)).toBe(false);expect(match.state.players[0].territory).toBe(62);const foreign=map.cells.find(c=>c.ownerId===2)!;expect(match.captureAtPosition(1,foreign.x,foreign.y)).toBe(false);expect(foreign.ownerId).toBe(2);const water=map.cells.find(c=>c.terrain==='water')!;expect(match.captureAtPosition(1,water.x,water.y)).toBe(false);expect(match.captureAtPosition(99,neutral.x+1,neutral.y)).toBe(false);expect(match.captureAtPosition(1,-999,-999)).toBe(false);});
 it('moves continuously, captures crossed cells, respects pause, and blocks water without city collision',()=>{const sim=new Simulation();sim.command({type:'GENERATE_MAP',config:DEFAULT_MAP_CONFIG,requestId:1});sim.command({type:'PREPARE_MATCH',playerCount:4,botDifficulty:'off'});sim.command({type:'START_MATCH',spawnId:0,name:'Human'});const match=sim.match!,map=sim.map!,start={...match.state.expedition!};const target=map.cells[match.state.cities[0].cellIds[1]];sim.command({type:'MOVE_EXPEDITION',playerId:1,target});sim.command({type:'SET_PAUSED',enabled:true});sim.step();expect(match.state.expedition!.x).toBe(start.x);sim.command({type:'SET_PAUSED',enabled:false});sim.step();const e=match.state.expedition!;expect(Math.hypot(e.x-start.x,e.y-start.y)).toBeCloseTo(9);for(let i=0;i<30;i++)sim.step();expect(e.x).toBeCloseTo(target.x);expect(e.y).toBeCloseTo(target.y);expect(e.status).toBe('idle');const water=map.cells.find(c=>c.terrain==='water')!;expect(()=>match.move(1,water.x,water.y)).toThrow();expect(()=>match.move(2,target.x,target.y)).toThrow();sim.command({type:'RESET'});expect(sim.match).toBe(match);expect(match.state.players[0].territory).toBe(61);});
 it('rejects invalid setup without mutating the prepared state',()=>{const {map,match}=setup();expect(()=>findSpawns(map,1)).toThrow();expect(()=>findSpawns(map,9)).toThrow();expect(()=>match.start(-1,'Human')).toThrow();expect(()=>match.start(0,'')).toThrow();expect(match.state.phase).toBe('preparation');expect(map.cells.every(c=>c.ownerId===null)).toBe(true);});
});
