import {describe,it,expect} from 'vitest';
import {Simulation} from '../simulation/engine';
import {DEFAULT_MAP_CONFIG} from '../map/types';
import {UNIT_MODES,UNIT_STRIDE} from '../shared/configs/units';
function setup(){const sim=new Simulation(false);sim.command({type:'GENERATE_MAP',config:{...DEFAULT_MAP_CONFIG,landform:'pangea'},requestId:0});sim.command({type:'PREPARE_MATCH',playerCount:2,botDifficulty:'off'});sim.command({type:'START_MATCH',spawnId:0,name:'Teste'});const army=sim.army!,match=sim.match!,center=sim.map!.cells[match.state.cities[0].anchorId],id=army.spawn(1,'infantry',center);return {sim,army,match,center,id};}
describe('Modos militares',()=>{
 it('descobre e conquista terras neutras próximas e mantém o modo após a chegada',()=>{const {sim,army,match,id}=setup(),before=match.state.players[0].territory;sim.command({type:'SET_UNIT_MODE',playerId:1,unitIds:[id],mode:'discovery'});for(let n=0;n<400;n++)sim.step();expect(match.state.players[0].territory).toBeGreaterThan(before);expect(army.modes[army.index(id)]).toBe(UNIT_MODES.discovery);expect(army.snapshot()).toHaveLength(UNIT_STRIDE);expect(army.snapshot()[16]).toBe(UNIT_MODES.discovery);});
 it('ordens manuais cancelam somente os modos das unidades selecionadas; destinos inválidos preservam o modo',()=>{const {army,sim,id,center}=setup(),other=army.spawn(1,'tank',center);army.setMode(1,[id,other],'discovery');expect(()=>army.move(1,[id],sim.map!.cells.find(c=>c.terrain==='water')!)).toThrow();expect(army.modes[army.index(id)]).toBe(1);army.move(1,[id],center,'block',true,true);expect(army.modes[army.index(id)]).toBe(0);expect(army.modes[army.index(other)]).toBe(1);army.stop(1,[other]);expect(army.modes[army.index(other)]).toBe(0);});
 it('ataque aguarda em paz, avança na guerra e interrompe o avanço quando as hostilidades terminam',()=>{const {army,match,id,center}=setup();army.setMode(1,[id],'attack');for(let n=0;n<40;n++)army.step(.05);expect(army.x[0]).toBeCloseTo(center.x);expect(army.y[0]).toBeCloseTo(center.y);expect(army.groups.size).toBe(0);match.diplomacy!.testWar(1,2);for(let n=0;n<40;n++)army.step(.05);expect(Math.hypot(army.x[0]-center.x,army.y[0]-center.y)).toBeGreaterThan(1);expect(army.modes[0]).toBe(3);match.diplomacy!.eliminate(2);for(let n=0;n<25;n++)army.step(.05);const p={x:army.x[0],y:army.y[0]};for(let n=0;n<40;n++)army.step(.05);expect(army.x[0]).toBe(p.x);expect(army.y[0]).toBe(p.y);expect(army.modes[0]).toBe(3);});
 it('defesa patrulha sem conquistar terras neutras e reage à preparação inimiga',()=>{const {army,match,id,center}=setup(),before=match.state.players[0].territory;army.setMode(1,[id],'defense');for(let n=0;n<100;n++)army.step(.05);expect(match.state.players[0].territory).toBe(before);match.diplomacy!.act(2,'prepare_war',1);for(let n=0;n<25;n++)army.step(.05);const target=army.groups.values().next().value?.target??{x:army.x[army.index(id)],y:army.y[army.index(id)]};expect(target).toBeDefined();expect(Math.hypot(target!.x-center.x,target!.y-center.y)).toBeGreaterThan(0);expect(army.modes[0]).toBe(2);for(let n=0;n<200;n++)army.step(.05);expect(match.state.players[0].territory).toBe(before);});
 it('não aceita modos inválidos ou tropas estrangeiras e limpa modos ao reutilizar um slot',()=>{const {army,id,center}=setup();army.setMode(1,[id],'defense');expect(()=>army.setMode(1,[id],'invalid' as 'attack')).toThrow();expect(army.modes[0]).toBe(2);const enemy=army.spawn(2,'infantry',center);expect(()=>army.setMode(1,[enemy],'attack')).toThrow();army.remove(0);const next=army.spawn(1,'infantry',center);expect(army.index(next)).toBe(0);expect(army.modes[0]).toBe(0);});
});
