import {completeConstruction} from './economy-fixture';
import {TRAINING} from '../shared/configs/training';
import {fundCountry} from './economy-fixture';
import {describe,it,expect,beforeAll} from 'vitest';
import {Simulation} from '../simulation/engine';
import {generateMap} from '../map/generation/generate';
import {DEFAULT_MAP_CONFIG} from '../map/types';
import {NavigationGrid} from '../simulation/navigation/grid';
import {evaluatePlacement} from '../simulation/economy/placement';
import {UNITS,UNIT_STRIDE} from '../shared/configs/units';
function setup(){const sim=new Simulation();sim.command({type:'GENERATE_MAP',config:DEFAULT_MAP_CONFIG,requestId:0});sim.command({type:'PREPARE_MATCH',playerCount:4,botDifficulty:'off'});sim.command({type:'START_MATCH',spawnId:0,name:'Human'});const e=sim.match!.economy!;fundCountry(e);const anchor=sim.map!.cells.find(c=>evaluatePlacement(sim.map!,e.occupied,e.countries[0],1,'barracks',c.id,0).valid)!;sim.match!.build(1,'barracks',anchor.id,0);completeConstruction(e, sim.match!.state.buildings.at(-1)!);return {sim,barracks:e.buildings.at(-1)!,c:e.countries[0],army:sim.army!};}
describe('Phase 4 independent navigation',()=>{let nav:NavigationGrid;beforeAll(()=>{const map=generateMap({...DEFAULT_MAP_CONFIG,size:'small'});for(const c of map.cells)c.terrain=c.x>2500&&c.x<2750&&(c.y<1800||c.y>2300)?'water':'land';nav=new NavigationGrid(map);});
 it('uses terrain-aware node dimensions, routes around water and smooths only walkable segments',()=>{expect(nav.columns).toBe(160);expect(nav.rows).toBe(125);const start={x:2000,y:1000},goal={x:3200,y:1000};expect(nav.clear(start,goal)).toBe(false);const path=nav.route(start,goal);expect(path.length).toBeGreaterThan(1);expect(path.at(-1)).toEqual(goal);let from=start;for(const p of path){expect(nav.clear(from,p)).toBe(true);from=p;}expect(path.some(p=>p.y>1700)).toBe(true);});
 it('rejects water, nonfinite coordinates and disconnected islands',()=>{expect(()=>nav.route({x:2000,y:1000},{x:2600,y:1000})).toThrow(/terra/);expect(()=>nav.route({x:2000,y:1000},{x:NaN,y:0})).toThrow();const map=generateMap({...DEFAULT_MAP_CONFIG,size:'small'});for(const c of map.cells)c.terrain=c.x>2500&&c.x<2750?'water':'land';const disconnected=new NavigationGrid(map);expect(()=>disconnected.route({x:2000,y:1000},{x:3200,y:1000})).toThrow(/rota terrestre/);});
});
describe('Phase 4 recruitment and movement',()=>{
 it('debits resources and free civil population atomically for infantry and tanks',()=>{const {army,barracks,c}=setup();const stock={...c.stock};army.recruit(1,barracks.id,'infantry',5);expect(army.count).toBe(0);expect(army.queuedCount).toBe(5);army.stepTraining(TRAINING.seconds.infantry*5);expect(army.count).toBe(5);expect(c.population).toBe(195);expect(c.builders).toBeCloseTo(55.5);expect(c.stock.money).toBe(stock.money-UNITS.infantry.cost.money!*5);expect(c.stock.mineral).toBe(stock.mineral-UNITS.infantry.cost.mineral!*5);army.recruit(1,barracks.id,'tank',1);army.stepTraining(TRAINING.seconds.tank);expect(c.population).toBe(190);expect(c.stock.fuel).toBe(stock.fuel-UNITS.tank.cost.fuel!);expect(army.kind[5]).toBe(1);const before={...c.stock};expect(()=>army.recruit(1,barracks.id,'tank',1)).toThrow(/Recursos/);expect(c.stock).toEqual(before);expect(army.count).toBe(6);});
 it('requires an owned barracks, integer bounded batches and sufficient unoccupied population',()=>{const {sim,army,barracks,c}=setup();const initial={...c.stock};for(const args of [[2,barracks.id,'infantry',1],[1,sim.match!.state.cities[0].id,'infantry',1],[1,barracks.id,'infantry',0],[1,barracks.id,'tank',1.5],[1,barracks.id,'infantry',51]] as const)expect(()=>army.recruit(args[0],args[1],args[2],args[3])).toThrow();sim.match!.economy!.buildings.find(b=>b.ownerId===1&&b.city)!.city!.population=60.9;sim.match!.economy!.recalculate();expect(()=>army.recruit(1,barracks.id,'infantry',1)).toThrow(/População/);expect(c.stock).toEqual(initial);expect(army.count).toBe(0);sim.match!.damageBuilding(barracks.id,barracks.maxHp);expect(()=>army.recruit(1,barracks.id,'infantry',1)).toThrow(/quartel/);});
 it('moves at type speed in continuous X/Y, pauses and stops without teleporting',()=>{const {sim,army,barracks}=setup();army.recruit(1,barracks.id,'infantry',1);army.stepTraining(TRAINING.seconds.infantry);army.recruit(1,barracks.id,'tank',1);army.stepTraining(TRAINING.seconds.tank);const start={x:army.x[0],y:army.y[0]},tank={x:army.x[1],y:army.y[1]},target=sim.map!.cells[barracks.cellIds[2]];army.move(1,[1,2,1],target);const tankDestination={x:army.snapshot()[UNIT_STRIDE+7],y:army.snapshot()[UNIT_STRIDE+8]};sim.command({type:'SET_PAUSED',enabled:true});sim.step();expect(army.x[0]).toBe(start.x);sim.command({type:'SET_PAUSED',enabled:false});sim.step();expect(Math.hypot(army.x[0]-start.x,army.y[0]-start.y)).toBeCloseTo(UNITS.infantry.speed/20,3);expect(Math.hypot(army.x[1]-tank.x,army.y[1]-tank.y)).toBeCloseTo(UNITS.tank.speed/20,3);army.stop(1,[1]);const stopped={x:army.x[0],y:army.y[0]};for(let i=0;i<200;i++)sim.step();expect(army.x[0]).toBe(stopped.x);expect(army.y[0]).toBe(stopped.y);expect(army.x[1]).toBeCloseTo(tankDestination.x,2);expect(army.y[1]).toBeCloseTo(tankDestination.y,2);expect(army.snapshot()[UNIT_STRIDE+6]).toBe(0);});
 it('captures neutral land by passage, preserves foreign ownership and passes through cities',()=>{const {sim,army,barracks}=setup();army.recruit(1,barracks.id,'infantry',1);army.stepTraining(TRAINING.seconds.infantry);const map=sim.map!,start={x:army.x[0],y:army.y[0]},target=map.cells.find(c=>c.terrain==='land'&&c.ownerId===null&&Math.hypot(c.x-start.x,c.y-start.y)<500&&army.navigation.clear(start,c))!;expect(target).toBeDefined();const before=sim.match!.state.players[0].territory;army.move(1,[1],target);for(let i=0;i<250;i++)sim.step();expect(target.ownerId).toBe(1);expect(sim.match!.state.players[0].territory).toBeGreaterThan(before);const city=map.cells[sim.match!.state.cities[0].anchorId];army.move(1,[1],city);for(let i=0;i<300;i++)sim.step();expect(army.x[0]).toBeCloseTo(city.x,2);expect(army.y[0]).toBeCloseTo(city.y,2);expect(sim.match!.state.players[1].territory).toBe(61);});
 it('rejects invalid group orders without partially replacing existing paths; reset preserves troops',()=>{const {sim,army,barracks}=setup();army.recruit(1,barracks.id,'infantry',2);army.stepTraining(TRAINING.seconds.infantry*2);const target=sim.map!.cells[barracks.cellIds[2]];army.move(1,[1,2],target);const old=army.snapshot();const water=sim.map!.cells.find(c=>c.terrain==='water')!;for(const ids of [[1,999],[],[1.5]])expect(()=>army.move(1,ids,target)).toThrow();expect(()=>army.move(2,[1],target)).toThrow();expect(()=>army.move(1,[1,2],water)).toThrow();expect(army.snapshot()).toEqual(old);sim.command({type:'RESET'});expect(sim.army).toBe(army);expect(army.count).toBe(2);sim.command({type:'GENERATE_MAP',config:DEFAULT_MAP_CONFIG,requestId:2});expect(sim.army).toBeNull();});
});
