import {fundCountry} from './economy-fixture';
import {describe,it,expect} from 'vitest';
import {Simulation} from '../simulation/engine';
import {DEFAULT_MAP_CONFIG} from '../map/types';
import {UNIT_STRIDE} from '../shared/configs/units';
function setup(){const sim=new Simulation();sim.command({type:'GENERATE_MAP',config:{...DEFAULT_MAP_CONFIG,size:'small'},requestId:0});for(const c of sim.map!.cells)c.terrain='land';sim.command({type:'PREPARE_MATCH',playerCount:4,botDifficulty:'off'});sim.command({type:'START_MATCH',spawnId:0,name:'Test'});return {sim,match:sim.match!,army:sim.army!,war:sim.territorial!,d:sim.match!.diplomacy!,map:sim.map!};}
function ticks(sim:Simulation,seconds:number){for(let n=0;n<seconds*20;n++)sim.step();}
function alliance(s:ReturnType<typeof setup>,a:number,b:number){s.d.act(a,'request_alliance',b);s.d.step(2);}
function pocket(){const s=setup(),c=s.map.cells.find(c=>c.ownerId===null&&c.neighbors.length===6&&c.neighbors.every(id=>s.map.cells[id].ownerId===null&&s.map.cells[id].neighbors.length===6))!;s.match.captureAtPosition(2,c.x,c.y);for(const id of c.neighbors){const n=s.map.cells[id];s.match.captureAtPosition(1,n.x,n.y);}s.d.testWar(1,2);return {...s,c};}
describe('Phase 8 diplomacy',()=>{
 it('answers alliances after simulation time, supports breaking and rejects invalid commands atomically',()=>{const s=setup();s.sim.command({type:'DIPLOMACY_ACTION',playerId:1,action:'request_alliance',targetId:3});expect(s.d.allied(1,3)).toBe(false);s.sim.paused=true;ticks(s.sim,10);expect(s.d.state.time).toBe(0);s.sim.paused=false;ticks(s.sim,2);expect(s.d.allied(1,3)).toBe(true);expect(s.d.allied(3,1)).toBe(true);const before=structuredClone(s.d.state);expect(()=>s.sim.command({type:'DIPLOMACY_ACTION',playerId:3,action:'break_alliance',targetId:1})).toThrow();expect(()=>s.d.act(1,'prepare_war',3)).toThrow();expect(()=>s.d.act(1,'request_alliance',99)).toThrow();expect(s.d.state).toEqual(before);s.d.act(1,'break_alliance',3);expect(s.d.relation(1,3)!.state).toBe('NEUTRAL');});
 it('requires 15 seconds of preparation and declaration before any hostilities',()=>{const s=setup();s.d.act(1,'prepare_war',2);expect(s.d.hostile(1,2)).toBe(false);expect(()=>s.d.act(1,'declare_war',2)).toThrow();s.d.step(14.95);expect(()=>s.d.act(1,'declare_war',2)).toThrow();s.d.step(.05);s.d.act(1,'declare_war',2);expect(s.d.hostile(1,2)).toBe(true);expect(s.d.hostile(2,1)).toBe(true);expect(s.match.state.combatOpponents).toEqual([2]);expect(s.d.state.wars[0].exercise).toBe(false);});
 it('can cancel tension and expires a 60-second truce without resuming war automatically',()=>{const s=setup();s.d.act(1,'prepare_war',2);s.d.act(1,'cancel_preparation',2);expect(s.d.relation(1,2)!.state).toBe('NEUTRAL');expect(()=>s.d.act(1,'declare_war',2)).toThrow();s.d.testWar(1,2);s.d.act(1,'request_truce',2);s.d.step(2);expect(s.d.hostile(1,2)).toBe(false);expect(s.d.state.wars[0].endedAt).toBe(2);expect(()=>s.d.act(1,'prepare_war',2)).toThrow();expect(()=>s.d.testWar(1,2)).toThrow();s.d.step(59.95);expect(s.d.relation(1,2)!.state).toBe('TRUCE');s.d.step(.05);expect(s.d.relation(1,2)!.state).toBe('NEUTRAL');expect(s.d.hostile(1,2)).toBe(false);});
 it('calls an allied country, credits foreign conquests to the principal and ends the whole coalition war',()=>{const s=setup();alliance(s,1,3);const w=s.d.testWar(1,2);s.d.act(1,'call_ally',3,w.id);expect(s.d.hostile(3,2)).toBe(false);s.d.step(2);expect(w.attackerAllies).toEqual([3]);expect(s.d.hostile(3,2)).toBe(true);expect(s.d.hostile(1,3)).toBe(false);const c=s.map.cells.find(c=>c.ownerId===2&&!s.match.economy!.occupied[c.id])!,counts=s.match.state.players.map(p=>p.territory),total=s.match.state.captured;expect(s.match.captureCellInWar(3,c.id)).toBe(true);expect(c.ownerId).toBe(1);expect(s.match.state.players[0].territory).toBe(counts[0]+1);expect(s.match.state.players[1].territory).toBe(counts[1]-1);expect(s.match.state.players[2].territory).toBe(counts[2]);expect(s.match.state.captured).toBe(total);expect(()=>s.d.act(1,'break_alliance',3)).toThrow();expect(()=>s.d.act(3,'request_truce',2)).toThrow();s.d.act(1,'request_truce',2);s.d.step(2);expect(s.d.hostile(3,2)).toBe(false);expect(s.d.relation(3,2)!.state).toBe('TRUCE');expect(c.ownerId).toBe(1);});
 it('allows voluntary participation but rejects allies of both sides and conflicting independent wars',()=>{const s=setup();alliance(s,1,3);const w=s.d.testWar(3,2);s.d.act(1,'join_war',undefined,w.id);expect(w.attackerAllies).toEqual([1]);expect(s.d.captureOwner(1,2)).toBe(3);const t=setup();alliance(t,1,3);alliance(t,2,3);const conflict=t.d.testWar(1,2);expect(()=>t.d.act(3,'join_war',undefined,conflict.id)).toThrow();expect(conflict.attackerAllies).toEqual([]);const u=setup();alliance(u,1,3);const first=u.d.testWar(1,2),second=u.d.testWar(3,2);expect(()=>u.d.act(1,'join_war',undefined,second.id)).toThrow();expect(u.d.captureOwner(1,2)).toBe(first.attackerId);});
 it('rejects stale proposals when treaties change and bounds the event history',()=>{const s=setup();s.d.act(1,'request_alliance',2);s.d.act(1,'prepare_war',2);s.d.step(2);expect(s.d.state.offers[0].status).toBe('rejected');expect(s.d.relation(1,2)!.state).toBe('TENSION');for(let n=0;n<100;n++)s.d.event('event '+n);expect(s.d.state.events).toHaveLength(80);expect(s.d.state.events.at(-1)!.message).toBe('event 99');});
});
describe('Phase 7 territorial war',()=>{
 it('requires war and military occupation; protects structures, defenders and water',()=>{const s=setup(),c=s.map.cells.find(c=>c.ownerId===2&&!s.match.economy!.occupied[c.id])!;expect(s.match.captureCellInWar(1,c.id)).toBe(false);s.d.testWar(1,2);expect(s.match.captureAtPosition(1,c.x,c.y)).toBe(false);const defender=s.army.spawn(2,'infantry',c);s.war.refreshOccupancy();expect(s.match.captureCellInWar(1,c.id)).toBe(false);s.army.remove(s.army.index(defender));s.war.refreshOccupancy();expect(s.match.captureCellInWar(1,c.id)).toBe(true);const city=s.match.state.buildings.find(b=>b.ownerId===2)!;expect(s.match.captureCellInWar(1,city.anchorId)).toBe(false);s.match.damageBuilding(city.id,city.maxHp);expect(s.match.captureCellInWar(1,city.anchorId)).toBe(true);const water=s.map.cells.find(c=>c.ownerId===null)!;water.terrain='water';expect(s.match.captureCellInWar(1,water.id)).toBe(false);expect(s.match.state.players.reduce((sum,p)=>sum+p.territory,0)).toBe(s.match.state.captured);});
 it('captures under a stationary army after declaration and stops combat and conquest on truce',()=>{const s=setup(),c=s.map.cells.find(c=>c.ownerId===2&&!s.match.economy!.occupied[c.id])!,id=s.army.spawn(1,'infantry',c);s.war.step(1);expect(c.ownerId).toBe(2);s.d.testWar(1,2);s.war.step(1);expect(c.ownerId).toBe(1);const other=s.map.cells.find(c=>c.ownerId===2&&!s.match.economy!.occupied[c.id])!;s.d.act(1,'request_truce',2);s.d.step(2);s.army.x[s.army.index(id)]=other.x;s.army.y[s.army.index(id)]=other.y;s.army.spawn(2,'infantry',other);const hp=s.army.hp.slice();ticks(s.sim,2);expect(other.ownerId).toBe(2);expect(s.army.hp).toEqual(hp);expect(c.ownerId).toBe(1);});
 it('detects a disconnected hostile pocket, counts 20 seconds and annexes without inflating total land',()=>{const s=pocket(),total=s.match.state.captured;s.war.step(1);expect(s.match.state.encirclements.find(p=>p.cellIds.includes(s.c.id))?.remaining).toBe(19);for(let n=0;n<18;n++)s.war.step(1);expect(s.c.ownerId).toBe(2);s.war.step(1);expect(s.c.ownerId).toBe(1);expect(s.match.state.captured).toBe(total);expect(s.d.state.events.at(-1)!.message).toContain('anexou');expect(s.match.state.encirclements).toHaveLength(0);});
 it('resets the countdown while troops defend the pocket and gives a full delay after they leave',()=>{const s=pocket();s.war.step(10);const id=s.army.spawn(2,'infantry',s.c);s.war.step(1);expect(s.match.state.encirclements[0].blocked).toBe('troops');expect(s.match.state.encirclements[0].remaining).toBe(20);s.war.step(25);expect(s.c.ownerId).toBe(2);s.army.remove(s.army.index(id));s.war.step(19);expect(s.c.ownerId).toBe(2);s.war.step(1);expect(s.c.ownerId).toBe(1);});
 it('does not annex an intact structure or a pocket opened to neutral territory',()=>{const s=pocket();fundCountry(s.match.economy!,2);s.match.build(2,'refinery',s.c.id,0);s.war.step(30);expect(s.c.ownerId).toBe(2);expect(s.match.state.encirclements[0].blocked).toBe('structures');const b=s.match.state.buildings.find(b=>b.anchorId===s.c.id)!;s.match.damageBuilding(b.id,b.maxHp);s.war.step(19);expect(s.c.ownerId).toBe(2);s.war.step(1);expect(s.c.ownerId).toBe(1);const t=setup(),c=t.map.cells.find(c=>c.ownerId===null&&c.neighbors.length===6&&c.neighbors.every(id=>t.map.cells[id].ownerId===null))!;t.match.captureAtPosition(2,c.x,c.y);for(const id of c.neighbors.slice(1)){const n=t.map.cells[id];t.match.captureAtPosition(1,n.x,n.y);}t.d.testWar(1,2);t.war.step(30);expect(c.ownerId).toBe(2);expect(t.match.state.encirclements).toHaveLength(0);});
 it('cancels a siege on truce and does not rerun flood-fill on unchanged borders every tick',()=>{const s=pocket();s.war.step(1);const scans=s.war.scans;for(let n=0;n<100;n++)s.war.step(.05);expect(s.war.scans).toBe(scans);s.d.act(1,'request_truce',2);s.d.step(2);s.war.step(30);expect(s.c.ownerId).toBe(2);expect(s.match.state.encirclements).toHaveLength(0);});
 it('handles coastal closure and refuses map-edge pockets',()=>{const s=pocket();s.map.cells[s.c.neighbors[0]].terrain='water';s.war.step(20);expect(s.c.ownerId).toBe(1);const t=setup(),c=t.map.cells.find(c=>c.ownerId===null&&c.neighbors.length<6&&c.neighbors.every(id=>t.map.cells[id].ownerId===null))!;t.match.captureAtPosition(2,c.x,c.y);for(const id of c.neighbors){const n=t.map.cells[id];t.match.captureAtPosition(1,n.x,n.y);}t.d.testWar(1,2);t.war.step(30);expect(c.ownerId).toBe(2);expect(t.match.state.encirclements).toHaveLength(0);});
 it('recovers own supply, preserves allied supply and applies faster hostile depletion and lethal attrition',()=>{const s=setup();alliance(s,1,3);s.d.testWar(1,2);const own=s.map.cells.find(c=>c.ownerId===1)!,ally=s.map.cells.find(c=>c.ownerId===3)!,enemy=s.map.cells.find(c=>c.ownerId===2)!,neutral=s.map.cells.find(c=>c.ownerId===null)!,id=s.army.spawn(1,'infantry',own),i=s.army.index(id);s.army.supply[i]=20;s.war.logistics(2);expect(s.army.supply[i]).toBe(36);s.army.x[i]=ally.x;s.army.y[i]=ally.y;s.war.logistics(2);expect(s.army.supply[i]).toBe(36);s.army.x[i]=neutral.x;s.army.y[i]=neutral.y;s.war.logistics(2);expect(s.army.supply[i]).toBe(34);s.army.x[i]=enemy.x;s.army.y[i]=enemy.y;s.war.logistics(2);expect(s.army.supply[i]).toBe(28);s.army.supply[i]=0;s.war.logistics(2);expect(s.army.hp[i]).toBe(96);s.sim.paused=true;const snapshot=s.army.snapshot();ticks(s.sim,20);expect(s.army.snapshot()).toEqual(snapshot);expect(snapshot.length).toBe(UNIT_STRIDE);expect(snapshot[15]).toBe(0);s.army.hp[i]=1;s.war.logistics(1);expect(s.army.index(id)).toBe(-1);});
 it('preserves treaties on synthetic reset and clears diplomacy when regenerating the map',()=>{const s=setup();alliance(s,1,3);s.d.testWar(1,2);s.sim.command({type:'RESET'});expect(s.sim.match!.diplomacy).toBe(s.d);expect(s.d.hostile(1,2)).toBe(true);s.sim.command({type:'GENERATE_MAP',config:{...DEFAULT_MAP_CONFIG,size:'small'},requestId:1});expect(s.sim.territorial).toBeNull();expect(s.sim.match).toBeNull();});
});
