import {cellAtWorld} from '../../map/hex/coordinates';
import {RESOURCE_KEYS} from '../../shared/configs/buildings';
import {AIR,NAVAL,MISSILES,type MissileType} from '../../shared/configs/operations';
import {UNIT_STATE,UNIT_MODES} from '../../shared/configs/units';
import type {Command} from '../../shared/types/protocol';
import type {Building} from '../economy/types';
import type {Point} from '../navigation/grid';
import type {TerritoryMatch} from '../territory/match';
import type {Army} from '../units/army';
interface Flight {id:number;autoReturn:boolean;returning:boolean;warned:boolean;points:Point[];targetUnit?:number;targetBuilding?:number;mode?:'defense'|'attack';elapsed:number;}
interface Passenger {id:number;target:Point;landing:number;}
interface Waiting extends Passenger {portId:number;}
interface Boat {id:number;portId:number;passengers:Passenger[];points:Point[];landing:number|null;target:Point|null;status:'loading'|'sailing'|'unloading'|'idle'|'trading'|'returning'|'waiting'|'manual';lastArrival:number;firstArrival:number;timer:number;destinationPort?:number;profit:number;}
interface Impact {id:number;ownerId:number;anchorId:number;radius:number;remaining:number;damage:number;}
/** Naval routes are shared per pair of water cells. Embarked troops leave spatial/render updates. */
export class OperationsSystem {
 readonly flights=new Map<number,Flight>();readonly boats=new Map<number,Boat>();readonly waiting=new Map<number,Waiting>();readonly impacts:Impact[]=[];
 private transportPlans=new Map<string,{portId:number;landing:number}>();private waterComponents:Int32Array;private waterRoutes=new Map<string,number[]>();private coasts:number[]=[];private coastByWater=new Map<number,number[]>();private time=0;private publishElapsed=0;private tradeElapsed=0;private nextImpact=1;private internal=false;
 constructor(readonly match:TerritoryMatch,readonly army:Army){
  const cells=match.map.cells;this.waterComponents=new Int32Array(cells.length).fill(-1);let component=0;
  for(const c of cells)if(c.terrain==='water'&&this.waterComponents[c.id]<0){const queue=[c.id];this.waterComponents[c.id]=component;for(let h=0;h<queue.length;h++)for(const n of cells[queue[h]].neighbors)if(cells[n].terrain==='water'&&this.waterComponents[n]<0){this.waterComponents[n]=component;queue.push(n);}component++;}
  for(const c of cells)if(c.terrain==='land'&&c.neighbors.some(n=>cells[n].terrain==='water')){this.coasts.push(c.id);for(const component of new Set(c.neighbors.filter(n=>cells[n].terrain==='water').map(n=>this.waterComponents[n]))){let coasts=this.coastByWater.get(component);if(!coasts)this.coastByWater.set(component,coasts=[]);coasts.push(c.id);}}
  army.onRemove=id=>this.removed(id);army.specialTarget=i=>this.flights.get(army.ids[i])?.points.at(-1)??this.boats.get(army.ids[i])?.points.at(-1);this.publish();
 }
 private event(text:string){this.match.diplomacy!.event(text);}
 private friendly(a:number,b:number|null){return b===null||a===b||this.match.diplomacy!.allied(a,b)||this.match.diplomacy!.hostile(a,b);}
 private waterAt(b:Building){return this.match.map.cells[b.anchorId].neighbors.find(n=>this.match.map.cells[n].terrain==='water');}
 private ports(owner:number){return this.match.state.buildings.filter(b=>b.type==='port'&&!b.construction&&(b.ownerId===owner||this.match.diplomacy!.allied(owner,b.ownerId)));}
 private waterRoute(a:number,b:number){if(this.waterComponents[a]<0||this.waterComponents[a]!==this.waterComponents[b])throw new Error('Não existe ligação navegável entre essas águas.');const key=a+':'+b;const cached=this.waterRoutes.get(key);if(cached)return cached;const cells=this.match.map.cells,parents=new Int32Array(cells.length).fill(-1),queue=[a];parents[a]=a;for(let h=0;h<queue.length&&parents[b]<0;h++)for(const n of cells[queue[h]].neighbors)if(cells[n].terrain==='water'&&parents[n]<0){parents[n]=queue[h];queue.push(n);}if(parents[b]<0)throw new Error('Não há rota aquática.');const path=[b];while(path.at(-1)!==a)path.push(parents[path.at(-1)!]);path.reverse();if(this.waterRoutes.size>=128)this.waterRoutes.delete(this.waterRoutes.keys().next().value!);this.waterRoutes.set(key,path);return path;}
 private point(i:number){return {x:this.army.x[i],y:this.army.y[i]};}
 private stopGround(owner:number,ids:number[]){if(ids.length)this.army.stop(owner,ids);}
 private groundMove(owner:number,ids:number[],point:Point){if(!ids.length)return;this.internal=true;try{this.army.enqueueOrder({type:'MOVE_UNITS',playerId:owner,unitIds:ids,target:point,cohesion:false},'background');}finally{this.internal=false;}}
 private flight(id:number){let f=this.flights.get(id);if(!f){f={id,autoReturn:true,returning:false,warned:false,points:[],elapsed:0};this.flights.set(id,f);}return f;}
 private planTransport(owner:number,i:number,target:Point):Waiting {
  const cells=this.match.map.cells,start=this.point(i),dest=cellAtWorld(this.match.map,target.x,target.y);if(!dest||dest.terrain!=='land')throw new Error('Escolha um destino terrestre para as tropas.');
  const cacheKey=owner+':'+Math.floor(start.x/192)+':'+Math.floor(start.y/192)+':'+dest.id+':'+this.match.state.buildingRevision+':'+this.match.state.diplomacy.revision+':'+this.match.state.borderRevision;const cached=this.transportPlans.get(cacheKey);if(cached){const port=this.match.state.buildings.find(b=>b.id===cached.portId);if(port&&this.army.navigation.connected(start,cells[port.anchorId]))return {id:this.army.ids[i],...cached,target:{...target}};}const choices=this.ports(owner).filter(b=>this.army.navigation.connected(start,cells[b.anchorId])).map(b=>{const water=this.waterAt(b);return {b,water,score:Math.hypot(start.x-cells[b.anchorId].x,start.y-cells[b.anchorId].y)+Math.hypot(target.x-cells[b.anchorId].x,target.y-cells[b.anchorId].y)};}).sort((a,b)=>a.score-b.score);
  for(const {b,water}of choices){if(water===undefined)continue;const landing=(this.coastByWater.get(this.waterComponents[water])??[]).map(id=>cells[id]).filter(c=>this.friendly(owner,c.ownerId)&&this.army.navigation.connected(c,target)).sort((a,b)=>Math.hypot(a.x-target.x,a.y-target.y)-Math.hypot(b.x-target.x,b.y-target.y))[0];if(landing){if(this.transportPlans.size>=128)this.transportPlans.delete(this.transportPlans.keys().next().value!);this.transportPlans.set(cacheKey,{portId:b.id,landing:landing.id});return {id:this.army.ids[i],portId:b.id,target:{...target},landing:landing.id};}}
  throw new Error('Não há porto próprio ou aliado com acesso terrestre e rota navegável até esse destino.');
 }
 /** Handles special units and sea crossings before land routing enters the scheduler. */
 command(c:Command){if(this.internal)return false;
  if(c.type==='RESUME_COMMERCE'){const boat=this.boats.get(c.unitId),i=this.army.index(c.unitId),home=this.match.state.buildings.find(b=>b.id===boat?.portId),dest=this.match.state.buildings.find(b=>b.id===boat?.destinationPort);if(!boat||i<0||this.army.owner[i]!==c.playerId||this.army.kind[i]!==4||!home||!dest||!this.commercialAllowed(home,dest))throw new Error('Rota comercial indisponível.');const start=cellAtWorld(this.match.map,this.army.x[i],this.army.y[i])!;boat.status='returning';boat.profit=0;boat.points=this.waterRoute(start.id,this.waterAt(home)!).map(n=>this.match.map.cells[n]);this.publish();return true;}
  if(c.type==='PRODUCE_MISSILE'){this.produce(c.playerId,c.buildingId,c.missileType);return true;}
  if(c.type==='LAUNCH_MISSILE'){this.launch(c.playerId,c.buildingId,c.anchorId);return true;}
  if(c.type==='SET_AIR_RETURN'){for(const i of this.army.indices(c.playerId,c.unitIds))if(this.army.kind[i]===2)this.flight(this.army.ids[i]).autoReturn=c.enabled;this.publish();return true;}
  if(!['MOVE_UNITS','STOP_UNITS','RETREAT_UNITS','ATTACK_UNIT','ATTACK_BUILDING','SET_UNIT_MODE'].includes(c.type)||!('unitIds'in c))return false;
  const indices=this.army.indices(c.playerId,c.unitIds),special=indices.some(i=>this.army.kind[i]>=2||this.waiting.has(this.army.ids[i])||this.army.embarked[i]);
  const foreignTarget=c.type==='ATTACK_UNIT'?this.army.index(c.targetId):-1,nonLandTarget=foreignTarget>=0&&!this.army.navigation.land(this.point(foreignTarget));const crossing=c.type==='MOVE_UNITS'&&indices.some(i=>this.army.kind[i]<2&&!this.army.embarked[i]&&!this.army.navigation.connected(this.point(i),c.target));if(!special&&!crossing&&!nonLandTarget)return false;
  if(c.type==='MOVE_UNITS'){
   if(!cellAtWorld(this.match.map,c.target.x,c.target.y))throw new Error('Escolha um destino dentro do mapa.');
   const plans=new Map<number,Waiting>();for(const i of indices)if(this.army.kind[i]<2&&!this.army.embarked[i]&&!this.army.navigation.connected(this.point(i),c.target))plans.set(i,this.planTransport(c.playerId,i,c.target));
   const ground:number[]=[];for(const i of indices){const id=this.army.ids[i];if(this.army.embarked[i]){const boat=this.boats.get(this.army.embarked[i]),p=boat?.passengers.find(p=>p.id===id);if(p)p.target={...c.target};continue;}
    if(this.army.kind[i]===2){this.stopGround(c.playerId,[id]);const f=this.flight(id);f.returning=false;delete f.targetUnit;delete f.targetBuilding;delete f.mode;if(c.append)f.points.push({...c.target});else f.points=[{...c.target}];this.army.state[i]=UNIT_STATE.moving;}
    else if(this.army.kind[i]>=3)this.moveBoat(id,c.target,!!c.append);
    else if(plans.has(i)){const plan=plans.get(i)!;this.waiting.set(id,plan);this.army.waitingForTransport[i]=1;this.stopGround(c.playerId,[id]);this.groundMove(c.playerId,[id],this.match.map.cells[this.match.state.buildings.find(b=>b.id===plan.portId)!.anchorId]);}
    else {this.waiting.delete(id);this.army.waitingForTransport[i]=0;ground.push(id);}}
   if(ground.length){this.internal=true;try{this.army.enqueueOrder({...c,unitIds:ground},c.playerId===1?'human':'background');}finally{this.internal=false;}}this.publish();return true;
  }
  const ground=indices.filter(i=>this.army.kind[i]<2&&!this.army.embarked[i]).map(i=>this.army.ids[i]);
  if(c.type==='ATTACK_UNIT'||c.type==='ATTACK_BUILDING'){
   const target=c.type==='ATTACK_UNIT'?this.army.index(c.targetId):-1,b=c.type==='ATTACK_BUILDING'?this.match.state.buildings.find(b=>b.id===c.buildingId):undefined,owner=target>=0?this.army.owner[target]:b?.ownerId;if(owner===undefined||!this.match.diplomacy!.hostile(c.playerId,owner))throw new Error('Escolha um alvo inimigo durante guerra.');
   for(const i of indices)if(this.army.kind[i]===2){this.stopGround(c.playerId,[this.army.ids[i]]);const f=this.flight(this.army.ids[i]);f.returning=false;delete f.mode;f.targetUnit=c.type==='ATTACK_UNIT'?c.targetId:undefined;f.targetBuilding=b?.id;f.points=[target>=0?this.point(target):this.match.map.cells[b!.anchorId]];if(b)this.army.buildingOrders.set(i,b.id);}
  }else if(c.type==='RETREAT_UNITS'){for(const i of indices)if(this.army.kind[i]===2)this.returnFlight(this.flight(this.army.ids[i]));else if(this.army.kind[i]>=3){const b=this.match.state.buildings.find(b=>b.id===this.boats.get(this.army.ids[i])?.portId);const water=b&&this.waterAt(b);if(water!==undefined)this.moveBoat(this.army.ids[i],this.match.map.cells[water],false);}}
  else if(c.type==='STOP_UNITS'){for(const i of indices){this.waiting.delete(this.army.ids[i]);this.army.waitingForTransport[i]=0;if(this.army.kind[i]===2){const f=this.flight(this.army.ids[i]);f.points=[];f.returning=false;delete f.targetUnit;delete f.targetBuilding;delete f.mode;this.stopGround(c.playerId,[f.id]);}const boat=this.boats.get(this.army.ids[i]);if(boat){boat.points=[];boat.status='manual';boat.landing=null;this.army.state[i]=UNIT_STATE.idle;}}}
  else if(c.type==='SET_UNIT_MODE'){for(const i of indices)if(this.army.kind[i]===2){if(c.mode==='discovery')throw new Error('Aviões não conquistam terrenos. Use defesa ou ataque.');const f=this.flight(this.army.ids[i]);f.mode=c.mode;f.elapsed=2;this.army.modes[i]=UNIT_MODES[c.mode];}}
  if(ground.length&&c.type==='ATTACK_UNIT'&&nonLandTarget){const target=this.point(foreignTarget);const positions=ground.map(id=>{const i=this.army.index(id),range=this.army.definition(i).range;if(Math.hypot(this.army.x[i]-target.x,this.army.y[i]-target.y)<=range)return {id,point:this.point(i)};const shore=this.match.map.cells.filter(cell=>cell.terrain==='land'&&Math.hypot(cell.x-target.x,cell.y-target.y)<range*.9&&this.army.navigation.connected(this.point(i),cell)).sort((a,b)=>Math.hypot(a.x-this.army.x[i],a.y-this.army.y[i])-Math.hypot(b.x-this.army.x[i],b.y-this.army.y[i]))[0];if(!shore)throw new Error('O alvo está fora do alcance terrestre. Aproxime as tropas de uma costa acessível.');return {id,point:shore};});for(const p of positions){this.stopGround(c.playerId,[p.id]);this.groundMove(c.playerId,[p.id],p.point);}this.publish();return true;}
  if(ground.length){this.internal=true;try{if(c.type==='SET_UNIT_MODE')this.army.setMode(c.playerId,ground,c.mode);else if(c.type==='STOP_UNITS')this.army.stop(c.playerId,ground);else this.army.enqueueOrder({...c,unitIds:ground} as Extract<Command,{type:'RETREAT_UNITS'|'ATTACK_UNIT'|'ATTACK_BUILDING'}>,c.playerId===1?'human':'background');}finally{this.internal=false;}}
  this.publish();return true;
 }
 private moveBoat(id:number,target:Point,append:boolean){const boat=this.boats.get(id),i=this.army.index(id);if(!boat||i<0)throw new Error('Barco indisponível.');const dest=cellAtWorld(this.match.map,target.x,target.y)!;let landing:number|null=null,water=dest.id;if(dest.terrain==='land'){if(!this.friendly(this.army.owner[i],dest.ownerId))throw new Error('Desembarque permitido apenas em terra neutra, própria, aliada ou inimiga em guerra.');const from=cellAtWorld(this.match.map,this.army.x[i],this.army.y[i])!;const coast=(this.coastByWater.get(this.waterComponents[from.id])??[]).map(n=>this.match.map.cells[n]).filter(c=>this.friendly(this.army.owner[i],c.ownerId)&&this.army.navigation.connected(c,target)).sort((a,b)=>Math.hypot(a.x-target.x,a.y-target.y)-Math.hypot(b.x-target.x,b.y-target.y))[0];if(!coast)throw new Error('Essa costa não pode ser alcançada pelo barco.');landing=coast.id;water=coast.neighbors.find(n=>this.waterComponents[n]===this.waterComponents[from.id])!;}
  const from=append&&boat.points.length?cellAtWorld(this.match.map,boat.points.at(-1)!.x,boat.points.at(-1)!.y)!:cellAtWorld(this.match.map,this.army.x[i],this.army.y[i])!;const points=this.waterRoute(from.id,water).map(n=>this.match.map.cells[n]);boat.points=append?[...boat.points,...points]:[...points];boat.landing=this.army.kind[i]===4?null:landing;boat.target=landing!==null?{...target}:null;boat.status='manual';boat.timer=0;for(const p of boat.passengers)if(landing!==null){p.landing=landing;p.target={...target};}this.army.state[i]=UNIT_STATE.moving;
 }
 private returnFlight(f:Flight){const i=this.army.index(f.id);if(i<0)return;const base=this.match.state.buildings.filter(b=>b.type==='barracks'&&!b.construction&&(b.ownerId===this.army.owner[i]||this.match.diplomacy!.allied(this.army.owner[i],b.ownerId))).sort((a,b)=>{const p=this.match.map.cells[a.anchorId],q=this.match.map.cells[b.anchorId];return Math.hypot(p.x-this.army.x[i],p.y-this.army.y[i])-Math.hypot(q.x-this.army.x[i],q.y-this.army.y[i]);})[0];if(!base){if(!f.warned)this.event('Avião '+f.id+' sem quartel disponível para retornar.');return;}this.stopGround(this.army.owner[i],[f.id]);f.points=[this.match.map.cells[base.anchorId]];f.returning=true;delete f.targetUnit;delete f.targetBuilding;this.army.state[i]=UNIT_STATE.retreat;}
 private attackPass(i:number,target:Point){let angle=Math.atan2(target.y-this.army.y[i],target.x-this.army.x[i]);if(Math.hypot(target.x-this.army.x[i],target.y-this.army.y[i])<10)angle=this.army.angle[i];const exit={x:target.x+Math.cos(angle)*190,y:target.y+Math.sin(angle)*190};return cellAtWorld(this.match.map,exit.x,exit.y)?[{...target},exit]:[{...target}];}
 private advance(i:number,points:Point[],dt:number){let budget=this.army.definition(i).speed*dt;while(points.length&&budget>0){const p=points[0],dx=p.x-this.army.x[i],dy=p.y-this.army.y[i],d=Math.hypot(dx,dy);if(d<.1){points.shift();continue;}const travel=Math.min(d,budget);this.army.angle[i]=Math.atan2(dy,dx);this.army.x[i]+=dx/d*travel;this.army.y[i]+=dy/d*travel;budget-=travel;if(travel>=d-.1)points.shift();}if(points.length)this.army.state[i]=this.flights.get(this.army.ids[i])?.returning?UNIT_STATE.retreat:UNIT_STATE.moving;else if(this.army.state[i]!==UNIT_STATE.attack)this.army.state[i]=UNIT_STATE.idle;}
 private removed(id:number){this.flights.delete(id);this.waiting.delete(id);const boat=this.boats.get(id);if(boat){this.boats.delete(id);for(const p of boat.passengers){const i=this.army.index(p.id);if(i>=0){this.army.embarked[i]=0;this.army.remove(i);}}if(boat.passengers.length)this.event('Transporte '+id+' afundou: '+boat.passengers.length+' unidades a bordo foram perdidas.');}for(const b of this.boats.values())b.passengers=b.passengers.filter(p=>p.id!==id);}
 private boarding(){const cells=this.match.map.cells;for(const [id,w]of this.waiting){const i=this.army.index(id),port=this.match.state.buildings.find(b=>b.id===w.portId&&!b.construction);if(i<0||!port||!this.ports(this.army.owner[i]).some(b=>b.id===port.id)){this.waiting.delete(id);if(i>=0)this.army.waitingForTransport[i]=0;continue;}const p=cells[port.anchorId];if(Math.hypot(this.army.x[i]-p.x,this.army.y[i]-p.y)>NAVAL.arrivalRadius)continue;let boat=[...this.boats.values()].find(b=>b.portId===port.id&&b.status==='loading');const weight=this.army.kind[i]===1?5:1;if(boat&&(boat.landing!==w.landing||this.army.owner[this.army.index(boat.id)]!==this.army.owner[i]||boat.passengers.reduce((n,p)=>{const j=this.army.index(p.id);return n+(j>=0&&this.army.kind[j]===1?5:1);},0)+weight>NAVAL.capacity))continue;
   const water=this.waterAt(port);if(water===undefined)continue;if(!boat){const reusable=[...this.boats.values()].find(b=>b.portId===port.id&&b.status==='idle'&&!b.passengers.length&&this.army.owner[this.army.index(b.id)]===this.army.owner[i]&&Math.hypot(this.army.x[this.army.index(b.id)]-cells[water].x,this.army.y[this.army.index(b.id)]-cells[water].y)<NAVAL.arrivalRadius);if(reusable){boat=reusable;boat.status='loading';boat.firstArrival=this.time;boat.landing=w.landing;boat.target=w.target;}else{if(this.army.count+this.army.queuedCount>=5000)continue;const ship=this.army.spawn(this.army.owner[i],'transport',cells[water]);boat={id:ship,portId:port.id,passengers:[],points:[],landing:w.landing,target:w.target,status:'loading',lastArrival:this.time,firstArrival:this.time,timer:0,profit:0};this.boats.set(ship,boat);}}
   this.stopGround(this.army.owner[i],[id]);this.army.embarked[i]=boat.id;this.army.waitingForTransport[i]=0;this.army.x[i]=cells[water].x;this.army.y[i]=cells[water].y;boat.passengers.push({id,target:w.target,landing:w.landing});boat.lastArrival=this.time;this.waiting.delete(id);
  }
 }
 private sail(boat:Boat){const i=this.army.index(boat.id),start=cellAtWorld(this.match.map,this.army.x[i],this.army.y[i])!;const water=this.match.map.cells[boat.landing!].neighbors.find(n=>this.waterComponents[n]===this.waterComponents[start.id]);if(water===undefined){boat.status='manual';this.event('Transporte '+boat.id+' aguardando uma costa navegável.');return;}boat.points=this.waterRoute(start.id,water).map(n=>this.match.map.cells[n]);boat.status='sailing';this.army.state[i]=UNIT_STATE.moving;}
 private unload(boat:Boat){const i=this.army.index(boat.id);if(i<0||boat.landing===null)return;const coast=this.match.map.cells[boat.landing];if(!this.friendly(this.army.owner[i],coast.ownerId)){boat.status='manual';this.event('Desembarque bloqueado: a relação com o país da costa mudou.');return;}for(const p of [...boat.passengers]){const j=this.army.index(p.id);if(j<0)continue;this.army.embarked[j]=0;this.army.x[j]=coast.x;this.army.y[j]=coast.y;this.army.state[j]=UNIT_STATE.idle;if(this.army.navigation.connected(coast,p.target))this.groundMove(this.army.owner[j],[p.id],p.target);}boat.passengers=[];boat.status='idle';boat.landing=null;this.event('Transporte '+boat.id+' concluiu o desembarque.');}
 private commercialAllowed(a:Building,b:Building){const r=this.match.diplomacy!.relation(a.ownerId,b.ownerId);return a.ownerId!==b.ownerId&&!!r&&!['WAR','TENSION'].includes(r.state)&&!this.match.diplomacy!.hostile(a.ownerId,b.ownerId);}
 private trade(){const ports=this.match.state.buildings.filter(b=>b.type==='port'&&!b.construction);for(const a of ports){if([...this.boats.values()].some(b=>b.portId===a.id&&this.army.kind[this.army.index(b.id)]===4))continue;const water=this.waterAt(a);if(water===undefined)continue;const target=ports.filter(b=>this.commercialAllowed(a,b)&&this.waterAt(b)!==undefined&&this.waterComponents[this.waterAt(b)!]===this.waterComponents[water]).sort((b,c)=>{const p=this.match.map.cells[a.anchorId],q=this.match.map.cells[b.anchorId],r=this.match.map.cells[c.anchorId];return Math.hypot(q.x-p.x,q.y-p.y)-Math.hypot(r.x-p.x,r.y-p.y);})[0];if(!target||this.army.count+this.army.queuedCount>=5000)continue;const route=this.waterRoute(water,this.waterAt(target)!),distance=route.reduce((n,id,k)=>k?n+Math.hypot(this.match.map.cells[id].x-this.match.map.cells[route[k-1]].x,this.match.map.cells[id].y-this.match.map.cells[route[k-1]].y):0,0),id=this.army.spawn(a.ownerId,'cargo',this.match.map.cells[water]);this.boats.set(id,{id,portId:a.id,passengers:[],points:route.map(n=>this.match.map.cells[n]),landing:null,target:null,status:'trading',lastArrival:0,firstArrival:0,timer:0,destinationPort:target.id,profit:Math.min(NAVAL.maxProfit,Math.max(NAVAL.minProfit,distance*NAVAL.profitPerWorldUnit))});}}
 private produce(owner:number,id:number,type:MissileType){const b=this.match.state.buildings.find(b=>b.id===id&&b.ownerId===owner&&b.type==='silo'&&!b.construction),def=MISSILES[type];if(!b||!def)throw new Error('Selecione um silo concluído e um míssil válido.');if(b.missile)throw new Error('O silo já está produzindo ou armazenando um míssil.');const c=this.match.state.economies.find(c=>c.playerId===owner)!;if(RESOURCE_KEYS.some(k=>c.stock[k]<(def.cost[k]??0)))throw new Error('Recursos insuficientes para produzir esse míssil.');for(const k of RESOURCE_KEYS)c.stock[k]-=def.cost[k]??0;b.missile={type,elapsed:0,duration:def.seconds};this.match.state.revision++;}
 private launch(owner:number,id:number,anchorId:number){const b=this.match.state.buildings.find(b=>b.id===id&&b.ownerId===owner&&b.type==='silo'&&!b.construction),cell=this.match.map.cells[anchorId];if(!b?.missile||b.missile.elapsed<b.missile.duration)throw new Error('O míssil ainda não está pronto.');if(!cell||cell.ownerId===null||!this.match.diplomacy!.hostile(owner,cell.ownerId))throw new Error('Selecione território de um país com quem você está em guerra.');const def=MISSILES[b.missile.type];this.impacts.push({id:this.nextImpact++,ownerId:owner,anchorId,radius:def.radius,remaining:def.flightSeconds,damage:def.damage});delete b.missile;this.event(def.name+' lançado por '+this.match.diplomacy!.name(owner)+'! Impacto em '+def.flightSeconds+' s, raio '+def.radius+'.');this.publish();}
 private explode(impact:Impact){const center=this.match.map.cells[impact.anchorId],distance=(id:number)=>{const c=this.match.map.cells[id];return Math.max(Math.abs(c.q-center.q),Math.abs(c.r-center.r),Math.abs(c.q+c.r-center.q-center.r));},damage=(d:number)=>impact.damage*(1-.75*d/impact.radius);for(let i=0;i<this.army.size;i++)if(this.army.ids[i]&&!this.army.embarked[i]){const cell=this.army.cell(i);if(cell&&distance(cell.id)<=impact.radius){this.army.hp[i]-=damage(distance(cell.id));if(this.army.hp[i]<=0)this.army.remove(i);}}for(const b of [...this.match.state.buildings]){const d=Math.min(...b.cellIds.map(distance));if(d<=impact.radius)this.match.damageBuilding(b.id,damage(d));}this.event('Impacto de míssil em área de '+impact.radius+' hexágonos de raio.');}
 step(dt:number){this.time+=dt;const bases=this.match.state.buildings.filter(b=>b.type==='barracks'&&!b.construction);
  for(let i=0;i<this.army.size;i++)if(this.army.ids[i]&&this.army.kind[i]===2){const f=this.flight(this.army.ids[i]),owner=this.army.owner[i],near=bases.some(b=>(b.ownerId===owner||this.match.diplomacy!.allied(owner,b.ownerId))&&Math.hypot(this.match.map.cells[b.anchorId].x-this.army.x[i],this.match.map.cells[b.anchorId].y-this.army.y[i])<=AIR.baseRadius);this.army.supply[i]=Math.max(0,Math.min(100,this.army.supply[i]+(near?AIR.restorePerSecond:-AIR.drainPerSecond)*dt));if(near){f.warned=false;if(f.returning&&this.army.supply[i]>=99){f.returning=false;f.points=[];this.army.state[i]=UNIT_STATE.idle;}}if(!near&&this.army.supply[i]<=AIR.returnThreshold&&f.autoReturn&&!f.returning)this.returnFlight(f);if(this.army.supply[i]<=0){if(!f.warned){this.event('Avião '+f.id+' de '+this.match.diplomacy!.name(owner)+' está sem recursos e perdendo vida.');f.warned=true;}this.army.hp[i]-=AIR.attritionPerSecond*dt;if(this.army.hp[i]<=0){this.army.remove(i);continue;}}
   f.elapsed+=dt;if(!f.returning&&f.elapsed>=2){f.elapsed=0;if(f.targetUnit){const target=this.army.index(f.targetUnit);if(target>=0&&this.match.diplomacy!.hostile(owner,this.army.owner[target])){if(!f.points.length)f.points=this.attackPass(i,this.point(target));}else delete f.targetUnit;}if(f.targetBuilding){const b=this.match.state.buildings.find(b=>b.id===f.targetBuilding&&this.match.diplomacy!.hostile(owner,b.ownerId));if(b){if(!f.points.length)f.points=this.attackPass(i,this.match.map.cells[b.anchorId]);}else delete f.targetBuilding;}if(f.mode==='attack'&&!f.targetBuilding){const enemy=this.match.state.buildings.filter(b=>this.match.diplomacy!.hostile(owner,b.ownerId)&&this.army.botVisibility(owner,-b.id)).sort((a,b)=>Math.hypot(this.match.map.cells[a.anchorId].x-this.army.x[i],this.match.map.cells[a.anchorId].y-this.army.y[i])-Math.hypot(this.match.map.cells[b.anchorId].x-this.army.x[i],this.match.map.cells[b.anchorId].y-this.army.y[i]))[0];if(enemy){f.targetBuilding=enemy.id;this.army.buildingOrders.set(i,enemy.id);f.points=this.attackPass(i,this.match.map.cells[enemy.anchorId]);}}if(f.mode==='defense'&&!f.points.length){const base=bases.find(b=>b.ownerId===owner);if(base){const c=this.match.map.cells[base.anchorId],angle=(f.id+this.time)*.6,p={x:c.x+Math.cos(angle)*AIR.baseRadius*.7,y:c.y+Math.sin(angle)*AIR.baseRadius*.7};f.points=[cellAtWorld(this.match.map,p.x,p.y)?p:c];}}}
   // Aircraft keep moving through attack passes instead of stopping in ground combat.
   if(f.points.length)this.advance(i,f.points,dt);
  }
  this.boarding();for(const boat of [...this.boats.values()]){const i=this.army.index(boat.id);if(i<0)continue;if(boat.status==='loading'){const load=boat.passengers.reduce((n,p)=>{const j=this.army.index(p.id);return n+(j>=0&&this.army.kind[j]===1?5:1);},0);if(load>=NAVAL.capacity||this.time-boat.lastArrival>=NAVAL.quietSeconds||this.time-boat.firstArrival>=NAVAL.maxWaitSeconds)this.sail(boat);}
   if(boat.points.length)this.advance(i,boat.points,dt);for(const p of boat.passengers){const j=this.army.index(p.id);if(j>=0){this.army.x[j]=this.army.x[i];this.army.y[j]=this.army.y[i];}}
   if(!boat.points.length&&(boat.status==='sailing'||boat.status==='manual')&&boat.landing!==null){boat.status='unloading';boat.timer=0;}
   if(boat.status==='unloading'){boat.timer+=dt;const coast=this.match.map.cells[boat.landing!],friendly=coast.ownerId===this.army.owner[i]||coast.ownerId!==null&&this.match.diplomacy!.allied(this.army.owner[i],coast.ownerId);if(boat.timer>=(friendly?NAVAL.friendlyLandingSeconds:NAVAL.landingSeconds))this.unload(boat);}
   if(this.army.kind[i]===4){const home=this.match.state.buildings.find(b=>b.id===boat.portId&&b.type==='port'&&!b.construction&&b.ownerId===this.army.owner[i]),dest=this.match.state.buildings.find(b=>b.id===boat.destinationPort&&b.type==='port'&&!b.construction);if(!home){this.army.remove(i);continue;}const valid=dest&&this.commercialAllowed(home,dest);if(!valid&&boat.status!=='returning'&&boat.status!=='manual'){boat.profit=0;boat.status='returning';const start=cellAtWorld(this.match.map,this.army.x[i],this.army.y[i])!;boat.points=this.waterRoute(start.id,this.waterAt(home)!).map(n=>this.match.map.cells[n]);}
    if(!boat.points.length&&boat.status==='trading'){boat.timer+=dt;if(boat.timer>=NAVAL.commercialTurnaround){const start=cellAtWorld(this.match.map,this.army.x[i],this.army.y[i])!;boat.points=this.waterRoute(start.id,this.waterAt(home)!).map(n=>this.match.map.cells[n]);boat.status='returning';boat.timer=0;}}
    else if(!boat.points.length&&boat.status==='returning'){if(valid&&boat.profit){this.match.state.economies.find(c=>c.playerId===home.ownerId)!.stock.money+=boat.profit;this.match.state.economies.find(c=>c.playerId===dest.ownerId)!.stock.money+=boat.profit*.25;}this.army.remove(i);}
   }
  }
  this.tradeElapsed+=dt;if(this.tradeElapsed>=5){this.tradeElapsed=0;this.trade();}
  for(const b of this.match.state.buildings)if(b.missile)b.missile.elapsed=Math.min(b.missile.duration,b.missile.elapsed+dt);
  for(const impact of [...this.impacts]){impact.remaining-=dt;if(impact.remaining<=0){this.impacts.splice(this.impacts.indexOf(impact),1);this.explode(impact);}}
  this.publishElapsed+=dt;if(this.publishElapsed>=.5){this.publishElapsed=0;this.publish();}
 }
 private publish(){this.match.state.operations={aircraft:[...this.flights.values()].map(f=>({id:f.id,autoReturn:f.autoReturn,returning:f.returning})),boats:[...this.boats.values()].map(b=>({id:b.id,portId:b.portId,passengers:b.passengers.length,capacity:b.passengers.reduce((n,p)=>{const i=this.army.index(p.id);return n+(i>=0&&this.army.kind[i]===1?5:1);},0),destination:b.destinationPort??b.landing,status:b.status,profit:b.profit})),missiles:this.impacts.map(({damage,...impact})=>({...impact}))};this.match.state.revision++;}
}
