import {visualLod,inView,type VisualMode,type MapLens} from './visual-lod';
import {drawStructureSurroundings} from './structure-art';
import {COMBAT} from '../../../packages/shared/configs/combat';
import {BUILDING_ASSETS,buildingArtKey,type BuildingArtKey} from './building-assets';
import {bridgeBanks} from '../../../packages/map/bridges';
import {spriteCountryTint} from '../../../packages/shared/configs/countries';
import {Assets,Container,Graphics,Sprite,Texture} from 'pixi.js';
import type {Building} from '../../../packages/simulation/economy/types';
import type {ProceduralMap} from '../../../packages/map/types';
import type {MatchState,OwnershipChange,SpawnCandidate} from '../../../packages/simulation/territory/types';
import {axialIndex,HEX_DIRECTIONS,hexCorners,hexEdge} from '../../../packages/map/hex/coordinates';
import type {Camera} from '../input/camera';
import {drawBuildingIcon,structureEdges} from './buildings';
import {BUILDINGS} from '../../../packages/shared/configs/buildings';
interface Chunk {graphics:Graphics;ids:number[];left:number;right:number;top:number;bottom:number;}
interface BuildingArt {underConstruction:boolean;root:Container;sprite:Sprite;surroundings:Graphics;strategic:Graphics;symbol:Graphics;bounds:{left:number;right:number;top:number;bottom:number};}
/** Pixi reuses the preceding fill/stroke geometry when no new path was drawn. */
export function drawOwnershipChunk(g:Graphics,map:ProceduralMap,ids:readonly number[],colors:ReadonlyMap<number,number>,fillAlpha=.19){
 g.clear();for(const [ownerId,color]of colors){
  const owned=ids.filter(id=>map.cells[id].ownerId===ownerId);if(!owned.length)continue;
  g.beginPath();for(const id of owned)g.poly(hexCorners(map.cells[id],map.layout.radius));g.fill({color,alpha:fillAlpha});
  g.beginPath();let edges=0;for(const id of owned){const cell=map.cells[id];for(let d=0;d<6;d++){const [dq,dr]=HEX_DIRECTIONS[d],n=axialIndex(cell.q+dq,cell.r+dr,map.layout);if(n<0||map.cells[n].ownerId!==ownerId){const e=hexEdge(cell,map.layout.radius,d);g.moveTo(e[0],e[1]).lineTo(e[2],e[3]);edges++;}}}
  if(edges)g.stroke({color,width:2.5,alpha:.95});
 }
}
export class OwnershipRenderer {
 visualMode:VisualMode='auto';lens:MapLens='countries';private lensRevision=-1;private lensBuildingRevision=-1;private tacticalLens=new Graphics();private diplomacyColors=new Map<number,number>();private paintLens:MapLens='countries';private paintDiplomacyRevision=-1;
 cancelling=false;private cancelOutline=new Graphics();private missileAreas=new Graphics();
 readonly root=new Container();private chunks:Chunk[]=[];private byCell=new Int32Array(0);private map:ProceduralMap|null=null;private colors=new Map<number,number>();private previews=new Graphics();private cities=new Graphics();private expedition=new Graphics();private target=new Graphics();private state:MatchState|null=null;private buildingRevision=-1;private health=new Graphics();private sieges=new Graphics();private siegeRevision=-1;private buildingLayer=new Container();private buildingArt=new Map<number,BuildingArt>();private textures=new Map<BuildingArtKey,Texture>();private hovered=new Graphics();private hoverCell=-1;private hoverBuilding=-1;private buildingsByCell=new Map<number,Building>();
 async init(){await Promise.all(Object.entries(BUILDING_ASSETS).map(async ([key,url])=>{const texture=await Assets.load<Texture>(url);texture.source.scaleMode='linear';this.textures.set(key as BuildingArtKey,texture);}));}
 private syncBuildingArt(state:MatchState){if(!this.map)return;const alive=new Set<number>();for(const building of state.buildings){
  const texture=this.textures.get(buildingArtKey(building));if(!texture)continue;alive.add(building.id);const tint=spriteCountryTint(this.colors.get(building.ownerId)??0xffffff),existing=this.buildingArt.get(building.id);if(existing){if(existing.sprite.texture!==texture)existing.sprite.texture=texture;existing.sprite.tint=tint;existing.underConstruction=!!building.construction;existing.sprite.alpha=building.construction?.45:1;this.drawStrategicFootprint(existing,building);continue;}
  const points=building.cellIds.flatMap(id=>hexCorners(this.map!.cells[id],this.map!.layout.radius)),xs=points.filter((_,i)=>i%2===0),ys=points.filter((_,i)=>i%2===1),bounds={left:Math.min(...xs),right:Math.max(...xs),top:Math.min(...ys),bottom:Math.max(...ys)},x=(bounds.left+bounds.right)/2,y=(bounds.top+bounds.bottom)/2,root=new Container(),sprite=new Sprite(texture),mask=new Graphics();root.position.set(x,y);sprite.anchor.set(.5);sprite.tint=tint;sprite.alpha=building.construction?.45:1;
  if(building.type==='city'){sprite.width=bounds.right-bounds.left;sprite.height=bounds.bottom-bounds.top;}else{
   // Rotate around the footprint's anchor; asymmetric footprints need an offset
   // because their bounding-box center shifts when rotated.
   const radius=this.map.layout.radius,base=BUILDINGS[building.type].footprint.flatMap(([q,r])=>hexCorners({x:radius*Math.sqrt(3)*(q+r/2),y:radius*1.5*r},radius)),baseX=base.filter((_,i)=>i%2===0),baseY=base.filter((_,i)=>i%2===1),left=Math.min(...baseX),right=Math.max(...baseX),top=Math.min(...baseY),bottom=Math.max(...baseY),cx=(left+right)/2,cy=(top+bottom)/2,angle=this.buildingAngle(building),anchor=this.map.cells[building.anchorId];sprite.width=right-left;sprite.height=bottom-top;sprite.rotation=angle;sprite.position.set(anchor.x+cx*Math.cos(angle)-cy*Math.sin(angle)-x,anchor.y+cx*Math.sin(angle)+cy*Math.cos(angle)-y);
  }
  for(const id of building.cellIds)mask.poly(hexCorners(this.map.cells[id],this.map.layout.radius).map((v,i)=>v-(i%2?y:x)));mask.fill(0xffffff);const surroundings=new Graphics(),strategic=new Graphics(),symbol=new Graphics();drawStructureSurroundings(surroundings,building.type,bounds.right-bounds.left,bounds.bottom-bounds.top);root.addChild(surroundings,sprite,mask,strategic,symbol);sprite.mask=mask;this.buildingLayer.addChild(root);const art={underConstruction:!!building.construction,root,sprite,surroundings,strategic,symbol,bounds};this.buildingArt.set(building.id,art);this.drawStrategicFootprint(art,building);
 }for(const [id,art]of this.buildingArt)if(!alive.has(id)){art.root.destroy({children:true});this.buildingArt.delete(id);}}

 private drawStrategicFootprint(art:BuildingArt,building:Building){if(!this.map)return;const g=art.strategic,color=this.colors.get(building.ownerId)??0xffffff;g.clear();for(const id of building.cellIds)g.poly(hexCorners(this.map.cells[id],this.map.layout.radius).map((v,i)=>v-(i%2?art.root.y:art.root.x)));g.fill({color,alpha:building.construction?.55:.95});art.symbol.clear();drawBuildingIcon(art.symbol,building.type,0,0,7,0xf2f0df);}
 setLens(lens:MapLens){if(this.lens===lens)return;this.lens=lens;this.lensRevision=-1;}
 private updateLens(){const state=this.state,map=this.map;if(!state||!map){this.tacticalLens.clear();return;}
  const diplomacyChanged=this.paintDiplomacyRevision!==state.diplomacy.revision;
  if(diplomacyChanged){this.diplomacyColors=new Map([[1,0x75b9cd]]);for(const p of state.players){if(p.id===1)continue;const relation=state.diplomacy.relations.find(r=>(r.a===1&&r.b===p.id)||(r.b===1&&r.a===p.id));this.diplomacyColors.set(p.id,state.combatOpponents.includes(p.id)||relation?.state==='WAR'?0xdd7668:relation?.state==='ALLIED'?0x8ebd79:relation?.state==='TENSION'&&relation.preparedBy!==null?0xdfb66a:0x969789);}}
  if(this.paintLens!==this.lens||this.lens==='diplomacy'&&diplomacyChanged)for(let i=0;i<this.chunks.length;i++)this.rebuild(i);
  this.paintLens=this.lens;this.paintDiplomacyRevision=state.diplomacy.revision;this.tacticalLens.visible=this.lens==='threats';if(!this.tacticalLens.visible)return;
  if(this.lensRevision===state.diplomacy.revision&&this.lensBuildingRevision===state.buildingRevision)return;this.lensRevision=state.diplomacy.revision;this.lensBuildingRevision=state.buildingRevision;const g=this.tacticalLens;g.clear();
  for(const building of state.buildings){if(building.type!=='defense'||building.construction)continue;const color=this.diplomacyColors.get(building.ownerId)??0x969789,cell=map.cells[building.anchorId];g.circle(cell.x,cell.y,COMBAT.defenseRange).fill({color,alpha:.1}).stroke({color,alpha:.55,width:2});}
 }

 private buildingAngle(building:Building){if(building.type==='bridge'&&this.map){const banks=bridgeBanks(this.map,building.anchorId);if(banks){const a=this.map.cells[banks[0]],b=this.map.cells[banks[1]];return Math.atan2(b.y-a.y,b.x-a.x);}}return building.rotation*Math.PI/3;}
 private syncSiloArt(state:MatchState){for(const building of state.buildings){if(building.type!=='silo')continue;const art=this.buildingArt.get(building.id),texture=this.textures.get(buildingArtKey(building));if(art&&texture&&art.sprite.texture!==texture)art.sprite.texture=texture;}}

 setMap(map:ProceduralMap){for(const child of this.root.removeChildren())child.destroy({children:true});this.buildingArt.clear();this.buildingsByCell.clear();this.hoverCell=this.hoverBuilding=-1;this.buildingLayer=new Container();this.map=map;this.state=null;this.buildingRevision=-1;this.siegeRevision=-1;this.chunks=[];this.colors.clear();this.byCell=new Int32Array(map.cells.length);const {columns,rows,radius}=map.layout;for(let r=0;r<rows;r+=16)for(let c=0;c<columns;c+=16){const ids:number[]=[];for(let y=r;y<Math.min(rows,r+16);y++)for(let x=c;x<Math.min(columns,c+16);x++){const id=y*columns+x;ids.push(id);this.byCell[id]=this.chunks.length;}const graphics=new Graphics();this.root.addChild(graphics);this.chunks.push({graphics,ids,left:Math.min(...ids.map(id=>map.cells[id].x))-radius,right:Math.max(...ids.map(id=>map.cells[id].x))+radius,top:Math.min(...ids.map(id=>map.cells[id].y))-radius,bottom:Math.max(...ids.map(id=>map.cells[id].y))+radius});}this.previews=new Graphics();this.cities=new Graphics();this.expedition=new Graphics();this.target=new Graphics();this.health=new Graphics();this.sieges=new Graphics();this.hovered=new Graphics();this.cancelOutline=new Graphics();this.missileAreas=new Graphics();this.tacticalLens=new Graphics();this.lensRevision=this.lensBuildingRevision=this.paintDiplomacyRevision=-1;this.paintLens='countries';this.root.addChild(this.tacticalLens,this.cancelOutline,this.missileAreas,this.previews,this.buildingLayer,this.cities,this.hovered,this.target,this.expedition,this.health,this.sieges);}
 buildingAt(cellId:number){return this.buildingsByCell.get(cellId);}
 highlight(cellId:number){this.hoverCell=cellId;const building=this.buildingAt(cellId),id=building?.id??-1;if(id===this.hoverBuilding)return;this.hoverBuilding=id;this.hovered.clear();if(!building||!this.map)return;const occupied=new Int16Array(this.map.cells.length);for(const cell of building.cellIds)occupied[cell]=building.ownerId;for(const e of structureEdges(this.map,building.cellIds,building.ownerId,occupied))this.hovered.moveTo(e[0],e[1]).lineTo(e[2],e[3]);this.hovered.stroke({color:0xf4edc9,width:2.5,alpha:.95});}
 private rebuild(index:number){if(this.map)drawOwnershipChunk(this.chunks[index].graphics,this.map,this.chunks[index].ids,this.lens==='diplomacy'?this.diplomacyColors:this.colors,this.lens==='diplomacy'?.32:.19);}
 updateState(state:MatchState,changes:OwnershipChange[]){this.state=state;if(!this.map)return;this.colors=new Map(state.players.map(p=>[p.id,p.color]));const dirty=new Set<number>();for(const change of changes){this.map.cells[change.cellId].ownerId=change.ownerId;dirty.add(this.byCell[change.cellId]);for(const n of this.map.cells[change.cellId].neighbors)dirty.add(this.byCell[n]);}for(const index of dirty)this.rebuild(index);if(this.buildingRevision!==state.buildingRevision){this.buildingRevision=state.buildingRevision;this.cities.clear();this.buildingsByCell.clear();for(const b of state.buildings)for(const id of b.cellIds)this.buildingsByCell.set(id,b);this.hoverBuilding=-2;this.highlight(this.hoverCell);this.syncBuildingArt(state);// Persistent outlines belong only to country borders; structure outlines appear on hover.
 for(const building of state.buildings){if(this.textures.has(building.type))continue;const cell=this.map.cells[building.anchorId],color=this.colors.get(building.ownerId)??0xffffff;this.cities.beginPath();for(const id of building.cellIds)this.cities.poly(hexCorners(this.map.cells[id],this.map.layout.radius));this.cities.fill({color,alpha:.8});if(building.type==='bridge'){const banks=bridgeBanks(this.map,cell.id);if(banks){const a=this.map.cells[banks[0]],b=this.map.cells[banks[1]],length=Math.hypot(b.x-a.x,b.y-a.y),dx=(b.x-a.x)/length,dy=(b.y-a.y)/length,r=this.map.layout.radius;this.cities.moveTo(cell.x-dx*r,cell.y-dy*r).lineTo(cell.x+dx*r,cell.y+dy*r).stroke({color:0xe3d5ad,width:r*.65});for(let t=-.8;t<=.8;t+=.3){const x=cell.x+dx*r*t,y=cell.y+dy*r*t;this.cities.moveTo(x-dy*r*.3,y+dx*r*.3).lineTo(x+dy*r*.3,y-dx*r*.3);}this.cities.stroke({color:0x31312b,width:Math.max(.8,r*.06)});}}else drawBuildingIcon(this.cities,building.type,cell.x,cell.y,this.map.layout.radius*.55,color);}}this.syncSiloArt(state);if(this.siegeRevision!==state.siegeRevision){this.siegeRevision=state.siegeRevision;this.sieges.clear();for(const p of state.encirclements){for(const id of p.cellIds)this.sieges.poly(hexCorners(this.map.cells[id],this.map.layout.radius*.83));this.sieges.fill({color:p.ownerId===1?0xe58e8e:0xd8b766,alpha:.2}).stroke({color:p.ownerId===1?0xe58e8e:0xd8b766,width:2,alpha:.7});}}if(state.phase==='playing')this.previews.clear();this.drawExpedition(1);}
 preparation(spawns:SpawnCandidate[],selectedId:number){if(!this.map)return;this.previews.clear();for(const spawn of spawns){const color=spawn.id===selectedId?0xf4edc9:0x91b9a0;for(const id of spawn.cellIds)this.previews.poly(hexCorners(this.map.cells[id],this.map.layout.radius*.95));this.previews.fill({color,alpha:spawn.id===selectedId?.22:.09});const center=this.map.cells[spawn.anchorId];this.previews.circle(center.x,center.y,this.map.layout.radius*.65).stroke({color,width:spawn.id===selectedId?3:2});this.previews.moveTo(center.x-7,center.y).lineTo(center.x+7,center.y).moveTo(center.x,center.y-7).lineTo(center.x,center.y+7).stroke({color,width:2});}}
 drawExpedition(zoom:number){this.expedition.clear();this.target.clear();const e=this.state?.expedition;if(!e)return;const size=Math.max(this.map!.layout.radius*.18,4/zoom);this.expedition.poly([e.x+size,e.y,e.x-size,e.y-size*.75,e.x-size*.6,e.y,e.x-size,e.y+size*.75]).fill(0xf4edc9).stroke({color:0x212121,width:1/zoom});if(e.moving){this.target.moveTo(e.x,e.y).lineTo(e.targetX,e.targetY).stroke({color:0xf4edc9,alpha:.25,width:1/zoom});this.target.circle(e.targetX,e.targetY,5/zoom).stroke({color:0xf4edc9,alpha:.8,width:1/zoom});}}
 update(camera:Camera){const b=camera.bounds(),lod=visualLod(this.map?.layout.radius??20,camera.zoom,this.visualMode);for(const chunk of this.chunks)chunk.graphics.visible=inView(chunk,b);const occupiedSymbols=new Set<string>();for(const art of this.buildingArt.values()){art.root.visible=inView(art.bounds,b,12/camera.zoom);art.sprite.visible=lod.building>0;art.sprite.alpha=lod.building*(art.underConstruction?.45:1);art.surroundings.visible=lod.decoration>0;art.surroundings.alpha=lod.decoration;art.strategic.visible=lod.icons>0;const symbolKey=Math.floor(art.root.x*camera.zoom/20)+':'+Math.floor(art.root.y*camera.zoom/20);art.symbol.visible=lod.icons>0&&art.root.visible&&!occupiedSymbols.has(symbolKey);if(art.symbol.visible)occupiedSymbols.add(symbolKey);art.strategic.alpha=art.symbol.alpha=lod.icons;art.symbol.scale.set(Math.max(.8,1/camera.zoom));}this.updateLens();this.drawExpedition(camera.zoom);this.health.clear();this.cancelOutline.clear();this.missileAreas.clear();if(this.state&&this.map){if(this.cancelling)for(const work of this.state.buildings.filter(b=>b.ownerId===1&&b.construction)){for(const id of work.cellIds)this.cancelOutline.poly(hexCorners(this.map.cells[id],this.map.layout.radius*.94));this.cancelOutline.stroke({color:0xd8b766,width:2,alpha:.9});}for(const impact of this.state.operations?.missiles??[]){const center=this.map.cells[impact.anchorId];this.missileAreas.circle(center.x,center.y,this.map.layout.radius*(impact.radius*1.75+1)).stroke({color:0xff765b,width:3,alpha:.7});this.missileAreas.circle(center.x,center.y,12).stroke({color:0xff765b,width:2});}}if(this.state&&this.map)for(const building of this.state.buildings){const artBounds=this.buildingArt.get(building.id)?.bounds,anchor=this.map.cells[building.anchorId];if(!inView(artBounds??{left:anchor.x,right:anchor.x,top:anchor.y,bottom:anchor.y},b,40/camera.zoom))continue;if(building.type==='silo'&&building.missile&&building.missile.elapsed>=building.missile.duration)this.health.circle(anchor.x+8/camera.zoom,anchor.y-8/camera.zoom,3/camera.zoom).fill(0xf3d58c).stroke({color:0x212121,width:1/camera.zoom});if(building.construction){const c=this.map.cells[building.anchorId],w=36/camera.zoom,y=c.y-this.map.layout.radius;this.health.rect(c.x-w/2,y,w,4/camera.zoom).fill(0x202020).rect(c.x-w/2,y,w*building.construction.elapsed/building.construction.duration,4/camera.zoom).fill(0xd8b766);}if(building.hp>=building.maxHp)continue;const c=this.map.cells[building.anchorId],art=this.buildingArt.get(building.id),x=art?(art.bounds.left+art.bounds.right)/2:c.x,w=32/camera.zoom,y=art?art.bounds.top-6/camera.zoom:c.y-this.map.layout.radius*.75;this.health.rect(x-w/2,y,w,3/camera.zoom).fill(0x202020).rect(x-w/2,y,w*building.hp/building.maxHp,3/camera.zoom).fill(building.ownerId===1?0x82c9a0:0xd77f7f);}}
}
