import {groupUnitMarkers} from './unit-groups';
import {RenderUnitIndex} from './unit-index';
import type {ArmyRoute} from '../../../packages/shared/configs/training';
import {Container,Graphics,Particle,ParticleContainer,type Application,type Texture} from 'pixi.js';
import {TEAM_COLORS} from '../../../packages/shared/configs/engine';
import {UNIT_STRIDE,UNIT_STATE,UNITS,UNIT_KIND} from '../../../packages/shared/configs/units';
import type {Camera} from '../input/camera';
export function unitShape(tank:boolean){const g=new Graphics();if(tank)g.roundRect(-10,-7,19,14,2).fill(0xffffff).rect(-7,-10,15,3).rect(-7,7,15,3).fill(0xbfc8c0).circle(0,0,4).fill(0xc7d3c8).rect(0,-2,17,4).fill(0xffffff);else g.poly([-6,-7,10,0,-6,7,-2,0]).fill(0xffffff).circle(-8,0,3).fill(0xd7e4da);return g;}
function specialShape(kind:number){
 const g=new Graphics();
 if(kind===2)g.poly([19,0,5,-4,-3,-18,-8,-18,-5,-4,-14,-3,-19,-9,-22,-9,-19,0,-22,9,-19,9,-14,3,-5,4,-8,18,-3,18,5,4]).fill(0xffffff).rect(-6,-2,12,4).fill(0x7e9789);
 else if(kind===3){
  // Broad landing barge: flat bow, open deck and boarding ramp.
  g.poly([-22,-8,-15,-12,22,-12,26,-8,26,8,22,12,-15,12,-22,8]).fill(0xffffff);
  g.rect(-12,-8,30,16).fill(0x5b7062).rect(-19,-6,7,12).fill(0xc1cdc3);
  g.rect(17,-8,9,16).fill(0xd8e2d8);
  g.moveTo(20,-7).lineTo(20,7).moveTo(23,-7).lineTo(23,7).stroke({color:0x536558,width:1.5});
  g.poly([-7,-5,4,-5,4,1,-1.5,6,-7,1]).fill(0xffffff);
 }
 else{
  // Narrow freighter: pointed bow, aft bridge and three cargo containers.
  g.poly([-28,-6,-22,-9,19,-9,32,0,19,9,-22,9,-28,6]).fill(0xd5dfd5);
  g.rect(-22,-7,43,14).fill(0x57675c);
  g.rect(-23,-6,8,12).fill(0xffffff).rect(-21,-4,4,8).fill(0x879a8b);
  g.rect(-12,-6,9,12).fill(0xffffff).rect(-1,-6,9,12).fill(0xaabb9e).rect(10,-6,9,12).fill(0xe0e6ca);
  g.moveTo(-9,-5).lineTo(-9,5).moveTo(2,-5).lineTo(2,5).moveTo(13,-5).lineTo(13,5).stroke({color:0x687763,width:1});
 }
 return g;
}
function navalMarker(kind:number){const g=new Graphics();if(kind===3)g.poly([-3,-3,3,-3,3,1,0,4,-3,1]).fill(0xffffff);else g.poly([-5,0,-3,-2,3,-2,5,0,3,2,-3,2]).fill(0xffffff);return g;}
interface RenderUnit{particle:Particle;kind:number;shot:number;flash:number;onscreen:boolean;frame:number;}
export class UnitRenderer {
 readonly spatial=new RenderUnitIndex();private alive=new Set<number>();private frame=0;private onscreenIds:number[]=[];private nextOnscreenIds:number[]=[];
 forceStrategic=false;private groups=new Graphics();private groupRefresh=0;private groupView='';
 colors=new Map<number,number>();routePlans:ArmyRoute[]=[];visible=0;details=0;lod='Detalhado';private pool:Particle[][]=[[],[],[],[],[]];private dot!:Texture;readonly root=new Container();readonly selection=new Set<number>();data:Float32Array=new Float32Array(0);showRange=false;enemies=new Set<number>();allies=new Set<number>();buildingTargets=new Map<number,{x:number;y:number}>();
 private positions=new Map<number,{x:number;y:number}>();private previous=new Map<number,{x:number;y:number}>();private receivedAt=0;private interval=50;private particles=new Map<number,RenderUnit>();private layers:ParticleContainer[]=[];private textures:Texture[]=[];private navalMarkers:Partial<Record<number,Texture>>={};private overlay=new Graphics();
 init(app:Application){for(let kind=0;kind<5;kind++){const shape=kind<2?unitShape(!!kind):specialShape(kind);this.textures.push(app.renderer.generateTexture(shape));shape.destroy();if(kind>=3){const marker=navalMarker(kind);this.navalMarkers[kind]=app.renderer.generateTexture(marker);marker.destroy();}const layer=new ParticleContainer({dynamicProperties:{position:true,rotation:true,color:true,vertex:true,uvs:true}});this.layers.push(layer);this.root.addChild(layer);}const dot=new Graphics().rect(-2,-2,4,4).fill(0xffffff);this.dot=app.renderer.generateTexture(dot);dot.destroy();this.root.addChild(this.groups,this.overlay);}
 received(data:Float32Array){this.data=data;const alive=this.alive;alive.clear();for(let k=0;k<data.length;k+=UNIT_STRIDE){const id=data[k];alive.add(id);let current=this.positions.get(id),previous=this.previous.get(id);if(!previous){previous={x:data[k+1],y:data[k+2]};this.previous.set(id,previous);}previous.x=current?.x??data[k+1];previous.y=current?.y??data[k+2];if(!current){current={x:data[k+1],y:data[k+2]};this.positions.set(id,current);}current.x=data[k+1];current.y=data[k+2];}this.spatial.rebuild(data,this.previous);this.interval=Math.max(1,performance.now()-this.receivedAt);this.receivedAt=performance.now();for(const id of this.positions.keys())if(!alive.has(id)){this.positions.delete(id);this.previous.delete(id);}for(const [id,unit]of this.particles)if(!alive.has(id)){if(unit.onscreen)this.layers[unit.kind].removeParticle(unit.particle);if(this.pool[unit.kind].length<256)this.pool[unit.kind].push(unit.particle);this.particles.delete(id);}for(const id of this.selection)if(!alive.has(id))this.selection.delete(id);}
 draw(camera:Camera){const now=performance.now(),alpha=Math.min(1,(now-this.receivedAt)/this.interval),bounds=camera.bounds(),positions=this.positions;this.overlay.clear();this.visible=0;this.details=0;const small=this.forceStrategic||camera.zoom<.35,grouped=camera.zoom<.14||(this.forceStrategic&&camera.zoom<.35);this.groups.visible=grouped;if(grouped)this.drawGroups(camera,now);this.lod=grouped?'Grupos':small?'Pontos':'Detalhado';let ranges=0;this.frame++;this.nextOnscreenIds.length=0;let selectedLeft=Infinity,selectedRight=-Infinity,selectedTop=Infinity,selectedBottom=-Infinity;const collective=this.selection.size>80;
 for(const k of this.spatial.query({left:bounds.left-40,right:bounds.right+40,top:bounds.top-40,bottom:bounds.bottom+40})){const d=this.data,id=d[k],prev=this.previous.get(id),x=prev?prev.x+(d[k+1]-prev.x)*alpha:d[k+1],y=prev?prev.y+(d[k+2]-prev.y)*alpha:d[k+2],visible=x>bounds.left-40&&x<bounds.right+40&&y>bounds.top-40&&y<bounds.bottom+40;let unit=this.particles.get(id);if(!visible){if(unit?.onscreen){this.layers[unit.kind].removeParticle(unit.particle);unit.onscreen=false;}continue;}this.visible++;if(grouped&&!this.selection.has(id))continue;this.nextOnscreenIds.push(id);if(!unit){const particle=this.pool[d[k+4]].pop()??new Particle({texture:this.textures[d[k+4]],anchorX:.5,anchorY:.5});unit={particle,kind:d[k+4],shot:d[k+14],flash:0,onscreen:false,frame:0};this.particles.set(id,unit);}if(!unit.onscreen){this.layers[unit.kind].addParticle(unit.particle);unit.onscreen=true;}unit.frame=this.frame;if(unit.shot!==d[k+14]){unit.shot=d[k+14];unit.flash=now+120;}const p=unit.particle;p.x=x;p.y=y;p.rotation=small?0:d[k+3];p.texture=small?(this.navalMarkers[unit.kind]??this.dot):this.textures[unit.kind];p.tint=unit.flash>now?0xffffff:(this.colors.get(d[k+5])??TEAM_COLORS[d[k+5]-1]);p.scaleX=p.scaleY=small?Math.max(1,.7/camera.zoom):Math.max(1,.8/camera.zoom);
 const selected=this.selection.has(id),detailSelected=selected&&!collective,enemy=this.enemies.has(d[k+5]),foreign=d[k+5]!==1,ally=this.allies.has(d[k+5]);
 if(selected&&collective){selectedLeft=Math.min(selectedLeft,x);selectedRight=Math.max(selectedRight,x);selectedTop=Math.min(selectedTop,y);selectedBottom=Math.max(selectedBottom,y);}
 if(detailSelected||foreign&&!small&&this.details++<200)this.overlay.circle(x,y,Math.max(d[k+4]?17:13,7/camera.zoom)).stroke({color:enemy?0xe58e8e:ally?0x72acd2:foreign?0xbababa:0xe9f9b0,width:1.5/camera.zoom,alpha:enemy?.7:1});
 if((detailSelected||!small&&(d[k+9]<d[k+10]||enemy)&&this.details++<200)&&camera.zoom>.22){const w=Math.max(24,22/camera.zoom),h=3/camera.zoom,top=y-21/camera.zoom;this.overlay.rect(x-w/2,top,w,h).fill(0x202020).rect(x-w/2,top,w*Math.max(0,d[k+9]/d[k+10]),h).fill(enemy?0xd77f7f:d[k+11]===UNIT_STATE.recover?0x72acd2:0x82c9a0);}
 if(detailSelected&&d[k+15]<99){const w=22/camera.zoom,top=y-16/camera.zoom;this.overlay.rect(x-w/2,top,w,2/camera.zoom).fill(0x202020).rect(x-w/2,top,w*d[k+15]/100,2/camera.zoom).fill(d[k+15]<=20?0xe58e8e:0xd8b766);}
 if(selected&&this.showRange&&ranges++<20)this.overlay.circle(x,y,UNITS[UNIT_KIND[d[k+4]]].range).stroke({color:0xe9f9b0,width:1/camera.zoom,alpha:.3});
 if(selected&&d[k+6]&&this.selection.size<=20){this.overlay.moveTo(x,y).lineTo(d[k+7],d[k+8]).stroke({color:d[k+11]===UNIT_STATE.retreat?0x72acd2:0xe9f9b0,width:1/camera.zoom,alpha:.3});this.overlay.circle(d[k+7],d[k+8],4/camera.zoom).stroke({color:0xe9f9b0,width:1/camera.zoom});}
 if(!small&&unit.flash>now&&d[k+12]&&this.details++<200){const target=d[k+12]>0?positions.get(d[k+12]):this.buildingTargets.get(-d[k+12]);if(target)this.overlay.moveTo(x,y).lineTo(target.x,target.y).stroke({color:0xf6d891,width:1.5/camera.zoom,alpha:.85});}}
 for(const id of this.onscreenIds){const unit=this.particles.get(id);if(unit?.onscreen&&unit.frame!==this.frame){this.layers[unit.kind].removeParticle(unit.particle);unit.onscreen=false;}}const old=this.onscreenIds;this.onscreenIds=this.nextOnscreenIds;this.nextOnscreenIds=old;if(collective&&selectedLeft!==Infinity){const pad=14/camera.zoom;this.overlay.rect(selectedLeft-pad,selectedTop-pad,selectedRight-selectedLeft+pad*2,selectedBottom-selectedTop+pad*2).stroke({color:0xe9f9b0,width:1.5/camera.zoom,alpha:.8});}
 let plans=0;for(const route of this.routePlans){if(collective||plans>=20)break;if(!route.unitIds.some(id=>this.selection.has(id)))continue;const first=route.unitIds.map(id=>positions.get(id)).find(Boolean);if(!first)continue;plans++;this.overlay.moveTo(first.x,first.y);for(const point of route.points)this.overlay.lineTo(point.x,point.y);this.overlay.stroke({color:0xe9f9b0,width:1.5/camera.zoom,alpha:.65});for(const point of route.points)this.overlay.circle(point.x,point.y,5/camera.zoom).stroke({color:0xe9f9b0,width:1.5/camera.zoom});}
 }
 private drawGroups(camera:Camera,now:number){const view=[camera.x,camera.y,camera.zoom,this.selection.size].join(':');if(now-this.groupRefresh<120&&this.groupView===view)return;this.groupRefresh=now;this.groupView=view;const bounds=camera.bounds(),markers=groupUnitMarkers(this.data,this.spatial.query(bounds),this.selection,camera.zoom),g=this.groups;g.clear();for(const [owner,color]of this.colors){const owned=markers.filter(m=>m.owner===owner);if(!owned.length)continue;g.beginPath();for(const marker of owned){const s=(2.3+Math.min(2.5,Math.log2(marker.count+1)*.5))/camera.zoom;if(marker.kind===1)g.rect(marker.x-s,marker.y-s,s*2,s*2);else if(marker.kind===2)g.poly([marker.x,marker.y-s*1.3,marker.x+s,marker.y+s,marker.x-s,marker.y+s]);else if(marker.kind===3)g.poly([marker.x-s,marker.y-s,marker.x+s,marker.y-s,marker.x+s,marker.y+s*.35,marker.x,marker.y+s*1.3,marker.x-s,marker.y+s*.35]);else if(marker.kind===4)g.poly([marker.x-s*1.6,marker.y,marker.x-s,marker.y-s*.65,marker.x+s,marker.y-s*.65,marker.x+s*1.6,marker.y,marker.x+s,marker.y+s*.65,marker.x-s,marker.y+s*.65]);else g.circle(marker.x,marker.y,s);}g.fill(color).stroke({color:0x182520,width:.6/camera.zoom,alpha:.8});}}
 hit(x:number,y:number,zoom:number,ownOnly=true){let id=0,best=Math.max(20,11/zoom);for(const k of this.spatial.query({left:x-best,right:x+best,top:y-best,bottom:y+best})){if(ownOnly&&this.data[k+5]!==1)continue;const distance=Math.hypot(this.data[k+1]-x,this.data[k+2]-y);if(distance<best){best=distance;id=this.data[k];}}return id;}
}
