import { ENGINE } from '../../../packages/shared/configs/engine';
export class Camera {
 canPan:(event:PointerEvent)=>boolean=()=>true;
 x=ENGINE.worldWidth/2;y=ENGINE.worldHeight/2;zoom=.35;width=1;height=1;private keys=new Set<string>();private pointers=new Map<number,{x:number;y:number}>();private pinchDistance=0;
 constructor(private canvas:HTMLCanvasElement){canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('wheel',e=>{e.preventDefault();this.zoomAt(Math.exp(-e.deltaY*.0015),e.offsetX,e.offsetY);},{passive:false});canvas.addEventListener('pointerdown',e=>{if(!this.canPan(e))return;this.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});canvas.setPointerCapture(e.pointerId);canvas.classList.add('dragging');this.pinchDistance=this.distance();});canvas.addEventListener('pointermove',e=>{const p=this.pointers.get(e.pointerId);if(!p)return;const dx=e.clientX-p.x,dy=e.clientY-p.y;this.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(this.pointers.size===2){const d=this.distance();if(this.pinchDistance>0)this.zoomAt(d/this.pinchDistance,this.width/2,this.height/2);this.pinchDistance=d;}else {this.x-=dx/this.zoom;this.y-=dy/this.zoom;this.clamp();}});const release=(e:PointerEvent)=>{this.pointers.delete(e.pointerId);this.pinchDistance=this.distance();if(!this.pointers.size)canvas.classList.remove('dragging');};canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);
 window.addEventListener('keydown',e=>{if(this.isControl(e.target)||document.querySelector('dialog[open]'))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d','W','A','S','D'].includes(e.key)){e.preventDefault();this.keys.add(e.key.toLowerCase());}if(e.key==='Home'){e.preventDefault();this.fit();}});window.addEventListener('keyup',e=>this.keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>this.keys.clear());}
 private isControl(target:EventTarget|null){return target instanceof HTMLElement&&['INPUT','TEXTAREA','SELECT'].includes(target.tagName);}
 private distance(){const p=[...this.pointers.values()];return p.length===2?Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y):0;}
 resize(w:number,h:number){this.width=w;this.height=h;this.clamp();}
 fit(){this.x=ENGINE.worldWidth/2;this.y=ENGINE.worldHeight/2;this.zoom=Math.max(.06,Math.min((this.width-80)/ENGINE.worldWidth,(this.height-160)/ENGINE.worldHeight));this.clamp();}
 zoomAt(factor:number,sx=this.width/2,sy=this.height/2){const before=this.screenToWorld(sx,sy);this.zoom=Math.max(.06,Math.min(8,this.zoom*factor));const after=this.screenToWorld(sx,sy);this.x+=before.x-after.x;this.y+=before.y-after.y;this.clamp();}
 update(dt:number){const speed=700*dt/this.zoom;this.x+=((this.keys.has('d')||this.keys.has('arrowright')?1:0)-(this.keys.has('a')||this.keys.has('arrowleft')?1:0))*speed;this.y+=((this.keys.has('s')||this.keys.has('arrowdown')?1:0)-(this.keys.has('w')||this.keys.has('arrowup')?1:0))*speed;this.clamp();}
 clamp(){this.x=Math.max(0,Math.min(ENGINE.worldWidth,this.x));this.y=Math.max(0,Math.min(ENGINE.worldHeight,this.y));}
 screenToWorld(x:number,y:number){return {x:this.x+(x-this.width/2)/this.zoom,y:this.y+(y-this.height/2)/this.zoom};}
 bounds(){return {left:this.x-this.width/(2*this.zoom),top:this.y-this.height/(2*this.zoom),right:this.x+this.width/(2*this.zoom),bottom:this.y+this.height/(2*this.zoom)};}
}
