import {isWalkable} from '../../map/bridges';
import {MILITARY_CONFIG} from '../../shared/configs/combat';
import {RESOURCE_KEYS} from '../../shared/configs/buildings';
import {SocialSystem} from '../diplomacy/social';
import {assignCountries} from '../../shared/configs/countries';
import type {BotDifficulty} from '../../shared/configs/bots';
import {VICTORY,createVictory} from '../../shared/configs/victory';
import {DiplomacySystem,createDiplomacy} from '../diplomacy/system';
import {EconomySystem} from '../economy/economy';
import {ECONOMY_RULES,type BuildingType} from '../../shared/configs/buildings';
import type {ProceduralMap} from '../../map/types';
import {cellAtWorld,hexDistance} from '../../map/hex/coordinates';
import {ENGINE} from '../../shared/configs/engine';
import {TERRITORY_RULES} from '../../shared/configs/territory';
import {findSpawns,spawnAt} from './spawns';
import type {MatchState,OwnershipChange} from './types';
export class TerritoryMatch {
 private preparationIdentity:{name:string;countryId:string;botCountryIds:string[]}|null=null;private preparationPool:import('./types').SpawnCandidate[]=[];
 readonly owned=new Map<number,Set<number>>();readonly dirtyCountries=new Set<number>();
 onDefeat:(playerId:number)=>void=()=>{};
 social:SocialSystem|null=null;diplomacy:DiplomacySystem|null=null;canOccupy:(actor:number,cellId:number)=>boolean=()=>true;economy:EconomySystem|null=null;private economyTime=0;state:MatchState;private changes:OwnershipChange[]=[];
 constructor(readonly map:ProceduralMap,count:number,botDifficulty:BotDifficulty='normal',holdSeconds=VICTORY.holdSeconds){if(!['off','easy','normal','hard'].includes(botDifficulty)||!Number.isFinite(holdSeconds)||holdSeconds<VICTORY.minHoldSeconds||holdSeconds>VICTORY.maxHoldSeconds)throw new Error('Configuração de partida inválida.');const spawns=findSpawns(map,count);this.state={phase:'preparation',bots:[],botDifficulty,victory:createVictory(holdSeconds),revision:0,playerCount:count,spawns,players:[],cities:[],expedition:null,landTotal:map.stats.land,captured:0,buildings:[],training:[],economies:[],buildingRevision:0,combatOpponents:[],skirmish:null,diplomacy:createDiplomacy(),borderRevision:0,siegeRevision:0,encirclements:[]};}
 beginPreparation(name:string,countryId:string,botCountryIds:string[]){
  if(this.state.phase!=='preparation'||this.state.preparation?.active)throw new Error('A preparação já começou.');
  assignCountries(this.state.playerCount,countryId,botCountryIds,this.map.config.seed);
  this.preparationIdentity={name,countryId,botCountryIds};this.preparationPool=[...this.state.spawns];
  const stride=Math.max(1,Math.floor(this.map.cells.length/1200));for(let id=0;id<this.map.cells.length;id+=stride){const spawn=spawnAt(this.map,id);if(spawn)this.preparationPool.push(spawn);}
  this.state.preparation={active:true,remaining:30,selectedAnchor:null,reservations:[]};this.state.revision++;
 }
 private available(spawn:import('./types').SpawnCandidate,playerId:number){return !this.state.preparation!.reservations.some(r=>r.playerId!==playerId&&(hexDistance(this.map.cells[r.spawn.anchorId],this.map.cells[spawn.anchorId])<10||r.spawn.cellIds.some(id=>spawn.cellIds.includes(id))));}
 selectTerrain(anchorId:number){
  const prep=this.state.preparation;if(this.state.phase!=='preparation'||!prep?.active)throw new Error('Inicie a preparação primeiro.');if(prep.reservations.some(r=>r.playerId===1))throw new Error('Seu terreno já foi confirmado.');
  const spawn=spawnAt(this.map,anchorId);if(!spawn)throw new Error('A cidade e o raio inicial de quatro hexágonos precisam caber inteiramente em terra.');if(!this.available(spawn,1))throw new Error('Esse terreno está perto demais de outro país.');
  prep.selectedAnchor=anchorId;prep.reservations.push({playerId:1,spawn});this.state.revision++;
 }
 advancePreparation(dt:number){
  const prep=this.state.preparation;if(!prep?.active)return null;prep.remaining=Math.max(0,prep.remaining-dt);
  for(let player=2;player<=this.state.playerCount;player++)if(!prep.reservations.some(r=>r.playerId===player)&&(30-prep.remaining>=5+(player-2)*2||prep.remaining===0)){
   const candidates=this.preparationPool.filter(s=>this.available(s,player));
   candidates.sort((a,b)=>{const score=(s:import('./types').SpawnCandidate)=>s.quality+Math.min(...prep.reservations.map(r=>hexDistance(this.map.cells[s.anchorId],this.map.cells[r.spawn.anchorId])),40);const spread=(s:import('./types').SpawnCandidate)=>this.map.config.landform==='continents'?prep.reservations.filter(r=>this.map.cells[r.spawn.anchorId].continentId===this.map.cells[s.anchorId].continentId).length*20:0;return score(b)-spread(b)-score(a)+spread(a);});
   if(candidates.length)prep.reservations.push({playerId:player,spawn:candidates[(player*13)%Math.min(8,candidates.length)]});
  }
  if(prep.remaining===0&&!prep.reservations.some(r=>r.playerId===1)){const spawn=this.preparationPool.find(s=>this.available(s,1));if(spawn){prep.selectedAnchor=spawn.anchorId;prep.reservations.push({playerId:1,spawn});}}
  this.state.revision++;
  if(prep.reservations.length===this.state.playerCount)return {...this.preparationIdentity!,spawnId:prep.reservations.find(r=>r.playerId===1)!.spawn.id};
  return null;
 }
 start(spawnId:number,name:string,countryId?:string,botCountryIds?:string[]){if(this.state.phase!=='preparation')throw new Error('A partida já começou.');const prepared=this.state.preparation?.active?this.state.preparation.reservations.slice().sort((a,b)=>a.playerId-b.playerId).map(r=>r.spawn):null;if(prepared&&prepared.length!==this.state.playerCount)throw new Error('Aguarde as escolhas de terreno.');const selected=prepared?.[0]??this.state.spawns.find(s=>s.id===spawnId);if(!selected)throw new Error('Território inicial inválido.');if(typeof name!=='string'||!name.trim()||name.trim().length>32)throw new Error('O nome do país deve ter entre 1 e 32 caracteres.');const countries=assignCountries(this.state.playerCount,countryId??'br',botCountryIds,this.map.config.seed);const ordered=prepared??[selected,...this.state.spawns.filter(s=>s.id!==spawnId)];this.state.spawns=ordered;this.state.players=ordered.map((spawn,i)=>({id:i+1,name:countryId?countries[i].name:i===0?name.trim():countries[i].name,countryId:countries[i].id,color:countries[i].color,human:i===0,spawnId:spawn.id,territory:0,defeated:false,defeatedAt:null}));this.state.cities=ordered.map((spawn,i)=>({id:i+1,ownerId:i+1,anchorId:spawn.anchorId,cellIds:[...spawn.cityCells]}));for(let i=0;i<ordered.length;i++)for(const id of ordered[i].cellIds)this.claim(id,i+1);const center=this.map.cells[selected.anchorId];this.state.expedition={playerId:1,x:center.x,y:center.y,targetX:center.x,targetY:center.y,moving:false,status:'idle'};this.economy=new EconomySystem(this.map,this.state.cities,(a,b)=>a===b||!!this.diplomacy?.allied(a,b));this.state.buildings=this.economy.buildings;this.state.economies=this.economy.countries;this.state.buildingRevision++;if(this.state.preparation)this.state.preparation.active=false;this.state.phase='playing';this.social=new SocialSystem(this.state);this.diplomacy=new DiplomacySystem(this.state,this.social);this.state.revision++;}
 private claim(id:number,playerId:number,hostile=false){const cell=this.map.cells[id];if(!cell||cell.terrain!=='land'||cell.ownerId===playerId)return false;let destination=playerId;const old=cell.ownerId;if(old!==null){if(!hostile||!this.diplomacy)return false;const principal=this.diplomacy.captureOwner(playerId,old);if(principal===null)return false;destination=principal;const building=this.economy?.buildings.find(b=>b.id===this.economy!.occupied[id]);if(building&&building.ownerId===old)return false;if(!this.canOccupy(playerId,id))return false;}const player=this.state.players.find(p=>p.id===destination);if(!player||player.defeated)return false;cell.ownerId=destination;if(old!==null){this.owned.get(old)?.delete(id);this.dirtyCountries.add(old);}let cells=this.owned.get(destination);if(!cells){cells=new Set();this.owned.set(destination,cells);}cells.add(id);this.dirtyCountries.add(destination);for(const n of cell.neighbors){const owner=this.map.cells[n].ownerId;if(owner!==null)this.dirtyCountries.add(owner);}if(old===null)this.state.captured++;else this.state.players.find(p=>p.id===old)!.territory--;player.territory++;this.social?.capture(playerId,old);this.changes.push({cellId:id,ownerId:destination});this.state.borderRevision++;this.state.revision++;return true;}
 captureAtPosition(playerId:number,x:number,y:number,hostile=false){if(this.state.phase!=='playing'||!this.state.players.some(p=>p.id===playerId&&!p.defeated))return false;const cell=cellAtWorld(this.map,x,y);return cell?this.claim(cell.id,playerId,hostile):false;}
 captureCellInWar(actor:number,cellId:number){return this.state.phase==='playing'&&this.claim(cellId,actor,true);}
 move(playerId:number,x:number,y:number){const e=this.state.expedition;if(this.state.phase!=='playing'||!e||playerId!==e.playerId||this.state.players.find(p=>p.id===playerId)?.defeated)throw new Error('Expedição indisponível para esse jogador.');if(!Number.isFinite(x)||!Number.isFinite(y)||x<0||y<0||x>ENGINE.worldWidth||y>ENGINE.worldHeight)throw new Error('Destino fora do mapa.');const cell=cellAtWorld(this.map,x,y);if(!cell||cell.terrain==='water')throw new Error('Escolha um destino em terra.');e.targetX=x;e.targetY=y;e.moving=true;e.status='moving';this.state.revision++;}
 build(playerId:number,type:BuildingType,anchorId:number,rotation:number){if(this.state.phase!=='playing'||!this.economy||!this.state.players.some(p=>p.id===playerId&&!p.defeated))throw new Error('Construção indisponível para esse jogador.');const b=this.economy.build(playerId,type,anchorId,rotation);if(b.type==='city'&&!b.construction)this.state.cities.push({id:b.id,ownerId:b.ownerId,anchorId:b.anchorId,cellIds:[...b.cellIds]});this.state.buildingRevision++;this.state.revision++;}
 demolish(playerId:number,buildingId:number){if(!this.economy||!this.state.players.some(p=>p.id===playerId&&!p.defeated))throw new Error('Demolição indisponível para esse jogador.');this.economy.demolish(playerId,buildingId);this.state.cities=this.state.cities.filter(c=>c.id!==buildingId);this.state.buildingRevision++;this.state.revision++;}
 captureBuilding(actor:number,id:number){const b=this.state.buildings.find(b=>b.id===id);if(!b||b.construction||b.ownerId===actor||b.type==='defense'||b.type==='barracks')return false;const old=b.ownerId,owner=this.diplomacy!.captureOwner(actor,old);if(owner===null||b.cellIds.some(cell=>!this.canOccupy(actor,cell)))return false;
 b.ownerId=owner;if(b.type==='bridge'&&!b.construction)this.map.cells[b.anchorId].bridgeOwnerId=owner;for(const cell of b.cellIds)this.claim(cell,actor,true);const city=this.state.cities.find(c=>c.id===id);if(city)city.ownerId=owner;
 this.economy!.recalculate();this.social?.capture(owner,old,b.type==='city');this.state.buildingRevision++;this.state.revision++;if(b.type==='city'&&!this.state.buildings.some(v=>v.ownerId===old&&v.type==='city'&&!v.construction))this.surrenderCountry(old,owner);this.checkDefeats();return true;}
 surrender(actor:number,opponent:number){if(this.state.phase!=='playing'||!this.diplomacy?.hostile(actor,opponent))throw new Error('A rendição exige guerra ativa.');const owner=this.diplomacy.captureOwner(opponent,actor);if(owner===null)throw new Error('Adversário inválido.');this.surrenderCountry(actor,owner);this.diplomacy.event(this.diplomacy.name(actor)+' se rendeu a '+this.diplomacy.name(owner)+'.');this.checkDefeats();}
 private surrenderCountry(old:number,owner:number){for(const b of this.state.buildings)if(b.ownerId===old){b.ownerId=owner;if(b.construction)b.construction.ownerId=owner;if(b.type==='bridge'&&!b.construction)this.map.cells[b.anchorId].bridgeOwnerId=owner;}for(const city of this.state.cities)if(city.ownerId===old)city.ownerId=owner;for(const id of [...this.owned.get(old)??[]])this.claim(id,owner,true);const defeated=this.state.economies.find(c=>c.playerId===old)!,winner=this.state.economies.find(c=>c.playerId===owner)!;for(const k of RESOURCE_KEYS){winner.stock[k]+=defeated.stock[k]*MILITARY_CONFIG.surrenderStockFraction;defeated.stock[k]=0;}this.economy!.recalculate();this.state.buildingRevision++;}
 damageBuilding(id:number,damage:number){const b=this.state.buildings.find(b=>b.id===id);if(!b||damage<=0)return;b.hp=Math.max(0,b.hp-damage);if(b.hp<=0){this.economy!.destroy(id);this.state.cities=this.state.cities.filter(c=>c.id!==id);this.state.buildingRevision++;if(b.type==='city')this.checkDefeats();}this.state.revision++;}
 step(dt:number){this.checkDefeats();this.diplomacy?.step(dt);this.social?.step(dt);if(this.economy){this.economyTime+=dt;const interval=1/ECONOMY_RULES.tickRate;while(this.economyTime+1e-8>=interval){const revision=this.economy.constructionRevision;this.economy.step(interval);if(revision!==this.economy.constructionRevision){this.state.cities=this.state.buildings.filter(b=>b.city&&!b.construction).map(b=>({id:b.id,ownerId:b.ownerId,anchorId:b.anchorId,cellIds:[...b.cellIds]}));this.state.buildingRevision++;}this.economyTime-=interval;this.state.revision++;}}const e=this.state.expedition;if(!e?.moving)return;const dx=e.targetX-e.x,dy=e.targetY-e.y,distance=Math.hypot(dx,dy);if(distance<.001){e.moving=false;e.status='idle';this.state.revision++;return;}const travel=Math.min(distance,TERRITORY_RULES.expeditionSpeed*dt),segments=Math.max(1,Math.ceil(travel/(this.map.layout.radius*.2))),sx=dx/distance*travel/segments,sy=dy/distance*travel/segments;
 for(let s=0;s<segments;s++){const x=e.x+sx,y=e.y+sy,c=cellAtWorld(this.map,x,y);if(!c||!isWalkable(c)){e.moving=false;e.status='blocked';this.state.revision++;return;}e.x=x;e.y=y;this.captureAtPosition(e.playerId,x,y);}if(travel>=distance){e.x=e.targetX;e.y=e.targetY;e.moving=false;e.status='idle';}this.state.revision++;}
 checkDefeats(){if(this.state.phase!=='playing')return;for(const player of this.state.players){if(player.defeated||this.state.buildings.some(b=>b.ownerId===player.id&&b.type==='city'&&!b.construction))continue;player.defeated=true;player.defeatedAt=this.state.diplomacy.time;this.diplomacy?.eliminate(player.id);this.onDefeat(player.id);for(const b of [...this.state.buildings])if(b.ownerId===player.id)this.economy!.destroy(b.id);for(const id of this.owned.get(player.id)??[]){this.map.cells[id].ownerId=null;this.changes.push({cellId:id,ownerId:null});this.state.captured--;for(const n of this.map.cells[id].neighbors){const owner=this.map.cells[n].ownerId;if(owner!==null)this.dirtyCountries.add(owner);}}this.owned.delete(player.id);this.dirtyCountries.add(player.id);player.territory=0;this.state.encirclements=this.state.encirclements.filter(p=>p.ownerId!==player.id&&p.claimantId!==player.id);this.state.siegeRevision++;this.state.borderRevision++;this.state.buildingRevision++;if(this.state.expedition?.playerId===player.id)this.state.expedition.moving=false;this.state.revision++;}}
 drainChanges(){const changes=this.changes;this.changes=[];return changes;}
}
