import {CAPTURE_CONFIG,isMilitaryStructure} from '../../shared/configs/combat';
import {WAR_TERRITORY} from '../../shared/configs/diplomacy';
import {cellAtWorld} from '../../map/hex/coordinates';
import type {Army} from '../units/army';
import type {TerritoryMatch} from './match';
import type {Encirclement} from '../diplomacy/types';
export class WarTerritorySystem {
 private captures=new Map<number,{actor:number;time:number}>();private elapsed=0;private border=-1;private hostility='';private candidates:Encirclement[]=[];private timers=new Map<string,number>();readonly defenders:Uint16Array;private occupiedCells:number[]=[];private seen:Uint8Array;scans=0;
 constructor(private match:TerritoryMatch,private army:Army){this.defenders=new Uint16Array(match.map.cells.length);this.seen=new Uint8Array(match.map.cells.length);match.canOccupy=(actor,cellId)=>{const owner=match.map.cells[cellId].ownerId;if(owner===null)return true;return !match.state.players.some(p=>(this.defenders[cellId]&(1<<p.id))&&match.diplomacy!.hostile(actor,p.id));};}
 refreshOccupancy(){this.occupancy();}
 private occupancy(){for(const id of this.occupiedCells)this.defenders[id]=0;this.occupiedCells.length=0;for(let i=0;i<this.army.size;i++){if(!this.army.ids[i]||!this.army.canCapture(i))continue;const c=this.army.cell(i);if(!c)continue;if(!this.defenders[c.id])this.occupiedCells.push(c.id);this.defenders[c.id]|=1<<this.army.owner[i];}}
 private rebuild(affected:Set<number>){const {map,state,diplomacy}=this.match;this.scans++;const candidates:Encirclement[]=this.candidates.filter(p=>!affected.has(p.ownerId));if(!state.diplomacy.wars.some(w=>w.endedAt===null)){this.candidates=[];this.timers.clear();return;}const seen=this.seen;seen.fill(0);for(const country of state.players){if(!affected.has(country.id))continue;const components:number[][]=[];for(const id of this.match.owned.get(country.id)??[]){const c=map.cells[id];if(seen[c.id])continue;const queue=[c.id];seen[c.id]=1;for(let h=0;h<queue.length;h++)for(const n of map.cells[queue[h]].neighbors)if(!seen[n]&&map.cells[n].ownerId===country.id){seen[n]=1;queue.push(n);}components.push(queue);}if(components.length<2)continue;const capital=state.spawns.find(s=>s.id===country.spawnId)!.anchorId;const main=components.find(c=>c.includes(capital))??components.reduce((best,c)=>c.length>best.length?c:best,[] as number[]);
 for(const cells of components){if(cells===main)continue;let claimant:number|null=null,closed=true;for(const id of cells){const c=map.cells[id];if(c.neighbors.length<6){closed=false;break;}for(const n of c.neighbors){const neighbor=map.cells[n];if(neighbor.terrain==='water'||neighbor.ownerId===country.id)continue;if(neighbor.ownerId===null){closed=false;break;}const principal=diplomacy!.captureOwner(neighbor.ownerId,country.id);if(principal===null||(claimant!==null&&claimant!==principal)){closed=false;break;}claimant=principal;}if(!closed)break;}if(!closed||claimant===null)continue;cells.sort((a,b)=>a-b);const key=country.id+':'+claimant+':'+cells.join(',');candidates.push({id:key,ownerId:country.id,claimantId:claimant,cellIds:cells,state:'ENCIRCLED',remaining:WAR_TERRITORY.annexSeconds,blocked:null});}}
 this.candidates=candidates;const active=new Set(candidates.map(p=>p.id));for(const key of this.timers.keys())if(!active.has(key))this.timers.delete(key);}
 step(dt:number){this.elapsed+=dt;if(this.elapsed+1e-8<WAR_TERRITORY.interval)return;const time=this.elapsed;this.elapsed=0;this.occupancy();for(let i=0;i<this.army.size;i++)if(this.army.ids[i]&&this.army.canCapture(i))this.match.captureAtPosition(this.army.owner[i],this.army.x[i],this.army.y[i],true);
 this.captureStructures(time);
 const hostility=this.match.state.diplomacy.wars.filter(w=>w.endedAt===null).map(w=>[w.id,w.attackerId,w.defenderId,...w.attackerAllies,0,...w.defenderAllies].join(',')).join(';');if(this.border!==this.match.state.borderRevision||this.hostility!==hostility){this.rebuild(this.hostility!==hostility?new Set(this.match.state.players.map(p=>p.id)):this.match.dirtyCountries);this.match.dirtyCountries.clear();this.border=this.match.state.borderRevision;this.hostility=hostility;}
 const visible:Encirclement[]=[];for(const p of this.candidates){if(!this.match.diplomacy!.hostile(p.claimantId,p.ownerId))continue;const troops=p.cellIds.some(id=>this.match.state.players.some(owner=>(this.defenders[id]&(1<<owner.id))&&this.match.diplomacy!.hostile(p.claimantId,owner.id))),structures=p.cellIds.some(id=>{const buildingId=this.match.economy!.occupied[id];if(!buildingId)return false;const b=this.match.economy!.buildings.find(b=>b.id===buildingId);return b&&this.match.diplomacy!.hostile(p.claimantId,b.ownerId);});p.blocked=troops?'troops':structures?'structures':null;const age=p.blocked?0:(this.timers.get(p.id)??0)+time;this.timers.set(p.id,age);p.remaining=Math.max(0,WAR_TERRITORY.annexSeconds-age);if(p.remaining<=0){let captured=0;for(const id of p.cellIds)if(this.match.captureCellInWar(p.claimantId,id))captured++;if(captured)this.match.diplomacy!.event(`${this.match.diplomacy!.name(p.claimantId)} anexou um bolsão de ${captured} hexágonos de ${this.match.diplomacy!.name(p.ownerId)}.`);this.timers.delete(p.id);}else visible.push({...p});}
 const old=this.match.state.encirclements;if(old.length!==visible.length||old.some((p,i)=>p.id!==visible[i].id||p.remaining!==visible[i].remaining||p.blocked!==visible[i].blocked)){if(old.length!==visible.length||old.some((p,i)=>p.id!==visible[i].id))this.match.state.siegeRevision++;this.match.state.encirclements=visible;this.match.state.revision++;}}
 private captureStructures(dt:number){this.army.spatial.rebuild();const active=new Set<number>();for(const b of [...this.match.state.buildings]){if(b.construction||isMilitaryStructure(b.type))continue;const center=this.match.map.cells[b.anchorId],attackers=new Map<number,number>();let defenders=0;for(const i of this.army.spatial.near(center.x,center.y,Math.max(CAPTURE_CONFIG.radius,CAPTURE_CONFIG.defenderRadius))){if(!this.army.canCapture(i))continue;const distance=Math.hypot(this.army.x[i]-center.x,this.army.y[i]-center.y),actor=this.army.owner[i];if(this.army.buildingOrders.get(i)===b.id)continue;if(this.match.diplomacy!.hostile(actor,b.ownerId)&&distance<=CAPTURE_CONFIG.radius)attackers.set(actor,(attackers.get(actor)??0)+1);else if(this.match.diplomacy!.allied(actor,b.ownerId)&&distance<=CAPTURE_CONFIG.defenderRadius)defenders++;}
 const attacker=[...attackers].sort((a,b)=>b[1]-a[1])[0];if(defenders||!attacker||attacker[1]<(b.type==='city'?CAPTURE_CONFIG.cityMinimumTroops:1)){this.captures.delete(b.id);continue;}active.add(b.id);const previous=this.captures.get(b.id),timer=previous?.actor===attacker[0]?previous:{actor:attacker[0],time:0};timer.time+=dt;this.captures.set(b.id,timer);if(timer.time>=(b.type==='city'?CAPTURE_CONFIG.citySeconds:CAPTURE_CONFIG.economicSeconds)){if(this.match.captureBuilding(timer.actor,b.id))this.captures.delete(b.id);}}
 for(const id of this.captures.keys())if(!active.has(id))this.captures.delete(id);}
 /** Abstract stock carried by each unit; damage begins only after depletion. */
 logistics(dt:number){for(let i=0;i<this.army.size;i++){if(!this.army.ids[i]||!this.army.canCapture(i))continue;const c=this.army.cell(i),owner=c?.ownerId,actor=this.army.owner[i];let delta=0;if(owner===actor)delta=WAR_TERRITORY.supplyRestore;else if(owner!==null&&owner!==undefined&&this.match.diplomacy!.allied(actor,owner))delta=0;else delta=owner!==null&&owner!==undefined&&this.match.diplomacy!.hostile(actor,owner)?-WAR_TERRITORY.hostileDrain:-WAR_TERRITORY.neutralDrain;this.army.supply[i]=Math.max(0,Math.min(WAR_TERRITORY.supplyMax,this.army.supply[i]+delta*dt));if(this.army.supply[i]<=0&&delta<0){this.army.hp[i]=Math.max(0,this.army.hp[i]-WAR_TERRITORY.attritionDamage*dt);if(this.army.hp[i]<=0)this.army.remove(i);}}}
}
