import {ENGINE} from '../../shared/configs/engine';
import {isMilitaryStructure} from '../../shared/configs/combat';
import {COMBAT} from '../../shared/configs/combat';
import {UNIT_STATE,UNIT_LIMIT} from '../../shared/configs/units';
import type {Army} from '../units/army';
import type {TerritoryMatch} from '../territory/match';
interface Entity{id:number;x:number;y:number;owner:number;unit:number;building:number;automatic?:boolean;}
/** Bounded target acquisition in world-space buckets; damage resolves simultaneously within a tick. */
export class CombatSystem {
 private nextSearch=new Float64Array(UNIT_LIMIT);private rememberedUnit=new Uint32Array(UNIT_LIMIT);private rememberedBuilding=new Int32Array(UNIT_LIMIT).fill(-1);private attackerIds=new Uint32Array(UNIT_LIMIT);
 private buckets=new Map<number,Map<number,Entity[]>>();private entityPool:Entity[]=[];private pooled=0;private columns=Math.ceil(ENGINE.worldWidth/COMBAT.spatialCell);private defenses=new Map<number,number>();private unitDamage=new Float32Array(UNIT_LIMIT);private damaged:number[]=[];private buildingDamage=new Map<number,number>();private relationRevision=-1;private relations=new Uint8Array(81);time=0;searching=0;engaged=0;shots=0;
 constructor(readonly army:Army,private match:TerritoryMatch){}
 private syncHostility(){const d=this.match.diplomacy;if(!d||d.state.revision===this.relationRevision)return;this.relationRevision=d.state.revision;this.nextSearch.fill(0);this.relations.fill(0);for(const a of this.match.state.players)for(const b of this.match.state.players)this.relations[a.id*9+b.id]=Number(d.hostile(a.id,b.id));}
 hostile(a:number,b:number){this.syncHostility();return !!this.relations[a*9+b];}
 private add(id:number,x:number,y:number,owner:number,unit:number,building:number,automatic=true){let e=this.entityPool[this.pooled];if(!e){e={id,x,y,owner,unit,building};this.entityPool.push(e);}else {e.id=id;e.x=x;e.y=y;e.owner=owner;e.unit=unit;e.building=building;}e.automatic=automatic;this.pooled++;const key=Math.floor(y/COMBAT.spatialCell)*this.columns+Math.floor(x/COMBAT.spatialCell);let cell=this.buckets.get(key);if(!cell){cell=new Map();this.buckets.set(key,cell);}let bucket=cell.get(owner);if(!bucket){bucket=[];cell.set(owner,bucket);}bucket.push(e);}
 private nearest(x:number,y:number,owner:number,range:number,explicitBuilding?:number){let best:Entity|null=null,dist=range*range;const cx=Math.floor(x/COMBAT.spatialCell),cy=Math.floor(y/COMBAT.spatialCell),radius=Math.ceil(range/COMBAT.spatialCell);let candidates=0;for(const i of this.army.spatial.near(x,y,range,other=>!!this.relations[owner*9+other])){if(!this.relations[owner*9+this.army.owner[i]])continue;if(++candidates>COMBAT.candidates)break;const d=(this.army.x[i]-x)**2+(this.army.y[i]-y)**2;if(d<=dist){best={id:this.army.ids[i],x:this.army.x[i],y:this.army.y[i],owner:this.army.owner[i],unit:i,building:-1};dist=d;}}for(let dy=-radius;dy<=radius;dy++)for(let dx=-radius;dx<=radius;dx++){if(cx+dx<0||cx+dx>=this.columns||cy+dy<0)continue;const bucket=this.buckets.get((cy+dy)*this.columns+cx+dx);if(!bucket)continue;for(const [otherOwner,entities]of bucket){if(!this.relations[owner*9+otherOwner])continue;for(const e of entities){if(e.building>=0&&!e.automatic&&e.building!==explicitBuilding)continue;if(++candidates>COMBAT.candidates)return best;const d=(e.x-x)**2+(e.y-y)**2;if(d<=dist){best=e;dist=d;}}}}return best;}
 private acquire(i:number,range:number):Entity|null {
 const army=this.army,unit=army.index(this.rememberedUnit[i]),building=this.rememberedBuilding[i]>=0?this.match.state.buildings.find(b=>b.id===this.rememberedBuilding[i]):null;
 let target:Entity|null=unit>=0?{id:army.ids[unit],x:army.x[unit],y:army.y[unit],owner:army.owner[unit],unit,building:-1}:building&&isMilitaryStructure(building.type)?{id:building.id,x:this.match.map.cells[building.anchorId].x,y:this.match.map.cells[building.anchorId].y,owner:building.ownerId,unit:-1,building:building.id}:null;
 if(target&&this.relations[army.owner[i]*9+target.owner]&&(target.x-army.x[i])**2+(target.y-army.y[i])**2<=range*range)return target;
 const lost=this.rememberedUnit[i]!==0||this.rememberedBuilding[i]>=0;this.rememberedUnit[i]=0;this.rememberedBuilding[i]=-1;
 if(!lost&&this.time+1e-8<this.nextSearch[i])return null;
 this.searching++;target=this.nearest(army.x[i],army.y[i],army.owner[i],range);
 if(target){this.rememberedUnit[i]=target.unit>=0?target.id:0;this.rememberedBuilding[i]=target.building;}else this.nextSearch[i]=this.time+.2+(army.ids[i]%7)*.025;
 return target;
 }
 step(dt:number){if(this.match.state.phase!=='playing')return;this.time+=dt;this.searching=0;this.engaged=0;this.shots=0;this.pooled=0;this.syncHostility();for(const bucket of this.buckets.values())for(const entities of bucket.values())entities.length=0;const army=this.army;
 army.spatial.rebuild();
 for(const b of this.match.state.buildings){const c=this.match.map.cells[b.anchorId];this.add(b.id,c.x,c.y,b.ownerId,-1,b.id,isMilitaryStructure(b.type));}
 this.damaged.length=0;this.buildingDamage.clear();
 const hit=(e:Entity,damage:number)=>{if(e.unit>=0){if(!this.unitDamage[e.unit])this.damaged.push(e.unit);this.unitDamage[e.unit]+=damage;}else this.buildingDamage.set(e.building,(this.buildingDamage.get(e.building)??0)+damage);};
 for(let i=0;i<army.size;i++){if(!army.ids[i]||army.embarked[i]||army.kind[i]>=3)continue;army.cooldown[i]=Math.max(0,army.cooldown[i]-dt);if(army.state[i]===UNIT_STATE.retreat||army.state[i]===UNIT_STATE.recover){army.target[i]=-1;continue;}const def=army.definition(i);if(this.attackerIds[i]!==army.ids[i]){this.attackerIds[i]=army.ids[i];this.rememberedUnit[i]=0;this.rememberedBuilding[i]=-1;this.nextSearch[i]=0;}const explicitId=army.buildingOrders.get(i),explicit=explicitId===undefined?null:this.match.state.buildings.find(b=>b.id===explicitId),point=explicit?this.match.map.cells[explicit.anchorId]:null;const pursued=army.pursuitTarget(i),target:Entity|null=explicit&&point?(Math.hypot(point.x-army.x[i],point.y-army.y[i])<=def.range?{id:explicit.id,x:point.x,y:point.y,owner:explicit.ownerId,unit:-1,building:explicit.id}:null):pursued>=0?(Math.hypot(army.x[pursued]-army.x[i],army.y[pursued]-army.y[i])<=def.range?{id:army.ids[pursued],x:army.x[pursued],y:army.y[pursued],owner:army.owner[pursued],unit:pursued,building:-1}:null):this.acquire(i,def.range);if(!target){army.target[i]=-1;if(army.state[i]===UNIT_STATE.attack&&army.kind[i]<2)army.resume(i);continue;}army.state[i]=UNIT_STATE.attack;army.target[i]=target.unit>=0?target.id-1:-target.building-1;army.angle[i]=Math.atan2(target.y-army.y[i],target.x-army.x[i]);this.engaged++;if(army.cooldown[i]<=.00001){hit(target,def.attack*(target.unit>=0&&army.kind[i]<2?(army.kind[target.unit]===2?.08:army.kind[target.unit]>=3?.25:1):1));army.cooldown[i]=def.cooldown;army.shots[i]++;this.shots++;}}
 const liveDefenses=new Set<number>();for(const b of this.match.state.buildings){if(b.type!=='defense'||b.construction)continue;liveDefenses.add(b.id);const cooldown=Math.max(0,(this.defenses.get(b.id)??0)-dt);this.defenses.set(b.id,cooldown);const c=this.match.map.cells[b.anchorId],target=this.nearest(c.x,c.y,b.ownerId,COMBAT.defenseRange);if(target&&cooldown<=.00001){hit(target,COMBAT.defenseDamage*(target.unit>=0&&army.kind[target.unit]>=2?4:1));this.defenses.set(b.id,COMBAT.defenseCooldown);this.shots++;}}for(const id of this.defenses.keys())if(!liveDefenses.has(id))this.defenses.delete(id);
 for(const i of this.damaged){army.hp[i]=Math.max(0,army.hp[i]-this.unitDamage[i]);this.unitDamage[i]=0;if(army.hp[i]<=0)army.remove(i);}
 for(const [id,damage]of this.buildingDamage){const b=this.match.state.buildings.find(b=>b.id===id);if(b&&b.hp<=damage&&!isMilitaryStructure(b.type)){const attacker=[...army.buildingOrders].find(([,target])=>target===id);if(attacker)this.match.social?.destruction(army.owner[attacker[0]],b.ownerId,b.type==='city');}this.match.damageBuilding(id,damage);}
 for(const [i,barracksId]of army.recovery){if(!army.ids[i])continue;const b=this.match.state.buildings.find(b=>b.id===barracksId&&b.type==='barracks'&&!b.construction&&b.ownerId===army.owner[i]);if(!b)continue;const c=this.match.map.cells[b.anchorId];if(Math.hypot(army.x[i]-c.x,army.y[i]-c.y)>COMBAT.repairRadius||army.state[i]===UNIT_STATE.retreat)continue;army.state[i]=UNIT_STATE.recover;const country=this.match.state.economies.find(c=>c.playerId===army.owner[i])!,def=army.definition(i),heal=Math.min(def.health-army.hp[i],COMBAT.repairHpPerSecond*dt,country.stock.money/def.repair);if(heal>0){army.hp[i]+=heal;country.stock.money=Math.max(0,country.stock.money-heal*def.repair);this.match.state.revision++;}if(army.hp[i]>=def.health-.001){army.hp[i]=def.health;army.recovery.delete(i);army.state[i]=UNIT_STATE.idle;}}
 }
 startSkirmish(playerId:number){if(playerId!==1||this.match.state.phase!=='playing'||this.match.state.players.find(p=>p.id===2)?.defeated)throw new Error('Inicie uma partida primeiro.');if(this.army.count+this.army.queuedCount+6>5000)throw new Error('Limite de tropas atingido.');const relation=this.match.diplomacy!.relation(1,2)!;if(relation.state==='ALLIED'||relation.state==='TRUCE')throw new Error('Encerre a aliança ou aguarde a trégua para criar a patrulha.');if(Array.from(this.army.owner).some((owner,i)=>owner===2&&this.army.ids[i]))throw new Error('A patrulha adversária atual ainda está no mapa.');const own=[];for(let i=0;i<this.army.size;i++)if(this.army.ids[i]&&this.army.owner[i]===1)own.push(i);const base=own.length?{x:own.reduce((n,i)=>n+this.army.x[i],0)/own.length,y:own.reduce((n,i)=>n+this.army.y[i],0)/own.length}:this.match.map.cells[this.match.state.cities.find(c=>c.ownerId===1)?.anchorId??this.match.state.spawns.find(s=>s.id===this.match.state.players[0].spawnId)!.anchorId];const cells=this.match.map.cells.filter(c=>c.terrain==='land'&&c.ownerId===null&&Math.hypot(c.x-base.x,c.y-base.y)>190&&Math.hypot(c.x-base.x,c.y-base.y)<450).sort((a,b)=>Math.abs(Math.hypot(a.x-base.x,a.y-base.y)-260)-Math.abs(Math.hypot(b.x-base.x,b.y-base.y)-260));let chosen=cells.find(c=>this.army.navigation.clear(base,c));if(!chosen)chosen=cells.find(c=>{try{return this.army.navigation.route(base,c).length>0;}catch{return false;}});if(!chosen)throw new Error('Não há terra neutra próxima para posicionar a patrulha.');for(let n=0;n<6;n++){const p={x:chosen.x+(n%3-1)*25,y:chosen.y+(Math.floor(n/3)-.5)*25};this.army.spawn(2,n===5?'tank':'infantry',this.army.navigation.clear(chosen,p)?p:chosen);}this.match.diplomacy!.testWar(1,2);this.match.state.skirmish={x:chosen.x,y:chosen.y,playerId:2};this.match.state.revision++;}
}
